### ISSUE TITLE
Other examples

### ISSUE THREAD

**Issue by etiennebr** [r-spatial/stars#1]
The abstract is very clear. I don't know if it's relevant to include these examples in the abstract, but I wanted to share my thoughts:

- Spatial simulation often yield multidim rasters. 
- Multi-band time series such as Landsat series are a good example of something that requires heavy adaptation of current infrastructures
- This is an extension and it might not apply to the current proposal, but raster catalog (a large list of  -potentially sparse-- rasters) is also not very well supported, but it is similar to running small batches.

Having great support for gdal vrt format could be a good infrastructure to build on, I think it is listed in the proposal?

**Comment by edzer** [comment]
Is a raster catalog similar to what google earth engine calls an image collection?

**Comment by edzer** [comment]
@mdsumner

**Comment by etiennebr** [comment]
I'm not very familiar with Google Earth engine, but from the [description I could find](https://developers.google.com/earth-engine/tutorial_api_04) I think it's very similar.
