### ISSUE TITLE
Introduce function to get values of dimensions

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/stars#100]
Unless I am mistaken, there is no function to compute the values of the dimensions in `stars`. Currently, if the dimension is regular, the `values` slot is `NULL`, and values can be computed by taking the `offset`, `from`, `to` and `delta` values. This is all right, for example:
```
with(st_dimensions(stars_object)$x, offset + (from:to)*delta)
```
However this can sometimes be tricky, especially with times and non-standard calendars (using PCICt). For example, I am getting something like this for such a file, which is not very userfriendly and requires additional tinkering:
```
Time differences in days
 [1] 778896030 778896060 778896090 778896120 778896150 778896180 778896210 778896240 778896270 778896300
 [ reached getOption("max.print") -- omitted 782 entries ]
Warning message:
In eval(substitute(expr), data, enclos = parent.frame()) :
  Incompatible methods ("+.PCICt", "Ops.difftime") for "+"
```
A shorthand way to extract actual values from dimensions would be very useful in this case.

**Comment by edzer** [comment]
Good point! 

Internally stars uses `stars:::expand_dimensions`, which gives you a list of values: offsets, but optionally the other boundary or the cell center. We could expose this one; alternatively we could expose a function that converts regular grid -> rectilinear grid -> curvilinear grid, by filling up the $values.

A problem of the latter is that typically for x/y you would like to get the cell center, for time you would like to get the offset of each interval (which may reflect an interval, or an instance).

I'm not sure what to do; if I were I would already have exposed something.

**Comment by edzer** [comment]
And congrats for hitting issue #100!

**Comment by adrfantini** [comment]
Maybe the simplest thing would be an option to `st_dimensions` to compute the `values`?

**Comment by edzer** [comment]
.. as an option? Or else: add a `st_dimension_values`? Would you want a function returning values for a single, or rather for all dimensions?

**Comment by adrfantini** [comment]
Any of those would do honestly. Maybe what I would find more intuitive is an option to `st_dimensions`, and for all dimensions at the same time. But really any of the things you mentioned would be fine.

**Comment by adrfantini** [comment]
Currently, if `which` is not specified, returns `NULL`, instead of error.

**Comment by edzer** [comment]
t.b. closed?

**Comment by adrfantini** [comment]
Sure, thaks!
