### ISSUE TITLE
st_as_sf geometry column name

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/stars#101]
Slight inconsistency. These have geometry column name 'geometry':
```
attr(st_as_sf(x, merge = TRUE,  long=FALSE), 'sf_column')
attr(st_as_sf(x, merge = TRUE,  long=TRUE ), 'sf_column')
attr(st_as_sf(x, merge = FALSE, long=FALSE), 'sf_column')
```
This has 'sfc':
```
attr(st_as_sf(x, merge = FALSE, long=TRUE ), 'sf_column')
```

**Comment by edzer** [comment]
I suggest to give it the same name as the corresponding dimension in the `stars` object.

**Comment by adrfantini** [comment]
If dimensions are `x` and `y`, like in:
```R
system.file("tif/L7_ETMs.tif", package = "stars") %>% read_stars -> x
```
What are you going to call it? `xy`? Personally I would default to `geometry`, for the sake of simplicity.

**Comment by edzer** [comment]
"geometry", and geometry column names from sf objects are now preserved when using `st_as_stars`.
