### ISSUE TITLE
hdf4 MODIS not working

### ISSUE THREAD

**Issue by kendonB** [r-spatial/stars#105]
Hi there,

I am trying to read an hdf4 MODIS file. One can be downloaded from:

```
"https://e4ftl01.cr.usgs.gov/MOTA/MCD12Q1.006/2001.01.01/MCD12Q1.A2001001.h00v08.006.2018053181403.hdf"
```

but you will need to log in to NASA earthdata in your browser before you get it.

When I try to read it, I get:
```r
stars::read_stars("path_to/MCD12Q1.A2001001.h15v01.006.2018053201408.hdf")
#> trying to read file: 
#> my_working_dir\HDF4_EOS:EOS_GRID:"path_to\MCD12Q1.A2001001.h15v01.006.2018053201408.hdf":MCD12Q1:LC_Type1
#> Error in CPL_read_gdal(as.character(x), as.character(options), as.character(driver),  : 
#>   file not found
```
Note that the file path prefix that gets slapped on the front is the working directory, so that could be part of the problem.

**Comment by mdsumner** [comment]
Try normalizePath on the file name first? (I can test  more deeply later, this just a hunch)

**Comment by edzer** [comment]
When I try to download this file, it replies with:
```
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.
```
please provide it some other way.

**Comment by edzer** [comment]
It is indeed probably the `normalizePath` issue, working on it (debugging windows through appveyor...).

**Comment by kendonB** [comment]
@edzer, as I said, you will need to log in to NASA earthdata to get a copy. I will try normalizePath when back at my computer tomorrow morning NZ time. Cheers

**Comment by edzer** [comment]
@kendonB could you retry after updating stars? Might work now.

**Comment by kendonB** [comment]
Looks like it's working great now. Thanks heaps!
