### ISSUE TITLE
Add connect8 option in st_as_sf

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/stars#106]
As per discussion in #99 , `st_as_sf` will need a `connect8` option to enable 8-connectedness if `merge=TRUE`. Currently it is disabled due to `sf` dependency problems. Will need to be re-enabled after the next `sf` version reaches CRAN.

**Comment by edzer** [comment]
closed through https://github.com/r-spatial/stars/commit/1d992412b907ea109ed3cfeedd23df9ff0041349
