### ISSUE TITLE
Error: $ operator is invalid for atomic vectors when using st_warp

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/stars#110]
I was playing around with `st_warp`, and got this error:
```
geomatrix = system.file("tif/geomatrix.tif", package = "stars")
x = read_stars(geomatrix)
st_warp(x, crs = 4326)
# Error: $ operator is invalid for atomic vectors
```
The error is due to the fact that `st_warp` expects a `crs` object instead of a character or a numeric, so this instead works:
```
st_warp(x, crs = st_crs(4326))
```

While this is all fine and good, I feel like the error should be more explicit, maybe a check could be added that prints something more useful?

**Comment by edzer** [comment]
Closed through https://github.com/r-spatial/stars/commit/f6896c984cbd8e5fd0f03328e17b183367107aa6
