### ISSUE TITLE
st_warp to current CRS should do nothing

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/stars#111]
Warping to the same CRS as the current object CRS should imho do nothing. Currently:
```
geomatrix = system.file("tif/geomatrix.tif", package = "stars")
x = read_stars(geomatrix)
identical(x, st_warp(x, crs=st_crs(x)))
# FALSE
```

**Comment by edzer** [comment]
Sorry closed the wrong one!

**Comment by edzer** [comment]
I think 
```r
identical(x, st_warp(x, dest = x))
```
should be `TRUE`, which it is. 

`st_warp` warps to a regular grid, aligned with x and y, which `geomatrix.tif` is not. Maybe we should improve the documentation?

**Comment by adrfantini** [comment]
Oh, I see now. Yes, the docs indeed say that it warps to a regular grid, but it might be highlighted a bit more (maybe in the main description and not only in the details). Also some examples with `dest` (such as those from the 5th vignette) might be useful.

I have some confusion, I think it is stemming from the way different grids are `show`ed. These below are the kinds that `stars` accepts, right?

1. regular (orthogonal axes, constant grid spacing)
2. rotated/affine (orthogonal axes but not aligned to x/y, constant grid spacing) -> gets printed in `show` explicitly
3. rectilinear (orthogonal axes, non-constant grid spacing) -> gets printed in `show` (by setting `values` to non-NULL)
4. curvilinear (non orthogonal axes, non-constant grid spacing) -> gets printed in `show` explicitly

Is there any other possible combination to be had? Maybe a "grid type" argument that gets printed would help. 

As far as I can understand the vignettes 4 and 5, we can handle grid transformations as follows:

1. `st_warp` (lossily) warps to `regular` (always and only?)
2. `st_transform` (losslessly) transforms to `curvilinear` (unless very lucky!)

Also, does `st_warp` check that `dest` is regular? I had a quick tray I just got `Error: cannot allocate vector of size 58.3 Gb` so I guess it does not do it immediately.

**Comment by edzer** [comment]
@adrfantini was this issue resolved?

**Comment by adrfantini** [comment]
Aye aye
