### ISSUE TITLE
Equivalent of raster::merge?

### ISSUE THREAD

**Issue by kendonB** [r-spatial/stars#112]
Is there an equivalent of `raster::merge` in `stars`? It merges disparate windows from a single layer parent raster. Satellite imagery often ships this way, for example.

**Comment by edzer** [comment]
Currently not as raster, doing the logic in R , but you could try `gdal_utils("buildvrt", c("in1.tif", "in2.tif", "in3.tif"), "out.vrt")` and then read `out.vrt` with `read_stars`.

**Comment by adrfantini** [comment]
I think there are a few of these useful functions that could be very useful to have. Merge, aggregate, disaggregate, etc etc. Some of them are already feasible with some coding (but might benefit from a shortcut function), some would be nice to have.

It might be nice to have a list of these nice-to-haves, even though I'm not sure @Edzer thinks they should be in `stars`.

**Comment by edzer** [comment]
It would be useful to have a table similar to [this](https://github.com/r-spatial/sf/wiki/Migrating) for comparing operations between `stars` and `raster`, and perhaps also `GDAL` and `xarray`. Not entirely dissimilar to table 1 in [this paper](https://www.mdpi.com/2220-9964/7/8/313/htm). Maybe also in wiki form in this repo?

**Comment by adrfantini** [comment]
> It would be useful to have a table similar to [this](https://github.com/r-spatial/sf/wiki/Migrating) for comparing operations between `stars` and `raster`, and perhaps also `GDAL` and `xarray`. Not entirely dissimilar to table 1 in [this paper](https://www.mdpi.com/2220-9964/7/8/313/htm). Maybe also in wiki form in this repo?

I'm willing to help with this, as I have a lot of experience with `raster`.
But it's going to take me a while to find the time, unfortunately I have a few deadlines coming up.

**Comment by edzer** [comment]
Great! You should now have write permission to the repo.

**Comment by adrfantini** [comment]
The `raster` manual has a very handy [summary](https://cran.r-project.org/web/packages/raster/raster.pdf) of major functions under `raster-package`; if this is to be primarily a tool fro migrating from `raster`, I might follow the same structure, what do you think?
