### ISSUE TITLE
appveyor build breaks because rtools is not present

### ISSUE THREAD

**Issue by edzer** [r-spatial/stars#113]
See [here](https://ci.appveyor.com/project/edzerpebesma/stars/builds/22431727) - this happens when CRAN source packages are newer than the windows binaries, which is quite often the case! @krlmlr any idea how I can instruct appveyor to install rtools, or to install a lower version binary?

**Comment by krlmlr** [comment]
Can you please try setting the `PKGTYPE` env variable to `win.binary`?

**Comment by edzer** [comment]
Thanks a lot, @krlmlr !

**Comment by krlmlr** [comment]
Thanks for the nudge. Working on making it a bit more intuitive -- would it be too bad if this was the default?

**Comment by edzer** [comment]
It would definitely be a good default for packages that don't have compiled code, for others it's not too critical. When forced to say yes or no, I would say yes make this the default.
