### ISSUE TITLE
Parallel st_apply(PROGRESS = TRUE) and non-interactive sessions

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/stars#118]
Currently the progress bar produced by `st_apply(PROGRESS = TRUE)` does not work in non-interactive sessions, due to [this](https://www.rdocumentation.org/packages/pbapply/versions/1.3-3/topics/pbapply):

> The functions fall back to their original equivalents when the progress bar is disabled (i.e. getOption("pboptions")$type == "none" or dopb() is FALSE). This is the default when interactive() if FALSE (i.e. called from command line R script).

I think that if someone writing a script sets `PROGRESS = TRUE`, then this should work even in non-interactive sessions, since `pbapply` is loaded by stars automatically.

**Comment by edzer** [comment]
Should we make default `PROGRESS = interactive()` ?

**Comment by adrfantini** [comment]
No, maybe I was not clear. The issue currently is that even if `PROGRESS = TRUE`, if `interactive() == FALSE` no progress bar is shown. This is of course unexpected for the user.
AFAICT, the user cannot set the `option` without first loading `pbapply` by himself.
I think we should set the appropriate `option` when you load `pbapply`, so that the user does not have to do this (and understand this) by himself.

**Comment by edzer** [comment]
I think it is good that progress bars are not shown in non-interactive use. If users can override that with obscure pbapply options, all the better!

**Comment by adrfantini** [comment]
I'm sorry but I don't really see the reasoning. If a user has *explicitly* set an option to show progress, why would you prevent him from doing so? If the user wanted the current behaviour with `PROGRESS = TRUE`, he could have set `PROGRESS = interactive()`, which works the same but is definitely more explicit and clear.

**Comment by edzer** [comment]
I feel that this is pbapply complexity, and users need to learn that the solutions are there, not in stars.

**Comment by adrfantini** [comment]
I understand this point of view, then maybe some additional details in the documentation (stating that TRUE has not effect for non-interactive sessions) might be welcome.

**Comment by edzer** [comment]
Suggestions welcome!

**Comment by adrfantini** [comment]
Basically, what needs to happen to make the progress bar work, from a user's point of view, is currently this:
```R
library(parallel)
nthreads = 4
cluster = makeCluster(nthreads)
library(pbapply)
pboptions('type' = 'timer')
st_apply(..., CLUSTER = cluster, PROGRESS = TRUE)
```
I would personally think that the first two rows should be redundant and taken care by `st_apply`. However, I also see your point in not doing so and using bare `pbapply`, which shows a progress bar only in interactive sessions. If we want to keep this behaviour, we could add an example (just like the one above) in the `st_apply` documentation that shows how to set a progress bar even for non-interactive workloads.

**Comment by edzer** [comment]
`pbapply` lets you configure this: setting
```r
library(pbapply)
pboptions(type = "timer")
```
before a call to `st_apply` shows a progress bar also in non-interactive mode. That is enough: it's not up to stars to interfere with this.

**Comment by adrfantini** [comment]
I think adding this example to the docs could be useful for some people.
