### ISSUE TITLE
color tables for stars objects

### ISSUE THREAD

**Issue by edzer** [r-spatial/stars#128]
See also: https://github.com/r-spatial/mapview/issues/208
GDAL has ability to read color tables from files that have them; should we support this somehow? Should stars objects then carry a color table? If they're given as table, in what form? Or use the current path: numeric -> factor with legend labels -> plot with color ramp as hexcodes? We need to choose, and document this.

**Comment by edzer** [comment]
See also https://github.com/r-spatial/discuss/issues/16

**Comment by edzer** [comment]
See also https://github.com/mtennekes/tmap/issues/368

**Comment by edzer** [comment]
The approach I took now is that if a GDAL raster file has color tables, they are all read (for every layer, potentially, one). Next, the array is converted into a factor with levels 1:ncolors. Before plotting, these values are used as the index on the color vector, so that a color matrix is plotted. Note that:
* since the colors are added as attribute to the data array, color tables on layers past layer one are essentially ignored
* if the color interpretation reported by GDAL is not rgb, a warning is emitted but rgb is assumed nevertheless.

**Comment by edzer** [comment]
See [here](https://github.com/mtennekes/tmap/issues/368#issuecomment-595727166); raster attribute table values can now be read, and used as factor levels.

**Comment by Nowosad** [comment]
@edzer another small example is at [lanform-example.zip](https://github.com/r-spatial/stars/files/4345255/lanform-example.zip). It is read (with colors and labels) by QGIS and **raster**.

**Comment by edzer** [comment]
Thanks @Nowosad ! GDAL apparently has two interfaces for category labels ... second now added as well.
![x](https://user-images.githubusercontent.com/520851/76900918-88f17800-689a-11ea-9357-33151baa6dc9.png)

**Comment by mdsumner** [comment]
Works for GIF: 

(In combination with https://github.com/r-spatial/sf/pull/1306)


``` r
 f <- file.path(R.home(), "Tcl/lib/tk8.6/images/logo100.gif")
library(stars)
#> Loading required package: abind
#> Loading required package: sf
#> Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3
st <- read_stars(f)
plot(st)
```

![](https://i.imgur.com/6QBW4Fi.png)

<sup>Created on 2020-03-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mdsumner** [comment]
I can't stand how ugly that is so I fixed it

``` r
 f <- file.path(R.home(), "Tcl/lib/tk8.6/images/logo100.gif")
library(stars)
#> Loading required package: abind
#> Loading required package: sf
#> Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3
st <- read_stars(f)
plot(NA, xlim = c(0, dev.size("px")[1]), ylim = c(-dev.size("px")[2], 0))
plot(st, add = TRUE)
bb <- st_bbox(st)
abline(v = bb[c(1, 3)], h = bb[c(2, 4)])
```

![](https://i.imgur.com/5W4ubZa.png)

<sup>Created on 2020-03-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by edzer** [comment]
Nice!
