### ISSUE TITLE
Clean up the option combination in st_as_sf, after adding st_contour

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/stars#132]
As discussed in #99, after `st_contour` has been introduced, we could implement the following option combination for `st_as_sf`:
```
as_points    merge
        T        T      ->    MULTIPOINTS
        T        F      ->    POINTS
        F        T      ->    POLYGONS, merged, maybe MULTIPOLYGONS?
        F        F      ->    POLYGONS, not merged
```
This is in contrast with the current situation:
```
as_points    merge
        T        T      ->    CONTOURS, GDAL>=2.4
        T        F      ->    POINTS
        F        T      ->    POLYGONS, merged
        F        F      ->    POLYGONS, not merged
```

Instead of `as_points`, it would be also possible to have a `type` argument with `c('POINT', 'POLYGON')` as possible options. This would imho be a bit clearer.

**Comment by edzer** [comment]
The POINT to MULTIPOINT is something you could do with `sf`; I don't see a strong case to do this within stars' scope.
