### ISSUE TITLE
Possibly use tsibble for time handling and aggregation?

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/stars#134]
Time aggregation by day, month, season or year is something climate scientists use all the time. The package `tsibble` ([link](https://github.com/tidyverts/tsibble)) provides a useful interface to tidy time modification and might be handy in this case. It is however designed to handle tibbles, and not arrays. Also, it currently does not support `PCICt` calendars.

**Comment by edzer** [comment]
... and third, it doesn't handle time _intervals_. But you are right: conversion to and from `tsibble` would make sense.

**Comment by adrfantini** [comment]
In any case, in your plans time aggregation should happen via `aggregate`, right? Do you have any idea on how to implement it already?

**Comment by dvictori** [comment]
I'm also puzzled by this. I'm trying to obtain monthly climatology from a 20 year monthly time series and I though `aggregate` could be used for that, similar to `raster::stackapply`. But I could not understand how to do this. I also tried using `group_by` with no luck. Is `aggregate` the right tool for this? I ended up using a mix of `filter`, `st_apply` and other functions.

I described it here: https://gis.stackexchange.com/questions/333053/netcdf-time-aggregation-using-r-stars-package

**Comment by michaeldorman** [comment]
I'm using something similar, a `for` loop going over the subsets, summarizing each, then merging back into a multi-band raster:

```r
seasons = c("winter", "spring", "summer", "fall")
season_means = list()
for(i in seasons) {
  v = which(dates$season == i)
  s = r[,,,v]
  season_means[[i]] = st_apply(s, 1:2, mean, na.rm = TRUE)
}
season_means$along = 3
season_means = do.call(c, season_means)
names(season_means) = "NDVI"
```

where `r` is a `stars` object with a monthly times series of NDVI images, and `dates$season` is the corresponding vector of season names for each image. 

The result is:

![season-means-1](https://user-images.githubusercontent.com/9386655/67157964-d80e9d80-f33a-11e9-96f1-baf95756a882.png)

I'm also happy to hear if there is a more convenient way to split-apply-combine, based on a grouping vector (such as calculating season means).

**Comment by michaeldorman** [comment]
@dvictori Your suggestion on [StackOverflow](https://gis.stackexchange.com/questions/333053/netcdf-time-aggregation-using-r-stars-package) is more elegant, I used the ideas from there to modify my example:

```r
f = function(season) {
  s = r[,,,dates$season == season]
  st_apply(s, 1:2, mean, na.rm = TRUE)
}
season_means = lapply(seasons, f)
season_means = do.call(c, season_means)
season_means = merge(season_means)
names(season_means) = "NDVI"
st_set_dimensions(season_means, 3, names = "season", values = seasons)
```

**Comment by edzer** [comment]
Here's an example (from `?aggregate.stars`):
```r
library(stars)
# Loading required package: abind
# Loading required package: sf
# Linking to GEOS 3.9.0, GDAL 3.2.1, PROJ 7.2.1

d = c(10, 10, 150)
a = array(rnorm(prod(d)), d) # pure noise
times = Sys.Date() + seq(1, 2000, length.out = d[3])
m = as.numeric(format(times, "%m"))
signal = rep(sin(m / 12 * pi), each = prod(d[1:2])) # yearly period
s = (st_as_stars(a) + signal) %>%
		st_set_dimensions(3, values = times)
f = function(x, format = "%B") {
	months = format(as.Date(paste0("01-", 1:12, "-1970")), format)
	factor(format(x, format), levels = months)
}
agg = aggregate(s, f, mean)
plot(agg)
```
![x](https://user-images.githubusercontent.com/520851/117584325-9b68e980-b10c-11eb-9723-e46ff1d3de08.png)
