### ISSUE TITLE
Consider not using udunits for time in read_ncdf

### ISSUE THREAD

**Issue by kendonB** [r-spatial/stars#135]
Dates before 1582 deviate from ISO8601 (which R uses) in udunits, which uses a hybrid Gregorian/Julian calendar: see https://github.com/r-quantities/units/issues/194

To address this, instead of using `units`, you could parse the units within stars itself, OR put in a hack like this:

```r
origin = lubridate::parse_date_time(u, orders = c("ymdHMS", "ymd"))
if(origin < "1582-10-15"){
  # udunits uses a mixed gregorian/standard calendar whereas R uses ISO8601
  # This can cause problems if origin is earlier than "1582-10-15"
  # This section of code is a bit of a "hack" as it just adds
  # 6999 years to ensure that the two calendars are the same.
  # If year -4712 is the origin we're all good. Dates after 10000 seem to
  # also get messed up so this will also allow for years out to 3000 
  new_origin = origin + lubridate::years(6999)
  # For this to be parseable by units, it must be of the form:
  # period SINCE [-]Y[Y[Y[Y]]]-MM-DD[(T| )hh[:mm[:ss[.sss*]]][ [+|-]hh[[:]mm]]]
  
  before_since = gsub("(.+?)since(.*)", "\\1", tolower(u))
  new_u <- paste0(before_since, "since ", new_origin)
  start = as.POSIXct(units::set_units(v$start, new_u, mode = "standard")) # or: RNetCDF::utcal.nc(u, tm, "c")
  end =   as.POSIXct(units::set_units(v$end,   new_u, mode = "standard")) # or: RNetCDF::utcal.nc(u, tm, "c")
  start = start - lubridate::years(6999)
  end = end - lubridate::years(6999)
} else {
  start = as.POSIXct(units::set_units(v$start, u, mode = "standard")) # or: RNetCDF::utcal.nc(u, tm, "c")
  end =   as.POSIXct(units::set_units(v$end,   u, mode = "standard")) # or: RNetCDF::utcal.nc(u, tm, "c")
}
```
The above would replace:
https://github.com/r-spatial/stars/blob/1d992412b907ea109ed3cfeedd23df9ff0041349/R/ncdf.R#L217-L218

And it would require similar hacks everywhere else `as.POSIXct.units` gets called. This would also introduce a dependency on `lubridate`.

**Comment by kendonB** [comment]
`lubridate::parse_date_time` is also not yet perfect: https://github.com/tidyverse/lubridate/issues/755

**Comment by edzer** [comment]
I think that the creators of the netcdf files must have udunits in mind - at least they're forced to use udunits syntax - when they write their files. I'm somewhat hesitant to use another interpretation on it when we read it - would the netcdf file writer have this in mind?

More in general I'm hesitant to put calenders on epochs where calendars were absent or ambiguous. If you're in historical research, sorting out the ambiguities may be the research itself. If you're e.g. in climate research, decimal year might be good enough.

**Comment by adrfantini** [comment]
> calenders on epochs where calendars were absent or ambiguous

In CF-Compliant netCDF files there is no ambiguity, the calendar is uniquely specified. I've yet to find a `netCDF` file which did not include a calendar attribute. The CF-Conventions (which is what `stars` aims at supporting, as far as I can tell) [support several calendars](http://cfconventions.org/cf-conventions/cf-conventions.html#calendar), with the mixed `udunits2` being the dafault (if missing).

`udunits2` is [not a time package](https://www.unidata.ucar.edu/software/udunits/udunits-current/doc/udunits/udunits2lib.html#Time), and does not handle calendars. So any calendar handling done in R cannot go through `udunits2`. Unfortunately, the only calendar package available is `PCICt`, which is however a bit limited. But it works for all kind of CF calendars, as far as I can tell.

**Comment by kendonB** [comment]
From PCICt: Calendar types include 360 day calendars("360_day", "360"),
365 day calendars ("365_day", "365", "noleap"), and Gregorian calendars ("gregorian", "prolep-
tic_gregorian").

Do we know if the "gregorian" calendar refers to the mixed Julian/Gregorian calendar that udunits uses?

If so, it looks like PCICt can be used for everything.

Or PCICt not provide `+` methods?

**Comment by edzer** [comment]
So far we've only looked at PCICt for 360 and 365/noleap calendars. You now have the use case where you need the Gregorian variaties, it seems. Maybe you can try this out?

**Comment by adrfantini** [comment]
> If so, it looks like PCICt can be used for everything. 
> 
> Or does PCICt not provide `+` methods?

It does provide basic arith.  In fact I have been using it as default for all CF-compliant calendars lately, and it seems to work fine. But this is in no way a rigid testing, as I mostly use files with modern times (>1950)  and either gregorian, 360days or 365days calendars.

**Comment by edzer** [comment]
Please reopen if there are new views here.
