### ISSUE TITLE
It it possible to plot stars and sf in the same plot?

### ISSUE THREAD

**Issue by ibarraespinosa** [r-spatial/stars#138]
I would like to plot a vector of lines above an elevation map. 

Is it possible to do that?

Thanks!

**Comment by edzer** [comment]
Haven't tried, but I think yes, if you use `reset = FALSE` in the first plot. Have you tried?

**Comment by ibarraespinosa** [comment]
It worked with reset! Many thanks and sorry for this unimportant issue. I didn't know how to use reset.
![good](https://user-images.githubusercontent.com/27447280/53884450-8ee13600-4056-11e9-870c-443943b318a3.png)

**Comment by adrfantini** [comment]
Just as an added suggestion, you could also plot with `ggplot` and use `geom_sf` and `geom_stars`, or maybe transform the `stars` object to `sf` polygons using `st_as_sf(as_points = FALSE)`.

**Comment by ibarraespinosa** [comment]
I sometimes try to avoid ggplot, especially for larger vector data. Thanks for the idea anyways

**Comment by mdsumner** [comment]
(It's about to improve, in R 3.6.0 and ggplot2 update fwiw)

**Comment by adrfantini** [comment]
> (It's about to improve, in R 3.6.0 and ggplot2 update fwiw)

Nice, any pointers? I remember something related to sf/stars, but can't find it.
