### ISSUE TITLE
stars_proxy st_apply while write_stars

### ISSUE THREAD

**Issue by jimoreira** [r-spatial/stars#139]
I'm trying to work in a timeseries of 4 band images (planet). My intention is to produce calculations on that stars object. I have tried to work with stars_proxi objects but i'm not understanding the st_apply way to produce, for instance, a ndvi value for each, pixel-time. 
The dimensions of the current stars object are: 
```x       y    band new_dim ```
   ``` 812     580       4      43 ```
my code is as follows,

```library(stars)
library(XML)
library(raster)
library(here)
library(dplyr)

#set_here()
here()
#getwd()
setwd("D:\\OneDrive\\teleysig_javierMoreira\\TrabajoFinal\\Tesis\\seguimiento_ndvi\\elmirador\\planet")
#home<-file.path(getwd())

l<-list.files(recursive = TRUE)
#lapply(l,unzip )
l2<-list.files(pattern = "AnalyticMS_SR_clip.tif$")

fecha<-lapply(l2, function(x){
    fecha1 = unlist(strsplit(x,"\\_"))[1]
    fecha2 = as.Date(fecha1,"%Y%m%d")
    return(fecha2)
    })
fecha<-do.call("c",fecha) %>% as.POSIXct()

##corregir extension de imagenes diferentes, hacerlo para todas, para asegurarse
recortar<-function(x){
    i= 2
    for (i in 1:length(l2)){
        xorg<-brick(l2[1])
        x<-brick(l2[i])
        nuevo<-crop(x,xorg)
        nombre = unlist(strsplit(l2[i],"\\."))[1]
        writeRaster(nuevo,filename = paste0(nombre,"_recorte",".tif"))
        i = i+1
    }
}
recortar(l2)

l3<-list.files(pattern = "recorte.tif$")
##generar un archivo stars con todas las fechas (PROXY)
y2<-read_stars(l3,along = 4, proxy = TRUE)

#calcular ndvi para usarlo para co-registrar
ndvi <- function(x) (x[4]-x[3])/(x[4]+x[3])
y2.ndvi<-st_apply(y2, "band", ndvi)

#testear write-stars
write_stars(y2[,,,1,23],"XCVBN.tif", type = "Float32")
#producir la serie temporal
write_stars(y2.ndvi,"XCVBN.tif", type = "Float32")

```
i have been reding the vignettes and other info and still haven't found the solution, 

thanks for your help!

**Comment by edzer** [comment]
There's little one can do from a distance and looking at your script, but my guess would be to replace the `st_apply` with
```r
y2.ndvi<-st_apply(y2, c("x", "y", "new_dim"), ndvi)
```
so that `ndvi` is applied to the `band` dimension.

**Comment by jimoreira** [comment]
ok. i had allready try that way, 
it produces a one band file with 0 values, when one expects a 43 band .tif file. 
in addition of the following error:
`Error in CPL_write_gdal(mat, file, driver, options, type, dims, from,  : 
  write failure
In addition: Warning message:
In CPL_write_gdal(mat, file, driver, options, type, dims, from,  :
  GDAL Error 5: XCVBN.tif: RasterIO(): nBandCount cannot be greater than 1`

i have allready test write the `y2` stars_proxy file, and it works when one choose only one layer, as it's done with:
`write_stars(y2[,,,1,23],"XCVBN.tif", type = "Float32")`
but i don't know if it is possible to write a multy layer object.

thanks!

**Comment by edzer** [comment]
The only way we can make progress here is if you provide reproducible examples. I know that that is hard.

**Comment by jimoreira** [comment]
ok i'm sending the Rproj and files to work
https://1drv.ms/f/s!AsKUvf59Z2PFo_cW-blKUsXJsRWPXg[](url)

thanks again

**Comment by edzer** [comment]
The link is wrong, and please send a clean, minimal R script and not a Rproj file.

**Comment by jimoreira** [comment]
https://1drv.ms/f/s!AsKUvf59Z2PFqMcaF_VxY5fEQ5WYgg
Those are the files, and the script is in the original message
Thanks

**Comment by edzer** [comment]
Thanks; this is a bug. What works now is
```r
y <- st_apply(y2, c("x", "y", "new_dim"), ndvi)
write_stars(st_as_stars(y))
```
but that of course doesn't scale up for large datasets. Also, automatic naming gets messy, and you seem to have lost your time stamps somewhere.

**Comment by jimoreira** [comment]
Ok, it produces a really funky file, but it gets the work done.
thanks once again for your help and for your quick response.

**Comment by jimoreira** [comment]
I have a couple of questions;
1- It´s possible to obtain a file adding a band to the original file, with the output of the function? (ndvi) instead of producing a new file with the output. 

2- How can i add time stamps when the original files don't have it?. I find the way of seldom get it done in a stars object, adding a list of `as.POSIXct()` Dates, (still gettin `NAs` in `refsys`), but can't do it in a stars proxy file.

thanks for your comments

**Comment by edzer** [comment]
Please raise a new issue when you have new questions.
