### ISSUE TITLE
aggregate a stars proxy object over a sf object

### ISSUE THREAD

**Issue by jimoreira** [r-spatial/stars#146]
i'm trying to obtain a `sf` object with the aggregated mean of one dimension of a `stars proxy` object (dimension = time). And st_join the sf object with other one that includes attributes lost in the aggregated version.
i have tried:
1-
get a stars object from the stars proxy, and that works fine, until the `aggregate` when i touch a memory limit. (y3 is the stars from stars proxy object) 
```
muestreo= read_sf(contenido)
a = aggregate(y3, muestreo, mean, na.rm = TRUE)
a_sf<-st_join(muestreo,a)
write_sf(a_sf, paste0(name,"timeSeries",".shp"))
```
the error given when `aggregate`
`stars object with 2 dimensions and 1 attribute
attribute(s):
Error in do.call(data.frame, c(x, alis)) : 
  variable names are limited to 10000 bytes`

2- i also try to work directly with the` stars proxy `object, but when i need to change from `stars` to `stars proxy` `(st_as_stars(a))` to produce the `st_join,` an error appears (y2.ndvi is an `stars proxy` object)
```
muestreo= read_sf(contenido)
agregar<- function (x){
            aggregate(x,  muestreo, mean, na.rm = TRUE)
        }
a = st_apply(y2.ndvi, c("x", "y", "new_dim"), agregar)
a_sf <- st_join(muestreo, st_as_stars(a))
```
error given when `st_join(muestreo, st_as_stars(a))`,
`Error in inherits(x, "sf") && inherits(y, "sf") : 
  arguments must have same length`

thanks for your help!

**Comment by edzer** [comment]
Please provide a reproducible example.

**Comment by jimoreira** [comment]
link to images
[https://1drv.ms/f/s!AsKUvf59Z2PFqMcQQ6CZqy2FcURZhg](url)
link to shapefile
[https://1drv.ms/f/s!AsKUvf59Z2PFpIlNBPPDYi9t3CDD8Q](url)

code 
```
library(stars)
library(XML)
library(raster)
library(here)
library(dplyr)
library(sf)

setwd("D:\\OneDrive\\teleysig_javierMoreira\\TrabajoFinal\\Tesis\\seguimiento_ndvi\\estanzuela\\planet")

l2<-list.files(pattern = "AnalyticMS_SR_clip.tif$")

fecha<-lapply(l2, function(x){
    fecha1 = unlist(strsplit(x,"\\_"))[1]
    fecha2 = as.Date(fecha1,"%Y%m%d")
    return(fecha2)
})
fecha <- do.call("c",fecha)  

l3<-list.files(pattern = "(.*)shifted(.*)tif$")
##generar un archivo stars con todas las fechas (PROXY)
#
y2<-read_stars(l3,along = 4, proxy = TRUE)
##change time stamps wait for bug confirmation on github


#calcular ndvi para usarlo para co-registrar
ndvi <- function(x) (x[4]-x[3])/(x[4]+x[3])

###testing##
y2.ndvi<-st_apply(y2, c("x","y","new_dim"), ndvi)

#producir la serie temporal
plot(y2.ndvi)
y3<-st_as_stars(y2.ndvi)
y3<-st_set_dimensions(y3,"new_dim", values = fecha, names = "fechas")
st_dimensions(y3)

##path to shapefiel
setwd("D:\\OneDrive\\teleysig_javierMoreira\\TrabajoFinal\\Tesis\\chacras\\estanzuela")
listas<-list.files()
print(listas)
##select estanzuelaB.shp file
contenido<-readline(prompt="seleccionar archivo a abrir (.shp, sin comillas): ")
muestreo= read_sf(contenido)
agregar<- function (x){
    aggregate(x, muestreo, mean, na.rm = TRUE)
}
a = st_apply(y2.ndvi,c("x","y","new_dim"),agregar)
a_sf<-st_join(muestreo,st_as_sf(a))
name<-unlist(strsplit(contenido,"\\."))[1]
write_sf(a_sf, paste0(name,"timeSeries",".shp"))
```

thanks

**Comment by edzer** [comment]
Please reduce the script so that it runs and focuses on your problem (remove setwd's, readline's etc)

**Comment by jimoreira** [comment]
```
l3<-list.files(pattern = "(.*)shifted(.*)tif$")
y2<-read_stars(l3,along = 4, proxy = TRUE)
ndvi <- function(x) (x[4]-x[3])/(x[4]+x[3])

**Comment by jimoreira** [comment]
with that command
`Error in inherits(x, "sf") && inherits(y, "sf") : 
  arguments must have same length`

**Comment by edzer** [comment]
With the `aggregate` command, what exactly do you try to do?

**Comment by jimoreira** [comment]
what i really need is a table with the mean of the ndvi timeseries for each plot. I'm doing it throug getting an sf object with that values.

**Comment by edzer** [comment]
Do you want the
* time series of the mean ndvi for each plot, or
* the mean of the ndvi time series, for each plot

**Comment by jimoreira** [comment]
the first one, a series of values of mean ndvi for the area of the plot.
One of the issues that i mentioned is that, if doing it through sf object, i must keep the attributes of the original file, in order to identify the plots.
thanks

**Comment by edzer** [comment]
```r
s = st_as_stars(y2.ndvi)
st = st_set_dimensions(s, 3, values = Sys.Date() + 1:125) # sensible values needed!
a = aggregate(st, muestreo, mean)
names(a) = "ndvi" # this is a problem I need to address
plot(a, max.plot = 16)
```
![x](https://user-images.githubusercontent.com/520851/54342631-479e0b00-463d-11e9-9283-580440bebdc5.png)

**Comment by edzer** [comment]
With this patch, this
```r
st = st_set_dimensions(y2.ndvi, 4, values = Sys.Date() + 1:125) # sensible values needed!
sta = st_as_stars(st)
ag = aggregate(sta, muestreo, mean)
plot(ag, max.plot = 16)
```
should also work.

**Comment by jimoreira** [comment]
the problem is with the 4th dimension (Date), you use `Sys.Date` and works, but those are not the correct dates, i use a file that look like this:
`str(fecha)
 Date[1:125], format: "2017-10-15" "2017-10-16" "2017-10-19" "2017-10-19" "2017-10-19" ...`
i add it as the values in either of your 2 proposed ways, 
and get the following, 
-Second solution:
```
sta = st_as_stars(st)
sta
```
`stars object with 3 dimensions and 1 attribute
attribute(s), summary of first 1e+05 cells:
Error in do.call(data.frame, c(x, alis)) : 
  variable names are limited to 10000 bytes`

-First solution:
```
st = st_set_dimensions(s, 3, values = fecha) 
st
```
`stars object with 3 dimensions and 1 attribute
attribute(s), summary of first 1e+05 cells:
Error in do.call(data.frame, c(x, alis)) : 
  variable names are limited to 10000 bytes`

**Comment by edzer** [comment]
You need to reinstall stars from github.

**Comment by jimoreira** [comment]
👍 works fine! thanks!
