### ISSUE TITLE
Reading large geotiff

### ISSUE THREAD

**Issue by mountainMath** [r-spatial/stars#151]
Reading large geotiff gives `Error: vector memory exhausted (limit reached?)`, raster package reads the same file without a problem.

Example is [GHS population model](http://data.jrc.ec.europa.eu/dataset/jrc-ghsl-ghs_pop_gpw4_globe_r2015a/resource/cfd728a6-6b4d-42f4-bad5-2ddd03648c80).

**Comment by mdsumner** [comment]
Try `proxy = TRUE` in read_stars, raster does that by default ( in different ways)

**Comment by mountainMath** [comment]
Thanks! That works.
