### ISSUE TITLE
`[` using equivalent of st_intersects

### ISSUE THREAD

**Issue by kendonB** [r-spatial/stars#152]
Running `stars_object[sf_polygon_object]` seems to subset using the centroids of the stars grid cells. It would be neat if there was an option that subsets if any part of a grid cell intersects with the polygon object.

[PRISM_tmax_stable_4kmD1_19880611_bil.zip](https://github.com/r-spatial/stars/files/3020397/PRISM_tmax_stable_4kmD1_19880611_bil.zip)

Code below shows that several grid cells that intersect with the polygon get omitted.
``` r
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3
library(tidyverse)
#> Warning: package 'tidyverse' was built under R version 3.5.2
#> Warning: package 'tibble' was built under R version 3.5.2
#> Warning: package 'purrr' was built under R version 3.5.2
#> Warning: package 'dplyr' was built under R version 3.5.2
#> Warning: package 'stringr' was built under R version 3.5.2
library(stars)
#> Loading required package: abind
library(mapview)
x1 = read_stars("PRISM_tmax_stable_4kmD1_19880611_bil/PRISM_tmax_stable_4kmD1_19880611_bil.bil")
nc = read_sf(system.file("shape/nc.shp", package="sf"))

nc = nc %>% st_transform(st_crs(x1)) %>% filter(CNTY_ID == 2099)

nc$geometry[[1]][[1]] <- NULL

x1[nc] %>% st_as_sf() %>% ggplot() + geom_sf() + 
  geom_sf(data = nc)
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar
```

![](https://i.imgur.com/sjfW7qA.png)

<sup>Created on 2019-03-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by edzer** [comment]
Thanks! This
```r
x1[nc, as_points = FALSE] %>% st_as_sf() %>% ggplot() + geom_sf() + 
  geom_sf(data = nc)
```
now gives

![x](https://user-images.githubusercontent.com/520851/55224812-9210b180-5211-11e9-94ef-e236ac4a6f2b.png)
