### ISSUE TITLE
Support Tidy Spatial Interpolation 

### ISSUE THREAD

**Issue by harryprince** [r-spatial/stars#154]
Spatial Interpolation in R/Python is still pretty messy now, does anyone want to change this situation?

Here is the current some solutions that I found:

* https://github.com/retostauffer/Rgetgrib
* https://gist.github.com/andrie/2dff13157cfe46396ff0

**Comment by edzer** [comment]
Wow, bold statement - I'm not entirely sure why you bring this up here, or what you are looking for. R package `gstat` supports sf objects for observations, and `stars` objects as input and output rasters, both for spatial geostatistical models, and and spatiotemporal models. Many more pointers in the [spatial CRAN task view](https://cran.r-project.org/web/views/Spatial.html).
