### ISSUE TITLE
area_overlap_weights argument to aggregate?

### ISSUE THREAD

**Issue by kendonB** [r-spatial/stars#155]
See also: https://github.com/r-spatial/stars/issues/32

This might be a nice interface to calculate area-weighted aggregations.

It could be something like:
```r
weighted_mean <- function(x, weights) {
  sum(x*weights)
}
aggregate(stars_object, sf_polygon_object, weighted_mean, as_points = FALSE, area_overlap_weights = TRUE)
```
In the background, stars/sf would calculate the overlap areas, normalize so that they add to 1, then pass the stars values as `x` and the normalized area overlaps as `weights`.

A generalization might be to pass a function to calculate the weights from a single feature from `sf_polygon_object`. A user might want to weight using a second stars object, for example. The interface might then be something like:
```r
aggregate(stars_object, sf_polygon_object, weighted_mean, as_points = FALSE, weights = get_area_overlap_weights)
```
where `get_area_overlap_weights` takes a single polygon feature and the stars object and calculates normalized area overlap weights.

**Comment by edzer** [comment]
This is like a `stars` interface to `sf::st_interpolate_aw`, right?

**Comment by adrfantini** [comment]
Just a quick heads up: the package `areal` [provides](https://slu-opengis.github.io/areal/) some additional features compared to `sf::st_interpolate_aw`.

**Comment by kendonB** [comment]
> This is like a stars interface to sf::st_interpolate_aw, right?
Yes exactly.

**Comment by edzer** [comment]
I think the `exact = TRUE` option to `aggegate.stars` has fixed this (quite a while ago, already).
