### ISSUE TITLE
Support Sparklyr

### ISSUE THREAD

**Issue by harryprince** [r-spatial/stars#156]
Hi stars team,
    I open a issue about bringing `stars` to spark, here is the ralated issue:
https://github.com/rstudio/sparklyr/issues/1966

**Comment by edzer** [comment]
Since you seem to know something about this, it would be most helpful here if you could elaborate here a bit more on the context of this issue: what is it you'd like to achieve, why, how, by whom, when, what would it take, and so on.

**Comment by harryprince** [comment]
Goal: Wish people known `stars` can easily parallel the same pipeline on big data.
Scenario: 
** satellite image analysis **: https://medium.com/analytics-vidhya/satellite-imagery-analysis-with-python-3f8ccf8a7c32
The Way:
[RasterFrames](http://rasterframes.io/) is a great interface of Spark, which provides a DataFrame schema like `stars`.
