### ISSUE TITLE
bug in subsetting by polygon after subsetting by bbox

### ISSUE THREAD

**Issue by kendonB** [r-spatial/stars#157]
https://github.com/r-spatial/stars/files/3020397/PRISM_tmax_stable_4kmD1_19880611_bil.zip

I believe this is a bug
``` r
library(sf)
library(tidyverse)
library(stars)
x1 = read_stars("PRISM_tmax_stable_4kmD1_19880611_bil/PRISM_tmax_stable_4kmD1_19880611_bil.bil")
nc = read_sf(system.file("shape/nc.shp", package="sf"))

nc = nc %>% st_transform(st_crs(x1)) %>% filter(CNTY_ID == 2099)

nc$geometry[[1]][[1]] <- NULL

# Subset by bbox first
tmp <- x1[nc %>% st_bbox()]
# Then subset by the polygon
tmp[nc]
#> Error in x[[i]][1:22, 1:-804, drop = FALSE]: only 0's may be mixed with negative subscripts
```

Created on 2019-04-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.0.9000).

**Comment by edzer** [comment]
Thanks, good catch! Be warned that such low-level messing with geometries does not reset the object's bounding box, but you're probably aware of that.
