### ISSUE TITLE
Wrong times in 360_day file

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/stars#158]
I found `stars` is reading times wrong in this file [here](https://drive.google.com/open?id=1svIBaGgbFeqncziqfDCZCbQXlNVxgNoK) (200KB).
 The correct times are reported by `ncdump`:
```
> ncdump -t -v time subset2.nc
...
    time:units = "months since 1995-1-1 00:00:00" ;
    time:calendar = "360_day" ;
...
 time = "2000-05-01", "2000-06-01", "2000-07-01", "2000-08-01", "2000-09-01", 
    "2000-10-01", "2000-11-01", "2000-12-01", "2001-01-01", "2001-02-01", 
    "2001-03-01", "2001-04-01", "2001-05-01", "2001-06-01", "2001-07-01", 
    "2001-08-01" ;
```
```R
library(stars)
s = read_stars('subset2.nc')
st_get_dimension_values(s, 'time')
# [1] "2000-05-28 23:00:05" "2000-06-29 09:29:09" "2000-07-29 19:58:12" "2000-08-30 06:27:16" "2000-09-30 16:56:20"
# [6] "2000-11-01 03:25:24" "2000-12-01 13:54:28" "2001-01-02 00:23:32" "2001-02-02 10:52:35" "2001-03-02 21:21:39"
#[11] "2001-04-03 07:50:43" "2001-05-03 18:19:47" "2001-06-04 04:48:51" "2001-07-04 15:17:55" "2001-08-05 01:46:58"
#[16] "2001-09-05 12:16:02"
```
Notice that there is an entire month skipped (`2000-10`), too. However, other programs also seem to struggle with it. `ncview`, for example, reports the same dates as `stars`, so I am wondering what's wrong here.

I'm wondering if this is an issue in the file, or maybe in something else on which `stars` has no control?

**Comment by edzer** [comment]
Good catch! Dealing with units "months since ..." needs dedicated handling for the 360 and 365 day calendars. Hope it works now!

**Comment by adrfantini** [comment]
Do you think `years since` require the same workaround?

**Comment by edzer** [comment]
Typically the time units are chosen such that the values are integer numbers. In case of fractional numbers, for units `years since` I'd expect trouble, but who would do that? Indeed: with netCDF, because you can, somebody will.

**Comment by adrfantini** [comment]
I've seen that. I've also seen dates encoded as direct numerics, e.g. 2001-06-13 being encoded 2001.0613. You live and learn and frequently curse.
