### ISSUE TITLE
stars_proxy subset by polygon uses bbox

### ISSUE THREAD

**Issue by kendonB** [r-spatial/stars#168]
https://github.com/r-spatial/stars/files/3020397/PRISM_tmax_stable_4kmD1_19880611_bil.zip

``` r
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3
library(tidyverse)
library(stars)
#> Loading required package: abind
x1_proxy = read_stars("PRISM_tmax_stable_4kmD1_19880611_bil/PRISM_tmax_stable_4kmD1_19880611_bil.bil", proxy = TRUE)
nc = read_sf(system.file("shape/nc.shp", package="sf"))

nc = nc %>% st_transform(st_crs(x1_proxy)) %>% 
  .[1,]

read_data_first <- st_as_stars(x1_proxy)[nc]
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar

subset_first <- st_as_stars(x1_proxy[nc])

read_data_first %>% 
  st_as_sf() %>% 
  ggplot() + 
  geom_sf()
```

![](https://i.imgur.com/pXlaiWr.png)

``` r

# Seems to use the bbox, not the polygon
subset_first %>% 
  st_as_sf() %>% 
  ggplot() + 
  geom_sf()
```

![](https://i.imgur.com/fGOPR6b.png)

<sup>Created on 2019-04-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by edzer** [comment]
Thanks, yes that is inconsistent. I think this is hard to implement, and I'm inclined to document this, rather than try to make it work identically.

**Comment by edzer** [comment]
Thanks, fixed now. This turned out to be much easier than I initially thought.

**Comment by kendonB** [comment]
A while back I was using a many-GB raster using the `raster` package and found it was very slow to extract just a few pixels. Eventually I dug into the code and found it would read an entire row in the raster (millions of pixels) then subset that in R.

Leaving this issue unaddressed would lead to similar inefficiencies when people try to subset by more than 1 small but distant polygon as all the pixels in the region in between would get read in.

I'm willing to help with this, but wouldn't have time to dig into the difficult code for several months. Any guidance to get started would be helpful.

**Comment by kendonB** [comment]
Great! Is the subsetting done such that only the non-NA elements of the raster on disk get read in?

**Comment by edzer** [comment]
No, you can't read non-rectangular regions from a grid. Everything in the bounding box gets read in, and then the cropping is done  (so, if all is well, to low resolution data if you only want to plot).

**Comment by kendonB** [comment]
Is there a lot of overhead at the reading stage? Could one do it in contiguous chunks? Perhaps looping through rows then looping through contiguous chunks within a row?

I'm just thinking of use cases with high resolution or many-layer data that this would introduce noticeable inefficiencies for. A while back I wrote a patch for raster which used this approach using an R loop and I saw noticeable gains.

**Comment by edzer** [comment]
See [this](https://github.com/r-spatial/stars/blob/master/R/write.R#L61-L107) function for how stars does chunked read-process-writing.

What I haven't gotten to looking at is a read-process-write loop over the features (points, polygons) over which you want to aggregate (polygons) or from which you want to sample (points). I believe that is a quite common use case.
