### ISSUE TITLE
add vector plot to stars plot with several attributes

### ISSUE THREAD

**Issue by ibarraespinosa** [r-spatial/stars#172]
I've downloaded some data from Era Interim (t2m.rds) and I have regional  limits (netchina.rds).
I would like add the limits to the plot but it is not working.

```
library(stars)
library(sf)
library(cptcity)
# unzip data.zip
t2m <- readRDS("temp.rds")
netchina <- readRDS("netchina.rds")
plot(t2m - 273.15, 
     axes = T,  
     col = cpt(pal = find_cpt("tempe")[1]), 
     reset = F,
     main = NULL,
     key.pos = 4)
plot(netchina$geometry, add = T)

```
![fS5_temperature](https://user-images.githubusercontent.com/27447280/56628530-c050a800-667c-11e9-8b9e-95ac60a89fab.png)

I would like something like this using the code above:
![f3_temperature](https://user-images.githubusercontent.com/27447280/56628771-a8c5ef00-667d-11e9-980d-8b8048bcdb36.png)

Any ideas how to solve it? Many thanks!

[data.zip](https://github.com/r-spatial/stars/files/3110314/data.zip)

**Comment by edzer** [comment]
Thanks!
```r
library(stars)
library(sf)
library(cptcity)
# unzip data.zip
t2m <- readRDS("temp.rds")
netchina <- readRDS("netchina.rds")
png("x.png")
plot(t2m - 273.15, 
     axes = T,  
     col = cpt(pal = find_cpt("tempe")[1]), 
     reset = F,
     main = NULL,
     key.pos = 4,
	 add.geom = list(netchina$geometry))
```
now gives

![x](https://user-images.githubusercontent.com/520851/56644185-7c10d800-667b-11e9-8f52-01b5e8f47698.png)
