### ISSUE TITLE
`regular_intervals()` returns false positive for longitude that crosses international date line. 

### ISSUE THREAD

**Issue by dblodgett-usgs** [r-spatial/stars#173]
Just ran across this working on a file that crosses the date line over in `intersectr` was hoping I could steal some fancy `stars` logic... but found that this line returns positive if the `diff(range(ud)) / mean(ud)` is super negative as is the case when you cross the international date line. Plenty of ways to hack this but probably some smarter than others?

https://github.com/r-spatial/stars/blob/630f2210cfb22eb8130ebc6a27ae7c8c09e66053/R/dimensions.R#L157

```r
lon <- c(179.0625, 179.3750, 179.6875, 180.0000, -179.6875, -179.3750, -179.0625, -178.7500)
stars:::is_regular(lon)
[1] FALSE
stars:::regular_intervals(lon)
[1] TRUE
lon[1] <- lon[1] - 0.01
stars:::regular_intervals(lon)
[1] TRUE
```

**Comment by edzer** [comment]
Ah, lovely. I thought most NetCDF files would choose longitude ranging form [0, 360] in such cases to avoid exactly this, but apparently not? Where do these come from, do you have an example file? What happens if it is taken as rectilinear?

**Comment by dblodgett-usgs** [comment]
I don't have an example that crosses the date line and uses -180 to 180, but plenty of North American examples that use lon in the -180 to 0 range so I would assume there are some out there that do. 

Is this the expected behavior of is_regular? 

```r
> x <- c(358, 359, 360, 1, 2)
> stars:::is_regular(x)
[1] FALSE
> stars:::regular_intervals(x)
[1] TRUE
>
```

p.s. I just noticed that there is now a "is_regular" and a ".is_regular" -- Need both?

**Comment by edzer** [comment]
Thanks, I tried to clean them up and clarify, and fix `regular_intervals`.
