### ISSUE TITLE
Focal filter with `stars`

### ISSUE THREAD

**Issue by michaeldorman** [r-spatial/stars#176]
This is a general question - hope it's appropriate to ask here. 

As someone who just started to work with `stars` (as replacement for `raster`), I find the `raster::focal` function the most significant thing missing from `stars` at the moment. 

According to the migration table (https://github.com/r-spatial/stars/issues/122), `raster::focal` is marked as "Not present, *could* be implemented".

I was wondering whether there are any more concrete development paths in mind - 
Is it likely that that a  focal filter function will be implemented in `stars`? If not, do you think it makes sense to use a wrapper that transforms `stars`<->`raster` and uses `raster::focal`? Perhaps you are aware of any general focal filtering function in R, which is aimed at `array` object and thus may work on `stars` objects as is?

Thanks for the great work - so far enjoyed using `stars` very much!

**Comment by edzer** [comment]
After applying this patch, you can try this:
```r
library(stars)
tif = system.file("tif/L7_ETMs.tif", package = "stars")
x1 = read_stars(tif)
foc = function(x, w) {
	raster::as.matrix(raster::focal(raster::raster(x), w))
}
f = st_apply(x1, 3, foc, w = matrix(1, 3, 3))
plot(f)
```
![x](https://user-images.githubusercontent.com/520851/57775430-4b253f80-771d-11e9-9271-a6ad8c7839eb.png)

**Comment by michaeldorman** [comment]
Nice! I will use this approach, thank you very much for the help and quick reply!

**Comment by florisvdh** [comment]
I think that the `raster::raster(x)` part of the above solution should be `as(x, "Raster")`, i.e. the function provided by `stars`. It seems that `raster::raster()` does not yet accept `stars` objects.

**Comment by edzer** [comment]
Did you try? Functions passed as argument to `st_apply` receive sub-arrays, in this case matrices, not (subsetted) `stars` objects.

**Comment by florisvdh** [comment]
You are right; my mistake! Thanks for the clarification.

**Comment by jan-abel-inwt** [comment]
Hi there, i hope this the right place.

 I did the same as described above using `terra::focal` instead of `raster::focal` and it's working fine so far. 

```R
apply_focal_filter <- function(stars_slice, w) {
  # Convert the stars slice to a terra raster
  raster <- rast(stars_slice)
  # Apply the filter
  filtered_raster <- focal(
    raster,
    w,
    fun = "sum",
    expand = TRUE
  )
  mat <- as.matrix(filtered_raster)
  # mat <- transpose_flat_mat(mat)
  return(mat)
}

sf <- st_apply(
    s,
    MARGIN = "date_time", # Specifies the dimension over which to apply function
    FUN = apply_focal_filter, # The filter function wrapper for terra::focal
    w = gauss_kernel, # The Weight matrix for the filter
    CLUSTER = my.cluster, # Cluster for parallel processing
    PROGRESS = TRUE # Display progress
  )
  # Rename Attribute / Feature
  sf <- setNames(sf, "kfz_per_hour_neigh")
  # Save the filtered result into the results list
  s_filtered <- sf
}
```

However, in my particular case, my data was transposed (mirrored at the diagonal) by the `as.matrix()` function. I believe this issue might be related to the orientation of the delta of my stars object. I am generating the `stars` object from a dataframe with a `x`, `y`, `date_time` and a attribute column:

```R
dims <- c("x", "y", "date_time")
crs <- 25833

s <- st_as_stars(input, dims = dims)
st_crs(s) <- st_crs(crs)
s
```

```
stars object with 3 dimensions and 1 attribute
attribute(s), summary of first 1e+05 cells:
              Min. 1st Qu. Median     Mean 3rd Qu. Max.
kfz_per_hour     0       0      0 201.7703     287 2987
dimension(s):
          from   to         offset   delta                refsys x/y
x            1   21         387575      50 ETRS89 / UTM zone 33N [x]
y            1   21        5823175     -50 ETRS89 / UTM zone 33N [y]
date_time    1 8760 2022-01-01 CET 1 hours               POSIXct    
```

I found a workaround by transposing the matrix after applying the filter with this function:

```R
transpose_flat_mat <- function(mat) {
  # get dimension & name
  dim <- dim(mat)
  sq_dim <- sqrt(dim[1])
  name <- colnames(mat)

  # transform to square matrix & transpose
  dim(mat) <- c(sq_dim, sq_dim)
  mat <- t(mat)

  # set back to orig dimensions
  dim(mat) <- dim
  colnames(mat) <- name
  return(matrix)
}
```

Is there a more elegant solution to this issue?

**Comment by edzer** [comment]
Reading the `as.matrix()` help of package `terra`: I'm guessing you may want to try
```r
  mat <- as.matrix(filtered_raster, wide = TRUE)
```
in your `apply_focal_filter()` function.

**Comment by jan-abel-inwt** [comment]
Thanks a lot!
