### ISSUE TITLE
Subset stars based on attribute value

### ISSUE THREAD

**Issue by florisvdh** [r-spatial/stars#178]
I hope this is a sensible question; I'm yet starting with `stars`, which looks very promising to me. Maybe I still overlooked an available solution for my question.

In the `raster` package one can produce a raster subset based on the cell values (for x and y dimensions at once), e.g. :

`rasterobj[rasterobj > 10, drop  = FALSE]`

It sets the non-conforming cells to `NA`.

Further, if `rasterobj` has pure '`NA`' rows and/or columns at the edges, the following effectively crops these and reduces the extent:

`rasterobj[!is.na(rasterobj), drop  = FALSE]`

My case at hand is the last one. I could not find an equivalent 'subsetting' application in stars for this purpose, but maybe you can help.

I've looked into the [migration table](https://github.com/r-spatial/stars/wiki/How-%60raster%60-functions-map-to-%60stars%60-functions) but saw no specific mention.

**Comment by edzer** [comment]
See section 4.2.3 of http://r-spatial.org/book/ for masking out areas based on attribute(s). There is (currently) no auto-crop based on NA edges; you can use `st_crop` if you have a geometry of the crop area.

**Comment by florisvdh** [comment]
Thanks for the quick response and for the pointers, I will study this further! As this is for a workflow on several rasters where the NA edges cannot be easily predicted, I think I'll have to convert forth and back to/from raster.

I'm using `stars` now because it is successful in storing the rasters as subsets in a geopackage and because of its efficient and versatile polygonization and rasterization - that's so great!

**Comment by edzer** [comment]
See #176 for raster round tripping, but that approach might fail if the size of the sub-array changes randomly.

**Comment by florisvdh** [comment]
OK, thanks for this interesting example. (FYI, a rough prototype of the workflow, i.e. on a subset of the whole RasterBrick, is in [here](https://github.com/inbo/n2khab-inputs/blob/c6a8190c3adc44f1f254bf55da9d8f74b1fbb2a3/src/miscellaneous/GRTSmh.Rmd#L1054), but for further implementation I'll instead convert back to stars in order to write it as a geopackage subset, as prototyped [further](https://github.com/inbo/n2khab-inputs/blob/c6a8190c3adc44f1f254bf55da9d8f74b1fbb2a3/src/miscellaneous/GRTSmh.Rmd#L1203)).
