### ISSUE TITLE
write_stars using proxy requires reading entire file?

### ISSUE THREAD

**Issue by tghoward** [r-spatial/stars#179]
Howdy. This follows #74 and, it looks like, #139

Using the same example as #74, and following right to the end:

```
library(stars)
tif = system.file("tif/L7_ETMs.tif", package = "stars")
y <- read_stars(tif, proxy = TRUE)
y <- y[,,,1]
pol <- y %>% st_bbox() %>% st_as_sfc() %>% st_centroid() %>% st_buffer(200)
ysub <- y[pol]
plot(ysub)

#this doesn't work, gives "subscript out of bounds"
write_stars(ysub, dsn = "test.tif")
# this does work
write_stars(st_as_stars(ysub), dsn = "test.tif")
unlink("test.tif")
```

The problem, from what I can tell, is that `st_as_stars` forces a read of the entire, original tif, not the smaller cropped area. While the `plot` call doesn't and the image renders very quickly (even with very large original source data), `write_stars` takes forever when wrapped around `st_as_stars`. 

It looks like you already recognize this as you note that `write_stars(st_as_stars())` doesn't scale (https://github.com/r-spatial/stars/issues/139#issuecomment-470279997). 

Is there a work-around or best practice for trying to crop out a very small portion of a very large tiff and write that portion out to file, without reading the original tiff into memory?  Note I'm currently using `gdalwarp` directly (not within stars) but it changes the origin (cell locations shift slightly), a side effect I'd like to avoid.

**Comment by edzer** [comment]
I tried with this test:
```r
library(stars)
granule = system.file("sentinel/S2A_MSIL1C_20180220T105051_N0206_R051_T32ULE_20180221T134037.zip", package = "starsdata")
s2 = paste0("SENTINEL2_L1C:/vsizip/", granule, 
   "/S2A_MSIL1C_20180220T105051_N0206_R051_T32ULE_20180221T134037.SAFE/MTD_MSIL1C.xml:10m:EPSG_32632")
(y = read_stars(s2, proxy = TRUE))

y <- y[,,,1]
pol <- y %>% st_bbox() %>% st_as_sfc() %>% st_centroid() %>% st_buffer(200)
ysub <- y[pol]

system.time(write_stars(st_as_stars(ysub), dsn = "test.tif"))
```
and `st_as_stars` only  reads the subgrid selected. (see code in `stars:::fetch`).

If this doesn't work for you, please provide a real use case.

**Comment by tghoward** [comment]
Good, I'm glad it isn't doing what I suspected.  Here's a comparison with `fasterize` and `raster`
Download data here, unzip and put it in a temp folder
https://www.dropbox.com/s/gddmmr2bbm4dtvt/testRasAndClipShape.zip?dl=0

my test code 
```
setwd("D:/temp")
library(tictoc)

library(stars)
library(sf)

library(fasterize)
library(raster)

tic()
ras <- read_stars("test_raster.tif", proxy = TRUE)
clpShp <- st_read("clipShapeTest.gpkg")
ras_sub <- ras[clpShp]
write_stars(st_as_stars(ras_sub), dsn = "test_starsCrop.tif")
toc()


tic()
r <- raster("test_raster.tif")
rc <- raster::crop(r, extent(as(clpShp, "Spatial")))
cropRas <- fasterize(clpShp, rc)
rc <- raster::mask(rc, cropRas, filename = "test_rasCrop.tif")
toc()
```

my results:
```
> tic()
> ras <- read_stars("test_raster.tif", proxy = TRUE)
> clpShp <- st_read("clipShapeTest.gpkg")
Reading layer `clipShapeTest' from data source `D:\temp\clipShapeTest.gpkg' using driver `GPKG'
Simple feature collection with 1 feature and 17 fields
geometry type:  POLYGON
dimension:      XY
bbox:           xmin: -1676367 ymin: 1840535 xmax: -1606927 ymax: 1896125
epsg (SRID):    NA
proj4string:    +proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
> ras_sub <- ras[clpShp]
> write_stars(st_as_stars(ras_sub), dsn = "test_starsCrop.tif")
> toc()
35.58 sec elapsed
> 
> 
> tic()
> r <- raster("test_raster.tif")
> rc <- raster::crop(r, extent(as(clpShp, "Spatial")))
> cropRas <- fasterize(clpShp, rc)
> rc <- raster::mask(rc, cropRas, filename = "test_rasCrop.tif")
> toc()
1.41 sec elapsed
> 
```

also, file size is 16MB for `test_starsCrop` and 600KB for `test_rasCrop`.  Is this because of different choices for NA?

Thanks,
Tim

**Comment by edzer** [comment]
Thanks, very helpful, great use cae. After some muddling, I now see this:
```r
library(tictoc)

# stars:
library(stars)
# Loading required package: abind
# Loading required package: sf
# Linking to GEOS 3.7.0, GDAL 2.4.0, PROJ 5.2.0

tic()
ras <- read_stars("test_raster.tif", proxy = TRUE)
clpShp <- read_sf("clipShapeTest.gpkg")
box_crop <- st_as_stars(st_crop(ras, st_bbox(clpShp)))
rasterize <- st_rasterize(clpShp, box_crop)
# Warning message:
# In CPL_rasterize(file, driver, st_geometry(sf), as.double(as.data.frame(sf)[[1]]),  :
#   NAs introduced by coercion
box_crop[!is.na(rasterize)] = NA
write_stars(box_crop, dsn = "test_starsCrop.tif", options = "COMPRESS=LZW")
toc()
# 0.593 sec elapsed

# raster/fasterize:
library(fasterize)

library(raster)
# Loading required package: sp
tic()
r <- raster("test_raster.tif")
rc <- raster::crop(r, extent(as(clpShp, "Spatial")))
cropRas <- fasterize(clpShp, rc)
rc <- raster::mask(rc, cropRas, filename = "test_rasCrop.tif", overwrite=TRUE)
toc()
# 1.044 sec elapsed
```
Clearly, this needs more cleaning up & streamlining, but it's a start.

**Comment by tghoward** [comment]
Excellent, thank you for working on this so quickly and for tweaking and offering a fast solution. I'm glad my use case could help out here!

**Comment by tghoward** [comment]
@edzer in trying this out my first attempt was at the edge of the test raster and thus there were NAs  in box_crop outside the crop area,  and this line
`box_crop[!is.na(rasterize)] = NA`  
assumes NAs are only within the crop area. So this approach won't work as-is for me. I tried various permutations of sending extra info to GDALrasterize (following this guidance https://gdal.org/programs/gdal_rasterize.html), like this:

`st_rasterize(rng, template = box_crop, options = "-i")`
`st_rasterize(rng, template = box_crop, options = "-burn -9999")`
`st_rasterize(rng, template = box_crop, options = " -INVERT ")`
`st_rasterize(rng, template = box_crop, options = " INVERT=TRUE ")`

but nothing I tried had any effect on changing the behavior of `st_rasterize`.  Any suggestions on successfully sending options to GDALrasterize?
Thanks.

**Comment by tghoward** [comment]
I stand corrected! Your code works as written. I have a feeling I didn't correctly download your commits related to this issue. In the process of creating a shape at the edge to test this, my results came out cleanly. For the sake of completeness, here's a shape overlapping the edge of the same test raster. 

https://www.dropbox.com/s/gddmmr2bbm4dtvt/testRasAndClipShape.zip?dl=0

I still can't figure out how to send options to GDALrasterize, which might be a cleaner solution.
