### ISSUE TITLE
Can't extract values at point from stars_proxy objects

### ISSUE THREAD

**Issue by dvictori** [r-spatial/stars#181]
I'm trying to extract a time series from a point in a NetCDF file read as stars_proxy object. One problem I found is that when I read the NetCDF file, it does not know the CRS. So I need to set it when reading. When I try to extract the data, it seems like the star_proxy object looses the CRS information so I get an error:

> Error in st_crop.stars(x, i, crop = crop, ...) : 
>    for cropping, the CRS of both objects have to be identical

Here is a code to reproduce my problem.

```r
library(tidyverse)
library(stars)
library(sf)

# This is a 2.5Mb file that I created using CDO (Climate Data Operator)
ncfile <- "https://drive.google.com/uc?export=download&id=1s463jb9aIUr2Y0wl_ygGGgEMcxGkNUKF"
download.file(ncfile, "mntp_xavier_monthly_climatology.nc")

nc_proxy <- read_stars("mntp_xavier_monthly_climatology.nc", proxy = TRUE) %>%
  st_set_crs(4326)

nc_noproxy <- read_stars("mntp_xavier_monthly_climatology.nc") %>%
  st_set_crs(4326)

point <- st_sfc(st_point(c(-52, -23)), crs = st_crs(4326))

# do they line up?
plot(nc_proxy[,,,1], reset = FALSE)
plot(point, col = "red", pch = 13, add = TRUE)

# this gives error
mntp <- aggregate(nc_proxy, point, function(x) x[1], as_points = FALSE)

# this works
mntp <- aggregate(nc_noproxy, point, function(x) x[1], as_points = FALSE)
```

Also, just realized that I can access the *starts* object using `[i,x,y,t]` notation but the stars_proxy does not work.

```r
# this works
> as.data.frame(nc_noproxy[1,90,118,1:12])
         x       y       time mntp_xavier_monthly_climatology.nc
1  -51.875 -23.125 2005-01-01                           20.49445
2  -51.875 -23.125 2005-02-01                           20.25978
3  -51.875 -23.125 2005-03-01                           19.76612
4  -51.875 -23.125 2005-04-01                           18.09576
5  -51.875 -23.125 2005-05-01                           14.98275
6  -51.875 -23.125 2005-06-01                           13.54327
7  -51.875 -23.125 2005-07-01                           12.93913
8  -51.875 -23.125 2005-08-01                           14.40682
9  -51.875 -23.125 2005-09-01                           15.59009
10 -51.875 -23.125 2005-10-01                           17.63863
11 -51.875 -23.125 2005-11-01                           18.80549
12 -51.875 -23.125 2005-12-01                           19.80995

# this does not
> as.data.frame(nc_proxy[1,90,118,1:12])
             x       y       time mntp_xavier_monthly_climatology.nc
1      -74.125   6.125 2005-01-01 mntp_xavier_monthly_climatology.nc
2      -73.875   6.125 2005-01-01 mntp_xavier_monthly_climatology.nc
3      -73.625   6.125 2005-01-01 mntp_xavier_monthly_climatology.nc
4      -73.375   6.125 2005-01-01 mntp_xavier_monthly_climatology.nc
5      -73.125   6.125 2005-01-01 mntp_xavier_monthly_climatology.nc
6      -72.875   6.125 2005-01-01 mntp_xavier_monthly_climatology.nc
7      -72.625   6.125 2005-01-01 mntp_xavier_monthly_climatology.nc
8      -72.375   6.125 2005-01-01 mntp_xavier_monthly_climatology.nc
9      -72.125   6.125 2005-01-01 mntp_xavier_monthly_climatology.nc
10     -71.875   6.125 2005-01-01 mntp_xavier_monthly_climatology.nc
11     -71.625   6.125 2005-01-01 mntp_xavier_monthly_climatology.nc
(...) goes on for 326592 records
```

Am I using the stars_proxy object in a wrong way?

**Comment by edzer** [comment]
Thanks! You are using them in the the right way, it's just a bit challenging to get them do the right thing. This patch should help, although there's still some noise to be looked into.

**Comment by dvictori** [comment]
Great! It works now! Thanks

```R
> mntp <- aggregate(nc_proxy, point, function(x) x[1], as_points = FALSE)
although coordinates are longitude/latitude, st_intersects assumes that they are planar
although coordinates are longitude/latitude, st_intersects assumes that they are planar
although coordinates are longitude/latitude, st_intersects assumes that they are planar
Warning message:
In c.stars(list(mntp_xavier_monthly_climatology.nc = c(20.4537023397592,  :
  along argument ignored; maybe you wanted to use st_redimension?
> mntp
stars object with 2 dimensions and 1 attribute
attribute(s):
 mntp_xavier_monthly_climatology.nc 
 Min.   :12.88                      
 1st Qu.:14.78                      
 Median :17.82                      
 Mean   :17.14                      
 3rd Qu.:19.73                      
 Max.   :20.45                      
dimension(s):
         from to offset delta                       refsys point                    values
geometry    1  1     NA    NA +proj=longlat +datum=WGS8...  TRUE       POINT (-52.1 -23.1)
time        1 12     NA    NA                      POSIXct    NA 2005-01-01,...,2005-12-01
> as.data.frame(mntp)
              geometry       time mntp_xavier_monthly_climatology.nc
1  POINT (-52.1 -23.1) 2005-01-01                           20.45370
2  POINT (-52.1 -23.1) 2005-02-01                           20.21931
3  POINT (-52.1 -23.1) 2005-03-01                           19.71621
4  POINT (-52.1 -23.1) 2005-04-01                           18.03462
5  POINT (-52.1 -23.1) 2005-05-01                           14.92675
6  POINT (-52.1 -23.1) 2005-06-01                           13.48226
7  POINT (-52.1 -23.1) 2005-07-01                           12.87718
8  POINT (-52.1 -23.1) 2005-08-01                           14.33437
9  POINT (-52.1 -23.1) 2005-09-01                           15.53268
10 POINT (-52.1 -23.1) 2005-10-01                           17.59952
11 POINT (-52.1 -23.1) 2005-11-01                           18.76505
12 POINT (-52.1 -23.1) 2005-12-01                           19.77881
```

**Comment by rgzn** [comment]
Any thoughts on the best way to the same type of operation, but instead of producing another stars object, producing an SF object? 

IE, I would like to sample a stars raster at points from an SF points collection and add the values from the stars stack as columns to the SF object. 

This is my current code, but I feel like there should be a simpler way for a very common operation in spatial analysis. Am I doing this wrong?

```
my_stars %>% 
  aggregate(my_points,
            function(x) x[1], 
            as_points = FALSE) %>% 
  st_as_sf %>% 
  st_intersection(my_points)
```

**Comment by edzer** [comment]
You're doing this right. What would be your suggestion?

**Comment by rgzn** [comment]
I am not sure exactly, tbh. But I think a method for sfc points object might be the way to do it. The very common use case is: 

Starting with an `sfc` with geometry type `POINT` you want to add a column for each attribute of the `stars` object. 

Ideally this would be something akin to `mutate` for the `sfc` to add columns?  Maybe an `st_extract_from()` function? 

```points_sf %>% st_extract_from(my_stars)``` would return an amended sfc? 

Is there already a way to do this with dplyr verbs?

**Comment by edzer** [comment]
The difficulty I see is when the stars object is a time series of images, you end up with your times encoded (at best) as column names, and as such hard to retrieve as a time series. When returned as a stars object, they are automatically there.

In your example, without the pipe, the command would be `st_extract_from(points_sf, my_stars)`, which suggests (to me) `from` to refer to the first argument, not the second. Changing the argument order would call for the dreadful dot in the pipe form: `points_sf %>% st_extract_from(my_stars, .)` . Package `raster` uses `extract`, in the latter form `extract(from, where)`, but does not give you the time values associated with layers.

I do agree that the `aggregate` verb is not very intuitive when you want to extract the point values over coverages (rasters or polygons). In the `sf` package this is done with `st_intersection`, but then that sounds symmetric (and I believe it is).

**Comment by rgzn** [comment]
> The difficulty I see is when the stars object is a time series of images, you end up with your times encoded (at best) as column names, and as such hard to retrieve as a time series. When returned as a stars object, they are automatically there.

I see your point, and I see why this is a more complicated process than I originally envisioned. As I understand it, the only way for `sfc` or `tibble` to handle time series is to put them in a long data format? I see how this could get troublesome.

I wonder if the join verbiage from `dplyr` might be relevant here.

**Comment by edzer** [comment]
I think this can be closed now.
