### ISSUE TITLE
Allow factors in dimension values

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/stars#188]
I have one usecase where I plot my `stars` data with `ggplot` using facets (it's awesome): one facet per climatological season. The different seasons are read in alphabetical order from different files (DJF, JJA, MAM, SON) but of course I'd like to plot them in chonological order (DJF, MAM, JJA, SON).

In `ggplot`, the primary way to reorder facets is [basically](https://ggplot2.tidyverse.org/reference/facet_grid.html):

> To change plot order of facet grid,
change the order of variable levels with factor()

This does not work in `stars`:

```R
library(ggplot2)
library(stars)
tif = system.file("tif/L7_ETMs.tif", package = "stars")
x = read_stars(tif)[,,,1:2]
band_names = c('second band', 'first band')
band_factor = factor(band_names, levels = rev(band_names))
x = st_set_dimensions(x, 'band', values = band_factor)
ggplot() + geom_stars(data = x) + facet_wrap(~band)
```
![Screenshot_20190628_102456](https://user-images.githubusercontent.com/12826141/60328634-f9fca280-998e-11e9-9dcb-f4008f070e7e.png)

As you can see the ordering of the levels in `band_factor` are not respected.  
This is because the `factor` gets dropped, I guess:
```R
band_factor
# [1] second band first band 
# Levels: first band second band
st_get_dimension_values(x, 'band')
# [1] "second band" "first band"
```

**Comment by edzer** [comment]
Thanks - should work now!
