### ISSUE TITLE
read_stars limitation when reading packed netCDF variable?

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/stars#189]
I have this netCDF file which causes a very weird issue: if I read it with `read_stars` (which I want to do since it supports `along`) the values are a factor (approx?) 1e11 smaller than with `read_ncdf` (which reads it correctly).

[File link](https://drive.google.com/open?id=1f_sXnPdoWlUTGVsxGkgD0fO1M6A7yI2m)

Example:
```R
library(stars)
stars = read_stars('eobs_1d.nc')
ncdf = read_ncdf('eobs_1d.nc')
ncdf/stars
```

Maybe this has to do with the fact that the dataset has `scale_factor` and `add_offset` attributes? (This means it is [packed](https://www.unidata.ucar.edu/mailing_lists/archives/netcdfgroup/2002/msg00034.html))  
In fact, if I remove the packing (using e.g. NCO's `ncpdq -U`), everything seems to be fine.

**Comment by edzer** [comment]
Thanks - a miracle that this hasn't surfaced earlier! Note the fix is in `sf`.

**Comment by adrfantini** [comment]
Awesome, thanks!
