### ISSUE TITLE
object 'd' not found in aggregate.stars

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/stars#191]
I believe there is an issue with `aggregate.stars` for non-raster objects.
I am trying to read [this file](https://drive.google.com/open?id=1a9kNX0TSukE51f2RIyo7a6aRX0FaoMOk), as reported in another issue (#190). The aggregating file is [this one](https://drive.google.com/open?id=1zUrhVWt5nkm2VEfcnxBzTTgW0zB93ea0).

I try the following:
```R
library(stars)
library(ncdf4)
library(units)

fin = '201010.nc'
timeunit = "Seconds since 1970-01-01 00:00:00 UTC"
region_file = 'italy_istat2016_regioni.gpkg'

nc = nc_open(fin)
lon = ncvar_get(nc, 'lon')
lat = ncvar_get(nc, 'lat')

sfc = st_as_sf(
    data.frame(lon = lon, lat = lat),
    coords = 1:2,
    crs = 4326
)$geometry

regions = st_read(region_file) %>% st_transform(4326)

times = nc %>%
    ncvar_get('time') %>%
    as_units(timeunit)
pr = ncvar_get(nc, 'pr')
nc_close(nc)

dims = st_dimensions(loc = sfc, time = as.POSIXct(times))
s = st_as_stars(
    list(pr = array(pr, dim = dim(dims))),
    dimensions = dims
)

aggregate(s, regions, mean, na.rm = TRUE)
# Error in aggregate.stars(s, regions, mean, na.rm = TRUE, as_points = TRUE,  : 
#   object 'd' not found
```

I think the issue is here:
https://github.com/r-spatial/stars/blob/d64ed7c6382220f7c1d2a195658bb9b82ad836a8/R/aggregate.R#L45

**Comment by edzer** [comment]
Thanks! You were close to sending a PR, right?

**Comment by adrfantini** [comment]
Probably should have :relaxed:
