### ISSUE TITLE
How to fix a color scale for different plots?

### ISSUE THREAD

**Issue by ibarraespinosa** [r-spatial/stars#192]
Hello Edzer,

I have two stars objects with the same dimensions but different values. 
How can I create the same color scale to compare them?

Thanks

![Rplot1](https://user-images.githubusercontent.com/27447280/60421398-5d4f3480-9c1c-11e9-88c5-119e7f2cfd1e.png)
![Rplot2](https://user-images.githubusercontent.com/27447280/60421401-5de7cb00-9c1c-11e9-9a1e-1606e0bd1c70.png)

**Comment by edzer** [comment]
In case of identical dimensions you can copy over an array, as in
```r
obj1$second_map = obj2$first_map
plot(obj1)
```

**Comment by ibarraespinosa** [comment]
I tried that and it did not work

however, I tried tgis and it worked:

I converted into sf adjust manually the breaks

```
plot(st_as_sf(nee10_iea), 
     pal = cpt(rev = F, pal = find_cpt("temp")[1], colorRampPalette = T), 
     lty = 0,
     breaks =  c(seq(min(ed$BC, na.rm = T), quantile(ed$BC, .9, na.rm = T), length.out = 75),
                 seq(quantile(ed$BC, .91, na.rm = T), max(ed$BC, na.rm = T),
                     length.out=25)),
     axes  = T, #breaks = "fisher",
     reset = FALSE,
     key.pos = 1, key.length = 1)
```

It might be better approaches but it still solves my problem

Cheers!

**Comment by edzer** [comment]
Ah, I now see, I thought you wanted a shared key. For `plot.stars`, the `key.pos`, `key.length` and `breaks` arguments should also work; I believe that `pal` should be called `col`.

**Comment by ibarraespinosa** [comment]
It worked, Thank you so much!
