### ISSUE TITLE
Visual artifacts in `plot` of `stars` objects 

### ISSUE THREAD

**Issue by michaeldorman** [r-spatial/stars#194]
Perhaps this is a minor issue and not specific to `stars`, but I was interested to understand what is the reason for it, and whether there is a simple solution I'm not aware of. 

The issue is that when plotting a `stars` object and exporting to a `pdf` device, there are visual artifacts in the pattern of pixels. This depends on the PDF viewer, so I guess that it has something to do with the rendering or smoothing of the PDF file in the various PDF viewers. For example, on my computer the issue does occur in the Evince viewer, but not in the Ocular viewer. 

Interestingly, the artifacts also appear when plotting with `rasterVis::levelplot`, but not when plotting with `raster::plot` or `ggplot2::geom_stars`. The difference between the two sets of tools is revealed when zooming-in: it seems like with `stars::plot` and `rasterVis::levelplot` each pixel is surrounded by white border, while with `raster::plot` and `ggplot2::geom_stars` the pixels are drawn without gaps. 

Here is a reproducible code for producing four PDFs using the various methods:

```r
# Create 'stars' object
library(stars)
tif = system.file("tif/L7_ETMs.tif", package = "stars")
r = read_stars(tif)

# Plot - stars
pdf("plot_stars.pdf", width = 7, height = 4)
plot(r, downsample = FALSE)
dev.off()

# Plot - rasterVis
library(rasterVis)
pdf("plot_rastervis.pdf", width = 7, height = 4)
levelplot(as(r, "Raster"), par.settings = GrTheme)
dev.off()

# Plot - raster
library(raster)
pdf("plot_raster.pdf", width = 7, height = 4)
plot(as(r, "Raster"), col = grey.colors(30))
dev.off()

# Plot - ggplot2
library(ggplot2)
pdf("plot_ggplot2.pdf", width = 7, height = 4)
ggplot() + 
  geom_stars(data = r) + 
  facet_wrap(~ band) + 
  coord_fixed() + 
  scale_fill_distiller(palette = "Greys")
dev.off()
```

And here are screenshots of the way that the PDFs appear on screen.

First `stars::plot` and `rasterVis::levelplot`, *with* the artifacts: 

![Screenshot from 2019-07-16 11-42-40](https://user-images.githubusercontent.com/9386655/61279349-9d86e900-a7be-11e9-83e8-a5015bc3b051.png)

![Screenshot from 2019-07-16 11-42-54](https://user-images.githubusercontent.com/9386655/61279363-a2e43380-a7be-11e9-842a-d745245da34c.png)

And now `raster::plot` and `ggplot2::geom_stars` *without* the artifacts:

![Screenshot from 2019-07-16 11-43-00](https://user-images.githubusercontent.com/9386655/61279397-b8595d80-a7be-11e9-9533-61b894d75633.png)
![Screenshot from 2019-07-16 11-43-05](https://user-images.githubusercontent.com/9386655/61279413-be4f3e80-a7be-11e9-9c1e-fd7fc3610a24.png)

Finally, here is a zoomed-in view of the `stars::plot` and `rasterVis::levelplot` PDFs showing the gaps between pixels:

![Screenshot from 2019-07-16 11-45-37](https://user-images.githubusercontent.com/9386655/61279497-e6d73880-a7be-11e9-90f3-f0030af114a5.png)

![Screenshot from 2019-07-16 11-45-48](https://user-images.githubusercontent.com/9386655/61279505-eb035600-a7be-11e9-8f49-6ef96b19b193.png)

I apologize in advance if this is irrelevant to the development of `stars` and feel free to close the issue in such case :-)

**Comment by edzer** [comment]
Very helpful! Could you please rerun your `stars` base plot examples while adding parameter `useRaster = TRUE`, and check whether the problem disappears? It is currently only used for rgb plots, but should probably be used in all cases; this should then cause in `graphics::rasterImage` being used, which pkg `raster` seems to do by default, but `stars` currently doesn't.

**Comment by michaeldorman** [comment]
Yes! That's what I was looking for and it solves the problem - thank you very much!

Here are screenshots of the PDF with and without `useRaster=TRUE`: 

![Screenshot from 2019-07-16 13-07-55](https://user-images.githubusercontent.com/9386655/61285989-96fe6e80-a7ca-11e9-8540-e5b3d2a0254f.png)
![Screenshot from 2019-07-16 13-08-51](https://user-images.githubusercontent.com/9386655/61285996-9a91f580-a7ca-11e9-82eb-374277447e23.png)

**Comment by edzer** [comment]
I have the line
```r
options(preferRaster=TRUE)
```
in my `.Rprofile`, which seems to make this the default, but we can default to this more actively.
