### ISSUE TITLE
Subset with '[' does not work when index passed as named vector

### ISSUE THREAD

**Issue by michaeldorman** [r-spatial/stars#198]
Subsetting `stars` object does not seem to work when the index is passed as a named numeric vector. 

Here is a reproducible example. First we create a `stars` object: 

```r
# Create 'stars' object
library(stars)
d = st_dimensions(x = 1:ncol(volcano), y = 1:nrow(volcano))
r = st_as_stars(t(volcano))
r = st_set_dimensions(r, 1, offset = 0, delta = 1)
r = st_set_dimensions(r, 2, offset = nrow(volcano), delta = -1)
plot(r)
```

![unnamed-chunk-1-1](https://user-images.githubusercontent.com/9386655/62193255-16ba3a80-b380-11e9-9976-d94273a2087b.png)

and the corresponding `raster` object (for comparison): 

```r
# Create 'raster' object
library(raster)
s = as(r, "Raster")
plot(s)
```

![unnamed-chunk-1-2](https://user-images.githubusercontent.com/9386655/62193272-1cb01b80-b380-11e9-90c8-14ae4b20a664.png)

Next, a vector of column indices for subsetting raster columns 1 through 10:

```r
start = 1
end = 10
ids = start:end
```

When subsetting the `stars` object, the first two of the following work expressions work as expected:

```r
# Subset
plot(r[, 1:10, ])       # Works
plot(r[, start:end, ])  # Works
plot(r[, ids, ])        # Doesn't work!
```

But the third one, unexpectedly, doesn't work. The entire raster is returned, as if subsetting has no effect. 

The result of the first two expressions looks like this:

![unnamed-chunk-1-3](https://user-images.githubusercontent.com/9386655/62193577-b4156e80-b380-11e9-9531-92f15bf96ef4.png)

while the result of the third expression looks like this:

![unnamed-chunk-1-4](https://user-images.githubusercontent.com/9386655/62193593-c2fc2100-b380-11e9-900a-4a73dd337d33.png)

For comparison, when subsetting the `raster` object all three methods work as expected:

```r
plot(s[, 1:10, drop = FALSE])       # Works
plot(s[, start:end, drop = FALSE])  # Works
plot(s[, ids, drop = FALSE])        # Works
```

giving this result:

![unnamed-chunk-1-5](https://user-images.githubusercontent.com/9386655/62193678-ec1cb180-b380-11e9-8d45-61cb2b329904.png)

Thanks!

**Comment by edzer** [comment]
@michaeldorman are you working with the github version of `stars`? If yes, could you give me the output of your `sessionInfo()`? For me, `r[,ids,]` works as expected.

**Comment by michaeldorman** [comment]
You're right - sorry! Maybe had the CRAN version installed without noticing. Now with the GitHub version it works. 

Thanks!
