### ISSUE TITLE
Units fails when reading ecmwf weather data

### ISSUE THREAD

**Issue by bart1** [r-spatial/stars#201]
I am reading netcdf data provided by the ecmwf (era5, https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-pressure-levels?tab=form ) the units fail for quantities that have exponents in them. The units for wind speed for example is coded as (extracted using `ncdump -x era5-demoq2.nc`) :
```
    <attribute name="units" value="m s**-1" />
```
When reading this with `read_ncdf` I get warnings that the units cant be parsed
```R
> rr<-read_ncdf(ncfile)
Warning messages:
1: Could not parse expression: ‘`m`**2 `s`**-2’. Returning as a single symbolic unit() 
2: ignoring unrecognized unit: m**2 s**-2 
3: Could not parse expression: ‘`m` `s`**-1’. Returning as a single symbolic unit() 
4: ignoring unrecognized unit: m s**-1 
5: Could not parse expression: ‘`m` `s`**-1’. Returning as a single symbolic unit() 
6: ignoring unrecognized unit: m s**-1 
> rr
stars object with 4 dimensions and 4 attributes
attribute(s), summary of first 1e+05 cells:
     t [K]             z               u                  v           
 Min.   :249.1   Min.   :12340   Min.   :-18.9695   Min.   :-16.0736  
 1st Qu.:258.1   1st Qu.:13438   1st Qu.: -8.5395   1st Qu.: -4.0007  
 Median :260.2   Median :14005   Median : -4.1219   Median : -1.1547  
 Mean   :260.1   Mean   :13904   Mean   : -4.1987   Mean   : -0.2535  
 3rd Qu.:262.4   3rd Qu.:14374   3rd Qu.: -0.4942   3rd Qu.:  3.6364  
 Max.   :271.7   Max.   :14758   Max.   : 16.4199   Max.   : 16.3860  
dimension(s):
          from   to offset delta  refsys point                                      values    
longitude    1 1361  9.875  0.25      NA    NA                                        NULL [x]
latitude     1  721 90.125 -0.25      NA    NA                                        NULL [y]
level        1    3  837.5    25      NA    NA                                        NULL    
time         1    9     NA    NA POSIXct    NA 2000-04-28 21:00:00,...,2000-04-30 23:00:00    
```
It would be great if there was a way to get this correct. Currently I see two options either editing the netcdf file or after reading setting the units. Are there other options that actually read the units from the data? As I guess this is a pretty common data source I think this might be worth fixing.

**Comment by edzer** [comment]
Could you provide a dataset for checking this, or a (full) recipe getting one (I have CDS credentials)?

As alternative you could try `read_stars`, but I expect that to give the same error. As of parsing units in `units`, I see:
```r
> library(units)
> set_units(1, "m**-1", mode = "standard")
1 [1/m]
> set_units(1, "m s**-1", mode = "standard")
Error: ‘`m` `s`**-1’ is not a unit recognized by udunits or a user-defined unit
In addition: Warning message:
Could not parse expression: ‘`m` `s`**-1’. Returning as a single symbolic unit() 
> set_units(1, "m*s**-1", mode = "standard")
1 [m/s]
> set_units(1, "m s-1", mode = "standard")
1 [m/s]
```
and am smelling some inconsistency here (udunits2, the C library, is more forgiving but also entirely opaque)

**Comment by bart1** [comment]
Here is a small example using the `ecmwfr` package, the units for temperature work fine. Not the example requires to set your credentials using the `wf_set_key` function and require you to fill out your numeric user id for cds.

```R
require(stars)
require(ecmwfr)
request <- list("dataset"        = "reanalysis-era5-pressure-levels",
                "product_type"   = "reanalysis",
                "variable"       = c("temperature", 'geopotential','u_component_of_wind'),
                "pressure_level" = c("850",'875'),
                "year"           = "2000",
                "month"          = "04",
                "day"            = c('30'),
                "time"           = c('22:00','23:00'),
                "area"           = "10/0/5/5",
                "format"         = "netcdf",
                "target"         = "test.nc")
#> wf_set_key('uid','api key',service = 'cds')
ncfile <- wf_request(user = "uid",
                     request = request,   
                     transfer = TRUE,  
                     path = "~",
                     verbose = FALSE)
rr<-read_ncdf(ncfile)
```

Sorry for the extra dependency on `ecmwfr`

ps are there any good example/tutorials on intersection/interpolations of spatial temporal data using `stars`?

**Comment by edzer** [comment]
Thanks! This is somewhat hacky, but I now get:
```r
> rr
stars object with 4 dimensions and 3 attributes
attribute(s):
     t [K]        z [m^2/s^2]       u [m/s]        
 Min.   :291.3   Min.   :12402   Min.   :-3.95663  
 1st Qu.:292.3   1st Qu.:12474   1st Qu.:-0.99035  
 Median :293.2   Median :13704   Median :-0.09743  
 Mean   :293.3   Mean   :13702   Mean   :-0.06167  
 3rd Qu.:293.8   3rd Qu.:14931   3rd Qu.: 0.87562  
 Max.   :297.5   Max.   :14997   Max.   : 4.78096  
dimension(s):
      from to                  offset          delta  refsys point values    
x        1 21                  -0.125           0.25      NA    NA   NULL [x]
y        1 21                  10.125          -0.25      NA    NA   NULL [y]
level    1  2         850 [millibars] 25 [millibars]      NA    NA   NULL    
time     1  2 2000-04-30 22:00:00 UTC        1 hours POSIXct    NA   NULL    
```

**Comment by edzer** [comment]
Re: your question _are there any good example/tutorials on intersection/interpolations of spatial temporal data using stars?_ - could you pls elaborate what you're after?

* kriging interpolation: see [here](https://keen-swartz-3146c4.netlify.com/interpolation.html)
* grid warping: `st_warp`, which can use GDAL's gdalwarp options
* aggregate: aggregates over spatial regions, or temporal periods
* `st_join` under development - will join both space and time

**Comment by bart1** [comment]
On the question, I'm currently developing the project. I'm roughly speaking predicting bird migration based on weather variables. To do so I need to annotate a dataset of observation point/region with these weather variables/ derivatives there off. `Aggregate` works nicely for aggregating within the polygon but still require a time interpolation.  `st_wrap` as far as I quickly tested warps the spatial grid but does not do interpolation in other dimensions. Thanks for the link to the kriging chapter that looks interesting. I will have a look at `st_join` in the future.

**Comment by edzer** [comment]
OK, thanks. Maybe a case for [trilinear interpolation](https://en.wikipedia.org/wiki/Trilinear_interpolation)?
