### ISSUE TITLE
'st_warp' does not work on cropped raster 

### ISSUE THREAD

**Issue by michaeldorman** [r-spatial/stars#209]
I get an error when applying `st_warp` on cropped raster. 

With a "complete" raster, e.g., one read from file, `st_warp` works fine. For example:

``` r
# Create 'stars' object
library(stars)
tif = system.file("tif/L7_ETMs.tif", package = "stars")
r = read_stars(tif)
r = r[, , , 1]
plot(r)
```

![unnamed-chunk-1-1](https://user-images.githubusercontent.com/9386655/62980608-b7ecca80-be2f-11e9-952a-2fd772ea4dc7.png)

``` r
# Warp 1
s = st_warp(r, crs = st_crs(r), cellsize = 300)
plot(s)
```

![unnamed-chunk-1-2](https://user-images.githubusercontent.com/9386655/62981185-4a419e00-be31-11e9-9bdd-1a0dc2a38146.png)

However, after creating a subset of the raster, using `st_crop`, and trying to "warp" the subset, the `st_warp` function gives an error:

``` r
# Subset
ext = st_as_sf(r[1, 87, 89], as_points = TRUE)
ext = st_buffer(ext, 2000, endCapStyle = "SQUARE")
r = r[ext]
plot(r)
```

![unnamed-chunk-1-3](https://user-images.githubusercontent.com/9386655/62981222-62192200-be31-11e9-9470-cce21ab10662.png)

```r
# Warp 2a
r
```

    ## stars object with 3 dimensions and 1 attribute
    ## attribute(s):
    ##   L7_ETMs.tif    
    ##  Min.   : 52.00  
    ##  1st Qu.: 60.00  
    ##  Median : 64.00  
    ##  Mean   : 65.48  
    ##  3rd Qu.: 69.00  
    ##  Max.   :145.00  
    ## dimension(s):
    ##      from  to  offset delta                       refsys point values    
    ## x      17 157  288776  28.5 +proj=utm +zone=25 +south... FALSE   NULL [x]
    ## y      19 159 9120761 -28.5 +proj=utm +zone=25 +south... FALSE   NULL [y]
    ## band    1   1      NA    NA                           NA    NA   NULL

``` r
s = st_warp(r, crs = st_crs(r), cellsize = 300)
```

Gives an error:

    ## Error in matrix(1:prod(dims[dxy]), dims[dxy[1]], dims[dxy[2]])[xy]: subscript out of bounds

Transforming the subset to a `Raster*` object and back to `stars` solves the issue:

``` r
# Warp 2b
r = as(r, "Raster")
r = st_as_stars(r)
r
```

    ## stars object with 2 dimensions and 1 attribute
    ## attribute(s):
    ##      layer       
    ##  Min.   : 52.00  
    ##  1st Qu.: 60.00  
    ##  Median : 64.00  
    ##  Mean   : 65.48  
    ##  3rd Qu.: 69.00  
    ##  Max.   :145.00  
    ## dimension(s):
    ##   from  to  offset delta                       refsys point values    
    ## x    1 141  289232  28.5 +proj=utm +zone=25 +south...    NA   NULL [x]
    ## y    1 141 9120248 -28.5 +proj=utm +zone=25 +south...    NA   NULL [y]

``` r
s = st_warp(r, crs = st_crs(r), cellsize = 300)
plot(s)
```

![unnamed-chunk-1-5](https://user-images.githubusercontent.com/9386655/62981293-88d75880-be31-11e9-83d2-2671b57f651b.png)

From what I could tell the transformation changes the from/to values in the subset. In the result of `st_crop` the original indices are kept:
    
    ##      from  to  offset delta                       refsys point values    
    ## x      17 157  288776  28.5 +proj=utm +zone=25 +south... FALSE   NULL [x]
    ## y      19 159 9120761 -28.5 +proj=utm +zone=25 +south... FALSE   NULL [y]

while after the conversion to `Raster*` and back to `stars` the indices are reset to begin from `1`, which is when `st_warp` works again. 

    ##   from  to  offset delta                       refsys point values    
    ## x    1 141  289232  28.5 +proj=utm +zone=25 +south...    NA   NULL [x]
    ## y    1 141 9120248 -28.5 +proj=utm +zone=25 +south...    NA   NULL [y]

Is there an issue with `st_warp` and x-y dimension indices not starting from 1? And generally, is there a meaning to the original indices being kept? Is there a way to "reset" the indices to begin from 1?

Thanks a lot for any suggestion!

**Comment by edzer** [comment]
```r
st_warp(st_normalize(r))
```
but you are right, this is of course a bug.

**Comment by michaeldorman** [comment]
It works now, thank you very much!
