### ISSUE TITLE
plot() is not showing all the data

### ISSUE THREAD

**Issue by Nowosad** [r-spatial/stars#216]
Lately, I found out that **stars**' `plot()` does not show some values in some cases (I think it is the maximum value in this case). 
You can find the white cell in the northern part of the map. However, this cell has a value as shown in the **raster**'s `plot()` below.

```r
library(stars)
srtm_stars = read_stars("srtm.tif")

my_palette = hcl.colors(10, palette = "ag_Sunset")
plot(srtm_stars, col = my_palette)
```

![Rplot](https://user-images.githubusercontent.com/3457131/64514927-ee611c80-d2eb-11e9-91bb-d827b610cead.png)

```r
library(raster)
srtm_raster = raster("srtm.tif")
plot(srtm_raster)
```
![Rplot01](https://user-images.githubusercontent.com/3457131/64514924-ebfec280-d2eb-11e9-960f-93358901e7fa.png)

My dataset: [srtm.zip](https://github.com/r-spatial/stars/files/3589406/srtm.zip)

**Comment by edzer** [comment]
Thanks! Should work now.
