### ISSUE TITLE
Order of dimensions

### ISSUE THREAD

**Issue by michaeldorman** [r-spatial/stars#219]
Perhaps it is reasonable that the `"x"` and `"y"` dimensions, when present, should be consistently placed as 1st and 2nd dimensions of a `stars` object. This is often the case, but not always. For example, an `st_apply` on dimensions `c("x", "y")` using a `FUN` that returns more than one value per pixel (e.g., `range`) places the new dimension at the 1st position, so that `"x"` and `"y"` become the 2nd and 3rd dimensions, and also gives the new dimension a specific name depending on `FUN`:

``` r
# Create 'stars' object
library(stars)
x = read_stars(system.file("tif/L7_ETMs.tif", package = "stars"))

# Run 'st_apply' with 'range'
y = st_apply(x, 1:2, range)
y
```

    ## stars object with 3 dimensions and 1 attribute
    ## attribute(s):
    ##   L7_ETMs.tif    
    ##  Min.   :  1.00  
    ##  1st Qu.: 50.00  
    ##  Median : 71.00  
    ##  Mean   : 72.44  
    ##  3rd Qu.: 96.00  
    ##  Max.   :255.00  
    ## dimension(s):
    ##       from  to  offset delta                       refsys point values    
    ## range    1   2      NA    NA                           NA    NA   NULL    
    ## x        1 349  288776  28.5 +proj=utm +zone=25 +south... FALSE   NULL [x]
    ## y        1 352 9120761 -28.5 +proj=utm +zone=25 +south... FALSE   NULL [y]

To work with the new dimension, one needs to know its name or index:

``` r
# To do this I need to know in advance that the new dimension
# is named "range" or that it's index is 1
y = st_set_dimensions(y, "range", values = c("min", "max"))  # or
y = st_set_dimensions(y, 1, values = c("min", "max"))
y
```

    ## stars object with 3 dimensions and 1 attribute
    ## attribute(s):
    ##   L7_ETMs.tif    
    ##  Min.   :  1.00  
    ##  1st Qu.: 50.00  
    ##  Median : 71.00  
    ##  Mean   : 72.44  
    ##  3rd Qu.: 96.00  
    ##  Max.   :255.00  
    ## dimension(s):
    ##       from  to  offset delta                       refsys point   values
    ## range    1   2      NA    NA                           NA    NA min, max
    ## x        1 349  288776  28.5 +proj=utm +zone=25 +south... FALSE     NULL
    ## y        1 352 9120761 -28.5 +proj=utm +zone=25 +south... FALSE     NULL
    ##          
    ## range    
    ## x     [x]
    ## y     [y]

Is there a way to "standardize" a 'stars' object so that dimensions `"x"` and `"y"` are placed as dimensions 1 and 2? That way, in an operation such as above the new dimension is always going to be 3rd and then can be referred to by index `3`. Or, more in general, to reorder dimensions in any custom way? 

Thanks for any comments or ideas!

**Comment by edzer** [comment]
The reason for this is that it is consistent with `base::apply`:
```r
> dim(apply(matrix(runif(12), 3, 4), 1, range))
[1] 2 3
> dim(apply(matrix(runif(12), 3, 4), 2, range))
[1] 2 4
```
and (you probably know that) you can reorder dimensions with
```r
> aperm(y, c(2,3,1))
stars object with 3 dimensions and 1 attribute
attribute(s):
  L7_ETMs.tif    
 Min.   :  1.00  
 1st Qu.: 50.00  
 Median : 71.00  
 Mean   : 72.44  
 3rd Qu.: 96.00  
 Max.   :255.00  
dimension(s):
      from  to  offset delta                       refsys point values    
x        1 349  288776  28.5 +proj=utm +zone=25 +south... FALSE   NULL [x]
y        1 352 9120761 -28.5 +proj=utm +zone=25 +south... FALSE   NULL [y]
range    1   2      NA    NA                           NA    NA   NULL    
```
I am with you that it may be more convenient, for many, `st_apply` returned objects like this; I didn't do it because I wanted to make as few as possible modifications to what `base::apply` does. I'm not sure where the sweet spot is.

**Comment by michaeldorman** [comment]
Didn't know about `aperm` which solves the issue, and agree that it makes sense to be consistent with `apply`. Thanks, this is clear now!
