### ISSUE TITLE
Rotation does not preserve grid cell area

### ISSUE THREAD

**Issue by antoinedi** [r-spatial/stars#220]
Not sure if it was made deliberately, but if I am not mistaken, grid rotation does not preserve cell area:

```
library(sf)
library(stars)

m = matrix(1:20, nrow = 5, ncol = 4)
dim(m) = c(x = 5, y = 4) # named dim
(s = st_as_stars(m))

st_area(st_as_sf(s, as_points = FALSE))

a1 <- -0.5
a2 <- 0.5

attr(attr(s, "dimensions"), "raster")$affine = c(a1, a2)
st_area(st_as_sf(s, as_points = FALSE))

```

It can be handled by multiplying delta values with the cosine of the rotation angle, then you get a rotated grid with the same cell area than the original:

```
dx <- 1
dy <- 1

attr(s, "dimensions")[[1]]$delta = sqrt(1 - (a2/dx)^2) * dx
attr(s, "dimensions")[[2]]$delta = sqrt(1 - (a1/dy)^2) * dy

attr(attr(s, "dimensions"), "raster")$affine = c(a1, a2)
st_area(st_as_sf(s, as_points = FALSE))

```

Anyway maybe it would be good to have a rotation option that preserve area and length without this trick?

**Comment by edzer** [comment]
Setting the affine parameters directly was never meant to preserve area. Yes, it would be good to have a function that gets and sets the complete affine parameters, and that could include and handle a "rotate" parameters - how it needs to be done now looks very clumsy.

**Comment by antoinedi** [comment]
Yes, indeed, not a nice solution. Maybe a better one would be to integrate the cosine of the rotation angle in the two equations showed in r-spatial/stars, article 4: 

x= ox + (i−1) dx + (j−1) a1

y= oy + (i−1) a2+ (j−1) dy 

They would then become:

x= ox + (i−1) dx sqrt(1-(a2/dx)^2) + (j−1) a1

y= oy + (i−1) a2+ (j−1) dy sqrt(1-(a1/dy)^2) 

I made a short example and it seems to preserve the distance between points when a1 = −a2:

```

library(tidyverse)

Ox <- 3

Oy <- 3

i <- rep(1:5, 4)

j <- rep(1:4, each = 5)

dx <- 2

dy <- 2

a1 <- 0
  
a2 <- 0 

ij_xy <- tibble(i = i, j = j) %>%  
  mutate(x = Ox + (i-1) * dx + (j-1) * a1,
         y = Oy + (j-1) * dy + (i-1) * a2)


a1 <- -1

a2 <- 1

ij_xy_rot <- tibble(i = i, j = j) %>%  
  mutate(x = Ox + (i-1) * dx + (j-1) * a1,
         y = Oy + (j-1) * dy + (i-1) * a2)



ij_xy_rot_cor <- tibble(i = i, j = j) %>%  
  mutate(x = Ox + (i-1) * dx * sqrt(1 - (a2/dx)^2) + (j-1) * a1,
         y = Oy + (j-1) * dy * sqrt(1 - (a1/dy)^2)  + (i-1) * a2)

ggplot() + aes(x, y) + geom_point(data = ij_xy) +
  geom_point(data = ij_xy_rot, aes(col = "rot")) + geom_point(data = ij_xy_rot_cor, aes(col = "rot_cor"))


ij_xy <- ij_xy %>%  
  mutate(D = sqrt((x - ij_xy$x[1])^2 + (y - ij_xy$y[1])^2))

ij_xy_rot <- ij_xy_rot %>%  
  mutate(D = sqrt((x - ij_xy_rot$x[1])^2 + (y - ij_xy_rot$y[1])^2))

ij_xy_rot_cor <- ij_xy_rot_cor %>%  
  mutate(D = sqrt((x - ij_xy_rot_cor$x[1])^2 + (y - ij_xy_rot_cor$y[1])^2))


round(ij_xy$D - ij_xy_rot$D, 10)

round(ij_xy$D - ij_xy_rot_cor$D, 10)

```

Hope this can help and thanks for developing this package, I have been working with it since few days and it is so great to use together with sf.

**Comment by edzer** [comment]
Close?

**Comment by antoinedi** [comment]
Yes sure, thanks for your answer.
