### ISSUE TITLE
read_stars: cannot allocate vector of size

### ISSUE THREAD

**Issue by BatuhanKavlak** [r-spatial/stars#224]
I have a 62,2 GB satellite image with 44 bands as tif file. I can get the image with raster::brick() function and it is like so:

```
inImageName <-'201907_maras_antep_merged_true.tif'

satImage <- raster::brick(inImageName)

> satImage
class      : RasterBrick 
dimensions : 22215, 15903, 353285145, 44  (nrow, ncol, ncell, nlayers)
resolution : 10, 10  (x, y)
extent     : 250770, 409800, 4057110, 4279260  (xmin, xmax, ymin, ymax)
crs        : +proj=utm +zone=37 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0 
source     : /home/doktar-ziya/Desktop/201907_maras_antep_merged_true.tif 
names      : X201907_maras_antep_merged_true.1, X201907_maras_antep_merged_true.2, X201907_maras_antep_merged_true.3, X201907_maras_antep_merged_true.4, X201907_maras_antep_merged_true.5, X201907_maras_antep_merged_true.6, X201907_maras_antep_merged_true.7, X201907_maras_antep_merged_true.8, X201907_maras_antep_merged_true.9, X201907_maras_antep_merged_true.10, X201907_maras_antep_merged_true.11, X201907_maras_antep_merged_true.12, X201907_maras_antep_merged_true.13, X201907_maras_antep_merged_true.14, X201907_maras_antep_merged_true.15, ... 

```

However, when I want to use stars::read_stars() function:

```
> starsImage <- read_stars(inImageName)

Error: cannot allocate vector of size 115.8 Gb
```
I've been dealing with raster operations for 6 months. I am trying to optimize my operations with stars and sf packages.  My goal is to select training pixel values from the image with a polygon series. I stuck at reading the image. Maybe I need to do it without getting all the image at the first, but I couldn't get why I can get the image with brick() function but not with read_stars()

**Comment by edzer** [comment]
Currently, `read_stars` tries to read the entire file in memory, which fails. You can read it as a `stars_proxy` object, not in memory, by
```{r}
starsImage <- read_stars(inImageName, proxy = TRUE)
```
and then use `plot`.

**Comment by BatuhanKavlak** [comment]
Thank you!

I can use ``` nngeo::raster_extract() ``` function on proxy stars as well. I can select pixels randomly now after I get points with st_sample.
