### ISSUE TITLE
Mask hills etc i.e. sf objects (reverse st_crop)

### ISSUE THREAD

**Issue by singhkpratham** [r-spatial/stars#226]
New user here.

I have one raster and one sf object with multiple linestrings. I want to remove/mask out the sf objects (lines/polygons). st_crop does the reverse, ie it crops the raster (stars) object to where the sf objects are. I want the sf objects (the overlapping area) to be set as NA, rather than non-overlapping to be set as NAs.
Eg:
```
tif = system.file("tif/L7_ETMs.tif", package = "stars") %>% read_stars()
tif = tif[,,,1]
pt=c(st_bbox(tif)[c(1,3)] %>% mean ,
     st_bbox(tif)[c(2,4)] %>% mean) %>%
  st_point() %>% st_geometry()
st_crs(pt) = st_crs(tif)

plot(tif, axes=T, reset=F)
plot(pt,add=T,size=100, pch=4, col='red')
# stars output
st_crop(tif, st_buffer(pt,5000)) %>% plot
a=raster::mask(tif %>% as('Raster'),
             st_buffer(pt,4000) %>% as_Spatial(), inverse=T ) 
#what is required. weird that a %>% plot is giving error
ggplot()+geom_stars(data=a %>% st_as_stars())
```
Getting:
![image](https://user-images.githubusercontent.com/22996016/68216221-93575780-0006-11ea-83ee-162d4799d25d.png)

Required:
![image](https://user-images.githubusercontent.com/22996016/68216263-a23e0a00-0006-11ea-9f6d-23ed754ab9b3.png)

Another way
```
# works similar to st_crop
tif[a] %>% plot 
# assignment doesnt work
tif[a] = NA
Error in `[<-.stars`(`*tmp*`, st_buffer(pt, 4000), value = NA) : 
  selector should be a stars object
tif[st_buffer(pt,4000) %>% st_as_stars()] 
Error in x[i] : invalid subscript type 'list'
```

Apologies if it has been addressed earlier. I have spent literally 2 days searching issues and google, couldn't find any solution except for using raster package.

**Comment by edzer** [comment]
The "weird" error you notice is caused by package `raster` not being loaded. Note that `a` is a `Raster` object, you can't use that in expressions involving `stars` objects without converting. 

I tried this:
```r
crp = st_crop(tif, st_buffer(pt,5000), crop = FALSE)
plot(tif * ifelse(is.na(crp[[1]]), 1, NA))
```
![x](https://user-images.githubusercontent.com/520851/68248283-cc9ac200-001c-11ea-858a-adc5123ccb2c.png)

**Comment by singhkpratham** [comment]
Aah, simple matrix manipulation. 
Apologies for asking such question. My brain is still learning about the nitty gritties of how data is being stored in the background. eg today I found out that dimension of raster and star objects are basically inverted. 
```
r = raster()
r = raster(nrow=15,ncol=10)
r[] = 1:150
r %>% dim
 [1] 15 10  1  # as expected
r %>% st_as_stars %>% dim
r %>% st_as_stars %>% .[[1]] %>% dim 
[1] 10 15
```
Gotta read the book again!

Do you intend to add a 'inverse = TRUE' argument to st_crop which will basically do the `tif * ifelse(is.na(crp[[1]]), 1, NA)` automatically?

**Comment by mdsumner** [comment]
Actually, they are not inverted, raster stores flat (implicit dim) - like a single column (RasterLayer) or multi-colum matrix (RasterBrick/Stack). stars stores matrix or array  (explicit dim) within a list

If you use base graphics and matrix/array R stores pixel values down columns, the `image()` you see is counting from the left-to-right-up. stars and raster have the same storage orientation, and actually `image()` is different. 



``` r
  r <- raster::raster(volcano)
  
s <- stars::st_as_stars(r)
names(s) <- "stars"
par(mfrow = c(2, 2), mar = c(0, 0, 0.8, 0))
raster::image(r, axes = F, main = "raster", asp = 1)
raster::plot(r, axes = F, main = "stars")  ## so we get the same usr space
plot(s, add = TRUE, reset = FALSE)

all(r[] == s[[1]])
#> [1] TRUE

image(volcano, asp = 1, main = "image()")

## a bit more discussion: https://hypertidy.github.io/ffraster/articles/dimension-order.html
```

![](https://i.imgur.com/9PSuHe7.png)

<sup>Created on 2019-11-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
