### ISSUE TITLE
Setting units has no effect when selecting attribute with '$'

### ISSUE THREAD

**Issue by michaeldorman** [r-spatial/stars#228]
Trying to set the units of a particular attribute in a `stars` object works when selecting it with `[[` but not with `$`:

``` r
library(stars)
library(units)
```

``` r
# This works
r = read_stars(system.file("tif/L7_ETMs.tif", package = "stars"))
r[[1]] = set_units(r[[1]], "°")
str(r[[1]])
```

    ## Object of class units:
    ##  num [1:349, 1:352, 1:6] 69 69 63 60 61 61 62 60 64 63 ...
    ##  - attr(*, "units")=List of 2
    ##   ..$ numerator  : chr "°"
    ##   ..$ denominator: chr(0) 
    ##   ..- attr(*, "class")= chr "symbolic_units"

``` r
# This works
r = read_stars(system.file("tif/L7_ETMs.tif", package = "stars"))
r[["L7_ETMs.tif"]] = set_units(r[["L7_ETMs.tif"]], "°")
str(r[[1]])
```

    ## Object of class units:
    ##  num [1:349, 1:352, 1:6] 69 69 63 60 61 61 62 60 64 63 ...
    ##  - attr(*, "units")=List of 2
    ##   ..$ numerator  : chr "°"
    ##   ..$ denominator: chr(0) 
    ##   ..- attr(*, "class")= chr "symbolic_units"

``` r
# This doesn't work!
r = read_stars(system.file("tif/L7_ETMs.tif", package = "stars"))
r$L7_ETMs.tif = set_units(r$L7_ETMs.tif, "°")
str(r[[1]])
```

    ##  num [1:349, 1:352, 1:6] 69 69 63 60 61 61 62 60 64 63 ...

I was wondering whether there is a reason for this behavior or whether it is a bug. 

Thanks for any help!

**Comment by edzer** [comment]
Thanks! - should work now.

**Comment by michaeldorman** [comment]
It works now, thank you very much!

``` r
library(stars)
library(units)
```

``` r
# Works
r = read_stars(system.file("tif/L7_ETMs.tif", package = "stars"))
r[[1]] = set_units(r[[1]], "°")
str(r[[1]])
```

    ## Object of class units:
    ##  num [1:349, 1:352, 1:6] 69 69 63 60 61 61 62 60 64 63 ...
    ##  - attr(*, "units")=List of 2
    ##   ..$ numerator  : chr "°"
    ##   ..$ denominator: chr(0) 
    ##   ..- attr(*, "class")= chr "symbolic_units"

``` r
# Works
r = read_stars(system.file("tif/L7_ETMs.tif", package = "stars"))
r[["L7_ETMs.tif"]] = set_units(r[["L7_ETMs.tif"]], "°")
str(r[[1]])
```

    ## Object of class units:
    ##  num [1:349, 1:352, 1:6] 69 69 63 60 61 61 62 60 64 63 ...
    ##  - attr(*, "units")=List of 2
    ##   ..$ numerator  : chr "°"
    ##   ..$ denominator: chr(0) 
    ##   ..- attr(*, "class")= chr "symbolic_units"

``` r
# Works
r = read_stars(system.file("tif/L7_ETMs.tif", package = "stars"))
r$L7_ETMs.tif = set_units(r$L7_ETMs.tif, "°")
str(r[[1]])
```

    ## Object of class units:
    ##  num [1:349, 1:352, 1:6] 69 69 63 60 61 61 62 60 64 63 ...
    ##  - attr(*, "units")=List of 2
    ##   ..$ numerator  : chr "°"
    ##   ..$ denominator: chr(0) 
    ##   ..- attr(*, "class")= chr "symbolic_units"
