### ISSUE TITLE
Is there a need to have (by default) an xml file next to the gpkg file?

### ISSUE THREAD

**Issue by florisvdh** [r-spatial/stars#229]
When executing `write_stars(dsn = "myfile.gpkg", driver = "GPKG")` I get not only a `gpkg` file (which I would expect) but also an xml file `myfile.gpkg.aux.xml` with following contents:

```
<PAMDataset>
  <Metadata domain="IMAGE_STRUCTURE">
    <MDI key="INTERLEAVE">PIXEL</MDI>
  </Metadata>
  <Metadata>
    <MDI key="IDENTIFIER">myfile</MDI>
  </Metadata>
</PAMDataset>
```
What is this file? In other usecases (`sf`, `raster`), the file is not generated and at first sight it seems not necessary to me to have it. Can it be prevented from being generated, for the sake of neat workflows? Is it GDAL doing this?

Thanks for your time and your splendid work.

**Comment by mdsumner** [comment]
I don't see that, can you check the value of this? 

```R
Sys.getenv("GDAL_PAM_ENABLED")
```

Mine is "", and running this might prevent creation: 

```R
Sys.setenv(GDAL_PAM_ENABLED=NO")
```

https://gdal.org/doxygen/classGDALPamDataset.html#details 

BTW, how do you read such a file? Does that work? I can't get it to.

**Comment by florisvdh** [comment]
```
> Sys.getenv("GDAL_PAM_ENABLED")
[1] ""
```
I'm on GDAL 2.2.2

Reading back in the GPKG file with `read_stars("myfile.gpkg")` works. Also after manually deleting the xml file.

Just to be more clear, this is for a usecase with rasters. `stars::write_stars()` does support adding extra raster layers in a GPKG file (by providing `options = "APPEND_SUBDATASET=YES"` for GDAL), while I could not do that with `raster::writeRaster()`. Using a `RasterLayer` in `stars` works with `st_as_stars()`

**Comment by florisvdh** [comment]
But, indeed your suggestion to do `Sys.setenv(GDAL_PAM_ENABLED="NO")` is successful :+1: Thanks for the hint!

Maybe `raster` does actively set this, while `stars` does not? Anyway GDAL_PAM_ENABLED seems to be set by default to 'YES' (within GDAL) according to the hyperlink you provided, so it seems to be GDAL behaviour. That also explains why this variable does not need to be in the environment to have a 'YES' by default (GDAL-builtin):
> Note: The default value is build dependent and defaults to YES in Windows and Unix builds.

So maybe you're on a Mac then?

**Comment by mdsumner** [comment]
No Ubuntu.
