### ISSUE TITLE
str problem with units class

### ISSUE THREAD

**Issue by mdsumner** [r-spatial/stars#23]
I see

```R
x <- read_stars(system.file("nc/reduced.nc", package = "stars"))
str(x)
#List of 4
# $ sst :Error in Ops.units(ao, 1e-10) : 
# both operands of the expression should be "units" objects
```
I can't see where this is happening, it makes things a bit hard because the units are not at all relevant for mechanical uses, though I can unclass to get the information needed, but only if I know something about the structure already i.e. 

```R
str(unclass(x))  ## no help

str(unclass(x[[1]]))  ## now I have hook

```

Is there any way we could lighten up on the units formality to make exploration easier?

**Comment by edzer** [comment]
It's a known issue for `units`: https://github.com/r-quantities/units/issues/100

**Comment by edzer** [comment]
... which has now been closed. Thanks!

**Comment by mdsumner** [comment]
Ah, awesome - thanks
