### ISSUE TITLE
calculate ndvi for every time step on stars proxy

### ISSUE THREAD

**Issue by przell** [r-spatial/stars#231]
I would like to calculate the ndvi on every time step of a 4d data cube (x, y, bands, time) in on an stars proxy object. Do you have any ideas of how to achieve this on the proxy object? My current approach throws the error:
> Error in ds[-MARGIN] : only 0's may be mixed with negative subscripts
Here is the code that produces this error:
```
tif = system.file("tif/L7_ETMs.tif", package = "stars")
t1 = as.Date("2018-07-31")
x_prox = read_stars(c(tif, tif, tif, tif), 
               along = "time", 
               RasterIO = list(nXOff = c(1), 
                               nYOff = c(1), 
                               nXSize = 50, 
                               nYSize = 50, 
                               bands = c(1:6)), 
               proxy = TRUE) # FALSE will produce correct results
x_prox = stars::st_set_dimensions(.x = x_prox, which = "time", 
                                  values = c(t1, t1+1, t1+2, t1+3))
st_dimensions(x_prox)
st_get_dimension_values(x_prox, "time")

calc_ndvi = function(x) (x[2] - x[1])/(x[2] + x[1])
x_prox = st_apply(X = x_prox, MARGIN = c("x", "y", "time"), FUN = calc_ndvi)
x_prox_ndvi = st_as_stars(x_prox)
```
Changing `proxy = FALSE` returns correct values. I would have expected the same behavior on proxy objects as on none proxy objects. This is why I placed the issue here. I have also opened a gis.stackexchange question [here](https://gis.stackexchange.com/questions/343788/r-stars-calculate-ndvi-for-every-time-step-on-stars-proxy)

**Comment by edzer** [comment]
This should fix it; please close the SO question yourself.

**Comment by przell** [comment]
Yes, the fix worked. Thanks! I will close the SO question.
