### ISSUE TITLE
read_stars() does not pass driver argument to gdal_read()

### ISSUE THREAD

**Issue by djnavarro** [r-spatial/stars#237]
As far as I can tell the driver argument to read_stars() should be passed to gdal_read() to allow the user to override driver autodetection. The current version sets `driver=character(0)` in the call to gdal_read() rather than passing the user-specified value. At the risk of using the dreaded phrase, this works for me... :slightly_smiling_face: 

https://github.com/r-spatial/stars/compare/master...djnavarro:drivers?expand=1

**Comment by edzer** [comment]
Yes, I now merged this. Thanks!
