### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by fipoucat** [r-spatial/stars#239]
I am installing stars on mac but getting error message:

library(stars)
Loading required package: abind
Loading required package: sf
Linking to GEOS 3.7.2, GDAL 2.4.2, PROJ 5.2.0
Error: package or namespace load failed for ‘stars’:
 .onLoad failed in loadNamespace() for 'stars', details:
  call: get(genname, envir = envir)
  error: object 'as.tbl_cube' not found

Hope help correct this.

**Comment by edzer** [comment]
Maybe reinstall package `dplyr`?

**Comment by fipoucat** [comment]
I re-installed dplyr from github but the same error again after re-installing stars too.
very strange indeed

**Comment by edzer** [comment]
What is the output of your `sessionInfo()` ?

**Comment by edzer** [comment]
The problem is that you installed `dplyr` from github, not from CRAN. News.md says:
* tbl_cube() and nasa have been pulled out into a separate cubelyr package (#4429).

This will probably need changes in `stars`, so I'd suggest to go with the CRAN version of dplyr.

**Comment by edzer** [comment]
See https://github.com/hadley/cubelyr/issues/1

**Comment by fipoucat** [comment]
Ok, install Ok now.
