### ISSUE TITLE
Support subsetting by index (slice())

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/stars#24]
Python's `xarray` conveniently provides a way to subset a dimension by value (`sel()`, equivalent to our `filter()`) and by index (`isel()`, equivalent to `dplyr`'s `slice()`, I think). How can one achieve the same selection-by-index with `stars`? If not yet implemented, is this planned?

**Comment by edzer** [comment]
I'm away for the week, let's discuss in Vienna.

On 30 March 2018 12:17:16 CEST, Adriano Fantini <notifications@github.com> wrote:
>Python's `xarray` conveniently provides a way to subset a dimension by
>value (`sel()`, equivalent to our `filter()`) and by index (`isel()`,
>equivalent to `dplyr`'s `slice()`, I think). How can one achieve the
>same selection-by-index with `stars`? If not yet implemented, is this
>planned?

-- 
Sent from a phone. Please excuse my brevity.

**Comment by adrfantini** [comment]
Oh, I just saw that you can subset with `[,,,1]` in the new [blog post](https://www.r-spatial.org/r/2018/03/22/stars2.html). That's nice!

Still a pipe-friendly version à-la `select()` would be nice. See you in Vienna!

**Comment by edzer** [comment]
We now have `filter` selecting on dimension values, and `slice` on dimension index. `slice` can only handle a single dimension, `filter` more than one.
