### ISSUE TITLE
Error when specifying the variable

### ISSUE THREAD

**Issue by matteodefelice** [r-spatial/stars#247]
I have a NetCDF created by `xarray`. This is the `ncdump -h`:
```
netcdf test_stars {
dimensions:
	mode = 3 ;
	latitude = 256 ;
	longitude = 315 ;
	time = 40 ;
variables:
	int64 mode(mode) ;
		mode:long_name = "eof_mode_number" ;
	double latitude(latitude) ;
		latitude:_FillValue = NaN ;
		latitude:units = "degrees_north" ;
		latitude:standard_name = "latitude" ;
		latitude:long_name = "latitude" ;
		latitude:stored_direction = "decreasing" ;
	double longitude(longitude) ;
		longitude:_FillValue = NaN ;
	float eof(mode, latitude, longitude) ;
		eof:_FillValue = NaNf ;
		eof:long_name = "covariance_between_pcs_and_msl" ;
	int64 time(time) ;
	float pc(time, mode) ;
		pc:_FillValue = NaNf ;
}
```
When loading it with `stars` (0.4.0): 
```{R}
> read_ncdf('test_stars.nc')
no 'var' specified, using eof
other available variables:
 mode, latitude, longitude, time, pc
stars object with 3 dimensions and 1 attribute
attribute(s):
      eof          
 Min.   :-204.219  
 1st Qu.:  -5.783  
 Median :  12.055  
 Mean   :  19.035  
 3rd Qu.:  58.303  
 Max.   : 202.099  
dimension(s):
          from  to offset delta refsys point values    
longitude    1 315 68.125  0.25     NA    NA   NULL [x]
latitude     1 256  8.875 -0.25     NA    NA   NULL [y]
mode         1   3   -0.5     1     NA    NA   NULL    
Warning message:
In .get_nc_projection(meta$attribute, rep_var, all_coord_var) :
  No projection information found in nc file.
```
But, when specifying the variable:
```{R}
> read_ncdf('test_stars.nc', var = 'pc')
Error in `$<-.data.frame`(`*tmp*`, "curvilinear", value = FALSE) : 
  replacement has 1 row, data has 0
In addition: Warning messages:
1: Length of logical index must be 1 or 10, not 0 
2: In .get_nc_projection(meta$attribute, rep_var, all_coord_var) :
  No projection information found in nc file.
3: In max(not_na) : no non-missing arguments to max; returning -Inf
```

Here the file: https://www.dropbox.com/s/q5iqv3nbhtkfmla/test_stars.nc?dl=0

**Comment by dblodgett-usgs** [comment]
What would you expect to get back when reading the `pc` variable?

**Comment by matteodefelice** [comment]
The variable `pc`, which has two dimensions: time and mode. The same code works with other NetCDFs with a similar structure.

**Comment by edzer** [comment]
`pc` is a non-spatial time series; I'm not sure `stars` is the right tool for that. Have you tried reading it with `RNetCDF` or `ncdf4`?

**Comment by matteodefelice** [comment]
Yes, but I wanted to use `stars`, the other variables are spatial (`mode`) and I was wondering if this error was a bug. The same code works with similar NetCDFs created with `xarray`.

**Comment by edzer** [comment]
Ah, yes, interestingly
```r
read_stars('test_stars.nc', sub = 'pc')
```
returns, besides a lot of warnings, something somewhat useful, but without recognizing time as time.

**Comment by matteodefelice** [comment]
For example, with this NetCDF everything works: https://www.dropbox.com/s/ne6hu8cgb1zkbe3/test_stars_working.nc?dl=0

**Comment by dblodgett-usgs** [comment]
I'll have to look at what's happening in a debugger. With the extremely limited metadata of this file, `stars` and `ncmeta` have very little to go on to figure out what to do -- thus the warnings.

**Comment by matteodefelice** [comment]
Here the files: [Archive.zip](https://github.com/r-spatial/stars/files/4123340/Archive.zip)

**Comment by dblodgett-usgs** [comment]
OK, since `time` nor `mode` are recognized as a coordinate variable, requesting data for a variable that has no coordinate variables is causing an error. 

Side note, without attributes we also can't tell that longitude variable also isn't seen as a coordinate variable.

I don't have time at this moment, but next steps would be to add units to `time` and see what we get.

**Comment by dblodgett-usgs** [comment]
@mdsumner -- this would be a good one to add to `rasterwise`.

**Comment by dblodgett-usgs** [comment]
I now get:
```r
> stars::read_ncdf('test_nc/test_stars_not_working.nc', var = 'pc')
Warning in .get_nc_projection(meta$attribute, rep_var, all_coord_var) :
  No projection information found in nc file.
stars object with 2 dimensions and 1 attribute
attribute(s):
      pc           
 Min.   :-2.60685  
 1st Qu.:-0.67358  
 Median : 0.04532  
 Mean   : 0.00000  
 3rd Qu.: 0.65161  
 Max.   : 2.39213  
dimension(s):
     from to offset delta refsys point values    
mode    1  3   -0.5     1     NA    NA   NULL [x]
time    1 40 1978.5     1     NA    NA   NULL [y]
```
That was easier than I thought it'd be.

**Comment by mdsumner** [comment]
thanks for the reminder, meant to rasterwise it ;)

**Comment by matteodefelice** [comment]
@dblodgett-usgs : thanks for the fix, now my code works without problems!

**Comment by edzer** [comment]
marking `mode` and `time` as the `[x]` and `[y]` raster dimensions is however not how things are supposed to work.

**Comment by dblodgett-usgs** [comment]
I agree. Since this is non-spatial and not clearly a point timeseries, there's not a lot to do. What would your preferred behavior be here?

**Comment by matteodefelice** [comment]
I would just expect a consistent behaviour, if the dimensions are time and mode I would love to be able to load it, without errors. Sometimes spatial data (eof in this example) comes with non-spatial data structures. Maybe I will switch to tidync in the future.
