### ISSUE TITLE
data cube type

### ISSUE THREAD

**Issue by edzer** [r-spatial/stars#248]
There is no function to find out what kind of data cube we have, e.g. when `mapview` or `tmap` want to plot it. I'm proposing to find out the type of raster (in case there is a spatial raster), using  `st_raster_type(x)` returning one of `NA` (not a raster cube), `regular`, `rectilinear`, `affine`, `curvilinear`.

**Comment by tim-salabim** [comment]
I think this is a good idea. At the moment I am naively doing

https://github.com/r-spatial/leafem/blob/master/R/addStarsImage.R#L77-L82

which only checks for affine or curvilinear.

**Comment by tim-salabim** [comment]
Thanks!
