### ISSUE TITLE
Failure in writing a multiband stars object to a GeoPackage

### ISSUE THREAD

**Issue by florisvdh** [r-spatial/stars#250]
This should reproduce the problem:

```r
library(raster)
library(stars)
      # Linking to GEOS 3.5.1, GDAL 2.2.2, PROJ 4.9.2
library(magrittr)
set.seed(123456789)

artwork <- 
  raster(extent(188500, 190350, 227550, 229550), # xmin, xmax, ymin, ymax
         res = 50, # resolution of 50 meters
         crs = CRS("+init=epsg:31370")) %>% 
  setValues(runif(ncell(.)))  # fill with random values

arts <- brick(artwork) # RasterBrick with one layer (the RasterLayer from above)
arts[[2]] <- artwork + 10 # Add second layer, based on first one
names(arts) <- paste0("layer", 1:2)

# Writing layer by layer does work:

arts$layer1 %>% 
  st_as_stars %>% 
  write_stars("arts.gpkg",
              driver = "GPKG",
              options = c("RASTER_TABLE=layer1"))
arts$layer2 %>% 
  st_as_stars %>% 
  write_stars("arts.gpkg",
              driver = "GPKG",
              options = c("RASTER_TABLE=layer2",
                          "APPEND_SUBDATASET=YES"))

# However the following gives an error:

arts %>% 
  st_as_stars %>% 
  write_stars("arts2.gpkg",
              driver = "GPKG")
```

The error is:

```
Error in CPL_write_gdal(mat, file, driver, options, type, dims, from,  : 
  creating dataset failed
```

<details> <summary><strong>Session Info</strong></summary>

```r
─ Session info ────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.2 (2019-12-12)
 os       Linux Mint 18.1             
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language (EN)                        
 collate  nl_BE.UTF-8                 
 ctype    nl_BE.UTF-8                 
 tz       Europe/Brussels             
 date     2020-01-31                  

─ Packages ────────────────────────────────────────────────────────────────────────
 package     * version date       lib source        
 abind       * 1.4-5   2016-07-21 [1] CRAN (R 3.6.0)
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.0)
 class         7.3-15  2019-01-01 [4] CRAN (R 3.6.0)
 classInt      0.4-2   2019-10-17 [1] CRAN (R 3.6.1)
 cli           2.0.1   2020-01-08 [1] CRAN (R 3.6.2)
 codetools     0.2-16  2018-12-24 [4] CRAN (R 3.6.0)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.0)
 DBI           1.1.0   2019-12-15 [1] CRAN (R 3.6.2)
 drat          0.1.5   2019-03-28 [1] CRAN (R 3.6.0)
 e1071         1.7-3   2019-11-26 [1] CRAN (R 3.6.2)
 fansi         0.4.1   2020-01-08 [1] CRAN (R 3.6.2)
 glue          1.3.1   2019-03-12 [1] CRAN (R 3.6.0)
 KernSmooth    2.23-16 2019-10-15 [4] CRAN (R 3.6.1)
 lattice       0.20-38 2018-11-04 [4] CRAN (R 3.6.0)
 lwgeom        0.1-7   2019-05-06 [1] CRAN (R 3.6.0)
 magrittr    * 1.5     2014-11-22 [1] CRAN (R 3.6.0)
 packrat       0.5.0   2018-11-14 [1] CRAN (R 3.6.0)
 raster      * 3.0-12  2020-01-30 [1] CRAN (R 3.6.2)
 Rcpp          1.0.3   2019-11-08 [1] CRAN (R 3.6.2)
 rgdal         1.4-8   2019-11-27 [1] CRAN (R 3.6.2)
 rlang         0.4.4   2020-01-28 [1] CRAN (R 3.6.2)
 rstudioapi    0.10    2019-03-19 [1] CRAN (R 3.6.0)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.0)
 sf          * 0.8-1   2020-01-28 [1] CRAN (R 3.6.2)
 sp          * 1.3-2   2019-11-07 [1] CRAN (R 3.6.1)
 stars       * 0.4-0   2019-10-10 [1] CRAN (R 3.6.1)
 units         0.6-5   2019-10-08 [1] CRAN (R 3.6.1)
 withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.0)

[1] /home/floris/lib/R/library
[2] /usr/local/lib/R/site-library
[3] /usr/lib/R/site-library
[4] /usr/lib/R/library
```

</details>

**Comment by edzer** [comment]
Potentially with a newer GDAL setup, I see the following:
```
Error in CPL_write_gdal(mat, file, driver, options, type, dims, from,  : 
  creating dataset failed
In addition: Warning message:
In CPL_write_gdal(mat, file, driver, options, type, dims, from,  :
  GDAL Error 6: Only single band dataset supported for non Byte datatype
```
and indeed,
```
arts %>% st_as_stars %>% write_stars("x.gpkg", driver = "GPKG", type = "Byte")
```
does not give an error. I also don't know whether the output is useful.

**Comment by florisvdh** [comment]
Thanks for helping out @edzer . Essentially, I missed the warning because my RStudio truncated it. When done in R directly, I get the same warning message as you...

I think I'll have to stay with the layer-by-layer approach, as the Byte type is not appropriate here - and there is > 1 band.

1. Interestingly, when read back with `read_stars()`, the Byte-type saved gpkg returns a `stars` object with 4 bands instead of 2 -- this looks like a bug to me. It seems that the first original layer is repeated three times and the second is added once.

```r
arts %>% st_as_stars %>% write_stars("x.gpkg", driver = "GPKG", type = "Byte")
x <- 
    read_stars("x.gpkg") %>% 
    split("band") 
all.equal(x$X1, x$X2, x$X3)
# [1] TRUE
```

2. Regarding my case, given the capabilities of `write_stars()`, I could equally have used its attribute layer selection capabilities when writing the full stars object layer by layer:

```r
stellar <- 
    arts %>% 
    st_as_stars %>% 
    split("band")

stellar %>% 
    write_stars("stellar.gpkg",
                driver = "GPKG",
                layer = "layer1",
                options = c("RASTER_TABLE=layer1"))

stellar %>% 
    write_stars("stellar.gpkg",
                driver = "GPKG",
                layer = "layer2",
                options = c("RASTER_TABLE=layer2",
                            "APPEND_SUBDATASET=YES"))
```

I think the following features would be nice to have:

- `write_stars()` being able to write a multi-band (or multi-attribute) stars object to a GPKG file at once, which could internally perform the above (splitting bands as attributes and writing and appending layer by layer). This would mimic same behaviour for multi-layered GeoTIFF files: `st_as_stars(arts) %>% write_stars("arts_stars.tif"); read_stars("arts_stars.tif")` -- for larger cases, I've seen that GPKG files can be smaller than the multi-layered GeoTIFF.
However, as writing non-Byte multi-band GPKG is not supported by GDAL, reading it back in may need a `merge()` operation to return the band dimension again, if a single-attribute `stars` object was the input.
- using the attribute name for the GPKG table by default (preventing the need for `options = c("RASTER_TABLE=layer1")`)
- `write_stars()` being able to append a layer to an existing GPKG file, with an `append = TRUE` argument, or so. This would prevent the need for ` options = c(                            "APPEND_SUBDATASET=YES")`

However I am aware that you want to support many GDAL drivers, so I don't know how sensible these ideas are.

**Comment by edzer** [comment]
I would consider a PR doing this in a simple & clean way, but I would obviously prefer when this limitation was resolved at the level of GDAL, where it belongs AFAICS..

**Comment by florisvdh** [comment]
I agree such functionality is best taken care of at the level of GDAL, letting other applications profit as well. For now, it is clear how to handle the current situation.
