### ISSUE TITLE
st_mosaic from list of stars objects?

### ISSUE THREAD

**Issue by elaliberte** [r-spatial/stars#251]
Not an issue  per se, more of a question / request.

`st_mosaic()` works from a list of `stars `objects. But suppose I have hundreds of small rasters stored in a long `list `of `stars `objects.

I would like to do something like:

`st_mosaic(my_list_of_stars_objects)`

But this doesn't work on lists, so it would require something like
`st_mosaic(my_list_of_stars_objects[[1]], my_list_of_stars_objects[[2]], ...)`

But I can't possibly supply hundreds of these `stars `objects in this function call.

Currently I use a for loop to get around that, but it would be nice to be able to supply a `list `of `stars ` objects as this is terribly inefficient and slow. Or is there a better way?

Thanks for the great package.

**Comment by edzer** [comment]
R has `do.call(st_mosaic, my_list_of_stars_objects)` for this. Package `purrr` may provide wrappers for that.

**Comment by elaliberte** [comment]
Thanks!
