### ISSUE TITLE
Error in CPL_read_gdal - file not found

### ISSUE THREAD

**Issue by milujisb** [r-spatial/stars#261]
Dear all,

I am trying to merge geo-location information with observations data for Nighttime lights from Black Marble.

I have been received help from R-sig-geo mailing list with the following code;

```
library(ncdf4)
library(rgdal)
library(raster)
library(stars)

r <- read_stars("VNP02DNB.A2020015.0236.001.2020045162223.nc")

latlon <- read_stars(
  c('NETCDF:"VNP03DNB.A2020015.0236.001.2020044182419.nc":/geolocation_data/latitude',
    'NETCDF:"VNP03DNB.A2020015.0236.001.2020044182419.nc":/geolocation_data/longitude'))

r_ll = st_as_stars(r, curvilinear = list(x = latlon[[2]], y = latlon[[1]]))
```

The first file can be read successfully but while reading the geolocation data, I get the following error;

```
Error in CPL_read_gdal(as.character(x), as.character(options), as.character(driver),  : 
  file not found
```

I am cross-posting here as it seems to be an issue with the package but I might be wrong. ANy help will be highly appreciated.

I have uploaded the files for [geo-location](https://drive.google.com/open?id=1jLmXLjG0WGgdH3g4pGJNz0ZOqXOfKpcW) and [observations data](https://drive.google.com/open?id=1zpqXJ8AlEcnk6ApRb75tfQc4-Y8AfK5h) on Google Drive.

Source of geo-location data (VNP03DNB): https://ladsweb.modaps.eosdis.nasa.gov/missions-and-measurements/products/VNP03DNB/
Source of observation data (VNP02DNB): https://ladsweb.modaps.eosdis.nasa.gov/missions-and-measurements/products/VNP02DNB/   

**Session info**
```
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] stars_0.4-0       sf_0.8-1          abind_1.4-5       rhdf5_2.30.1      raster_3.0-12    
[6] rgdal_1.4-8       sp_1.4-1          data.table_1.12.8 ncdf4_1.17       

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4         lattice_0.20-38    codetools_0.2-16   class_7.3-15       grid_3.6.3        
 [6] lwgeom_0.2-1       DBI_1.1.0          magrittr_1.5       units_0.6-6        e1071_1.7-3       
[11] KernSmooth_2.23-16 rlang_0.4.5        Rhdf5lib_1.8.0     tools_3.6.3        parallel_3.6.3    
[16] compiler_3.6.3     classInt_0.4-2   
```

Regards,

Milu

**Comment by mdsumner** [comment]
NETCDF is the wrong driver. 

There's a `sf::gdal_subdatasets()` function that is how you can find the SDS string as it is meant to be. 

```R
sf::gdal_subdatasets("VNP02DNB_NRT.A2020069.1048.001.nc")
[[1]]
[1] "HDF5:\"VNP02DNB_NRT.A2020069.1048.001.nc\"://observation_data/DNB_observations"

[[2]]
[1] "HDF5:\"VNP02DNB_NRT.A2020069.1048.001.nc\"://observation_data/DNB_quality_flags"

> sf::gdal_subdatasets("VNP03DNB.A2020015.0236.001.2020044182419.nc")
[[1]]
[1] "HDF5:\"VNP03DNB.A2020015.0236.001.2020044182419.nc\"://geolocation_data/height"
...
```

Generally, you should use this function to find these strings. 

(I don't know if these should be called ".nc", or if there's some other conflation going on somewhere.)

**Comment by edzer** [comment]
Seems to depend on the GDAL version linked to:
```r
> sf::gdal_subdatasets("VNP02DNB_NRT.A2020069.1048.001.nc")
[[1]]
[1] "NETCDF:\"VNP02DNB_NRT.A2020069.1048.001.nc\":/observation_data/DNB_observations"

[[2]]
[1] "NETCDF:\"VNP02DNB_NRT.A2020069.1048.001.nc\":/observation_data/DNB_quality_flags"

> sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
       "3.8.0"        "3.0.2"        "6.2.1"         "true"         "true" 
```

**Comment by mdsumner** [comment]
Ew, thanks - have not encountered that.

**Comment by milujisb** [comment]
Dear @mdsumner and @edzer,

Thank you very much for your prompt replies! 

I no longer get the 'file not found error' using;

```
r <- sf::gdal_subdatasets("VNP02DNB.A2020015.0236.001.2020045162223.nc")

latlon <- sf::gdal_subdatasets("VNP03DNB.A2020015.0236.001.2020044182419.nc") 
```

But the following does not work;

`r_ll = st_as_stars(r, curvilinear = list(x = latlon[[2]], y = latlon[[1]]))`

Apologies for the repeated questions, however, I am confused with how to move forward with the merge. Thank you again.

Regards,

Milu

**Comment by edzer** [comment]
In your script, `r` and `latlon` contain names, not `stars` objects. You need to use `read_stars` to read a stars object from a dataset name. The `st_as_stars` call needs the three datasets, not their names.

**Comment by milujisb** [comment]
Thank you for your reply. I tried the following;

```
r <- sf::gdal_subdatasets("VNP02DNB.A2020015.0236.001.2020045162223.nc")
r1 = read_stars(r)

This works.

```
However, the following gives me the same error;

```
latlon <- sf::gdal_subdatasets("VNP03DNB.A2020015.0236.001.2020044182419.nc")

latlon1 = read_stars(
  c('latlon:/geolocation_data/latitude',
    'latlon:/geolocation_data/longitude'))

Error in CPL_read_gdal(as.character(x), as.character(options), as.character(driver),  : 
  file not found
```

I do not understand how the same code worked for @edzer but fails in my machine. Sorry.

Regards,

Milu

**Comment by edzer** [comment]
You are not calling `read_stars` with subdataset names. Try
```
read_stars(latlon[1:2])
```
