### ISSUE TITLE
Not an Issue - asking for help - aggregating

### ISSUE THREAD

**Issue by katricka** [r-spatial/stars#265]
Hello, 
I am quite new to R and I want/need to work with satelite data due to my diploma thesis. I am working with ECMWF datasets. In dataset I have for every day two observations (2different hours).

My stars object look like this:
```
stars object with 3 dimensions and 1 attribute
attribute(s), summary of first 1e+05 cells:
  so2 [kg/kg]       
 Min.   :3.531e-25  
 1st Qu.:3.982e-25  
 Median :4.702e-25  
 Mean   :6.134e-25  
 3rd Qu.:7.779e-25  
 Max.   :1.537e-24  
dimension(s):
     from  to offset delta                       refsys point                                      values    
x       1 701 11.995  0.01 +proj=longlat +datum=WGS8...    NA                                        NULL [x]
y       1 311 51.505 -0.01 +proj=longlat +datum=WGS8...    NA                                        NULL [y]
time    1  62     NA    NA                      POSIXct    NA 2006-01-01 06:00:00,...,2006-01-31 12:00:00 
```

My question is about aggregating. I am doing aggregation over czech regions (kraje in code), that is working fine. What I am trying to achieve is to aggregare mean vaule for one region for one day. But as I have 2 observations per day, I am getting one aggregated value for one hour and second value for another hour. 

```
table <-    aggregate(poll,by = kraje, FUN = mean) %>% 
    st_as_sf() %>%
    st_drop_geometry() %>%
    bind_cols(kraje,.) %>%
    st_drop_geometry() %>%
    pivot_longer(-KOD_CZNUTS3, names_to = "date", values_to = "so2")

```

Thank you very much for your help!

**Comment by edzer** [comment]
Have you tried `aggregate(by = 'days')` as a second step after the first aggregate?

**Comment by katricka** [comment]
Thank you for your quick reply

`table <-    aggregate(poll,by = kraje, FUN = mean) %>% aggregate(by = 'days')
    st_as_sf() %>%
    st_drop_geometry() %>%
    bind_cols(kraje,.) %>%
    st_drop_geometry() %>%
    pivot_longer(-KOD_CZNUTS3, names_to = "date", values_to = "so2") `
I tried now but get this error

`Error in aggregate.stars(., by = days) : 
  currently, only `by' arguments of class sf, sfc, POSIXct, Date, PCICt supported`

Is there a way I can sent you my data set and code so you will see the whole problem ? 
Thank you very much for support!

**Comment by edzer** [comment]
Maybe install `stars` from github, by
```
remotes::install_github("r-spatial/stars")
```

**Comment by katricka** [comment]
I think I have som problem on my side of compter with downloading this package from GitHub directly 

```
Error: Failed to install 'stars' from GitHub:
  (converted from warning) installation of package ‘C:/Users/KATRIK~1/AppData/Local/Temp/RtmpaU8qlk/file45444cc34709/stars_0.4-1.tar.gz’ had non-zero exit status
```

Do you know any other way how to treat my problem?

**Comment by edzer** [comment]
Easiest to wait a few weeks for CRAN release & binary distribution; harder is to install sf from source, using rtools.

**Comment by katricka** [comment]
Ok thanks a lot for you reccomendations. 
I would like to have one more question. Is there a way how to filter data from my dataset only for specific hour? As I said I have for each day 2 values (one at 6am one at 12pm. I want to be able to analyze separately only data messured at 6am. I figured out one way, but in case there will be multiple hours it is not very handy. 

`poll <- poll %>% slice("time",seq(1,62,2))`

Thanks!

**Comment by edzer** [comment]
You can extract particular properties of time using the `format` method for `POSIXct` objects, try e.g.
```
format(Sys.time()+1:100, "%S")
```
