### ISSUE TITLE
Activate it as an RStudio Project?

### ISSUE THREAD

**Issue by uribo** [r-spatial/stars#266]
There is no `.Rproj` file to use project features in RStudio.

I'm sure many R users (including myself) are using the project feature. It is expected that this will make it easier to contribute to the repository. The user's tab width can also be controlled.

If you agree, I will send a PR to add `stars.Rproj` file.

**Comment by edzer** [comment]
Good idea - please do!

**Comment by edzer** [comment]
Please check it out!

**Comment by uribo** [comment]
Thanks, it looks good.
PR #267 is closed.
