### ISSUE TITLE
Subsetting stars by sf object failing because shape crosses prime meridian

### ISSUE THREAD

**Issue by kylebutts** [r-spatial/stars#269]
I have a raster of the world that goes from 0 lat to 360 lat. However, I'm trying to subset a shape file of Africa, but since Africa spins around the globe, it's failing to get the Eastern part of Africa. 

Is there a way to fix this already or is this a bug?

![image](https://user-images.githubusercontent.com/19961439/77969223-4165e580-72b7-11ea-9a1f-7a6afc583269.png)

![image](https://user-images.githubusercontent.com/19961439/77969335-7d00af80-72b7-11ea-93cc-3c5e1a6902ae.png)

**Comment by edzer** [comment]
Thanks for raising this. It is inconvenient indeed, and something we'll try to make easier but that will take some time.

For now, you'll have to either convert the grid to [-180,180], or convert your shape to [0,360]. Working on a reproducible example would help.

**Comment by edzer** [comment]
With this patch, you might get your raster to a one-degree raster on [-180,180] with
```r
st_warp(x, st_as_stars())
```

**Comment by kylebutts** [comment]
Ahh thank you for the help!

For future visitors of this issue, the st_warp reference has the answer: 
https://r-spatial.github.io/stars/reference/st_warp.html
