### ISSUE TITLE
st_crop behaviour

### ISSUE THREAD

**Issue by Nowosad** [r-spatial/stars#275]
This situation happens to me a few times lately. The `st_crop()` function correctly mask values outside of the second argument, however it does not properly crop the extent. This problem does not exist in the **raster** package.  It is possible to fix it with a tiny value of `epsilon`, but (correct me if I am wrong) the default behaviour should not mask some values and crop some different values..

``` r
library(stars)
#> Loading required package: abind
#> Loading required package: sf
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
library(raster)
#> Loading required package: sp
library(sf)
library(spData)
elev_stars = st_as_stars(elev)

window = st_sf(st_sfc(st_polygon(list(rbind(c(-1, 0), c(-1, 1), c(0, 1), c(0, 0), c(-1, 0)))), crs = st_crs(elev_stars)))

plot(elev)
plot(window, add = TRUE)
```

![](https://i.imgur.com/zukAZZp.png)

``` r

elev2 = crop(elev, (window))
plot(elev2)
```

![](https://i.imgur.com/OnHHYM5.png)

``` r
dim(elev2)
#> [1] 2 2 1

elev_stars2 = st_crop(elev_stars, window)
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar
plot(elev_stars2)
```

![](https://i.imgur.com/7lpfKiQ.png)

``` r
dim(elev_stars2)
#> x y 
#> 3 3

elev_stars3 = st_crop(elev_stars, window, epsilon = 0.0000000001)
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar
plot(elev_stars3)
```

![](https://i.imgur.com/ALLr99X.png)

``` r
dim(elev_stars3)
#> x y 
#> 2 2
```

<sup>Created on 2020-04-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by edzer** [comment]
Yes, a non-zero default value for epsilon is a good idea.

**Comment by Nowosad** [comment]
Thanks!
