### ISSUE TITLE
Problems loading nc file from copernicus.eu

### ISSUE THREAD

**Issue by fraba** [r-spatial/stars#277]
Hello, 

It seems I can't load the NC file download from copernicus.eu correctly. I post a small version of the file [here](http://www.filedropper.com/adaptorcamsregionalfcretrieve-15879390618606012-22402-6-64f0e215-609d-4ca6-b65c-a9ef7dc53370).

The file loads correctly only if I do

```
library(stars)
nc <- read_ncdf(my_file)
```
> no 'var' specified, using pm10_conc, pm2p5_conc
> other available variables:
>  longitude, latitude, level, time
> No projection information found in nc file. 
>  Coordinate variable units found to be degrees, 
>  assuming WGS84 Lat/Lon.
> stars object with 4 dimensions and 2 attributes
> attribute(s):
>  pm10_conc [µg/m3]   pm2p5_conc [µg/m3]
>  Min.   :  0.08376   Min.   : 0.05215  
>  1st Qu.:  4.79556   1st Qu.: 2.08035  
>  Median :  9.77700   Median : 4.39209  
>  Mean   : 14.13988   Mean   : 5.51724  
>  3rd Qu.: 18.06134   3rd Qu.: 7.46488  
>  Max.   :196.88487   Max.   :54.89545  
> dimension(s):
>           from  to offset delta    refsys point                values    
> longitude    1 700     NA    NA EPSG:4326    NA [700] 0.05,...,359.95 [x]
> latitude     1 420     NA    NA EPSG:4326    NA [420] 30.05,...,71.95 [y]
> level        1   1     NA    NA        NA    NA                     0    
> time         1   2      0    24        NA    NA                  NULL

But if I try `system.file(my_file, package = "stars") %>% read_ncdf()`, I get

>  Error in nc_meta.character(.x) : NetCDF source cannot be empty string

or if I specify the x/y variables `read_ncdf(my_file, curvilinear = c("longitude","latitude"))`

> no 'var' specified, using pm10_conc, pm2p5_conc
> other available variables:
>  longitude, latitude, level, time
> No projection information found in nc file. 
>  Coordinate variable units found to be degrees, 
>  assuming WGS84 Lat/Lon.
> Error in .check_curvilinear(c_v, var, meta$variable, curvilinear) : 
>   Specified curvilinear coordinates are not 2-dimensional.

Then once loaded with ` read_ncdf(my_file)` if I try to `plot(nc)`

> Error in image.default(dims[[dimx]], dims[[dimy]], ar, asp = asp, xlab = xlab,  : 
>   increasing 'x' and 'y' values expected

**Comment by edzer** [comment]
I can read the file without problems using
```r
r = read_stars(my_file)
plot(units::drop_units(r),key.pos=1, logz=TRUE, nbreaks = 20,axes=T)
```
![x](https://user-images.githubusercontent.com/520851/80357968-06d27700-887c-11ea-8c05-da0e4e4ba7da.png)

@mdsumner or @dblodgett-usgs any idea why `read_ncdf` gives `NA`'s for offset and delta?
```

> read_ncdf("adaptor.cams_regional_fc.retrieve-1587939061.8606012-22402-6-64f0e215-609d-4ca6-b65c-a9ef7dc53370.nc")
no 'var' specified, using pm10_conc, pm2p5_conc
other available variables:
 longitude, latitude, level, time
No projection information found in nc file. 
 Coordinate variable units found to be degrees, 
 assuming WGS84 Lat/Lon.
stars object with 4 dimensions and 2 attributes
attribute(s):
 pm10_conc [µg/m3]   pm2p5_conc [µg/m3]
 Min.   :  0.08376   Min.   : 0.05215  
 1st Qu.:  4.79556   1st Qu.: 2.08035  
 Median :  9.77700   Median : 4.39209  
 Mean   : 14.13988   Mean   : 5.51724  
 3rd Qu.: 18.06134   3rd Qu.: 7.46488  
 Max.   :196.88487   Max.   :54.89545  
dimension(s):
          from  to offset delta refsys point                values    
longitude    1 700     NA    NA WGS 84    NA [700] 0.05,...,359.95 [x]
latitude     1 420     NA    NA WGS 84    NA [420] 30.05,...,71.95 [y]
level        1   1     NA    NA     NA    NA                     0    
time         1   2      0    24     NA    NA                  NULL    
```

**Comment by mdsumner** [comment]
the longitudes are discontinuous so it's falling back to rectilinear - it seems GDAL is auto-wrapping which seems new

**Comment by mdsumner** [comment]
Maybe, it disturbs me how sloppy the coordinates are but it does seem common enough

**Comment by dblodgett-usgs** [comment]
Yeah -- longitude is 0-360 and crosses the 360, 0 mid coordinate variable. Probably an edge case that should be handled... 
```
ncdump -v longitude adaptor.cams_regional_fc.retrieve-1587939061.8606012-22402-6-64f0e215-609d-4ca6-b65c-a9ef7dc53370.nc 
netcdf adaptor.cams_regional_fc.retrieve-1587939061.8606012-22402-6-64f0e215-609d-4ca6-b65c-a9ef7dc53370 {
dimensions:
	longitude = 700 ;
	latitude = 420 ;
	level = 1 ;
	time = UNLIMITED ; // (2 currently)
variables:
	float longitude(longitude) ;
		longitude:long_name = "longitude" ;
		longitude:units = "degrees_east" ;
	float latitude(latitude) ;
		latitude:long_name = "latitude" ;
		latitude:units = "degrees_north" ;
	float level(level) ;
		level:long_name = "level" ;
		level:units = "m" ;
	float time(time) ;
		time:long_name = "ANALYSIS time from 20200101" ;
		time:units = "hours" ;
	float pm10_conc(time, level, latitude, longitude) ;
		pm10_conc:_FillValue = -999.f ;
		pm10_conc:species = "PM10 Aerosol" ;
		pm10_conc:units = "µg/m3" ;
		pm10_conc:value = "hourly values" ;
		pm10_conc:standard_name = "mass_concentration_of_pm10_ambient_aerosol_in_air" ;
	float pm2p5_conc(time, level, latitude, longitude) ;
		pm2p5_conc:_FillValue = -999.f ;
		pm2p5_conc:species = "PM2.5 Aerosol" ;
		pm2p5_conc:units = "µg/m3" ;
		pm2p5_conc:value = "hourly values" ;
		pm2p5_conc:standard_name = "mass_concentration_of_pm2p5_ambient_aerosol_in_air" ;

// global attributes:
		:title = "PM10/PM25 Air Pollutant ANALYSIS at the Surface" ;
		:institution = "Data produced by Meteo France" ;
		:source = "Data from ENSEMBLE model" ;
		:history = "Model ENSEMBLE ANALYSIS" ;
		:ANALYSIS = "Europe, 20200101-20200102+[12H_12H]" ;
		:summary = "ENSEMBLE model hourly ANALYSIS of PM10/PM25 concentration at the Surface from 20200101-20200102+[12H_12H] on Europe" ;
		:project = "MACC-RAQ (http://macc-raq.gmes-atmosphere.eu)" ;
data:

 longitude = 335.05, 335.15, 335.25, ... 359.85, 359.95, 0.05, 
    0.15, 0.25, 0.35, 0.45, 0.55, ... , 44.55, 44.65, 44.75, 
    44.85, 44.95 ;
}
```

Would have to pop open a debugger, but I think this would be handled in here? https://github.com/r-spatial/stars/blob/master/R/ncdf.R#L239 Or in here: https://github.com/r-spatial/stars/blob/master/R/ncdf.R#L509

**Comment by fraba** [comment]
Not sure I understand what's the problem exactly. But then how do I intersect the resulting `stars` object with an`sf` object? Is it still possible?

**Comment by mdsumner** [comment]
@dblodgett-usgs something like this

```R
.get_nc_dimensions <- function(dimensions, coord_var, coords, nc, dims,
                               var_names, curvilinear, eps, ignore_bounds) {

  to_rectilinear = FALSE
  ## hack longitudes for #277
  if ("longitude" %in% names(coords)) {
    lons <- coords[["longitude"]]
    if (!regular_intervals(lons) && lons[1L] > 180 && min(lons) > 0) {
      coords[["longitude"]] <- ((coords[["longitude"]] + 180) %% 360) - 180
    }
  }
```

But then is_regular still doesn't pass so for me it's undecidable, you end up with this stack of assumptions that will eventually bite in some other context. 

@fraba the problem is that the longitudes don't make sense as axis positions for a grid, *unless* you assume you are meant to wrap impliciitly - see the values with a generic netcdf tool i.e. 

```R
nc <- RNetCDF::open.nc(<your file>)
lons <- RNetCDF::var.get.nc(nc, "longitude")
plot(lons)
```

You can *fix* that by  using `lon2 <- ((lons + 180) %% 360) - 180` but they are still messy numerically, look at `plot(diff(lon2))` - clearly the intention is to all be 0.1. I don't know why netcdf is plagued by these issues, (generally it doesn't work with affine transforms is the ultimate cause ... but the community of sources very chaotic).   

I'm uncomfortable automating around them and when I do this I do it explicitly in a controlled context for a known data source. GDAL has clearly decided to automate around it, so I'd recommend using `read_stars`. That tool stores a lot of random details about a lot of different data, so it's best to leverage it in my opinion.

**Comment by dblodgett-usgs** [comment]
I'll look at this in the morning -- there are some "tricks" (hacks) I worked into `intersectr` for this kind of thing a while ago that I want to revisit.

**Comment by edzer** [comment]
@fraba yes you can, after setting the CRS which `read_stars` doesn't infer; e.g. cropping to France:
```r
library(stars)
r = read_stars("adaptor.cams_regional_fc.retrieve-1587939061.8606012-22402-6-64f0e215-609d-4ca6-b65c-a9ef7dc53370.nc")
plot(units::drop_units(r),key.pos=1, logz=TRUE, nbreaks = 20,axes=T)

st_crs(r) = 4326

library(rnaturalearth)
ne_countries(country = "France", returnclass = "sf") %>% # contains territorial NG
    st_crop(st_bbox(c(xmin = -10, ymin = 20, xmax = 50, ymax = 70))) -> fr
plot(st_crop(r, fr), axes = TRUE)
```
![x](https://user-images.githubusercontent.com/520851/80460269-e36b0300-8933-11ea-9f57-97d7f33593ab.png)

**Comment by dblodgett-usgs** [comment]
PR incoming that does:
``` r
library(stars)
#> Loading required package: abind
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.0.4, PROJ 7.0.0
library(rnaturalearth)
    
f <- "~/Desktop/adaptor.cams_regional_fc.retrieve-1587939061.8606012-22402-6-64f0e215-609d-4ca6-b65c-a9ef7dc53370.nc"

nc <- read_ncdf(f, eps = 0.1)
#> no 'var' specified, using pm10_conc, pm2p5_conc
#> other available variables:
#>  longitude, latitude, level, time
#> No projection information found in nc file. 
#>  Coordinate variable units found to be degrees, 
#>  assuming WGS84 Lat/Lon.

ne_countries(country = "France", returnclass = "sf") %>% # crop territorial NG:
    st_crop(st_bbox(c(xmin = -10, ymin = 20, xmax = 50, ymax = 70))) -> fr
#> although coordinates are longitude/latitude, st_intersection assumes that they are planar
#> Warning: attribute variables are assumed to be spatially constant throughout all
#> geometries
plot(st_crop(nc, fr), axes = TRUE, reset = FALSE)
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar
plot(st_geometry(fr), border = 'red', lwd = 2, add = TRUE)
```

![](https://i.imgur.com/o7gg933.png)

<sup>Created on 2020-04-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by fraba** [comment]
Thanks, but I still get some missing data when I try to `aggregate()`. It might be a problem with my NC file? There's no missing data in the NC dataset... Or is it an issue with the aggregating function?

```
r <- 
  read_stars("adaptor.cams_regional_fc.retrieve-1587939061.8606012-22402-6-64f0e215-609d-4ca6-b65c-a9ef7dc53370.nc")
load("grid/hex_ita_1km.sf.RData") # file here http://www.filedropper.com/hexita1kmsf

st_crs(r) <- 4326
st_crs(hex_ita_1km.sf) <- st_crs(32632)

a <- 
  aggregate(st_transform(r, 32632), 
            by = hex_ita_1km.sf, 
            FUN = mean)

plot(a, max.plot = 1, border = NA)
```
<img width="508" alt="Screen Shot 2020-04-29 at 4 17 04 pm" src="https://user-images.githubusercontent.com/4167193/80565896-fb767b80-8a34-11ea-9950-b10a7a4ad942.png">

**Comment by edzer** [comment]
`http://www.filedropper.com/hexita1kmsf` doesn't work.

**Comment by fraba** [comment]
> `http://www.filedropper.com/hexita1kmsf` doesn't work.

Also [here](https://drive.google.com/file/d/1fEhy3V4h1h5efDMrfa0x_mvnx2VL5T66/view?usp=sharing).
