### ISSUE TITLE
could the sum method be used in st_warp?

### ISSUE THREAD

**Issue by hbermeo** [r-spatial/stars#285]
I am wanting to resample a star object, but no sum appears in the methods, nor in the help. Although if it is within these gdal methods [https://gdal.org/programs/gdalwarp.html](url)

When I want to use the "sum" method I get the following error:
Error in paste("unknown option:", options) : 
  cannot coerce type 'closure' to vector of type 'character'

**Comment by Nowosad** [comment]
The "sum" method is available since GDAL version 3.1 (released this month). Do you have this version of GDAL?

**Comment by hbermeo** [comment]
Oh I understand, I thought the library rgdal to work, but I see that the library gdal acts externally. As I see in gdal and the osgeo4w installer I still don't see version 3.1 to install in Windows

**Comment by edzer** [comment]
The R package and your OSGEO4W install are two entirely different things if you install packages binary from CRAN. R CRAN _binary_ packages come with a complete, local copy of the GDAL library (statically linked into sf.dll).

**Comment by hbermeo** [comment]
OK understood. In this case this would be the version of GDAL when loading the sf library, I imagine it is the same one that uses "stars"?

> > library(sf)
> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1

**Comment by edzer** [comment]
Yes, it uses the code linked to `sf`.
