### ISSUE TITLE
It is possible to concatenate two adjacent proxy rasters?

### ISSUE THREAD

**Issue by ErickChacon** [r-spatial/stars#286]
I am trying to join two adjacent rasters. I have no problem if I am working with `stars` objects. For example the following works without problems:
```r
library(stars)
tile3030 <- read_stars("tile3030.TIF")
tile3040 <- read_stars("tile3040.TIF")
(joined <- c(tile3040, tile3030, along = 2))
# stars object with 2 dimensions and 1 attribute
# attribute(s), summary of first 1e+05 cells:
#  tile3040.TIF    
#  Min.   : 14.23  
#  1st Qu.: 51.33  
#  Median : 86.76  
#  Mean   : 93.60  
#  3rd Qu.:128.58  
#  Max.   :227.36  
# dimension(s):
#   from   to  offset delta                       refsys point values    
# x    1 2501 3499975    25 PROJCS["ETRS89_ETRS_LAEA"... FALSE   NULL [x]
# y    1 1000 4012488   -25                           NA    NA   NULL [y]
write_stars(joined, "joined.TIF")
```
I wonder why the `y` dimension loses its `refsys`. Although when loading the saved `joined.TIF`, the `refsys` is recovered.

On the other hand, I have problems if I work with `stars_proxy` objects. the following code does not work.
```r
library(stars)
tile3030 <- read_stars("tile3030.TIF", proxy = TRUE)
tile3040 <- read_stars("tile3040.TIF", proxy = TRUE)
(joined <- c(tile3040, tile3030, along = 2))
# stars_proxy object with 1 attribute in files:
# $attr
#   tile3040.TIF   tile3030.TIF 
# "tile3040.TIF" "tile3030.TIF" 
# 
# dimension(s):
#   from   to  offset delta                       refsys point values    
# x    1 2501 3499975    25 PROJCS["ETRS89_ETRS_LAEA"... FALSE   NULL [x]
# y    1 1000 4012488   -25                           NA    NA   NULL [y]

write_stars(joined, "joined_proxy.TIF", chunk_size = c(1000, 500))
# Error in c.stars(tile3040.TIF = list(tile3040.TIF = c(134.222518920898,  :
# don't know how to merge arrays: please specify parameter along
```
I added `chunk_size` to reproduce the error that appears when working with big arrays. 
Trying to isolate the problem. we can see that `st_as_stars` also fails:
```r
joined <- st_as_stars(joined)
# Error in CPL_read_gdal(as.character(x), as.character(options), as.character(driver),  :
# read failure
# In addition: Warning message:
# In CPL_read_gdal(as.character(x), as.character(options), as.character(driver),  :
# GDAL Error 5: /home/rstudio/Documents/Projects/uk-data/scripts/30-process/tile3040.TIF:
# Access window out of range in RasterIO().
# Requested (0,0) of size 2501x1000 on raster of 2501x500.
```
Here are the files the reproduce the errors: 
[tiles.zip](https://github.com/r-spatial/stars/files/4629542/tiles.zip)

**Comment by edzer** [comment]
@ErickChacon you're looking for `st_mosaic`, either on `stars` objects
```r
st_mosaic(tile3030, tile3040)
```
or on files:
```r
st_mosaic(c("tile3030.TIF", "tile3040.TIF"))
```
A method for `stars_proxy` is currently missing, and will be added.

**Comment by ErickChacon** [comment]
Thank you for pointing out that I should use `st_mosaic`. I want to use it for relatively big files, so I would be very useful the have a method for `stars_proxy`. In the meantime, I will try to find a workaround.

**Comment by edzer** [comment]
This is quick and dirty, but might help you out if you have single-file proxy objects.

**Comment by ErickChacon** [comment]
@edzer thank you so much. I tested with big proxy objects and it worked as expected. It is simply amazing!

**Comment by edzer** [comment]
Thanks! R and GDAL are amazing, this is just glue.
