### ISSUE TITLE
360_day calendar attribute is ignored ; a warning could be issued

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/stars#29]
Several climate models do not use the gregorian calendar in their NetCDF output: they often use `360_day` calendars, which are quite challenging to deal with in R (AFAIK only the `PCICt` package can help, Python has more advanced tools for this). See the [CF-Conventions](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch04s04.html) for the list of convened-upon NetCDF calendars.

`stars` currently ignores the calendar option and treats the data (using `units`) as if it was in a gregorian calendar, as it is the only calendar supported (see also r-quantities/units#80).

It would be helpful if a warning was issued if a calendar attribute was found with value other than `gregorian` or `standard`, and maybe `proleptic_gregorian`.

However I do not know if you want to introduce such an ad-hoc check into `stars` or `units`.

**Comment by edzer** [comment]
> what I need more often is the ability to perform st_apply over days/months/seasons (something that's very easy with xarray), which I think is something stars should include and not leave up the the user to write his own functions to do so..

You mean compute aggregate statistics on a lower resolution time axis, right?

**Comment by adrfantini** [comment]
> You mean compute aggregate statistics on a lower resolution time axis, right?

Yup.

**Comment by adrfantini** [comment]
According to the CF-conventions, `365_day` calendars can also be called `noleap`:
http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#calendar

Currently we only support `cal %in% c("360_day", "365_day")`, can you add `, 'noleap'`?
