### ISSUE TITLE
Smooth time series - best option? 

### ISSUE THREAD

**Issue by bevingtona** [r-spatial/stars#295]
Thanks for the great package!  

I would like to smooth a time series of raster images in `stars` using a loess. 

A `raster` implementation of what I would like to do is available here https://github.com/jeffreyevans/spatialEco/blob/master/R/smooth.time.series.R

I am not sure the best way to do this and have been searching the documentation far and wide. 

Below is a `reprex`, with a very ineficient function that runs a `loess` for every combination of x and y, and then needs to be rearranged back into a `stars` object. 

Surely there is a better way? Perhaps with `st_apply`, but this is not clear to me. 

Thanks in advance!

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(stars)
#> Loading required package: abind
#> Loading required package: sf
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
  
raw_data <- system.file("nc/bcsd_obs_1999.nc", package = "stars") %>% read_stars()
#> Warning in CPL_read_gdal(as.character(x), as.character(options),
#> as.character(driver), : GDAL Message 1: Recode from UTF-8 to CP_ACP failed with
#> the error: "Invalid argument".
#> pr,
#> Warning in CPL_read_gdal(as.character(x), as.character(options),
#> as.character(driver), : GDAL Message 1: Recode from UTF-8 to CP_ACP failed with
#> the error: "Invalid argument".
#> tas,
#> Warning in CPL_read_gdal(as.character(x), as.character(options),
#> as.character(driver), : GDAL Message 1: Recode from UTF-8 to CP_ACP failed with
#> the error: "Invalid argument".
#> Warning in CPL_read_gdal(as.character(x), as.character(options),
#> as.character(driver), : GDAL Message 1: Recode from UTF-8 to CP_ACP failed with
#> the error: "Invalid argument".
#> pr,
#> Warning in CPL_read_gdal(as.character(x), as.character(options),
#> as.character(driver), : GDAL Message 1: Recode from UTF-8 to CP_ACP failed with
#> the error: "Invalid argument".
#> tas,
#> Warning in CPL_read_gdal(as.character(x), as.character(options),
#> as.character(driver), : GDAL Message 1: Recode from UTF-8 to CP_ACP failed with
#> the error: "Invalid argument".
plot(raw_data)
```

![](https://i.imgur.com/M2Zgcdt.png)

``` r
  
my_smooth <- function(c, f){
  for(i in 1:dim(c)[1]){
    for(j in 1:dim(c)[2]){
      mydf <- data.frame(
        index = 1:dim(c)[3],
        val = as.numeric(c[i,j,1:dim(c)[3]]))
      if(sum(is.na(mydf$val)) > 8){
        c[i,j,1:dim(c)[3]] <- mydf$val}else{
        c[i,j,1:dim(c)[3]] <- stats::predict(stats::loess(val ~ index, span = 0.8, data = mydf), 1:dim(c)[3])
          }}}
    return(c)}
  
  smooth_data <- my_smooth(c=raw_data$pr, f = 0.6)
  
  dims <- st_dimensions(raw_data)
  smooth_data <- smooth_data %>% st_as_stars()
  smooth_data <-  st_set_dimensions(smooth_data, 1, offset = dims$x$offset, delta = dims$x$delta)
  smooth_data <-  st_set_dimensions(smooth_data, 2, offset = dims$y$offset, delta = dims$y$delta)
  smooth_data <-  st_set_dimensions(smooth_data, 3, values = st_get_dimension_values(raw_data, which = 3))
  
  plot(smooth_data)
```

![](https://i.imgur.com/PT7kLPp.png)

<sup>Created on 2020-05-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by meteosimon** [comment]
Hi there, I had something similar: I wanted to apply a function to some margins, and use the left-out-dimension within the function. `st_apply()` can handle this via the `...` argument. In the above sample case:

```
library(stars)
raw_data <- read_stars(system.file("nc/bcsd_obs_1999.nc", package = "stars"))
foo <- function(x, idx) stats::lowess(idx, x)$y

smooth <- st_apply(raw_data,
	MARGIN = c("x", "y"),
	FUN = foo,
	idx = st_get_dimension_values(raw_data, "time")
)

smooth <- st_set_dimensions(smooth,
	which = "foo",
	values = st_get_dimension_values(raw_data, "time"),
	names = "time"
)
```

Tiny downside: I have to re-set the dimension's value and name after `st_apply()`. Though, I don't think that's an issue, as you can't assume that the function `foo()` returns a vector referenced with the left-out-dimension?!

**Comment by edzer** [comment]
Yes; the problem is we cannot tell from `foo` that it retains time; if `foo` would call `order`, or `sort`, then it wouldn't. Another downside is the loss of units...

**Comment by bevingtona** [comment]
Thanks @meteosimon !

I benchmarked the two methods ("my_smooth" vs st_apply)  and got 2467 ms and 324 ms, an excellent improvement!

**Comment by edzer** [comment]
@meteosimon I'm experimenting with alternative syntax for copying over dimension values:
```r
> st_dimensions(smooth)[1] = st_dimensions(raw_data)[3]
> smooth
stars object with 3 dimensions and 2 attributes
attribute(s):
      pr               tas        
 Min.   : 16.13   Min.   :-2.355  
 1st Qu.: 70.37   1st Qu.: 9.632  
 Median : 84.56   Median :15.327  
 Mean   : 87.73   Mean   :14.617  
 3rd Qu.:101.95   3rd Qu.:19.993  
 Max.   :278.64   Max.   :24.798  
 NA's   :7116     NA's   :7116    
dimension(s):
    from to offset  delta  refsys point                    values    
foo    1 12     NA     NA POSIXct    NA 1999-01-31,...,1999-12-31    
x      1 81    -85  0.125      NA    NA                      NULL [x]
y      1 33 37.125 -0.125      NA    NA                      NULL [y]
```
Do you consider that an improvement?

**Comment by meteosimon** [comment]
@edzer I think that's a very nice idea.

```
st_dimensions(smooth)[1] = st_dimensions(raw_data)[3]
```
is straight-forward for someone working with base R or for the use in a function that modifies the dimensions. One tricky thing is to change also the name of the dimension in that way. In `[<-.dimensions` you call `NextMethod()`, which should be then subset assignment for a list (not sure?). And I am not sure, how to do subset assignment for a list and simultaneously changing names of the elements and their values?

On the other hand, in an application when someone already has dplyr or the tidyverse on hand, it would be more natural to go for `st_set_dimensions()`, as it's pipe-able:
```
library(dplyr)
library(stars)

foo <- function(x, idx) stats::lowess(idx, x)$y
raw <- read_stars(system.file("nc/bcsd_obs_1999.nc", package = "stars"))
timeline <- st_get_dimension_values(raw, "time")

smooth <- raw %>%
  st_apply(MARGIN = c("x", "y"), FUN = foo, idx = timeline) %>%
  st_set_dimensions(which = "foo", values = timeline, names = "time")
```

**Comment by edzer** [comment]
Agreed; in that second setting, directly setting it back like in
```r
smooth <- raw %>%
  st_apply(MARGIN = c("x", "y"), FUN = foo, idx = timeline) %>%
  st_set_dimensions("foo", st_dimensions(raw)["time"])
````
would save you the step of extracting the time steps in the first place.

**Comment by meteosimon** [comment]
If I try this I get an error, as the [condition in line 114](https://github.com/r-spatial/stars/blob/1b21b7db34c75b2a6024bac7b9fbe2ad99478cc9/R/dimensions.R#L114) is `FALSE`. `length(values)` equals `1`, as values is of class `dimensions`. If I insert
```
        if (inherits(values, "dimensions")) {
            if (is.null(names))
                names <- names(values)
            values <- values[[1]]$values
        }
```
after line 112 and before line 113, it works and also changes the name of the dimension.

**Comment by edzer** [comment]
That's why I said "would", not will -- your comment is close to a PR - thanks!
