### ISSUE TITLE
Aggregation results different after crop

### ISSUE THREAD

**Issue by meteosimon** [r-spatial/stars#299]
I was aggregating a digital elevation model (`stars`) and got different results, if I crop (spatially subset) the `stars` object  before the aggregation.

Here an example, as reproducible as possible, it downloads one tile of SRTM data: 

``` r
library(stars)
#> Loading required package: abind
#> Loading required package: sf
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
url <- "https://dds.cr.usgs.gov/srtm/version2_1/SRTM3/Eurasia/N47E011.hgt.zip"
tmp <- tempfile(fileext = ".zip")
download.file(url, tmp, "wget")
f <- unzip(tmp)
x <- read_stars(f)
plot(x)
```

![](https://i.imgur.com/16al4CH.png)

I make a grid inside of the domain and aggregate:

``` r
grd <- st_make_grid(st_as_sfc(st_bbox(x) + c(+.25, +.25, -.25, -.25)), cellsize = .05)
#> although coordinates are longitude/latitude, st_relate_pattern assumes that they are planar

agg1 <- aggregate(x, grd, mean, na.rm = TRUE)
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar
plot(agg1)
```

![](https://i.imgur.com/77Wb0QY.png)

2nd, I crop the `stars` object, but `grd` is still fully contained in the cropped object. The I aggregate again with the cropped `stars` object but the same polygons `grd`:

``` r
x2 <- x[st_bbox(x) + c(+.15, +.15, -.15, -.15)]
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar
agg2 <- aggregate(x2, grd, mean, na.rm = TRUE)
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar
plot(agg2)
```

![](https://i.imgur.com/2maXMSj.png)

The results look similar, however, the last row of the aggregations reveals a clear difference.

``` r
identical(agg1, agg2)
#> [1] FALSE

plot(x, reset = FALSE)
plot(st_geometry(grd), add = TRUE, border = 'red')
plot(st_geometry(st_as_sfc(st_bbox(x2))), add = TRUE, border = 'red', lwd = 2)
```

![](https://i.imgur.com/M5tWDBn.png)

Last plot to summarize the extents of the objects.

<sup>Created on 2020-06-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I looked into the issues, but haven't found anything similar. It seems to me that `aggregate.stars()` gives different results, if the `stars` object got cropped before.

**Comment by meteosimon** [comment]
Just rerun the example with `join = st_within` as predicate, and the resulting aggregations are identical, and the aggregation looks as the expected topography.
Though, this is something other users could also run into. Maybe a warning that suggests to use `st_within` when `by` contains polygons is sufficient?

**Comment by edzer** [comment]
Good point - polygons contain all their borders, which is often confusing and annoying in a raster setting; (stars) raster cells have no borders in common; each raster cell typically contains its left and upper border, and only the upper-left corner point. I agree this needs to be written down, do you have a suggestion where? the man page of `aggregate`?

**Comment by meteosimon** [comment]
@edzer Sorry, for not answering your question directly, but I must admit, that I don't fully understand how everything works during the aggregation and handling of raster cells either as polygons or as points, and so on.... But I think, the result of the aggregation should not depend on the extent of the stars object. I rerun the example from above with a linestring, as geometry to be aggregated on:

``` r
library(stars)
#> Loading required package: abind
#> Loading required package: sf
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
url <- "https://dds.cr.usgs.gov/srtm/version2_1/SRTM3/Eurasia/N47E011.hgt.zip"
tmp <- tempfile(fileext = ".zip")
download.file(url, tmp, "wget")
f <- unzip(tmp)
x <- read_stars(f)

mat <- matrix(c(11.25, 11.75, 47.25, 47.75), ncol = 2)
ls <- st_as_sfc(list(st_linestring(mat)), crs = 4326)

agg1 <- aggregate(x, ls, mean, na.rm = TRUE)
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar
agg1[[1]]
#> [1] 1121.515

x2 <- x[st_bbox(x) + c(+.15, +.15, -.15, -.15)]
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar
agg2 <- aggregate(x2, ls, mean, na.rm = TRUE)
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar
agg2[[1]]
#> [1] 1174.074
```

<sup>Created on 2020-06-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The results differ (slightly), although the linestring fully lies within both the original stars object `x` and the cropped one `x2`.
Do I miss something here? Do I have to set another argument or is the crs lost somewhere?

**Comment by edzer** [comment]
No, this looks like a bug.

**Comment by edzer** [comment]
It was the NA's ... this should go better now, please check.

**Comment by meteosimon** [comment]
Here we go! Very nice! For the opening example--aggregation over polygons--I get identical results for the two aggregations, and the results look very meaningful!

For the 2nd example--aggregation along a linestring--the results still differ slightly:

``` r
library(stars)
#> Loading required package: abind
#> Loading required package: sf
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
f <- "./N47E011.hgt"
x <- read_stars(f)

mat <- matrix(c(11.25, 11.75, 47.25, 47.75), ncol = 2)
ls <- st_as_sfc(list(st_linestring(mat)), crs = 4326)

agg1 <- aggregate(x, ls, mean, na.rm = TRUE)
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar
agg1[[1]]
#> [1] 1301.421

x2 <- x[st_bbox(x) + c(+.15, +.15, -.15, -.15)]
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar
agg2 <- aggregate(x2, ls, mean, na.rm = TRUE)
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar
agg2[[1]]
#> [1] 1301.027
```

<sup>Created on 2020-06-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

However, I am not sure maybe this has different reason?

And I have another minor point:

* [The join function in aggregate.R](https://github.com/r-spatial/stars/blob/e7c61093d002b7c353cefa23e4f672aefbf9d662/R/aggregate.R#L109) gets `as_points` as argument, which is not declared in all predicates and thus would throw an error.

**Comment by edzer** [comment]
Thanks; other join functions should work again (please check); I'm now seeing
```r
library(stars)
# Loading required package: abind
# Loading required package: sf
# Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
#> Loading required package: abind
#> Loading required package: sf
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
f <- "./N47E011.hgt"
x <- read_stars(f)

mat <- matrix(c(11.25, 11.75, 47.25, 47.75), ncol = 2)
ls <- st_as_sfc(list(st_linestring(mat)), crs = 4326)
x2 <- x[st_bbox(x) + c(+.15, +.15, -.15, -.15)]
# although coordinates are longitude/latitude, st_intersects assumes that they are planar

all.equal(
aggregate(x, ls, mean, na.rm = TRUE, as_points = FALSE)[[1]],
aggregate(x2, ls, mean, na.rm = TRUE, as_points = FALSE)[[1]]
)
# although coordinates are longitude/latitude, st_intersects assumes that they are planar
# although coordinates are longitude/latitude, st_intersects assumes that they are planar
# [1] TRUE

all.equal(
aggregate(x, ls, mean, na.rm = TRUE, as_points = TRUE)[[1]],
aggregate(x2, ls, mean, na.rm = TRUE, as_points = TRUE)[[1]]
)
# although coordinates are longitude/latitude, st_intersects assumes that they are planar
# although coordinates are longitude/latitude, st_intersects assumes that they are planar
# [1] TRUE
```

**Comment by meteosimon** [comment]
Perfect!!! I checked again both examples, aggregations are now identical. Further, the aggregation over polygons with `join = st_within` yields the same as the default with `join = st_intersects`.

Documentation-wise, you could add the following as example to the aggregate man page (as a spatial case next to the temporal examples?):

``` r
library(stars)
#> Loading required package: abind
#> Loading required package: sf
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0

prec_file = system.file("nc/test_stageiv_xyt.nc", package = "stars")
prec = read_ncdf(prec_file, curvilinear = c("lon", "lat"))
#> no 'var' specified, using Total_precipitation_surface_1_Hour_Accumulation
#> other available variables:
#>  time_bounds, lon, lat, time
#> No projection information found in nc file. 
#>  Coordinate variable units found to be degrees, 
#>  assuming WGS84 Lat/Lon.
#> Warning in .get_nc_dimensions(dimensions, coord_var = all_coord_var, coords =
#> coords, : bounds for time seem to be reversed; reverting them
prec_slice = dplyr::slice(prec, index = 17, along = "time")

nc = sf::read_sf(system.file("gpkg/nc.gpkg", package = "sf"), "nc.gpkg")
nc = st_transform(nc, st_crs(prec_slice))

agg = aggregate(prec_slice, st_geometry(nc), mean)
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar
plot(agg)
```

![](https://i.imgur.com/cvjPgTF.png)

<sup>Created on 2020-06-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
