### ISSUE TITLE
borrow ideas from xarray?

### ISSUE THREAD

**Issue by shabbybanks** [r-spatial/stars#3]
I am not sure where to leave this comment, but the `stars` proposal (which I am very excited about!) reminds me of the Python [xarray package](http://xarray.pydata.org/en/stable/), which seems to provide support for multidimensional arrays, with operator broadcasting, multiple indices and dataframe-like structures. Would it be right to compare the goals of `stars` to those of `xarray`?

**Comment by shoyer** [comment]
I came here to suggest the same thing! I see a lot of similarities, especially when xarray is considered alongside Dask for distributed computation. Certainly many of the use cases are similar.

I'm the lead developer for xarray, so I'm happy to answer any questions once you've looked over the docs.

**Comment by edzer** [comment]
I was planning to discuss xarray with Fabien @fmaussion when he is at [EGU](http://meetingorganizer.copernicus.org/EGU2017/picos/22866), although I realize he's giving an xarray workshop during our session; good to meet you here.

Yes, I think both stars and xarray want to represent multidimensional arrays where (some) array dimensions refer to time and/or space. IIRC, xarray interfaces netcdf right now, which will (in practice) limit its use to mostly spatial rasters, and to data-on-local-disk. 

Exciting challenges will be handling multi-resolution datasets (e.g. Sentinel-2 being a mix of 10-, 20- and 60-meter pixels), and collections of scenes - think GEE image collections. What are xarray's ambitions in this respect? 

Not unrelated, while in Vienna and together with @cpaulik we're also planning another meeting to discuss how to realize [openEO](http://r-spatial.org/2016/11/29/openeo.html), where you and @fmaussion are also more than welcome to join.

**Comment by cpaulik** [comment]
AFAIK, xarray does also interface to e.g. opendap so it is not strictly limited to local datasets. Also multiresolution datasets should be no problem for the [Common Data Model](http://www.unidata.ucar.edu/software/thredds/current/netcdf-java/CDM/) that xarray implements.

It would of course be good to discuss the existing solutions in the context of openEO in Vienna.

**Comment by cpaulik** [comment]
@edzer Yes xarray uses the Common Data Model that also netCDF uses but it works on data that is loaded on demand into memory. 

When working with data that does not fit into memory xarray can use dask - see http://xarray.pydata.org/en/latest/dask.html

**Comment by shoyer** [comment]
Xarray has a data model inspired by netCDF, but data doesn't need to be loaded from netCDF files or even from disk. There are lots of xarray users who don't use netCDF files at all (especially non-geoscience users, e.g., in other areas of science or finance).

**Comment by shabbybanks** [comment]
I work in finance (`banks` is my work handle), and have long been waiting for a good multidimensional time series data structure to work with. So kudos, and I can't wait to test out the code, in 6-12 months time. 
(Should I close the issue? It's not a real one.)

**Comment by fmaussion** [comment]
Thanks for the info, I agree it would be nice to meet! Regarding the xarray related events at EGU, we have a stupid overlap between the xarray presentation (the mentioned [PICO session](http://meetingorganizer.copernicus.org/EGU2017/session/22866)) and the [xarray tutorial](http://meetingorganizer.copernicus.org/EGU2017/session/25651) (both Thursday, 15:30-17:00).

Thanks to this great community, we are still able to do both:
- Benoit (@benbovy) will present xarray at the PICO session
- Ed (@?), Matthew (@gidden) and myself will give the tutorial

We can continue this discussion per mail if you wish!

**Comment by shoyer** [comment]
By the way, our paper on xarray just came out today in JORS: http://openresearchsoftware.metajnl.com/articles/10.5334/jors.148/

**Comment by edzer** [comment]
Congratulations with a very nice paper, in a promising journal!
