### ISSUE TITLE
missing value where TRUE/FALSE needed when opening a file

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/stars#31]
Use [this](https://drive.google.com/open?id=1KEjwxeeCyuJGaU3naU0rZAtGAZZsx11E) example  NetCDF file. Try to open it:

```R
read_stars("EOBS_2001-2016.nc")
```
Returns:
```
Error in if (diff(range(ud))/mean(ud) < 1e-10) { : 
  missing value where TRUE/FALSE needed
```

I can otherwise open the file normally with other software.

**Comment by edzer** [comment]
`ncdump` reveals it has a `-inf` value in one of the dimensions, and that is where things break -- how should `stars` treat that?

**Comment by adrfantini** [comment]
Shouldn't it be able to read in the dimension and display something like this?

```
       from    to     offset       delta  refsys point       values
bin    -Inf   1000       NA        NA       NA     NA       c(-Inf, 1, 2, 3, ...)
```

**Comment by adrfantini** [comment]
Thanks!

**Comment by adrfantini** [comment]
@mdsumner Apparently this was fixed in `read_stars` but not in `read_ncdf`.

 Also, @edzer , reding this file takes ages, even if it is in a RAMdisk.:
```
system.time(r <- read_stars('EOBS_2001-2016.nc'))
   user  system elapsed 
 49.484   0.160  49.690
```

**Comment by edzer** [comment]
Where do I find this file?

**Comment by adrfantini** [comment]
> Where do I find this file?

It is linked in the second word of this issue ;)

**Comment by adrfantini** [comment]
I suspect reading via GDAL means this is reading one layer (level) at a time, separately, instead of all at once? I remember something about this GDAL limitation. The file is compressed and chunked, removing the chunking helps:
```
   user  system elapsed 
  6.400   0.012   6.411
```
This suggests that GDAL is reading the file with an access pattern which is not efficient, given the chunking of the file.

**Comment by edzer** [comment]
Less than 1 second ...

**Comment by edzer** [comment]
Sorry, that commit was meant for #63
