### ISSUE TITLE
Export function to distinguish between vector or raster data cube

### ISSUE THREAD

**Issue by agila5** [r-spatial/stars#311]
Hi @edzer, following the discussion we had this morning, I created this issue to ask if it's possible to export the function that is used to distinguish between vector and raster data cubes (which is `has_raster()`?)

**Comment by edzer** [comment]
```
tif = system.file("tif/L7_ETMs.tif", package = "stars")
x = read_stars(tif)
st_raster_type(x)
# [1] "regular"
```

**Comment by agila5** [comment]
Thanks!
