### ISSUE TITLE
Calculate area of cells and/or provide a way to calculate area-weighted statistics

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/stars#32]
In many cases, the area of the cells of a `stars` object is not constant (e.g. lat-lon grids, or irregular grids in general). It would sometimes be useful to be able to obtain the area with the likes of `st_area()`.

One example use-case is doing field (x-y) averages of a given variable over the third dimension:
```R
tif = system.file("tif/L7_ETMs.tif", package = "stars")
x1 = read_stars(tif)
st_apply(x1, 3, mean)
```
This average, for irregular grids, is not area-weighted and thus can differ quite a bit from the real area average. Being able to calculate areas without going through `sf` would facilitate the correct computation of field means.

Also, if not too complicated, it would be nice if a way to calculate area-weighted statistics (any-dimension-weighted, really) were provided... although I have no idea on how this could be implemented.

**Comment by edzer** [comment]
`st_area()`; see #99
