### ISSUE TITLE
'stars' values from points: 'st_extract' much slower than conversion to polygons + 'st_join'

### ISSUE THREAD

**Issue by michaeldorman** [r-spatial/stars#322]
When "extracting" `stars` raster values to points, seems like `st_extract` is much slower than converting the raster to polygons and using `st_join`. I was under the impression that `st_extract` is a more specialized function and therefore should be faster or at least the same speed as the "brute force" approach of converting the raster to polygons and using spatial join... Will be happy to learn if I'm missing something or whether `st_extract` has different advantages I'm not aware of. Thanks!

Here is a reproducible example, with timing, for both approaches to extract raster values to points:

``` r
# Create 'stars' object
library(stars)
d = st_dimensions(x = 1:ncol(volcano), y = 1:nrow(volcano))
r = st_as_stars(t(volcano))
r = st_set_dimensions(r, 1, offset = 0, delta = 1)
r = st_set_dimensions(r, 2, offset = nrow(volcano), delta = -1)

# Create points
pnt = st_sample(st_as_sfc(st_bbox(r)), 1000)
pnt = st_as_sf(pnt)

# Plot
plot(r, reset = FALSE)
plot(st_geometry(pnt), add = TRUE, col = "red")
```

![unnamed-chunk-1-1](https://user-images.githubusercontent.com/9386655/93711091-018c0680-fb54-11ea-9f6b-33da965dfcc8.png)

``` r
# Extract - 'st_join'
start = Sys.time()
x = st_join(pnt, st_as_sf(r))
end = Sys.time()
x = x$A1
end - start
```

    ## Time difference of 0.2180228 secs

``` r
# Extract - 'st_extract'
start = Sys.time()
y = st_extract(r, pnt)
end = Sys.time()
y = y$A1
end - start
```

    ## Time difference of 4.922297 secs

``` r
# Compare
all.equal(x, y)
```

    ## [1] TRUE

**Comment by edzer** [comment]
Thanks, this should be faster now.

**Comment by michaeldorman** [comment]
Great, thanks! `st_extract` is now much faster than going through `st_join`, as expected:


``` r
# Create 'stars' object
library(stars)
```

    ## Loading required package: abind

    ## Loading required package: sf

    ## Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0

``` r
d = st_dimensions(x = 1:ncol(volcano), y = 1:nrow(volcano))
r = st_as_stars(t(volcano))
r = st_set_dimensions(r, 1, offset = 0, delta = 1)
r = st_set_dimensions(r, 2, offset = nrow(volcano), delta = -1)

# Create points
pnt = st_sample(st_as_sfc(st_bbox(r)), 1000)
pnt = st_as_sf(pnt)

# Extract - 'st_join'
start = Sys.time()
x = st_join(pnt, st_as_sf(r))
end = Sys.time()
x = x$A1
end - start
```

    ## Time difference of 0.0747416 secs

``` r
# Extract - 'st_extract'
start = Sys.time()
y = st_extract(r, pnt)
end = Sys.time()
y = y$A1
end - start
```

    ## Time difference of 0.004167795 secs

``` r
# Compare
all.equal(x, y)
```

    ## [1] TRUE
