### ISSUE TITLE
`st_extract` fails when there are points outside of raster extent

### ISSUE THREAD

**Issue by michaeldorman** [r-spatial/stars#332]
Function `st_extract` fails with an error when there are points outside the extent of the raster. IMHO the expected behaviour (such as in`raster::extract`) should be assigning an “extracted value” of `NA` to those points not coinciding with any raster value.

Please see reproducible example below. Thank you very much\!

-----

This creates a raster and points. Some of the points are beyond raster extent:

``` r
# Sample raster
library(stars)
d = st_dimensions(x = 1:ncol(volcano), y = 1:nrow(volcano))
r = st_as_stars(t(volcano))
r = st_set_dimensions(r, 1, offset = 0, delta = 1)
r = st_set_dimensions(r, 2, offset = nrow(volcano), delta = -1)

# Raster extent
ext = st_as_sfc(st_bbox(r))

# Create points
pnt = st_sample(st_buffer(ext, 10), 1000)
pnt = st_as_sf(pnt)

# Plot
plot(pnt, col = NA, reset = FALSE)
plot(r, reset = FALSE, add = TRUE)
plot(st_geometry(pnt), add = TRUE, col = "red")
```

![unnamed-chunk-1-1](https://user-images.githubusercontent.com/9386655/95067484-96723080-070c-11eb-9078-5a234bb5e8e3.png)

Extracting values doesn’t work:

``` r
st_extract(r, pnt)
```

    ## Error in ar[i, , drop = FALSE]: subscript out of bounds

Extracting values works for those points within the raster extent:

``` r
st_extract(r, pnt[ext, ])
```

    ## Simple feature collection with 634 features and 1 field
    ## geometry type:  POINT
    ## dimension:      XY
    ## bbox:           xmin: 0.125675 ymin: 0.04262365 xmax: 60.75116 ymax: 86.82023
    ## CRS:            NA
    ## First 10 features:
    ##     A1                         x
    ## 1  133 POINT (47.51692 46.84943)
    ## 2  124 POINT (46.77777 40.44146)
    ## 3  190 POINT (37.30389 68.48557)
    ## 4  155 POINT (18.16654 53.63597)
    ## 5  117 POINT (6.544409 29.59668)
    ## 6  112 POINT (39.14204 17.00526)
    ## 7  107 POINT (25.81144 4.555626)
    ## 8  132  POINT (24.7178 16.09534)
    ## 9  179 POINT (21.94223 67.23596)
    ## 10 116  POINT (7.38178 47.93327)

Session information:

``` r
sessionInfo()
```

    ## R version 4.0.2 (2020-06-22)
    ## Platform: x86_64-pc-linux-gnu (64-bit)
    ## Running under: Ubuntu 20.04.1 LTS
    ## 
    ## Matrix products: default
    ## BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
    ## LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0
    ## 
    ## locale:
    ##  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
    ##  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
    ##  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
    ##  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
    ##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
    ## [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
    ## 
    ## attached base packages:
    ## [1] stats     graphics  grDevices utils     datasets  methods   base     
    ## 
    ## other attached packages:
    ## [1] stars_0.4-4 sf_0.9-7    abind_1.4-5
    ## 
    ## loaded via a namespace (and not attached):
    ##  [1] Rcpp_1.0.5         knitr_1.30         magrittr_1.5       units_0.6-7       
    ##  [5] tidyselect_1.1.0   R6_2.4.1           rlang_0.4.7        stringr_1.4.0     
    ##  [9] dplyr_1.0.2        tools_4.0.2        parallel_4.0.2     grid_4.0.2        
    ## [13] xfun_0.18          KernSmooth_2.23-17 e1071_1.7-3        DBI_1.1.0         
    ## [17] ellipsis_0.3.1     htmltools_0.5.0    class_7.3-17       yaml_2.2.1        
    ## [21] digest_0.6.25      lwgeom_0.2-5       tibble_3.0.3       lifecycle_0.2.0   
    ## [25] crayon_1.3.4       purrr_0.3.4        vctrs_0.3.4        glue_1.4.2        
    ## [29] evaluate_0.14      rmarkdown_2.4      stringi_1.5.3      pillar_1.4.6      
    ## [33] compiler_4.0.2     generics_0.0.2     classInt_0.4-3     pkgconfig_2.0.3

**Comment by edzer** [comment]
Thanks, should work now! Yeah, 0 values for points outside proxy objects, don't see immediately how that can be resolved...

**Comment by michaeldorman** [comment]
Confirming that it works now, thank you very much\!

``` r
# Sample data
library(stars)
d = st_dimensions(x = 1:ncol(volcano), y = 1:nrow(volcano))
r = st_as_stars(t(volcano))
r = st_set_dimensions(r, 1, offset = 0, delta = 1)
r = st_set_dimensions(r, 2, offset = nrow(volcano), delta = -1)

# Raster extent
ext = st_as_sfc(st_bbox(r))

# Create points
pnt = st_sample(st_buffer(ext, 10), 1000)
pnt = st_as_sf(pnt)

# Extract
st_extract(r, pnt)
```

    ## Simple feature collection with 1000 features and 1 field
    ## geometry type:  POINT
    ## dimension:      XY
    ## bbox:           xmin: -9.947935 ymin: -9.972171 xmax: 70.93052 ymax: 96.97158
    ## CRS:            NA
    ## First 10 features:
    ##     A1                          x
    ## 1  108  POINT (6.188611 79.67573)
    ## 2  173  POINT (48.34761 61.80317)
    ## 3  116   POINT (57.7731 59.96615)
    ## 4  153  POINT (13.84765 58.88403)
    ## 5   NA POINT (57.95403 -6.008458)
    ## 6   NA  POINT (31.63817 96.91977)
    ## 7   NA POINT (-1.317134 22.98742)
    ## 8  164  POINT (22.61255 45.95987)
    ## 9  149  POINT (50.48054 65.06335)
    ## 10  NA   POINT (67.42111 1.71495)

**Comment by michaeldorman** [comment]
Another edge case about `st_extract`, I see that the above-mentioned
error persists when the `stars` isn’t normalized (for example, resulting
from subsetting where index doesn’t start from `1`).

Please see reproducible example below. Thank you very much\!

-----

``` r
# Sample data
library(stars)
```

    ## Loading required package: abind

    ## Loading required package: sf

    ## Linking to GEOS 3.8.1, GDAL 3.1.3, PROJ 7.1.1

``` r
d = st_dimensions(x = 1:ncol(volcano), y = 1:nrow(volcano))
r = st_as_stars(t(volcano))
r = st_set_dimensions(r, 1, offset = 0, delta = 1)
r = st_set_dimensions(r, 2, offset = nrow(volcano), delta = -1)

# Raster extent
ext = st_as_sfc(st_bbox(r))

# Create points
pnt = st_sample(st_buffer(ext, 10), 1000)
pnt = st_as_sf(pnt)

# Plot
plot(pnt, col = NA, reset = FALSE)
plot(r, reset = FALSE, add = TRUE)
plot(st_geometry(pnt), add = TRUE, col = "red")
```

![unnamed-chunk-1-1](https://user-images.githubusercontent.com/9386655/95200153-92b2dc80-07e6-11eb-8365-d5daaa7fbabd.png)

Extracting values works:

``` r
st_extract(r, pnt)
```

    ## Simple feature collection with 1000 features and 1 field
    ## geometry type:  POINT
    ## dimension:      XY
    ## bbox:           xmin: -9.93419 ymin: -9.783537 xmax: 70.95115 ymax: 96.87901
    ## CRS:            NA
    ## First 10 features:
    ##     A1                           x
    ## 1   NA  POINT (56.64792 -8.595702)
    ## 2   NA POINT (63.28851 -0.4141227)
    ## 3  140   POINT (14.44786 18.29725)
    ## 4  165   POINT (23.95218 41.53099)
    ## 5   NA   POINT (70.88821 37.80434)
    ## 6   NA POINT (-0.8037375 94.99484)
    ## 7   NA  POINT (64.50839 -4.626942)
    ## 8   NA   POINT (66.90432 44.14358)
    ## 9   94   POINT (56.89172 2.598991)
    ## 10 117    POINT (2.38296 35.28197)

Extracting values doesn’t work if raster extent isn’t “normalized”,
specifically if the indices don’t start from `1`:

``` r
r = r[,2:nrow(r),2:ncol(r)]
st_extract(r, pnt)
```

    ## Error in ar[i, , drop = FALSE]: subscript out of bounds

Normalizing the raster fixes the problem:

``` r
r = st_normalize(r)
st_extract(r, pnt)
```

    ## Simple feature collection with 1000 features and 1 field
    ## geometry type:  POINT
    ## dimension:      XY
    ## bbox:           xmin: -9.93419 ymin: -9.783537 xmax: 70.95115 ymax: 96.87901
    ## CRS:            NA
    ## First 10 features:
    ##     A1                           x
    ## 1   NA  POINT (56.64792 -8.595702)
    ## 2   NA POINT (63.28851 -0.4141227)
    ## 3  140   POINT (14.44786 18.29725)
    ## 4  165   POINT (23.95218 41.53099)
    ## 5   NA   POINT (70.88821 37.80434)
    ## 6   NA POINT (-0.8037375 94.99484)
    ## 7   NA  POINT (64.50839 -4.626942)
    ## 8   NA   POINT (66.90432 44.14358)
    ## 9   94   POINT (56.89172 2.598991)
    ## 10 117    POINT (2.38296 35.28197)

Session information:

``` r
sessionInfo()
```

    ## R version 4.0.2 (2020-06-22)
    ## Platform: x86_64-pc-linux-gnu (64-bit)
    ## Running under: Ubuntu 20.04.1 LTS
    ## 
    ## Matrix products: default
    ## BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
    ## LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0
    ## 
    ## locale:
    ##  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
    ##  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
    ##  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
    ##  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
    ##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
    ## [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
    ## 
    ## attached base packages:
    ## [1] stats     graphics  grDevices utils     datasets  methods   base     
    ## 
    ## other attached packages:
    ## [1] stars_0.4-4 sf_0.9-7    abind_1.4-5
    ## 
    ## loaded via a namespace (and not attached):
    ##  [1] Rcpp_1.0.5         knitr_1.30         magrittr_1.5       units_0.6-7       
    ##  [5] tidyselect_1.1.0   R6_2.4.1           rlang_0.4.7        stringr_1.4.0     
    ##  [9] dplyr_1.0.2        tools_4.0.2        parallel_4.0.2     grid_4.0.2        
    ## [13] xfun_0.18          KernSmooth_2.23-17 e1071_1.7-3        DBI_1.1.0         
    ## [17] ellipsis_0.3.1     htmltools_0.5.0    class_7.3-17       yaml_2.2.1        
    ## [21] digest_0.6.25      lwgeom_0.2-5       tibble_3.0.3       lifecycle_0.2.0   
    ## [25] crayon_1.3.4       purrr_0.3.4        vctrs_0.3.4        glue_1.4.2        
    ## [29] evaluate_0.14      rmarkdown_2.4      stringi_1.5.3      pillar_1.4.6      
    ## [33] compiler_4.0.2     generics_0.0.2     classInt_0.4-3     pkgconfig_2.0.3

**Comment by michaeldorman** [comment]
@edzer I couldn't reopen the issue, please let me know if you prefer this should be in a new issue, thanks

**Comment by edzer** [comment]
extractions from proxy objects now get proper NA values, scale/offset handling, and units.

**Comment by michaeldorman** [comment]
Confirming that it works now. Thank you very much\!

-----

``` r
# Sample data
library(stars)
```

    ## Loading required package: abind

    ## Loading required package: sf

    ## Linking to GEOS 3.8.1, GDAL 3.1.3, PROJ 7.1.1

``` r
d = st_dimensions(x = 1:ncol(volcano), y = 1:nrow(volcano))
r = st_as_stars(t(volcano))
r = st_set_dimensions(r, 1, offset = 0, delta = 1)
r = st_set_dimensions(r, 2, offset = nrow(volcano), delta = -1)

# Raster extent
ext = st_as_sfc(st_bbox(r))

# Create points
pnt = st_sample(st_buffer(ext, 10), 1000)
pnt = st_as_sf(pnt)
```

This now works:

``` r
r = r[,2:nrow(r),2:ncol(r)]
st_extract(r, pnt)
```

    ## Simple feature collection with 1000 features and 1 field
    ## geometry type:  POINT
    ## dimension:      XY
    ## bbox:           xmin: -9.943447 ymin: -9.942428 xmax: 70.98623 ymax: 96.97438
    ## CRS:            NA
    ## First 10 features:
    ##     A1                          x
    ## 1   NA POINT (-4.458159 71.69986)
    ## 2   NA  POINT (69.18706 26.01513)
    ## 3   NA POINT (20.52093 -9.551595)
    ## 4  143  POINT (9.352087 58.10756)
    ## 5   NA POINT (-3.664945 83.84356)
    ## 6  161  POINT (36.13035 47.10575)
    ## 7  158  POINT (21.20922 42.37821)
    ## 8   NA  POINT (-3.51655 77.96357)
    ## 9   NA POINT (55.79409 -1.179156)
    ## 10  NA POINT (-9.943447 64.07898)
