### ISSUE TITLE
NoData values in raster interpreted as `NaN`?

### ISSUE THREAD

**Issue by michaeldorman** [r-spatial/stars#333]
I noticed that NoData raster values are interpreted as `NaN`. For example:

``` r
# Sample data
library(stars)
f = tempfile()
download.file("https://geobgu.xyz/r/data/dem.tif", f)
r = read_stars(f)
```

``` r
r[[1]]
```

    ##      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
    ## [1,]  NaN  NaN  NaN  NaN  NaN  NaN  NaN    3    5     7
    ## [2,]  NaN  NaN  NaN   61  106   47   31   39   32    49
    ## [3,]  NaN  NaN  NaN    9  132  254  233  253  199   179
    ## [4,]  NaN  NaN  NaN    4   11  146  340  383  357   307
    ## [5,]  NaN    4    6    9    6    6  163  448  414   403
    ## [6,]    3    6    9   10    6    6   13  152  360   370
    ## [7,]    3    4    7   16   27   12   64   39   48    55

I wonder if this is intentional? If so, please feel free to close the issue. If not, IMHO the situation can be confusing when there is a mixture of `NA` and `NaN` values in the same object. For example, when cropping a raster:

``` r
x = st_bbox(r)
x = st_as_sfc(x)
x = st_centroid(x)
x = st_buffer(x, 10000)
r = r[x, crop = FALSE]
```

``` r
plot(r, text_values = TRUE, col = terrain.colors(10), reset = FALSE)
plot(st_geometry(st_as_sf(r, na.rm = FALSE)), add = TRUE)
```

![unnamed-chunk-4-1](https://user-images.githubusercontent.com/9386655/95372204-eb1bd400-08e3-11eb-8c69-685a0313a20b.png)

Here the resulting raster has a mixture of `NA` (“empty” cells) and `NaN` (marked with text labels “NaN”), although the meaning seems identical (missing raster value).

Thank you very much for your attention and sorry for the multiple issues over the last few days\! (I’m preparing the spatial R course materials for the forthcoming semester and therefore exploring the `stars` package to be able to better explain it in the course.)

Session information:

``` r
sessionInfo()
```

    ## R version 4.0.2 (2020-06-22)
    ## Platform: x86_64-pc-linux-gnu (64-bit)
    ## Running under: Ubuntu 20.04.1 LTS
    ## 
    ## Matrix products: default
    ## BLAS:   /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3.10.3
    ## LAPACK: /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3.10.3
    ## 
    ## locale:
    ##  [1] LC_CTYPE=en_IL       LC_NUMERIC=C         LC_TIME=en_IL       
    ##  [4] LC_COLLATE=en_IL     LC_MONETARY=en_IL    LC_MESSAGES=en_IL   
    ##  [7] LC_PAPER=en_IL       LC_NAME=C            LC_ADDRESS=C        
    ## [10] LC_TELEPHONE=C       LC_MEASUREMENT=en_IL LC_IDENTIFICATION=C 
    ## 
    ## attached base packages:
    ## [1] stats     graphics  grDevices utils     datasets  methods   base     
    ## 
    ## other attached packages:
    ## [1] stars_0.4-4 sf_0.9-6    abind_1.4-5
    ## 
    ## loaded via a namespace (and not attached):
    ##  [1] Rcpp_1.0.5         knitr_1.30         magrittr_1.5       units_0.6-7       
    ##  [5] tidyselect_1.1.0   R6_2.4.1           rlang_0.4.7        stringr_1.4.0     
    ##  [9] dplyr_0.8.5        tools_4.0.2        parallel_4.0.2     grid_4.0.2        
    ## [13] xfun_0.18          KernSmooth_2.23-17 e1071_1.7-3        DBI_1.1.0         
    ## [17] ellipsis_0.3.1     htmltools_0.5.0    class_7.3-17       yaml_2.2.1        
    ## [21] digest_0.6.25      assertthat_0.2.1   lwgeom_0.2-5       lifecycle_0.2.0   
    ## [25] tibble_3.0.3       crayon_1.3.4       purrr_0.3.4        vctrs_0.3.4       
    ## [29] glue_1.4.2         evaluate_0.14      rmarkdown_2.1      stringi_1.4.6     
    ## [33] pillar_1.4.6       compiler_4.0.2     classInt_0.4-3     pkgconfig_2.0.3

**Comment by edzer** [comment]
Good catch - should work now!

**Comment by michaeldorman** [comment]
Great, thank you!

``` r
# Sample data
library(stars)
f = tempfile()
download.file("https://geobgu.xyz/r/data/dem.tif", f)
r = read_stars(f)
```

``` r
r[[1]]
```

    ##      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
    ## [1,]   NA   NA   NA   NA   NA   NA   NA    3    5     7
    ## [2,]   NA   NA   NA   61  106   47   31   39   32    49
    ## [3,]   NA   NA   NA    9  132  254  233  253  199   179
    ## [4,]   NA   NA   NA    4   11  146  340  383  357   307
    ## [5,]   NA    4    6    9    6    6  163  448  414   403
    ## [6,]    3    6    9   10    6    6   13  152  360   370
    ## [7,]    3    4    7   16   27   12   64   39   48    55
