### ISSUE TITLE
Vignette 1 Figure 1 - axes missing in figure

### ISSUE THREAD

**Issue by michaeldorman** [r-spatial/stars#335]
This is a minor issue in Vignette 1.

Below the first image, the text says:

> We see that the image is geographically referenced (has coordinate values along axes)

![Screenshot from 2020-10-12 14-33-35](https://user-images.githubusercontent.com/9386655/95742445-b4a1d880-0c98-11eb-8ed9-11c61c1d8029.png)

However the figure doesn't have values along axes. Perhaps the last expression in the code section:

```r
plot(x)
```

should be replaced with:

```r
plot(x, axes = TRUE)
```

Thanks!

**Comment by edzer** [comment]
Thanks!
