### ISSUE TITLE
Conversion from raster to stars does not preserve factor levels properly

### ISSUE THREAD

**Issue by ailich** [r-spatial/stars#339]
Conversion from raster to stars object doesn't preserve factor levels properly if the raster has values that don't go in a sequence from 1 to the number of levels, which can be the case if you are subsetting an area or if you are stacking maps to get the unique combinations of 2 categorical raster layers. Instead of linking the value with the factor, it creates a sequence from 1 to the largest numerical value, where all other levels are filled with NA. This can cause issues in plotting with tmap (https://github.com/mtennekes/tmap/issues/516).
```
library(stars) #Version ‘0.4.3’
library(spData)
library(raster)

data("grain")
print(levels(grain)[[1]])
  ID VALUE
1  1  clay
2  2  silt
3  3  sand

grain2 <- as.factor(grain*10)
levels(grain2)[[1]]$VALUE <- levels(grain)[[1]]$VALUE
print(levels(grain2)[[1]])
  ID VALUE
1 10  clay
2 20  silt
3 30  sand

grain_stars<- st_as_stars(grain)
print(levels(grain_stars[["layer"]]))
#"clay" "silt" "sand"

grain2_stars<- st_as_stars(grain2)
print(levels(grain2_stars[["layer"]]))
# [1] NA     NA     NA     NA     NA     NA     NA     NA     NA     "clay" NA     NA     NA     NA     NA     NA     NA     NA     NA     "silt" NA    
# [22] NA     NA     NA     NA     NA     NA     NA     NA     "sand"

```

**Comment by edzer** [comment]
I see
```
> grain2_stars[[1]]
     [,1] [,2] [,3] [,4] [,5] [,6]
[1,] sand silt silt clay silt sand
[2,] clay clay sand sand silt clay
[3,] sand clay sand sand sand silt
[4,] silt clay silt clay sand silt
[5,] clay silt silt sand clay clay
[6,] silt sand clay clay silt sand
30 Levels: <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> clay <NA> <NA> ... sand
Warning message:
In print.factor(x) : duplicated level [2] in factor
> levels(grain2_stars[[1]])[c(10,20,30)]
[1] "clay" "silt" "sand"
```
which seems to be in line with the information in `grain2`. `stars` and `raster` handle factor rasters differently: `raster` entirely emulates them, `stars` uses base R factors (with a `dim` attribute, making them factor arrays). This explains the difference in output what `levels` gives you. 

R doesn't work well with `NA` factor levels: usually you know the levels and only factor values can become `NA` (as of: eye color: blue/brown/NA - NA is not a factor level but a value not corresponding to a level). I see that
```
plot(grain2_stars)
```
doesn't look good, however
```
plot(droplevels(grain2_stars))
```
does.

So I am not entirely sure this is an issue that should be solved in `stars`: `stars` retains the values and correspondence to levels of the raster object.

Maybe `stars::plot.stars` and `tmap` should both, just before plotting
* check for NA values in levels of a factor raster layer
* if present, call `droplevels` on it before plotting

or else require users to call this before plotting such un-R-factor-like factor variables.

**Comment by edzer** [comment]
... as in
```
tm_shape(droplevels(st_as_stars(grain2))) + tm_raster()
```
since `Raster` objects do not have a `droplevels` method.

**Comment by ailich** [comment]
@edzer, thanks. Adding droplevels works perfectly for plotting. I do think adding it within the plotting functions could make it more intuitive.
