### ISSUE TITLE
Provide a method for modifying dimensions

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/stars#34]
Sometimes I want to modify dimensions. Say, for example, my file has 4 timesteps, one for each season. They have timestamps associated to them, but I'd prefer to have character values `c("DJF", "MAM", "JJA", "SON")`.

Currently one can do this with the following:
```R
attr(ss2, "dimensions")[["time"]]$values <- c("DJF", "MAM", "JJA", "SON")
```

I realize however this is not elegant nor, probably, correct, since I should also change `refsys` and possibly other metadata.
A mechanism to help with this could be handy... in case it is not there already and I completely missed it!

**Comment by edzer** [comment]
There already was a
```r
ss2 %>% st_set_dimensions("time", c("DJF", "MAM", "JJA", "SON"))
```
but the current setup should make this better. Pls test! See also https://github.com/r-spatial/stars/commit/e4d00b295bbacef5e24fdb2232720b3dc8111797

**Comment by adrfantini** [comment]
Thanks!
I am honoured, I really appreciate it.

**Comment by adrfantini** [comment]
If `s %>% st_set_dimensions("time", c("MAM", "JJA", "SON", "DJF"))` works, any reason why `st_dimensions(s, "time") <- c("MAM", "JJA", "SON", "DJF")` should not?

**Comment by edzer** [comment]
There is no `st_dimensions<-`.  A good reason to not have one is that `st_set_dimensions` takes three arguments, and all replacement functions, afaict, take two.

**Comment by adrfantini** [comment]
> all replacement functions, afaict, take two
Ah OK, I did not know this. Thanks for the clarification.

**Comment by mdsumner** [comment]
@adrfantini I encountered this labelling in these lessons that use Python's xarray https://carpentrieslab.github.io/python-aos-lesson/

Is that labelling and "time.season" functionality common in Python tools, or in the work you do with climate data? (Is it a CMIP5 thing?) I don't see those seasonal labels in the file in the lesson, so I assume it's an xarray idiom - but would like to know if it's widely used?   I find it pretty fragile given all the variability in ways that time and dates can be encoded, but maybe in CMIP5 it's reliable enough?

**Comment by adrfantini** [comment]
@mdsumner I'm not sure I understand what you mean.
Climatological seasons are different from actual seasons, for simplicity.
Labelling seasons with the initials of the respective months is extremely common in climate science (only in the final data-analysis, not in simulations). In Europe for example you will see papers referring to 'DJF' as often as to 'winter', or even more. In the same way, the monsoon season is usually referred to as 'JJAS' in India.

Is this what you were asking?

**Comment by mdsumner** [comment]
That answers, thanks!  It looks like xarray has auto-interpreters for time and will apply groupby("time.season") as a special case with those month-triplets as output labels.
