### ISSUE TITLE
Modifying `names` of individual dimension returns error

### ISSUE THREAD

**Issue by michaeldorman** [r-spatial/stars#354]
Possibly a minor bug, or at least not intuitive behavior (IMHO), in `st_set_dimensions`: setting the name (`names` property) of one specific dimension results in an error. 

``` r
# 'stars' object
library(stars)
r = read_stars(system.file("tif/L7_ETMs.tif", package = "stars"))

# Rename one dimension - doesn't work
st_set_dimensions(r, 3, names = "layer")
```

    ## Error in st_set_dimensions(r, 3, names = "layer"): length of names should match number of dimensions

The workarounds I’m using to modify the name of a particular dimension are: 
* Setting all dimension names at once (which means repeating the names of dimensions that I do not need to change) 

``` r
# Rename all dimensions - works
st_set_dimensions(r, names = c("x", "y", "layer"))
```

    ## stars object with 3 dimensions and 1 attribute
    ## attribute(s):
    ##   L7_ETMs.tif    
    ##  Min.   :  1.00  
    ##  1st Qu.: 54.00  
    ##  Median : 69.00  
    ##  Mean   : 68.91  
    ##  3rd Qu.: 86.00  
    ##  Max.   :255.00  
    ## dimension(s):
    ##       from  to  offset delta                       refsys point values
    ## x        1 349  288776  28.5 UTM Zone 25, Southern Hem... FALSE   NULL
    ## y        1 352 9120761 -28.5 UTM Zone 25, Southern Hem... FALSE   NULL
    ## layer    1   6      NA    NA                           NA    NA   NULL
    ##       x/y
    ## x     [x]
    ## y     [y]
    ## layer

* Modifying another property (such as `values`) along with the `names` (which is sometimes
unnecessary, when all I want to change is the name)

``` r
# Rename one dimension & set another property - works
st_set_dimensions(r, 3, names = "layer", values = paste0("band", 1:6))
```

    ## stars object with 3 dimensions and 1 attribute
    ## attribute(s):
    ##   L7_ETMs.tif    
    ##  Min.   :  1.00  
    ##  1st Qu.: 54.00  
    ##  Median : 69.00  
    ##  Mean   : 68.91  
    ##  3rd Qu.: 86.00  
    ##  Max.   :255.00  
    ## dimension(s):
    ##       from  to  offset delta                       refsys point
    ## x        1 349  288776  28.5 UTM Zone 25, Southern Hem... FALSE
    ## y        1 352 9120761 -28.5 UTM Zone 25, Southern Hem... FALSE
    ## layer    1   6      NA    NA                           NA    NA
    ##                values x/y
    ## x                NULL [x]
    ## y                NULL [y]
    ## layer band1,...,band6

Thank you very much, will appreciate any suggestion on this!

Session informarion:

``` r
sessionInfo()
```

    ## R version 4.0.3 (2020-10-10)
    ## Platform: x86_64-pc-linux-gnu (64-bit)
    ## Running under: Ubuntu 20.04.1 LTS
    ## 
    ## Matrix products: default
    ## BLAS:   /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3.10.3
    ## LAPACK: /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3.10.3
    ## 
    ## locale:
    ##  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
    ##  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
    ##  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
    ##  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
    ##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
    ## [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
    ## 
    ## attached base packages:
    ## [1] stats     graphics  grDevices utils     datasets  methods  
    ## [7] base     
    ## 
    ## other attached packages:
    ## [1] stars_0.4-4 sf_0.9-7    abind_1.4-5
    ## 
    ## loaded via a namespace (and not attached):
    ##  [1] Rcpp_1.0.5         knitr_1.30         magrittr_2.0.1    
    ##  [4] units_0.6-7        tidyselect_1.1.0   R6_2.4.1          
    ##  [7] rlang_0.4.9        stringr_1.4.0      dplyr_0.8.5       
    ## [10] tools_4.0.3        parallel_4.0.3     grid_4.0.3        
    ## [13] xfun_0.18          KernSmooth_2.23-18 e1071_1.7-4       
    ## [16] DBI_1.1.0          ellipsis_0.3.1     htmltools_0.5.0   
    ## [19] class_7.3-17       yaml_2.2.1         digest_0.6.25     
    ## [22] assertthat_0.2.1   lwgeom_0.2-5       lifecycle_0.2.0   
    ## [25] tibble_3.0.3       crayon_1.3.4       purrr_0.3.4       
    ## [28] vctrs_0.3.4        glue_1.4.2         evaluate_0.14     
    ## [31] rmarkdown_2.1      stringi_1.5.3      pillar_1.4.6      
    ## [34] compiler_4.0.3     classInt_0.4-3     pkgconfig_2.0.3

**Comment by michaeldorman** [comment]
Thanks\! This now works:

``` r
# 'stars' object
library(stars)
r = read_stars(system.file("tif/L7_ETMs.tif", package = "stars"))

# Rename one dimension - by index
st_set_dimensions(r, 3, names = "layer")
```

    ## stars object with 3 dimensions and 1 attribute
    ## attribute(s):
    ##   L7_ETMs.tif    
    ##  Min.   :  1.00  
    ##  1st Qu.: 54.00  
    ##  Median : 69.00  
    ##  Mean   : 68.91  
    ##  3rd Qu.: 86.00  
    ##  Max.   :255.00  
    ## dimension(s):
    ##       from  to  offset delta                       refsys point values
    ## x        1 349  288776  28.5 UTM Zone 25, Southern Hem... FALSE   NULL
    ## y        1 352 9120761 -28.5 UTM Zone 25, Southern Hem... FALSE   NULL
    ## layer    1   6      NA    NA                           NA    NA   NULL

However, when `which` is `character` it still doesn’t work...

``` r
# Rename one dimension - by name
st_set_dimensions(r, "band", names = "layer")
```

    ## Error in base::`names<-`(d, value = new_names): 'names' attribute [4] must be the same length as the vector [3]

Thanks again for the help\!

Session information:

``` r
sessionInfo()
```

    ## R version 4.0.3 (2020-10-10)
    ## Platform: x86_64-pc-linux-gnu (64-bit)
    ## Running under: Ubuntu 20.04.1 LTS
    ## 
    ## Matrix products: default
    ## BLAS:   /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3.10.3
    ## LAPACK: /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3.10.3
    ## 
    ## locale:
    ##  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
    ##  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
    ##  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
    ##  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
    ##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
    ## [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
    ## 
    ## attached base packages:
    ## [1] stats     graphics  grDevices utils     datasets  methods  
    ## [7] base     
    ## 
    ## other attached packages:
    ## [1] stars_0.4-4 sf_0.9-7    abind_1.4-5
    ## 
    ## loaded via a namespace (and not attached):
    ##  [1] Rcpp_1.0.5         knitr_1.30         magrittr_2.0.1    
    ##  [4] units_0.6-7        tidyselect_1.1.0   R6_2.4.1          
    ##  [7] rlang_0.4.9        stringr_1.4.0      dplyr_0.8.5       
    ## [10] tools_4.0.3        parallel_4.0.3     grid_4.0.3        
    ## [13] xfun_0.18          KernSmooth_2.23-18 e1071_1.7-4       
    ## [16] DBI_1.1.0          ellipsis_0.3.1     htmltools_0.5.0   
    ## [19] class_7.3-17       yaml_2.2.1         digest_0.6.25     
    ## [22] assertthat_0.2.1   lwgeom_0.2-5       lifecycle_0.2.0   
    ## [25] tibble_3.0.3       crayon_1.3.4       purrr_0.3.4       
    ## [28] vctrs_0.3.4        glue_1.4.2         evaluate_0.14     
    ## [31] rmarkdown_2.1      stringi_1.5.3      pillar_1.4.6      
    ## [34] compiler_4.0.3     classInt_0.4-3     pkgconfig_2.0.3

**Comment by edzer** [comment]
Thanks - should work now!

**Comment by michaeldorman** [comment]
Thanks\! It works:

``` r
library(stars)
r = read_stars(system.file("tif/L7_ETMs.tif", package = "stars"))
st_set_dimensions(r, "band", names = "layer")
```

    ## stars object with 3 dimensions and 1 attribute
    ## attribute(s):
    ##   L7_ETMs.tif    
    ##  Min.   :  1.00  
    ##  1st Qu.: 54.00  
    ##  Median : 69.00  
    ##  Mean   : 68.91  
    ##  3rd Qu.: 86.00  
    ##  Max.   :255.00  
    ## dimension(s):
    ##       from  to  offset delta                       refsys
    ## x        1 349  288776  28.5 UTM Zone 25, Southern Hem...
    ## y        1 352 9120761 -28.5 UTM Zone 25, Southern Hem...
    ## layer    1   6      NA    NA                           NA
    ##       point values
    ## x     FALSE   NULL
    ## y     FALSE   NULL
    ## layer    NA   NULL

**Comment by michaeldorman** [comment]
Sorry, but seems like now the old behaviour that worked in the initial comment (setting all dimension names at once, without `which`) is no longer working now:

```r
library(stars)
r = read_stars(system.file("tif/L7_ETMs.tif", package = "stars"))
st_set_dimensions(r, names = c("x", "y", "layer"))
## Error in st_set_dimensions(r, names = c("x", "y", "layer")) : 
##   argument "which" is missing, with no default
```
