### ISSUE TITLE
Add dimensions to st_rasterize

### ISSUE THREAD

**Issue by abesolberg** [r-spatial/stars#355]
I would like to add an additional dimension to st_rasterize. For example, give the following bit of code: 
```
system.file("gpkg/nc.gpkg", package = "sf") %>%
  read_sf() %>%
  st_transform(32119) -> nc
nc$dens79 = nc$BIR79 / units::set_units(st_area(nc), km^2)
nc$dens74 = nc$BIR74 / units::set_units(st_area(nc), km^2)

nc.long <- bind_rows(
  nc %>% select(NAME , dens = dens74 , geom) %>% mutate(year = 1974) , 
  nc %>% select(NAME , dens = dens79 , geom) %>% mutate(year = 1979)
)

nc.long

(nc.st = st_rasterize(nc.long["dens"], dx = 5000, dy = 5000))
```

I would like a stars object with 3 dimensions and one attribute, or a time-series stars raster with a year dimension, so one layer of the raster has 1974 density and another has 1979 density. Instead, I get only the two XY dimensions and one attribute. 

```
stars object with 2 dimensions and 1 attribute
attribute(s):
 dens [1/km^2]   
 Min.   : 0.255  
 1st Qu.: 1.226  
 Median : 1.932  
 Mean   : 3.346  
 3rd Qu.: 3.826  
 Max.   :21.248  
 NA's   :4808    
dimension(s):
  from  to offset delta                 refsys point values    
x    1 162 123830  5000 NAD83 / North Carolina FALSE   NULL [x]
y    1  61 318256 -5000 NAD83 / North Carolina FALSE   NULL [y]
```

I have tried to do this numerous ways, including `st_as_stars(nc.long , dim = 'year')` and `st_rasterize(nc.long["dens"], template = st_as_stars(st_bbox(nc.long) , dim = 'dens') , dx = 5000, dy = 5000)` but I always get the same result (or an error).

Is there a way to do this? I know I could create a stars object with the geom, but I need it rasterized. Thank you!

**Comment by edzer** [comment]
There's no way (AFAICT) to do this from the long table, and `st_rasterize` (currently) only rasterizes the frist attribute of an `sf` object. So what you can do is
```r
d74 = st_rasterize(nc["dens74"], dx = 5000, dy = 5000)
d79 = st_rasterize(nc["dens79"], dx = 5000, dy = 5000)
c(d74,d79)
merge(c(d74,d79)) %>% st_set_dimensions(3, names = "time", values = c(1974,1979))
```
to combine the two time attributes into a time dimension.

**Comment by abesolberg** [comment]
Thank you for the quick reply! That works very well for the repex I gave. However, the data I'm working with is a bit more complicated. It's species observations, and the points shift slightly every year, making it so that the XY dimensions change very slightly each year. 

Because of this, when I run `c(d1 , d2)` I get the error `Error in c.stars(d1, d2) : don't know how to merge arrays: please specify parameter along.` 

If I use `c(d1 , d2 , try_hard = T)`, I get a result, but I am no longer able to add the third dimension because it merges them along the rasterized field. 

If I try to set the template argument in st_rasterize to `template = st_bbox(range)`, I am then able to concatenate and merge them, but most of the values go to NA. I am working on a new regex for this follow up issue. 

Thank you again!

**Comment by edzer** [comment]
Please also explain what you are trying to accomplish.

**Comment by abesolberg** [comment]
I have a large dataset of fisheries observations in the North Atlantic. Each point represents the biomass from a certain survey on a certain year. There are about 80 points (surveys) per year,  and they are not in the same place each year. The overall extent of the surveys remains mostly the same however. 

I want to create a raster for each year, and I want to have a third dimension for the year, so that I can use the stars data cube structure and functions to compare across years and plot in ggplot. 

Year 1 outputs this:
```
stars object with 2 dimensions and 1 attribute
attribute(s):
    biomass        
 Min.   :    0.00  
 1st Qu.:   22.71  
 Median :  154.71  
 Mean   :  914.76  
 3rd Qu.:  672.71  
 Max.   :12785.42  
 NA's   :1058      
dimension(s):
  from to offset delta refsys point values    
x    1 55   47.8   0.2     NA    NA   NULL [x]
y    1 24   42.8   0.2     NA    NA   NULL [y]
```
Year 2 outputs this: 
```
stars object with 2 dimensions and 1 attribute
attribute(s):
    biomass       
 Min.   :   0.00  
 1st Qu.:  14.53  
 Median :  98.53  
 Mean   : 342.14  
 3rd Qu.: 286.53  
 Max.   :3471.20  
 NA's   :1132     
dimension(s):
  from to offset delta refsys point values    
x    1 56   47.8   0.2     NA    NA   NULL [x]
y    1 25   42.8   0.2     NA    NA   NULL [y]
```

I need to merge these to form something like this: 
```
stars object with 3 dimensions and 1 attribute
attribute(s):
    biomass       
 Min.   :   0.00  
 1st Qu.:  14.53  
 Median :  98.53  
 Mean   : 342.14  
 3rd Qu.: 286.53  
 Max.   :3471.20  
 NA's   :1132     
dimension(s):
  from to offset delta refsys point values    
x    1 56   47.8   0.2     NA    NA   NULL [x]
y    1 25   42.8   0.2     NA    NA   NULL [y]
year 1 2   1996 1                           1996...
```

**Comment by abesolberg** [comment]
This roughly approximates the problem using the Breweries dataset from mapview

```
df <- mapview::breweries %>% 
  na.omit() %>% 
  mutate(CENTURY = if_else(founded < 2000 , 1900 , 2000)) 

df <- split(df , df$CENTURY)
df <- map(df, select , c(beers = number.of.types , everything()))
df <- map(df , st_rasterize , dx = .5 , dy = .5)

b.19 <- df$`1900` ; b.20 <- df$`2000`

c(b.19 , b.20)
merge(c(b.19 , b.20))
```

Thank you!

**Comment by edzer** [comment]
Since the data is not gridded, (how) are you going to handle the case where more than one observation fall into a single grid cell? Plotting with `ggplot2` can be done, easier, without using stars. Comparing the years in a datacube structure will be complicated if the different years don't have observations at the same locations, as seems to be the case for you.

**Comment by abesolberg** [comment]
How does stars typically handle two points in the same grid cell, if you set large dx dy values? For me, ideally values would be summed to represent to the total biomass sampled in grid cell. The specific lat-lng locations are not the same across years, but the strata (or cell) remains consistent across years. It feels like I could use the template argument to standardize the grid (and standardize the dimensions), but whenever I do that the values get really wonky. 

```
df <- mapview::breweries %>% 
  na.omit() %>% 
  mutate(CENTURY = if_else(founded < 2000 , 1900 , 2000)) 
X <- df
df <- split(df , df$CENTURY)
df <- map(df, select , c(beers = number.of.types , everything()))
df <- map(df , st_rasterize , dx = .5 , dy = .5 , template = st_as_stars(st_bbox(X)))

b.19 <- df$`1900` ; b.20 <- df$`2000`

b.19 ; b.20

stars object with 2 dimensions and 1 attribute
attribute(s):
     beers         
 Min.   : 0.00000  
 1st Qu.: 0.00000  
 Median : 0.00000  
 Mean   : 0.00451  
 3rd Qu.: 0.00000  
 Max.   :14.00000  
dimension(s):
  from  to  offset       delta refsys point values    
x    1 336 9.46279  0.00736725 WGS 84 FALSE   NULL [x]
y    1 194 50.3232 -0.00736725 WGS 84 FALSE   NULL [y]

stars object with 2 dimensions and 1 attribute
attribute(s):
     beers         
 Min.   :0.000000  
 1st Qu.:0.000000  
 Median :0.000000  
 Mean   :0.000368  
 3rd Qu.:0.000000  
 Max.   :5.000000  
dimension(s):
  from  to  offset       delta refsys point values    
x    1 336 9.46279  0.00736725 WGS 84 FALSE   NULL [x]
y    1 194 50.3232 -0.00736725 WGS 84 FALSE   NULL [y]

```
Another solution that seems to work okay is to add `NULL` points from the st_bbox of the entire set to each year, which also standardizes the grid: 

```
df <- mapview::breweries %>% 
  na.omit() %>% 
  mutate(CENTURY = if_else(founded < 2000 , 1900 , 2000)) 
bnd <- st_bbox(df)
X <- bind_cols(
  lng = c(bnd['xmin'] , bnd['xmax']) , 
  lat = c(bnd['ymin'] , bnd['ymax']) , 
  CENTURY = c(1900 , 2000)
) %>% 
  complete(lat , lng , CENTURY) %>% 
  st_as_sf(coords = c("lng", "lat")) %>% 
  sf::st_set_crs(st_crs(df))

df <- bind_rows(df , X) 

df <- split(df , df$CENTURY)
df <- map(df, select , c(beers = number.of.types , everything()))
df <- map(df , st_rasterize , dx = .5 , dy = .5)

b.19 <- df$`1900` ; b.20 <- df$`2000`
# plot(b.19) ; plot(b.20)
b.19 ; b.20

b.star <- merge(c(b.19 , b.20)) %>% 
  st_set_dimensions(3, names = "Century", values = c(1900,2000))

b.star ; plot(b.star)
```

It seems like this last option works fine, but I'm wondering if there isn't a better/easier/faster way, and will these NULL points impact my ability to compare across years? 

Thanks again.
