### ISSUE TITLE
Installing the starsdata pkg

### ISSUE THREAD

**Issue by LDalby** [r-spatial/stars#357]
I wanted to use data from the starsdata pkg to see if I could replicate an issue I'm seeing with data provided in starsdata.
However I'm seeing this when trying to install the pkg:

``` r
install.packages("starsdata", repos = "http://gis-bigdata.uni-muenster.de", type = "source")
#> Installing package into '/home/au206907/R/x86_64-pc-linux-gnu-library/4.0'
#> (as 'lib' is unspecified)
#> Warning: unable to access index for repository http://gis-bigdata.uni-muenster.de/src/contrib:
#>   cannot open URL 'http://gis-bigdata.uni-muenster.de/src/contrib/PACKAGES'
#> Warning: package 'starsdata' is not available for this version of R
#> 
#> A version of this package for your version of R might be available elsewhere,
#> see the ideas at
#> https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
```
Is it possible to install starsdata on R 4.0.3?

<sup>Created on 2020-12-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by edzer** [comment]
I need to look into that. The alternative, 

`install.packages("starsdata", repos = "http://pebesma.staff.ifgi.de", type = "source") ` 

seems to work.

**Comment by LDalby** [comment]
Yes, that works - thanks!

I had to increase the timeout on my system due to our seriously slow internet connection, so in case others find this issue in the future timeout is set via:
```r
options(timeout = 100)
```

**Comment by StephanLo** [comment]
Is it possible to update the vignette and stars proxy objects article to reflect this?  (The alternative repo) 
I just faced the same issue.

Thanks!
