### ISSUE TITLE
st_rasterize applied to regular grid of points does not align pixel centers with points

### ISSUE THREAD

**Issue by hrodmn** [r-spatial/stars#360]
I expected `st_rasterize` to align pixel centers with the point coordinates of a regular grid but that is not what happened!

I believe this is because of the default behavior in `st_as_stars` that sets the minimum/maximum x/y bounds for the stars object to the min/max values from the bounding box of the input object.

Perhaps this is intentional but it seems somewhat counter-intuitive to me, or maybe there is a better way to convert a regular grid of points into a stars raster?

I have found a workaround where I first convert my points to a set of square pixels using `sf::st_buffer(..., endCapStyle = "SQUARE")` but I thought I might raise the question here.

``` r
# build a regular grid of points
dx <- dy <- 1

pts <- sf::st_as_sf(
  expand.grid(x = seq(1, 4, by = dx), y = seq(1, 4, by = dy)),
  coords = c("x", "y")
)

# fill in some values
pts$value <- rnorm(nrow(pts))

# convert to raster
pts_rast <- stars::st_rasterize(pts, dx = dx, dy = dy)

# plot shows raster cells corners aligned with points
ggplot2::ggplot() +
  stars::geom_stars(data = pts_rast) +
  ggplot2::geom_sf(data = pts)
```

![](https://i.imgur.com/BAkJcsK.png)

``` r

# if I make square polygons it does what I expect
polys <- sf::st_buffer(
  pts,
  dist = dx / 2,
  endCapStyle = "SQUARE"
)

poly_rast <- stars::st_rasterize(polys, dx = dx, dy = dy) 

ggplot2::ggplot() +
  stars::geom_stars(data = poly_rast) +
  ggplot2::geom_sf(data = pts)
```

![](https://i.imgur.com/jKvPhsf.png)

<sup>Created on 2020-12-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by edzer** [comment]
What you could do is
```r
pts_rast <- stars::st_rasterize(pts, dx = dx, dy = dy, xlim = c(0.5, 4.5), ylim = c(0.5, 4.5))
```
The reason this doesn't work out of the box is that `st_rasterize` can't assume that `pts` contains points layed out on a regular grid.

**Comment by hrodmn** [comment]
I understand why you cannot assume the points are on a regular grid. Is there a more logical path to convert a regular grid `sf` object to stars raster?

Your suggestion works well, here is what I came up with for determining the xlim and ylim on the fly:
``` r
# build a regular grid of points
dx <- dy <- 1

pts <- sf::st_as_sf(
  expand.grid(x = seq(1, 4, by = dx), y = seq(1, 4, by = dy)),
  coords = c("x", "y")
)

# fill in some values
pts$value <- rnorm(nrow(pts))

# define desired extent by buffering the bounding box by a half-pixel width
rast_extent <- sf::st_bbox(pts) + c(-dx / 2, -dy  / 2, dx / 2, dy / 2)

# convert to raster
pts_rast <- stars::st_rasterize(
  pts,
  dx = dx,
  dy = dy,
  xlim = c(rast_extent["xmin"], rast_extent["xmax"]),
  ylim = c(rast_extent["ymin"], rast_extent["ymax"])
)

# plot shows raster cells aligned with points
ggplot2::ggplot() +
  stars::geom_stars(data = pts_rast) +
  ggplot2::geom_sf(data = pts)
```

![](https://i.imgur.com/EbktNSH.png)

<sup>Created on 2020-12-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by edzer** [comment]
Yes, this could be built in in `st_rasterize`, e.g. by adding an argument `is_regular = TRUE` (default `FALSE`) which would then, for `POINT` geometries, sort out `dx`, `dy` and extent.

**Comment by edzer** [comment]
This should do it:
```
# build a regular grid of points
dx <- dy <- 1

pts <- sf::st_as_sf(
  expand.grid(x = seq(1, 4, by = dx), y = seq(1, 4, by = dy)),
  coords = c("x", "y")
)

# fill in some values
pts$value <- rnorm(nrow(pts))

# convert to raster
stars::st_rasterize(pts)
# stars object with 2 dimensions and 1 attribute
# attribute(s):
#      value        
#  Min.   :-1.7146  
#  1st Qu.:-0.1014  
#  Median : 0.3753  
#  Mean   : 0.3421  
#  3rd Qu.: 0.9365  
#  Max.   : 2.0289  
# dimension(s):
#   from to offset delta refsys point values x/y
# x    1  4    0.5     1     NA    NA   NULL [x]
# y    1  4    4.5    -1     NA    NA   NULL [y]

g = expand.grid(x = seq(1, 4, by = dx), y = seq(1, 4, by = dy))
g[1,1] = g[1,1] + 0.001 # shift
pts0 <- sf::st_as_sf(g, coords = c("x", "y"))
stars::st_rasterize(pts0) # doesn't do it
# stars object with 2 dimensions and 1 attribute
# attribute(s):
#       ID        
#  Min.   : 1.00  
#  1st Qu.: 4.75  
#  Median : 8.50  
#  Mean   : 8.50  
#  3rd Qu.:12.25  
#  Max.   :16.00  
#  NA's   :65009  
# dimension(s):
#   from  to offset      delta refsys point values x/y
# x    1 255      1  0.0117851     NA    NA   NULL [x]
# y    1 255      4 -0.0117851     NA    NA   NULL [y]
```
(committed to a branch, soon to be merged in master)
