### ISSUE TITLE
Processing raster in block

### ISSUE THREAD

**Issue by kadyb** [r-spatial/stars#361]
I try to load part of the raster in the block, but I get incorrect results.

```r
library(stars)

file = system.file("tif/olinda_dem_utm25s.tif", package = "stars")

rasterio = list(nXOff = 1, nYOff = 1, nXsize = 5, nYSize = 5)
img = stars::read_stars(file, RasterIO = rasterio)
dim(img)
#>   x   y
#> 111   5
```

I would expect a 5 x 5 result.

**Comment by edzer** [comment]
That should be `nXSize` instead of `nXsize`. Corrected in https://github.com/r-spatial/stars/pull/359 (by you).

**Comment by kadyb** [comment]
Oh, yeah. I forgot to correct in my code.
