### ISSUE TITLE
cannot share fill and colour scale between geom_stars and geom_sf

### ISSUE THREAD

**Issue by japhir** [r-spatial/stars#363]
I'm trying to plot some point data which were measured onboard a large ship on top of satellite sea surface temperature data.

However, I cannot get the colour and fill scales to collapse and use the same values.

- download the data from the WOA database: https://www.nodc.noaa.gov/cgi-bin/OC5/woa18/woa18.pl
- run reprex code below

``` r
library(tidyverse)
library(stars)
#> Loading required package: abind
#> Loading required package: sf
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.2

# world ocean atlas data from https://www.nodc.noaa.gov/cgi-bin/OC5/woa18/woa18.pl
# -> this leads to this download link:
# https://data.nodc.noaa.gov/thredds/fileServer/ncei/woa/temperature/decav/0.25/woa18_decav_t00_04.nc
# which I downloaded into downloads
woa18 <- read_ncdf("~/Downloads/woa18_decav_t00_04.nc", var = "t_an")
nc <- woa18 %>% filter(depth == 0)

# fake data
dat <- tibble(lat = 40:50,
              lon = -c(38, 38.2, 38.6, 39, 39.5, 40, 40.1, 41, 42, 42.3, 45),
              temperature = rnorm(11, 10, 3))

# quick inspection of results to show that they are not gridded
dat %>%
  ggplot(aes(x = lon, y = lat, colour = temperature)) +
  geom_point()
```

![](https://i.imgur.com/LphboYI.png)

``` r
# convert points to nc data according to https://ggplot2-book.org/maps.html#rastermaps
latlon <- dat %>%
  select(lon, lat) %>%
  as.matrix()

geometry <- latlon %>%
  st_multipoint() %>%
  st_sfc() %>%
  st_cast("POINT")

ctd <- st_sf(temperature = dat$temperature, geometry)
st_crs(ctd) <- st_crs("+proj=longlat +datum=WGS84")

ctd <- st_transform(ctd, st_crs(nc))

# plot combined
ggplot() +
  geom_stars(data = nc,
             downsample = #0,
             c(3, 3, 0)
             ) +
  geom_sf(aes(colour = temperature), data = ctd, size = 5) +
  coord_sf(xlim = c(-70, -30), ylim = c(30, 55), expand=0) +
  # normal way of merging fill and colour scales:
  # - make sure they have the same name
  # - make sure they have the same labels
  scale_fill_continuous(name = "t", labels = seq(0, 30, 5), breaks = seq(0, 30, 5)) +
  scale_colour_continuous(name = "t", labels = seq(0, 30, 5), breaks = seq(0, 30, 5))
```

![](https://i.imgur.com/ztxEPmZ.png)

<sup>Created on 2020-12-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by japhir** [comment]
Hmm from further experimentation, it appears that this is a general issue when using geom_raster and geom_point with the fill and colour aesthetics when I have two different data sources:

``` r
library(tidyverse)

dat <- tibble(x = 1:10, y = 11:20, z = rnorm(10))
dat2 <- dat %>% mutate(z = rnorm(10, z, .01))

ggplot(dat, aes(x = x, y = y, colour = z)) +
  geom_point() +
  geom_raster(aes(fill = z), data = dat2)
```

![](https://i.imgur.com/C9tH25c.png)

<sup>Created on 2020-12-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by japhir** [comment]
created an issue upstream: https://github.com/tidyverse/ggplot2/issues/4290

**Comment by luisDVA** [comment]
hi, scales for different data sources can be worked around with `ggnewscale`
https://github.com/eliocamp/ggnewscale

**Comment by japhir** [comment]
Thanks @luisDVA, but my goal here was actually to have the two scales merge into one, with a shared legend! Since they represent the same type of information/units etc.

**Comment by luisDVA** [comment]
my bad, I misread the question and now I see the issue. I've actually had this problem before so I'm glad it's being brought up formally.
