### ISSUE TITLE
Conversion from raster to stars loses factor levels if file is saved

### ISSUE THREAD

**Issue by ailich** [r-spatial/stars#364]
If a raster is saved on disk, the factor information seems to get lost when converting to a stars object.
Currently have the lastest version of stars (0.4-4), tmap (3.2), and raster (3.4-8) installed from github.

```
library(raster)
library(tmap)
library(stars)

r1<- raster(volcano)
r2<- reclassify(r1, rcl=matrix(data=c(90,120, 120, 200, 1,2), ncol=3, nrow = 2))
r2<- as.factor(r2)
levels(r2)[[1]]$Class<- c("CLASS_A", "CLASS_B")

r2_stars<- st_as_stars(r2)
unique(as.vector(r2_stars$layer))
#"CLASS_A" "CLASS_B"
levels(r2_stars$layer)
"CLASS_A" "CLASS_B"
tm_shape(r2_stars)+
  tm_raster(style = "cat")
```
![tmapplot1](https://user-images.githubusercontent.com/28163862/103033162-d1c41480-452f-11eb-99a1-5189c40e2289.png)
```
writeRaster(r2, filename = "temp.grd", overwrite=TRUE)

r3<- raster("temp.grd", overwrite=TRUE)
is.factor(r3)
#TRUE
levels(r3)
# [[1]]
# ID   Class
# 1  1 CLASS_A
# 2  2 CLASS_B

r3_stars<- st_as_stars(r3)
unique(as.vector(r3_stars$layer))
#1 2
levels(r3_stars$layer)
#"CLASS_B"

tm_shape(r3_stars)+
  tm_raster(style = "cat")
```

![tmapplot2](https://user-images.githubusercontent.com/28163862/103033228-033ce000-4530-11eb-8c87-4edcb9574bbc.png)

**Comment by edzer** [comment]
You can use
```
r3_stars<- st_as_stars(r3, ignore_file=TRUE)
```
to get the factor levels. In case you need to work with large files, use another file format -- .grd is AFAIR a dedicated format for which only package raster knows all the rules.

**Comment by ailich** [comment]
Awesome, thanks!
