### ISSUE TITLE
Subsetting raster stack/brick if written to file

### ISSUE THREAD

**Issue by ailich** [r-spatial/stars#365]
Subsetting a layer from a raster stack/brick and converting it to a stars object creates empty layers/bands instead of just a matrix. This can take up a lot of memory if there are many bands and you are just trying to get one, and prevents plotting in tmap.  Currently have the lastest version of stars (0.4-4), tmap (3.2), and raster (3.4-8) installed from github.

```
library(raster)
library(tmap)
library(stars)

r<- raster(volcano)
r_stack<- stack(r, focal(r, w=matrix(data = 1, nrow=3, ncol=3), fun=mean, na.rm=TRUE), focal(r, w=matrix(data = 1, nrow=3, ncol=3), fun=sd, na.rm=TRUE))

stars_obj<- st_as_stars(r_stack[[2]])
class(stars_obj$layer.2)
#[1] "matrix"
dim(stars_obj$layer.2)
# [1] 61 87
tm_shape(stars_obj)+
  tm_raster()
```
![tmapplot3](https://user-images.githubusercontent.com/28163862/103034806-c1159d80-4533-11eb-8f3d-4cfbebaa11b2.png)

```
writeRaster(r_stack, "temp.grd", overwrite=TRUE)

r_stack2<- brick("temp.grd")

stars_obj2<- st_as_stars(r_stack2[[2]])
class(stars_obj2$layer.2)
#[1] "array
dim(stars_obj2$layer.2)
# x    y band 
# 61   87    3 
tm_shape(stars_obj2)+
  tm_raster()
#Error in dim.stars(x) : length(d) == length(dim(x[[1]])) is not TRUE
```

**Comment by edzer** [comment]
See #364 ! ;-)

**Comment by edzer** [comment]
So, this is solved by conversion to `stars` using
```
stars_obj2<- st_as_stars(r_stack2[[2]], ignore_file=TRUE)
```
If you would omit the `[[2]]`, it seems to work without ignoring the file.
