### ISSUE TITLE
GeoPackage in detect.driver()?

### ISSUE THREAD

**Issue by KevCaz** [r-spatial/stars#366]
Hi @edzer , 

Is there any particular reason for not having GeoPackage included in `detect.driver()`? If not, I would not mind opening a PR to add it. 

Also, it might be worth using a`switch` statement in `detect.driver()` to improve readability? I did it on my fork https://github.com/KevCaz/stars/blob/db22418bd50d1f587c065c2b5200d97383d6a497/R/write.R#L139-L180, let me know if you think this could be useful.

Anyway, many thanks for your work on this great package.

**Comment by edzer** [comment]
Yes, good addition, and that improves readability - PR appreciated!

**Comment by KevCaz** [comment]
I think we can close this!
