### ISSUE TITLE
cut() for stars objects containing non-numeric values

### ISSUE THREAD

**Issue by KevCaz** [r-spatial/stars#368]
Hi @edzer 

As I was working with `stars` today, `cut()` threw the following error: *Error in dim.stars(x) : length(d) == length(dim(x[[1]])) is not TRUE* when stars values (values of the array) were of class `units`, below is a minimal reprex: 

```R
library(units)
library(stars)

# 1. Case without units 
m <- matrix(1:20, nrow = 5, ncol = 4) 
sta <- st_as_stars(m)
(sta_cut <- cut(sta, c(0, 10, 20)))
# stars object with 2 dimensions and 1 attribute
# attribute(s):
#       A1     
#  (0,10] :10  
#  (10,20]:10  
# dimension(s):
#    from to offset delta refsys point values    
# X1    1  5      0     1     NA FALSE   NULL [x]
# X2    1  4      0     1     NA FALSE   NULL [y]

# NB
sta_cut[[1]]
#      [,1]   [,2]   [,3]    [,4]   
# [1,] (0,10] (0,10] (10,20] (10,20]
# [2,] (0,10] (0,10] (10,20] (10,20]
# [3,] (0,10] (0,10] (10,20] (10,20]
# [4,] (0,10] (0,10] (10,20] (10,20]
# [5,] (0,10] (0,10] (10,20] (10,20]
# Levels: (0,10] (10,20]


# 2. Case with units 
m_u <- as_units(m)
sta_u <- st_as_stars(m_u)
sta_cut_u <- cut(sta_u, c(0, 10, 20))
sta_cut_u 
# Error in dim.stars(x) : length(d) == length(dim(x[[1]])) is not TRUE

# NB
sta_cut_u[[1]]
# [1] (0,10]  (0,10]  (0,10]  (0,10]  (0,10]  (0,10]  (0,10]  (0,10] 
# [9] (0,10]  (0,10]  (10,20] (10,20] (10,20] (10,20] (10,20] (10,20]
# [17] (10,20] (10,20] (10,20] (10,20]
# Levels: (0,10] (10,20]
```

As shown above, this is due to the conversion done for objects of class `units`: they are first converted to numeric (the dimensions are thereby lost) before the cut is actually applied.  I guess a simple way to overcome this is to store the dimensions before the conversion and then add them back to the vector, e.g.

```R
mycut <- function(x, ...) {
  out <- cut(x, ...)
  dim(out) <- dim(x)
  out
}
```

and then use `mycut` instead of `cut` in https://github.com/r-spatial/stars/blob/3f762e3c6ace52feda705fb7388414de48903d67/R/factors.R#L32-L34

This solution could solve any problem caused by the first conversion to numeric in `cut`.  Let me know if this is a suitable solution.

**Comment by edzer** [comment]
Thanks!
