### ISSUE TITLE
Direct readers to (terra} for non-data cubes

### ISSUE THREAD

**Issue by charliejhadley** [r-spatial/stars#373]
Until [recently](https://twitter.com/TimSalabim3/status/1349705933321068544?s=20) I was under the impression that {stars} was a replacement (and improvement) upon the {raster} package. Tim Salabim was kind enough to correct me that {terra} will replace {raster}.

I only have my experience to go on, but I feel this is a reasonable mistake to make based on the current documentation and that the [Task View didn't mention {terra}](https://github.com/r-spatial/task_views/issues/17).

I've made a PR for this here https://github.com/r-spatial/stars/pull/372

**Comment by edzer** [comment]
See #372
