### ISSUE TITLE
Memory allocation problem in 'write_stars'

### ISSUE THREAD

**Issue by kadyb** [r-spatial/stars#376]
I think there is some problem with memory allocation in `write_stars` function. Rewriting the same file fails for my dataset. For example, the first and second saves are OK, and the next ones fail. In the case of the **terra** package, I did not notice such a problem. I have 8 GB RAM. Uncompressed rasters are approximately 4.5 GB.

```r
library("stars")
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1

rasters = list.files("data/LC08_L1TP_190024_20200418_20200822_02_T1/",
                     pattern = "\\.TIF$", full.names = TRUE)

ras = read_stars(rasters, proxy = TRUE)
ras = st_redimension(ras)

# first save always works
write_stars(ras, "test1.tif", options = c("COMPRESS=LZW"))
#> =======================================================================

# error at start
write_stars(ras, "test2.tif", options = c("COMPRESS=LZW"))
#> Error: cannot allocate vector of size 1.9 Gb

# error in half time
write_stars(ras, "test3.tif", options = c("COMPRESS=LZW"))
#> ========================Error: cannot allocate vector of size 1.9 Gb
```

> R version 4.0.3 (2020-10-10)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 8.1 x64 (build 9600)
> 
> Matrix products: default
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods  
> [7] base     
> 
> other attached packages:
> [1] stars_0.5-0 sf_0.9-7    abind_1.4-5
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.5         rstudioapi_0.13    magrittr_2.0.1    
>  [4] units_0.6-7        tidyselect_1.1.0   R6_2.5.0          
>  [7] rlang_0.4.10       dplyr_1.0.3        tools_4.0.3       
> [10] parallel_4.0.3     grid_4.0.3         xfun_0.20         
> [13] tinytex_0.28       KernSmooth_2.23-17 e1071_1.7-4       
> [16] DBI_1.1.1          ellipsis_0.3.1     class_7.3-17      
> [19] lwgeom_0.2-5       tibble_3.0.5       lifecycle_0.2.0   
> [22] crayon_1.3.4       purrr_0.3.4        vctrs_0.3.6       
> [25] glue_1.4.2         compiler_4.0.3     pillar_1.4.7      
> [28] generics_0.1.0     classInt_0.4-3     pkgconfig_2.0.3

**Comment by edzer** [comment]
Have you tried changing the default `chunk_size` in `write_stars()`?

**Comment by kadyb** [comment]
Thanks. Original chunk size was 7771 x 3217. I changed it to 7771 x 1608 and run 10 iterations with raster saving. Everything worked fine without any memory error.

**Comment by edzer** [comment]
Thanks - maybe that's a better default!

**Comment by kadyb** [comment]
Hard to say. I use an old laptop with 8 GB of memory, but currently computers are over a dozen GB (even top smartphones have 12 or more RAM), so you may not need to change these default parameters.

Maybe someday some heuristics can be implemented that take into account the amount of available memory and select optimal processing parameters? Maybe some solutions can be implemented from GDAL?
