### ISSUE TITLE
Differences in the crs when reading with read_stars and read_ncdf 

### ISSUE THREAD

**Issue by RobinKohrs** [r-spatial/stars#393]
Hi everyone, 

I'm trying to read in a NetCDF-file with `stars`. I naively first tried the `read_stars`-function and everything worked. I then discovered that there is an explicit `read_ncdf`-function. So I tried this one and it also read it in. However, they end up in different locations when I plot them with `mapview`. 
Also the `st_crs()` does not return the same for both. I'm not an expert so it's probable that I'm missing something. From the print to the console I can see that there are some differences in the offset, delta and the refsys. So I was just wondering what I'm missing here. 

The one read with `read_stars` ends up in the right location. 

 the one read with `read_ncdf`

```
stars object with 3 dimensions and 1 attribute
attribute(s):
 precipitation [mm]
 Min.   :0.00      
 1st Qu.:0.00      
 Median :0.00      
 Mean   :0.07      
 3rd Qu.:0.00      
 Max.   :4.10      
 NA's   :194505    
dimension(s):
     from  to         offset  delta                       refsys point values    
x       1 641         605720    250 +proj=tmerc +lat_0=0 +lon...    NA   NULL [x]
y       1 643        5059487    250 +proj=tmerc +lat_0=0 +lon...    NA   NULL [y]
DATE    1   1 1980-01-01 UTC 1 days                      POSIXct    NA   NULL 
```

 the one read with `read_stars`
```
stars object with 3 dimensions and 1 attribute
attribute(s):
 DAILYPCP_198001.nc [mm]
 Min.   :0.00           
 1st Qu.:0.00           
 Median :0.00           
 Mean   :0.07           
 3rd Qu.:0.00           
 Max.   :4.10           
 NA's   :194505         
dimension(s):
     from  to                                           offset                                       delta  refsys point values
x       1 641                                           605720                                         250 unnamed    NA   NULL
y       1 643                                          5220237                                        -250 unnamed    NA   NULL
DATE    1   1 3652.5 [(days since 1970-01-01 00:00:00 +00:00)] 1 [(days since 1970-01-01 00:00:00 +00:00)]      NA    NA   NULL
        
x    [x]
y    [y]
DATE   
```

On a map this looks like this: 

![image](https://user-images.githubusercontent.com/48288925/109807020-ad6a6f80-7c25-11eb-8e06-b802709e3b45.png)

**Comment by edzer** [comment]
Can you make the offending file available, or at least one that reproduces the problem?

**Comment by RobinKohrs** [comment]
Sure. I think the file should be now available for download under this link: 
https://1drv.ms/u/s!AuG956rIlOiehDe97dTVi0PozefR?e=84eppd

**Comment by edzer** [comment]
Thanks! The `read_ncdf` code uses `ncmeta::nc_gm_to_prj`, which seems to miss the longitude of central meridian being 9 (according to ncdump) which might have caused the offset.
```
    char transverse_mercator ;
        transverse_mercator:grid_mapping_name = "transverse_mercator" ;
        transverse_mercator:long_name = "CRS definition" ;
        transverse_mercator:longitude_of_central_meridian = 9. ;
        transverse_mercator:false_easting = 500000. ;
        transverse_mercator:false_northing = 0. ;
        transverse_mercator:latitude_of_projection_origin = 0. ;
        transverse_mercator:scale_factor_at_central_meridian = 0.9996 ;
        transverse_mercator:longitude_of_prime_meridian = 0. ;
        transverse_mercator:semi_major_axis = 6378137. ;
        transverse_mercator:inverse_flattening = 298.257223563 ;
        transverse_mercator:spatial_ref = "PROJCS[\"unknown\",GEOGCS[\"unknown\",                                 DATUM[\"Unknown_based_on_WGS84_ellipsoid\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",         \"7030\"]],TOWGS84[0,0,0,0,0,0,0]],PRIMEM[\"Greenwich\",0],UNIT[\"degree\",0.0174532925199433]],                 PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"latitude_of_origin\",0],PARAMETER[\"central_meridian\",9],       PARAMETER[\"scale_factor\",0.9996],PARAMETER[\"false_easting\",500000],PARAMETER[\"false_northing\",0],          UNIT[\"metre\",1,AUTHORITY[\"EPSG\",\"9001\"]]]" ;
        transverse_mercator:GeoTransform = "605720.00012 250 0 5220237.4801 0 -250" ;
```
Otherwise the gdal netcdf driver is wrong. Which one is correct?

@mdsumner could you pls take a look?

**Comment by mdsumner** [comment]
yes that sounds right, I see generic tmerc rather than Zone 32 UTM from ncmeta - so don't trust the interpretation from `read_ncdf()`, GDAL is correct -  can override it with input "+proj=utm +zone=32 +datum=WGS4" if working around

**Comment by mdsumner** [comment]
@dblodgett-usgs here in stars where the ncmeta code constructs a PROJ string

https://github.com/r-spatial/stars/blob/71be39d0e2b4039d6237615ce4787799d4a179bc/R/ncdf.R#L231

this file already has a 'spatial_ref' component that could be used directly by `st_crs()` so it could avoid problems of the churn through proj string. 

(In ncmeta the proj string is missing the "+lon_0" parameter from "longitude_of_central_meridian" ... but generally seems fraught to me to try reconstructing these strings there when the parameters are all present. )

**Comment by RobinKohrs** [comment]
Thanks a lot everyone for the help and the clarification:)! For now I will then just use `read_stars`.

**Comment by edzer** [comment]
@mdsumner maybe it is an idea to go for the WKT in `transverse_mercator:spatial_ref` when present - as in this case - and only parse the other arguments when it's not there?

**Comment by dblodgett-usgs** [comment]
`spatial_ref` is non standard but useful. We could ad something that searches through the attributes and returns what is found to be a valid WKT string? 

Missing "+lon_0" sounds like a bug. Is that in the ncmeta issue tracker @mdsumner ?

**Comment by mdsumner** [comment]
No it's not, felt out of my depth on that stuff

**Comment by dblodgett-usgs** [comment]
Looking into this just now. I am mapping "longitude_of_project_origin" onto "lon_0" rather than "longitude_of_central_meridian". So yeah, that's a bug according to this: http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#_transverse_mercator

PR incoming @mdsumner

**Comment by edzer** [comment]
Does it mean we can close here?

**Comment by dblodgett-usgs** [comment]
I think so.

**Comment by edzer** [comment]
Thanks!
