### ISSUE TITLE
read_stars don't find the variable of a netcdf file

### ISSUE THREAD

**Issue by silasprincipe** [r-spatial/stars#396]
Hello all. I'm trying to open a nc file using read_stars. The file is from Sea Surface Temperatura from the MIROC contribution to the CMIP6 (can be found here: https://esgf-node.ipsl.upmc.fr/search/cmip6-ipsl/). However, when using read_stars the object don't contain the variable attribute ("tos"), just the lon, lat and time dimensions:

 `> hist <- read_stars("data/cmip/tos_Oday_MIROC6_historical_r1i1p1f1_gn_20100101-20141231.nc")
Warning messages:
1: In CPL_read_gdal(as.character(x), as.character(options), as.character(driver),  :
  GDAL Message 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
2: In CPL_read_gdal(as.character(x), as.character(options), as.character(driver),  :
  GDAL Message 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
> hist
stars_proxy object with 1 attribute in file:
$`tos_Oday_MIROC6_historical_r1i1p1f1_gn_20100101-20141231.nc`
[1] "[...]/tos_Oday_MIROC6_historical_r1i1p1f1_gn_20100101-20141231.nc"

dimension(s):
     from   to                  offset  delta  refsys point values x/y
x       1  360                       0      1      NA    NA   NULL [x]
y       1  256                     256     -1      NA    NA   NULL [y]
time    1 1826 2010-01-01 12:00:00 UTC 1 days POSIXct    NA   NULL `

I can perfectly read this file using the ncdf4 package. Is there any way to clearly indicate to the read_stars function which is the variable to be read?

Thanks!

`> sessionInfo()
R version 4.0.4 (2021-02-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=Portuguese_Brazil.1252  LC_CTYPE=Portuguese_Brazil.1252    LC_MONETARY=Portuguese_Brazil.1252
[4] LC_NUMERIC=C                       LC_TIME=Portuguese_Brazil.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ncmeta_0.3.0 rgdal_1.5-23 sp_1.4-5     ncdf4_1.17   stars_0.5-1  sf_0.9-7     abind_1.4-5 

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6         pillar_1.5.0       compiler_4.0.4     class_7.3-18       tools_4.0.4        PCICt_0.5-4.1     
 [7] lifecycle_1.0.0    tibble_3.0.6       lattice_0.20-41    RNetCDF_2.4-2      pkgconfig_2.0.3    rlang_0.4.10      
[13] DBI_1.1.1          parallel_4.0.4     e1071_1.7-4        dplyr_1.0.4        raster_3.4-5       generics_0.1.0    
[19] vctrs_0.3.6        classInt_0.4-3     grid_4.0.4         tidyselect_1.1.0   glue_1.4.2         R6_2.5.0          
[25] fansi_0.4.2        purrr_0.3.4        magrittr_2.0.1     codetools_0.2-18   ellipsis_0.3.1     units_0.6-7       
[31] assertthat_0.2.1   utf8_1.1.4         KernSmooth_2.23-18 lwgeom_0.2-5       crayon_1.4.1      `

**Comment by mdsumner** [comment]
it's effectively impossible to get access to cmip data if you aren't in the loop ... any chance you can share the file?

**Comment by silasprincipe** [comment]
Hum, I see. Well, maybe it's a problem with the files. I also had problems opening it on the CDO (Climate Data Operators) on Windows (but no problems on Linux), so may also be something on my machine/R.

The file is really big to send over here, so here is the link: http://esgf-data2.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/tos/gn/v20181212/tos_Omon_MIROC6_historical_r1i1p1f1_gn_195001-201412.nc

Thanks!

**Comment by edzer** [comment]
With latitudes ranging from 90 to -150 it is completely unclear to me what these data try to convey.

**Comment by mdsumner** [comment]
you can access the file @edzer ? 

it's common to have some wonky grid in climate data (with unclear mapping-to-spatial -  sometimes they just "ignore" certain regions as being conveniently out of bounds for forgotten historical reasons). But, haven't come across that actual situation ...

**Comment by edzer** [comment]
Yes, I did a `wget` on the link provided above by @silasprincipe . Ah, I see, it is a curvilinear grid.

**Comment by edzer** [comment]
Looks weird:
```r
r = read_ncdf("tos_Omon_MIROC6_historical_r1i1p1f1_gn_195001-201412.nc", curvilinear = c("longitude", "latitude"))
plot(r[,,,1])
```
![x](https://user-images.githubusercontent.com/520851/112384540-d8108b00-8cee-11eb-9491-ffa3e28bbdb3.png)

**Comment by mdsumner** [comment]
this is normal ... there's a wrap with a non-standard meridian edge, it's got a logic to it and can be dealt with but not simply like that

I have notes I'll dig up, done this with anglr/angstroms - it requires special handling to fit straightforward vis examples

**Comment by mdsumner** [comment]
😋https://gist.github.com/mdsumner/61be4632bf5641dc31653d9d7cecdc01

**Comment by silasprincipe** [comment]
Thanks for the solution for visualizing those files @mdsumner! So, it's possible to open the file whrough the read_ncdf, but not through read_stars, right?

**Comment by edzer** [comment]
`read_stars` won't recognize the `longitude` and `latitude` arrays, but will read the main (temperature) array.

**Comment by mdsumner** [comment]
yes, there's no stars-ish way to really do this - but if you do the curvilinear thing with stars (as in edzer's code and plot above) and make a reprojected map you should get something reasonable (it's just really slow because polygons, but as given the long-lat space is not sensible, it has an abrupt boundary shift internally, but probably an orientation issue as well)

taking on the gdal-way you'd say that the lon/lat values are *GCPs* and churn that through GDALwarp (in the gdal api), but this hasn't been done in stars afaik (I've experimented loosely with it elsewhere)

(when we use these data seriously in research we don't want those sort of brute force structural conversions, we re-index our query - cells or polygons or points or lines to lookup - and transfer just the values back to the mapping contexts we use

**Comment by mdsumner** [comment]
and so, candidate projections are polar azimuthal or stereographic, these sort out the variable meridional boundary without fudging, stereographic is too expansive for the southern ocean and equal area too constrained, for pure vis can go with Azimuthal Equidistant, i.e. 

adapt @edzer code above (how to explicitly polygonize just one slice?)

```R
r = read_ncdf("tos_Omon_MIROC6_historical_r1i1p1f1_gn_195001-201412.nc", curvilinear = c("longitude", "latitude"))
p = st_as_sf(r[ <something>])

plot(st_transform(p, "+proj=aeqd +lat_0=90"))
```

you should see a map like this, which at least gives something sane to look at while exploring further use (I don't have the file used above, but I have access to similar (this is *ssp245/intpp/intpp_Omon_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_201501-203412.nc*)


![image](https://user-images.githubusercontent.com/4107631/112564649-c2ef4580-8e2f-11eb-8da5-2de8a6655d83.png)

**Comment by edzer** [comment]
Almost:
```r
p = st_as_sf(r[,,,1]) # select first time slice
plot(st_transform(units::drop_units(p), "+proj=aeqd +lat_0=90"), border = NA)
```
![x](https://user-images.githubusercontent.com/520851/112639140-38fba880-8e40-11eb-9d63-d63685c7e181.png)

(it breaks on the units; there's also a funny shape along the zero meridian, and a funny diamond shape in the center)

**Comment by silasprincipe** [comment]
Both @mdsumner and @edzer solutions are quite interesting for ploting the data. I will probably go with read_ncdf now (but read_stars is much faster at reading files, at least in my PC) and try to work with this data. Should I close the issue now?
