### ISSUE TITLE
stars objects with time dimensions don't survive export and re-import

### ISSUE THREAD

**Issue by charliejhadley** [r-spatial/stars#397]
Issue https://github.com/r-spatial/stars/issues/323 identified that dimension values didn't survive export and this was fixed in https://github.com/r-spatial/sf/commit/7f0a03f54f826239e15a0b30340179edd2b02b74.

Inserting values as dates breaks this loop:

```r
tif = system.file("tif/L7_ETMs.tif", package = "stars")
x = read_stars(tif)
# Fictional dates, these are actually bands
x = st_set_dimensions(x, 3, values = seq(as.Date("2021-01-01"), as.Date("2021-01-06"), "day"), name = "time")
write_stars(x, "x.tif")
read_stars("x.tif")
# stars object with 3 dimensions and 1 attribute
# attribute(s):
#   x.tif       
# Min.   :  1.00  
# 1st Qu.: 54.00  
# Median : 69.00  
# Mean   : 68.91  
# 3rd Qu.: 86.00  
# Max.   :255.00  
# dimension(s):
#   from  to  offset delta                       refsys point values x/y
# x       1 349  288776  28.5 UTM Zone 25, Southern Hem... FALSE   NULL [x]
# y       1 352 9120761 -28.5 UTM Zone 25, Southern Hem... FALSE   NULL [y]
# band    1   6      NA    NA                           NA    NA   NULL   
```

Despite a lot of research I can't figure out if the GeoTiff standard (such as there exists such a thing) supports a band containing a date format that R would be able to recognise. I'm happy to hear "this isn't possible" in which case for future readers of this issue, here are two solutions:

- store dates as characters

```r
tif = system.file("tif/L7_ETMs.tif", package = "stars")
x = read_stars(tif)
x = st_set_dimensions(x, 3, values = as.character(seq(as.Date("2021-01-01"), as.Date("2021-01-06"), "day")), name = "time")
write_stars(x, "x.tif")
x_read <- read_stars("x.tif")
st_set_dimensions(x_read, 3, values = as.Date(names(split(x_read, "band"))), name = "time")
```

- store meanings of bands in a readme or data file that's stored alongside the exported .tif file

**Comment by edzer** [comment]
Yes, good issue. I think GeoTIFFs can contain arbitray key=value strings, e.g.
```r
> gdal_metadata(system.file("tif/L7_ETMs.tif", package = "stars"))
[1] "AREA_OR_POINT=Area"
```
but I haven't come across a "standard" (or useful convention) that encodes dates for bands, or sets of bands. Also the GDAL 2.x interface used by stars can read bands, and write bands, and that's it - there's no model for time. So I see no point in `write_stars` doing anything with it (other than that it could read it back, and hope that the rest of the world follows).

For future work, to write multidimensional arrays two ways out would be:
* write NetCDF, either directly, or through RNetCDF or ncdf4, or
* build further on GDAL using its MDM interface https://gdal.org/user/multidim_raster_data_model.html

This latter part is now available in most distributions (requires GDAL >= 3.1). It will also write NetCDF, but might do more generally also HDF5 and HDF4. I'm not sure how feature complete this MDM interface is, or how robust it has been tested/used.
