### ISSUE TITLE
Request: add `coords` as an argument to `st_as_stars`

### ISSUE THREAD

**Issue by AndyBunn** [r-spatial/stars#398]
Would it be desirable to have `coords` as an argument to `st_as_stars` for the S3 method for class `data.frame`?  That would match `st_as_stars` to `st_as_sf` and make more sense (to me) than the `dims` argument. E.g., at the moment the coordinates are specified with `dims` for stars (and I don't think names are supported even though the help file says they are). Is there a good reason not to have  `coords` as an argument to make stars look and feel more like sf? Feel free to file this under "Prima Donna User Requests" if that's what it is.

```
data(meuse)
# make points into sf object
meuseSF <- st_as_sf(meuse, coords = c("x", "y")) %>%
  st_set_crs(value = 28992)
data(meuse.grid)
# make into stars object
meuse.gridST <- st_as_stars(meuse.grid, dims=1:2) %>%
  st_set_crs(value = 28992)
# doesn't work but should?
meuse.gridST <- st_as_stars(meuse.grid, dims=c("x","y")) %>%
  st_set_crs(value = 28992)

```

**Comment by edzer** [comment]
Great idea - that should all work, now.

**Comment by AndyBunn** [comment]
Thanks!
