### ISSUE TITLE
stars to Raster object

### ISSUE THREAD

**Issue by pramitghosh** [r-spatial/stars#40]
I was trying to convert a stars object `stars_obj` to a Raster object using `as()` and encountered the following error:
```
> stars_obj
stars object with 4 dimensions and 1 attribute
attribute(s):
     attr        
 Min.   : 238.0  
 1st Qu.: 621.0  
 Median :1009.0  
 Mean   : 887.3  
 3rd Qu.:1132.0  
 Max.   :3631.0  
dimension(s):
     from  to              offset   delta                       refsys point              values
x       1 300              699960      10 +proj=utm +zone=34 +south...    NA                NULL
y       1 300             7900000     -10 +proj=utm +zone=34 +south...    NA                NULL
band    1   2                  NA      NA                           NA    NA                   z
time    1   3 2017-05-01 08:16:11 10 days                           NA    NA 2017-05-11 08:20:11
> as(stars_obj, "Raster")
Error: length(dim(x)) %in% c(2, 3) is not TRUE
```
I believe it has something to do with [this line](https://github.com/r-spatial/stars/blob/3d101e3245a27300a9fdc65f68e204a6b1e2d2ff/R/raster.R#L29) here in `st_as_raster()`. I am not sure about its role but is that conditional really necessary? Thanks!

**Comment by adrfantini** [comment]
Reading the code it seems that `stars` only supports translating to 2D and 3D `raster` objects.

As far as I know `raster` does not have proper support for 4D data such as the one you are considering. Or better, if can work, but only by using one layer/band at a time. Am I mistaken?

**Comment by pramitghosh** [comment]
No, I think you are correct @adrfantini . It was rather stupid of me. It works fine with one band and time as below
```
> (t2 = stars_obj[,,,1,1, drop = TRUE])
stars object with 2 dimensions and 1 attribute
attribute(s):
     attr      
 Min.   : 951  
 1st Qu.:1032  
 Median :1057  
 Mean   :1063  
 3rd Qu.:1086  
 Max.   :1352  
dimension(s):
  from  to  offset delta                       refsys point values
x    1 300  699960    10 +proj=utm +zone=34 +south...    NA   NULL
y    1 300 7900000   -10 +proj=utm +zone=34 +south...    NA   NULL
> as(t2, "Raster")
class       : RasterLayer 
dimensions  : 300, 300, 90000  (nrow, ncol, ncell)
resolution  : 10, 10  (x, y)
extent      : 699960, 702960, 7897000, 7900000  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=utm +zone=34 +south +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0 
data source : in memory
names       : layer 
values      : 951, 1352  (min, max)
```
I am not sure though if it would be a useful feature to have `st_as_raster()` convert a stars object of arbitrary dimensions to a structured format such as a nested list (say) of Raster objects based on its (stars object's) dimensions.

**Comment by adrfantini** [comment]
You should be able to do that quite easily using some form of `apply` (but it will be slow for looping over many layers). Do you really need data to be stored in list of rasters? It does not look like the most convenient format to me.

**Comment by edzer** [comment]
It could of course flatten dimension 4 and higher into 3 before writing as Raster; maybe that should happen, along with a warning message?

**Comment by pramitghosh** [comment]
@adrfantini Yes, probably it isn't the best data structure for the job. But I haven't given it a thought yet and not thinking about it in general at this moment. However, I am always open to suggestions and ideas. My objective is to convert stars objects (currently containing multi-band, multi-temporal rasters) into a nested list of pixel values grouped by bands. So each "group" contains a nested list with 3 levels for time, x and y containing the raw pixel values of the image. This is later converted to a JSON. Currently, my strategy is converting the stars to Raster objects first and then extracting the x and y values for each in loops.

Dear @edzer, I'm sorry but I am not sure what you mean by flattening a stars object with >=4 dimensions into one with 3 dimensions before writing it as a Raster object.

**Comment by edzer** [comment]
By flattening I meant this: say you have x/y raster maps for (t1, t2) x (band1, band2), so four raster maps, then you'd choose some order, say (t1, band1), (t2, band1), (t1, band2), (t2, band2) to write the two (time, bands) dimensions to one having length four.

**Comment by pramitghosh** [comment]
@edzer Yes, I get the concept of flattening it to 3 dimensions now. If I understood it correctly, it's like having all possible combinations of the values in all dimensions >=3.

> It could of course flatten dimension 4 and higher into 3 before writing as Raster; maybe that should happen, along with a warning message?

Is it already implemented or do you mean that this is a feature that could be added?

**Comment by edzer** [comment]
That could be added, right now we get the error you saw above.

**Comment by pramitghosh** [comment]
Yes, I think that will be quite useful if added.

Will it be possible for the user to choose the order? So, for example, whether the user could do something like
```r
as(stars_obj, "Raster", order = c(3,4))
```
where the argument `order` would specify the order of the dimensions (of the stars object) which would be "looped" over. A reasonable convention, imo, would be to have the dimensions higher up in `order` run slower. So, if dimension 3 is bands and dimension 4 is time, and we have a stars object according to your example (with 2 time values and 2 bands each), then it could be flattened as:

(band1, t1), (band1, t2), (band2, t1), (band2, t2)

I think another aspect of adding this feature would be to decide on what data structure would the rasters being returned by `st_as_raster()` be in. Is a list of RasterBrick or RasterStack objects a good idea?

**Comment by edzer** [comment]
You can use `aperm` for to permute the stars array(s).

**Comment by edzer** [comment]
I think that
```r
st_apply(stars_obj, 1:2, c)
```
flattens your object into a 3-dimensional one.

**Comment by pramitghosh** [comment]
Yes, that's also true. The user could then change the order of the dimensions of the stars object using `aperm()` before passing it over to `st_as_raster()`.

Yes, running `st_apply()` in that way certainly works but the resulting stars object loses other important data such as the `from`, `to`, `offset`, `delta` etc. of the newly merged dimension as shown below:

```
> stars_obj
stars object with 4 dimensions and 1 attribute
attribute(s):
     attr        
 Min.   : 238.0  
 1st Qu.: 621.0  
 Median :1009.0  
 Mean   : 887.3  
 3rd Qu.:1132.0  
 Max.   :3631.0  
dimension(s):
     from  to              offset   delta                       refsys point              values
x       1 300              699960      10 +proj=utm +zone=34 +south...    NA                NULL
y       1 300             7900000     -10 +proj=utm +zone=34 +south...    NA                NULL
band    1   2                  NA      NA                           NA    NA                   z
time    1   3 2017-05-01 08:16:11 10 days                           NA    NA 2017-05-11 08:20:11
> st_apply(stars_obj, 1:2, c)
stars object with 3 dimensions and 1 attribute
attribute(s):
     attr        
 Min.   : 238.0  
 1st Qu.: 621.0  
 Median :1009.0  
 Mean   : 887.3  
 3rd Qu.:1132.0  
 Max.   :3631.0  
dimension(s):
  from  to  offset delta                       refsys point values
x    1 300  699960    10 +proj=utm +zone=34 +south...    NA   NULL
y    1 300 7900000   -10 +proj=utm +zone=34 +south...    NA   NULL
c    1   6      NA    NA                           NA    NA   NULL
```
Furthermore, neither will it make sense to have values for those since it is no longer a "true" dimension as such.
