### ISSUE TITLE
Downsample option in geom_stars() clashes with facet_wrap()

### ISSUE THREAD

**Issue by bjoernbos** [r-spatial/stars#401]
Many thanks for working on this great package!

I've came across an issue with the downsample option in `geom_stars()` together with the `facet_wrap()` function. I am trying to reduce the resolution of my data to plot multiple bands next to each other in a faster way. When using `downsample = 2 `, however, it only keeps `n/2` of the facets. Under `downsample = 3`  only `n/3`. Instead of a spatial downsampling, it does a downsampling of the bands.

```
# From the reference:
system.file("tif/L7_ETMs.tif", package = "stars") %>% read_stars() -> x
library(ggplot2)
ggplot() + geom_stars(data = x) +
    coord_equal() +
    facet_wrap(~band) +
    theme_void() +
    scale_x_discrete(expand=c(0,0))+
    scale_y_discrete(expand=c(0,0))
```
![Bildschirmfoto 2021-03-18 um 15 22 56](https://user-images.githubusercontent.com/32138245/111642049-09c0b800-87fe-11eb-8cd8-98c8dab98f52.png)

If I now want to reduce the resolution, it drops every 2nd facet:
```
ggplot() + geom_stars(data = x, downsample = 2) +
    coord_equal() +
    facet_wrap(~band) +
    theme_void() +
    scale_x_discrete(expand=c(0,0))+
    scale_y_discrete(expand=c(0,0))
```
![Bildschirmfoto 2021-03-18 um 15 23 05](https://user-images.githubusercontent.com/32138245/111641967-f0b80700-87fd-11eb-9e18-2ca5003db59d.png)

Without the facets, downsampling works as expected
```
ggplot() + geom_stars(data = x, downsample = 5) +
    coord_equal() +
    theme_void() +
    scale_x_discrete(expand=c(0,0))+
    scale_y_discrete(expand=c(0,0))
```
![Bildschirmfoto 2021-03-18 um 15 24 11](https://user-images.githubusercontent.com/32138245/111642031-03cad700-87fe-11eb-8bf6-a6af92981073.png)

**Comment by edzer** [comment]
please try `downsample = c(5, 5, 0)`, and yes, this should be documented somewhere more clearly!

**Comment by bjoernbos** [comment]
Great, that's it! Would be great to have this documented.
