### ISSUE TITLE
Trouble saving model output using stars proxy object

### ISSUE THREAD

**Issue by jmburgos** [r-spatial/stars#404]
This may be a bug, or just my lack of knowledge. I am doing PCA on some stars objects  that I read using the proxy=TRUE option.  The output of the predict() function is also a stars proxy object, which seems to be ok (for example it gets plotted with no problem), but when saving I get the following error:

```
Error in `st_dimensions<-.stars`(`*tmp*`, value = st_dimensions(ret[[1]])) : 
  length(x) && all(dim(x[[1]]) == dim(value)) is not TRUE
In addition: Warning message:
In dim(x[[1]]) == dim(value) :
  longer object length is not a multiple of shorter object length
```

The following code replicates my analysis and the error message:

```r
library(stars)
library(stringr)
library(tidyverse)
r <- system.file("tif/L7_ETMs.tif", package = "stars") %>%
  read_stars() %>%
  split()

write_stars(r[1], "r1.tif")
write_stars(r[2], "r2.tif")
write_stars(r[3], "r3.tif")
write_stars(r[4], "r4.tif")
write_stars(r[5], "r5.tif")
write_stars(r[5], "r6.tif")

files <- str_c("r", 1:6, ".tif")

sm <- sample(1:(349 * 352), 1000)

dt <- NULL
for (i in 1:6){
  st <- read_stars(files[i]) %>% set_names("z")
  dt <- cbind(dt, c(st$z[sm]))
}

dt <- as_tibble(dt, .name.repair = "minimal") %>%
  set_names(files)

pca <- prcomp(dt, scale = TRUE)

stack <- read_stars(files, proxy = TRUE)

pred <- predict(stack, pca) %>%
  merge()

write_stars (pred, "pca.tif")

```
I get no error If I try to save individual layers, for example by doing

`write_stars (pred, layer = "r1.tif", dsn = "pca1.tif")`

...but I was hoping to save the output as a multi layer tiff file.  Is this possible?

**Comment by edzer** [comment]
Thanks - great report - this should fix it, hopefully!

**Comment by jmburgos** [comment]
Yes, it works like a charm.  Thank you!
