### ISSUE TITLE
Printing stars objects returns only the dimensions

### ISSUE THREAD

**Issue by odeleongt** [r-spatial/stars#411]
I think the general expectation in R is that `identical(x, print(x))` is `TRUE`, so the current behavior of `print.stars` threw me off.

Turns out that the `print.stars` method returns the dimensions:

https://github.com/r-spatial/stars/blob/73e113a6d6a95f8e3c1d949cbe3c5dcd4ab00b39/R/stars.R#L383-L385

So wouldn't something like the following be more appropriate?

```R
    cat("dimension(s):\n") 
    print(st_dimensions(x), ...)
    invisible(x)
 } 
```

Besides stars objects, it also seems there are similar issues with:

-  `print.dimensions`, which returns `as.data.frame(x, ...)` instead of `x`:

https://github.com/r-spatial/stars/blob/73e113a6d6a95f8e3c1d949cbe3c5dcd4ab00b39/R/dimensions.R#L590-L592

- `print.stars_raster`, which always returns `NULL` (only `cat`s stuff)

- `pring.stars_proxy`, which returns the call list if there is one, otherwise it returns the dimensions.

https://github.com/r-spatial/stars/blob/c10c7af58826cebda9c1088cb65d02145fdaef63/R/proxy.R#L29-L35

So maybe there is a reason for this behavior that I'm missing?

**Comment by edzer** [comment]
I don't think there are that many people checking on this "general expectation". How did you find out?

**Comment by odeleongt** [comment]
I agree, I couldn't even think of a scenario where this would be an issue except in my use case (which really makes it just an inconvenience and not really a problem):

When reading in a raster, id usually do it like

```R
x <- print( stars::read_stars("sample.tif"))

# or the equivalent
x <- stars::read_stars("sample.tif") %>%
  print()
```

Such that I immediately see some information about the object. And a similar procedure when calculating a new object (usually ending a bunch of piped operations with `%>% print()`.

In both cases, this is solved by splitting the print statement after reading or calculating, but since both _look_ the same I was surprised when, after reading in a tif, it was not a `stars` object but a `dimensions` object. I haven't found this behavior anywhere else, which is why I thought of asking.

**Comment by edzer** [comment]
No, you're right of course. For combining print & assign, I usually do
```r
(x <- stars::read_stars("sample.tif"))
```
