### ISSUE TITLE
Different behavior regard what {raster} and {terra} do  to load multiple files

### ISSUE THREAD

**Issue by frzambra** [r-spatial/stars#414]
I'm trying to move part of my workflow to `{stars}`, so I'm doing a little comparison against `{terra}` and `{raster}`.

I've exported 19 years of MCD12Q1 MODIS dataset from GEE to my local as GeoTIFF. 

When I call
```r
library(raster)
files <- list.files(...)
modis <- stack(files)

library(terra)
modis <- rast(files)
```
that works fine, but then, when I tried with `{stars}` I get the following issue

```r
library(stars)
modis <- read_stars(files, along = 'time',  proxy = TRUE)

#Error in combine_dimensions(dots, along_dim) : 
# dimensions of element 1 and 19 are not identical
```
Well, diving into the problem I just figure out that in fact are not identical, there are minor differences in some dimensions.

```r
options(digits=15)
st_dimensions(modis1)$x$offset

#-8026892.81382816

st_dimensions(modis19)$x$offset
# -8026892.813838
```
I jumped the problem by copying the dimensions of the file 1 to 19 and save it as GeoTIFF, and then reread all with `stars_read(files)`. I believe that the issue has to do with the `Affine GeoTransform` parameters get with `gdal`. I don't know how {raster} and {terra} deal with it.

**Comment by edzer** [comment]
I think it would be good to use `all.equal` for such comparison, and allow setting `tolerance` in `read_stars`, to have that passed on for these comparisons.

**Comment by edzer** [comment]
This should now work e.g. with 
```r
library(stars)
modis <- read_stars(files, along = 'time',  proxy = TRUE, tolerance = 1e-3)
```

**Comment by frzambra** [comment]
I've installed the development version of `{stars}`

```
library(devtools)
install_github('https://github.com/r-spatial/stars')
library(stars)
modis <- read_stars(files, along = 'time',  proxy = TRUE, tolerance = 1e-3)

Error in combine_dimensions(dots, along_dim) : 
  dimensions of element 1 and 19 are not identical
```
Still, same error.

**Comment by edzer** [comment]
Maybe you can share element 1 and 19 with us, or me?

**Comment by frzambra** [comment]
modis1 -> https://storage.googleapis.com/modis_chile/MCD12Q1/MCD12Q1_2001001.tif
modis19 -> https://storage.googleapis.com/modis_chile/MCD12Q1/MCD12Q1_2019001.tif

Also, I do

```r
all.equal(st_dimensions(modis1),st_dimensions(modis19))
[1] TRUE
> identical(st_dimensions(modis1),st_dimensions(modis19))
[1] FALSE
```

**Comment by edzer** [comment]
Thanks! This should do it.
