### ISSUE TITLE
Stars rasters don't render on mapview (cross posted issue)

### ISSUE THREAD

**Issue by qdread** [r-spatial/stars#415]
I am having trouble getting a `stars` or `stars_proxy` class object to display in a `mapview` window. Please take a look at [the issue I opened on the mapview repo](https://github.com/r-spatial/mapview/issues/378). Thanks in advance!

**Comment by edzer** [comment]
Works for me with
```
other attached packages:
[1] mapview_2.9.8 raster_3.4-5  sp_1.4-5      stars_0.5-3   sf_1.0-0     
[6] abind_1.4-5  
```
Have you tried installing `mapview` from github?
