### ISSUE TITLE
[Feature Request] Support for sf to stars hypercube transitions

### ISSUE THREAD

**Issue by pinehowe** [r-spatial/stars#418]
I couldn't find any open issues similar to this and the documentation for hypercubes focuses on downloaded data.

Would it be possible to take a sf object with polygon geometries (in this case square, since they originally came from a raster) and turn it into a hypercube?

For example, lets say that I have an sf object with columns: year, elevation, temperature, slope, precipitation, and geometry. Under the current stars workflow, I would have to create separate stars layers for each year/column combination. Could there instead be a stars function to construct a hypercube from an sf object?

**Comment by edzer** [comment]
There could, but if the order of the records in the `sf` object is (assumed to be) unspecified, this is somewhat tricky.

**Comment by edzer** [comment]
There is an `st_as_stars` method for `sf` objects, but we'd need a small reprex to see if it does what you have in mind.
