### ISSUE TITLE
Provide a way for subsetting with polygons without cropping the bounding box

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/stars#42]
I have a particular task in which I subset several gridded files (identical in X-Y size) with different polygons, then write them back by going through `raster`. The issue is that after subsetting all the files have different extent, since by default subsetting crops the `stars` item to the polygon's bounding box.

Would it be possible to provide an option for subsetting (something like `stars[sf, crop = FALSE]`) which allows for the bounding box to be retained, but the external values set to NA?

**Comment by edzer** [comment]
Doesn't it already work like that?

**Comment by adrfantini** [comment]
Duh! Easiest fix ever: it was already in place, exactly like proposed!
Since I did not find it documented (is it, anywhere? Can't find it) I did not even bother to try, I guess I should have read the code.

**Comment by edzer** [comment]
Lack of documentation is an issue.

**Comment by adrfantini** [comment]
Searching the repo for `crop` shows it's in the news for version 0.1-0 but not much else. So yeah, this should be documented somewhere.

**Comment by edzer** [comment]
```r
?`[.stars`
```
