### ISSUE TITLE
Potential bug calling plot() on the output of st_crop()

### ISSUE THREAD

**Issue by qdread** [r-spatial/stars#423]
Sorry to keep opening issues. This may be a bug.

If I call `st_crop()` on a `stars` object and use `plot()` to plot the result with an `add.geom` on top, there appears to be a bug causing the raster and polygon layers to be offset. This does not occur if I use `ggplot()` to plot the result. The behavior only occurs with certain CRS. Here is a reproducible example that I have tested using the CRAN version of `stars` and `GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1`. 

[Dropbox link to download tif used in example, 2 MB](https://www.dropbox.com/s/any8a6njjq2tpkq/nlcd_agg.tif?dl=0)

```
library(stars)
library(ggplot2)

nlcd <- read_stars('nlcd_agg.tif')

# Get sf object to demonstrate
mdco <- USAboundaries::us_counties(resolution = 'low', state = 'MD') %>%
  st_transform(st_crs(nlcd))

# Plot uncropped, gives expected result.
plot(nlcd, add.geom = st_geometry(mdco))

# Crop stars object to bounding box of sf object
nlcdcrop <- st_crop(nlcd, st_bbox(mdco))

# Plot cropped, gives bad result.
plot(nlcdcrop, add.geom = st_geometry(mdco))

# Plot cropped with ggplot2, gives expected result.
ggplot() +
  geom_stars(data = nlcd) +
  geom_sf(data = st_geometry(mdco)) +
  theme(legend.position = 'none')
```

Uncropped plotted with `plot()` (no offset)

![image](https://user-images.githubusercontent.com/9200842/118066499-d5d0c180-b36c-11eb-8759-bdc55c9c71cd.png)

Cropped plotted with `plot()` (unexpected offset)

![image](https://user-images.githubusercontent.com/9200842/118066541-dff2c000-b36c-11eb-8d94-0662f28c8868.png)

Cropped plotted with `ggplot()` (no offset)

![image](https://user-images.githubusercontent.com/9200842/118066628-057fc980-b36d-11eb-8874-9b24d7aa695d.png)

**Comment by edzer** [comment]
Definitely a bug! What does work right now is
```r
plot(st_normalize(nlcdcrop), add.geom = st_geometry(mdco))
```
but this needs fixing obviously.

**Comment by edzer** [comment]
Should work now - thanks!
