### ISSUE TITLE
Potential bug: st_extract() factor variable does not treat factor levels correctly

### ISSUE THREAD

**Issue by qdread** [r-spatial/stars#425]
Yet another issue, sorry... (we are translating our old geospatial data science curriculum from `raster` to `stars` so I am going over a bunch of code with a fine-toothed comb, hence all the issues).

If you call `st_extract(r, pts)` where `r` is a `stars` object with `factor` values, and `pts` is an `sfc` points object, the factor levels do not seem to propagate correctly to the extracted point values.

Reproducible example

```
library(stars)

lc <- read_stars(system.file("tif/lc.tif", package = "stars"))

pt1 <- st_sfc(st_point(c(3200000, 0)),
              st_point(c(3250000, 1000)),
              st_point(c(3270000, 3000)),
              crs = st_crs(lc))

extract1 <- lc[pt1]

extract2 <- st_extract(lc, pt1) %>% st_as_sf()

as.character(extract2$lc.tif)
```

In this example, `extract1` contains 3 pixels with the correct values, but `as.character(extract2$lc.tif)` returns `c("", "", "")`.

Thanks again for your great work on this package!!! 🏅

**Comment by edzer** [comment]
Thanks for reporting, should work now.
