### ISSUE TITLE
st_contour on a raster datacube

### ISSUE THREAD

**Issue by danstrobridge-Weston** [r-spatial/stars#426]
I'm trying to figure out how I can extract contours (either plys or lines) from a raster datacube such that there's a set of contours for each layer in the stack and the name of the layer is stored in the attributes of the sf object.  I suspect that I could write some sort of function that uses st_contour and use purrr to loop it, but I didn't want to expend the effort if this feature exists natively (or might soon b/c it wouldn't take too much development effort).  The st_contour function creates output when I call it on raster datacube, but it seems only the first layer gets processed.

**Comment by edzer** [comment]
Sounds like a reasonable feature request!

**Comment by edzer** [comment]
On second thought: what you'd get out from contouring several bands is not a data cube, also not a vector data cube, since the new values have no reference to a common set of geometries, so that doesn't fit in a `stars` object. I'd convert the band dimension to a set of attributes using `split`, then loop over that object.

**Comment by edzer** [comment]
Here's an example with computing contours for all bands in the example data, The first `map()` creates a list of `stars` objects, each with a single attribute:
```r
library(stars)
library(tidyverse)
tif = system.file("tif/L7_ETMs.tif", package = "stars")           
x1 = read_stars(tif)  
l = split(x1)
l0 = l[,1:20,1:20] # reduce runtime
l0 %>%
  map(function(x) st_as_stars(x, dimensions = st_dimensions(l0))) %>%
  map(st_contour) %>%
  `[[`(6) %>% # pull out contours for band 6
  `[`(1) %>% # select first attribute
  plot(pal = sf.colors, key.width = lcm(4))
```
![x](https://user-images.githubusercontent.com/520851/118458852-6e639a80-b6fb-11eb-9a2e-9c498891ca8d.png)

**Comment by danstrobridge-Weston** [comment]
thanks so much for even considering my request and even more for providing working code that i can use to create a function in my homegrown package.  unfortunately, my company has committed pretty heavily to ESRI products and i'm trying to at least leverage Desktop's really handy data-driven-pages via a "stacked" shapefile of filled polygon contours so that I don't always have to use ESRI's raster catalog (equivalent of a raster::rasterstack/brick / stars raster datacube).  i do a lot of modeling work, but some folks simply don't appreciate the fact that models don't always turn out how you envision.  it's much easier to provide someone a shapefile and say "edit this if you don't like the model" than to hand them a raster catalog to work with.
