### ISSUE TITLE
cellsize argument in st_warp() should be passed to -tr option of gdalwarp

### ISSUE THREAD

**Issue by qdread** [r-spatial/stars#427]
I opened a PR for this a little while ago (#422 ) but maybe I did not go through the proper channels?

I noticed that in the documentation of `st_warp()`, the `cellsize` argument is documented as being the resolution of the output raster. But it is actually passed to the `-ts` option of `gdalwarp` [on this line](https://github.com/r-spatial/stars/blob/8b52416ba5618e8ddebdaa5da2ea417f9c2cc455/R/warp.R#L162). That's the "target size" or the dimensions of the output raster. I think that `cellsize` should be passed to the `-tr` option of `gdalwarp` instead (target resolution). So then `cellsize` would be the size of the cells in the output raster. 

I think this is fixable by changing a single character: `-ts` should be `-tr`.

**Comment by edzer** [comment]
merged now -- thanks!!
