### ISSUE TITLE
docs won't deploy

### ISSUE THREAD

**Issue by edzer** [r-spatial/stars#43]
@pat-s could you please take a look at https://travis-ci.org/r-spatial/stars/jobs/413579888 ? The deploy step gives an authentication error. To be sure, I just ran
```r
travis::use_tic()
```
on the rep (again?) - what am I overlooking?

**Comment by pat-s** [comment]
Hi Edzer,

for authentication you need to call `travis::use_travis_deploy()`.

FYI: We are about to streamline this process in the future and integrate all the `travis` and `tic` steps into a single command called from `usethis` called `use_ci`.

Should be ready end of summer.

**Comment by pat-s** [comment]
uhm, that's odd.
We've never faced any issues in this step.

Please check if there is an env variable called "id_rsa" in the repo settings on Travis. If you are on https://travis-ci.org/r-spatial/stars, there should be a a "settings" tab under "more options" on the far right.

**Comment by edzer** [comment]
Yes, the `id_rsa` thing is there.

**Comment by pat-s** [comment]
mh, the log is also not really telling me anything useful.

@krlmlr	Could you have a look here?

**Comment by pat-s** [comment]
Successful deployment in the last build: https://travis-ci.org/r-spatial/stars/jobs/420784477

Probably only a temporary issue then. Good news!

**Comment by edzer** [comment]
Yes, it is! No success here, yet: https://travis-ci.org/r-spatial/lwgeom/jobs/420784384

**Comment by pat-s** [comment]
This error is different, its caused by the `pkgdown::build_site()` call. Can you check if it works locally?

**Comment by edzer** [comment]
That worked - thank!

**Comment by pat-s** [comment]
Great! Deployment also worked.

**Comment by edzer** [comment]
Well, that was a short pleasure. Is tic development intentionally unstable, is this something we should come back to when the developers think this is for instance ready for CRAN? @tim-salabim .

**Comment by pat-s** [comment]
`tic` is about to hit CRAN in the next weeks. I've already fixed the issues for `mapview` and `stars`. PRs in some minutes.

I don't see another breaking change coming soon. Also it wouldn't be efficient to revert everything for some weeks only, including no deployment of the pkgdown docs. But in the ends its up to you of course :)

**Comment by krlmlr** [comment]
I'm aware of the problems, working on making _tic_ more reliable. I'm using it for my packages too.

**Comment by pat-s** [comment]
Ok, we're facing some issues currently and I don't wanna open PRs including hotfixes that have to be removed again after some days, e.g. for mapview: https://travis-ci.org/pat-s/mapview/jobs/422292590 (which is green).

Give us some days to get rid of the issues and then I'll update both repos. 
I am on vacation starting tomorrow but as soon as we've fixed the issues I'll try to incorporate everything ASAP - even during the vacation :)

**Comment by tim-salabim** [comment]
No worries, no rush, enjoy the holidays and start with a fresh mind when you're back!
