### ISSUE TITLE
Problem with read from a ESRI grid file

### ISSUE THREAD

**Issue by evanliu3594** [r-spatial/stars#435]
Hi there, I tried to crop and downscale from the [LandScan](https://landscan.ornl.gov/) gridded population data which was in the format of `.adf` using stars.

Code:
```
library(tidyverse)
library(stars)

domain <- st_bbox(c(xmin=70, xmax = 140, ymin = 0, ymax = 60), crs=4326)

domainGrid <- st_make_grid(st_as_sfc(domain), cellsize = .1, crs = 4326)

lspop_domain <- read_stars('./temp/lspop2019/w001001.adf', proxy = T)[domain]

lspop_domain_downscale <- aggregate(lspop_domain,st_geometry(domainGrid),sum,na.rm = T)

```

and encountered with error.
```
Error in as.character.factor(X, ...) : malformed factor
Besides: Warning message:
In read_stars(file_name, RasterIO = rasterio, NA_value = attr(x,  :
  categorical data values starting at 0 are shifted with one to start at 1
```

I also tried `st_warp()`:
```
st_warp(lspop_domain,domainGrid %>% st_as_stars(),sum,na.rm=T)
```

but still not work.
```
Error in matrix(seq_len(prod(dims[dxy])), dims[dxy[1]], dims[dxy[2]])[xy]
Subscript out of bounds
Besides: Warning message:
In read_stars(file_name, RasterIO = rasterio, NA_value = attr(x,  :
  categorical data values starting at 0 are shifted with one to start at 1

```

Then I find out that the stars_proxy object won't be able to transform into sf object.

```
> lspop_domain %>% st_as_sf()
#Error in as.character.factor(X, ...) : malformed factor
#Besides: Warning message:
#In read_stars(file_name, RasterIO = rasterio, NA_value = attr(x,  :
#  categorical data values starting at 0 are shifted with one to start at 1
```

I was confused because it's all fine using `raster()` to read it. Is there anything wrong with my code? or how to read properly the `.adf` file in `stars`?

Thanks!

The `temp` dir (which contains the landscan 2019) can be accessed at 
https://1drv.ms/u/s!AnKDtoVUNyeqiNA3O9eD8anX6flu4Q?e=xeEcZZ

**Comment by edzer** [comment]
What do these data represent? It looks like they contain counts, but then the file has a raster attribute table that only seems to carry the frequencies. Is it meant to represent a categorical variable, or a (discrete) continuous one?

**Comment by evanliu3594** [comment]
Sorry for the ambiguity, the LandScan Population Dataset presents a 2-D annual population estimate at a 30"*30" resolution. Under this view, the presented data is meant to be a discrete variable.

**Comment by edzer** [comment]
Related to https://github.com/rspatial/terra/issues/234 ?

**Comment by edzer** [comment]
Chose the same solution as `terra` did: ignore attribute tables with frequencies from funny smelling ESRI grids.
