### ISSUE TITLE
Error while reading file: time unit not recognized

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/stars#44]
I am trying to open [this](https://drive.google.com/open?id=1cOEpTaZi0YeH5njoC_xrne5XDoLAed6d) 700KB netcdf file using `stars`, but I get the following error:
```
read_stars("chym-intdb-fil_masked_reg1_22_01.nc")   
Error in as.POSIXct.numeric(pr$dim_extra[[v]]) : 
  'origin' must be supplied
In addition: Warning message:
ignoring unrecognized unit: day as %Y%m%d.%f
```
The reason is that the time in the file is specified in this weird format: 
```
        double time(time) ;
                time:standard_name = "time" ;
                time:units = "day as %Y%m%d.%f" ;
                time:calendar = "proleptic_gregorian" ;
                time:axis = "T"
```

Maybe Stars should:
a) (maybe) be able to read such format (this is one for the `units` package) and/or
b) be robust to this kind of problems, with a flag to ignore errors and return NA values for the problematic variables, so that one can fix the problem by issuing `st_set_dimensions` afterwards

**Comment by edzer** [comment]
I think CF prescribes that units should be udunits2 compatible, in which case R package units (and hence stars) reads them. I'm not crazy on expanding on that. But the warning message suggests we try this and continue in case of failure. The problem is that we have a time variable that we can't properly convert to time. What does `.%f` mean? Does your file contain data from before the year 1582?

**Comment by adrfantini** [comment]
You are right, this time is not CF-compliant. Stars should not refuse to read it entirely however, but allow (with a flag maybe?) the user to set the units afterwards.

Notice that unfortunately it's not always that easy: udunits2 does not cover exactly all of the CF.  Think for example of 360-day calendars, which are supported by the CF but not by udunits2: even if the time units are recognized, the calendar will be out. The udunits documentation itself  suggests NOT to use udunits2 for reading time:

> You should use a true calendar package rather than the UDUNITS-2 package to handle time. Having said that, many people use the time-handling capabilities of the UDUNITS-2 package because it supports "units" like "seconds since 1970-01-01". You should be aware, however, that the hybrid Gregorian/Julian calendar used by the UDUNITS-2 package cannot be changed. Dates on or after 1582-10-15 are assumed to be Gregorian dates; dates before that are assumed to be Julian dates. In particular, the year 1 BCE is immediately followed by the year 1 CE.

I'm not sure however what the alternatives are tho.

In this case, I suspect %f stands for the minutes, maybe in fraction of an hour... who knows? It's only one timestep and the value is 20000115 (double). This file is actually the output of a `writeRaster` call; I do not know why Raster uses this format.

**Comment by edzer** [comment]
This should fix it. Yes, I agree with the 360 day years, but R doesn't have a framework for this, so I'm afraid one would have to make one, in order to obtain some interoperability with usual time.

**Comment by adrfantini** [comment]
Yeah the only thing I know of is https://cran.r-project.org/web/packages/PCICt/index.html
