### ISSUE TITLE
How to calculate rotation of each cell with regards to N-S axis

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/stars#441]
Hi!
I need to rotate some 2D X-Y wind data from a data source on an LCC grid.
For each grid cell, I have the X-Y coordinates of the wind, relative to the orientation of the cell.

However, to find the wind vector angle relative to the Earth (e.g. N-S axis), I need to know how much each cell is "rotated".
Is there any simple way to calculate this for each cell in the raster?

For example, say my data is this:
```R
tif = system.file("tif/L7_ETMs.tif", package = "stars")
x1 = read_stars(tif)[,,,1]
```

I'm thinking of a workflow like
1. transform to polygon (`st_xy2sfc`)
2. `st_transform` to 4326
3. Extract the polygons (`st_geometry`)
4. For each ~square (or rectangle), extract corner coordinates and calculate the (average) rotation relative to a N-S axis.
5. Bring this data back to `stars` in some way

Is there any less convoluted way to calculate this?

**Comment by edzer** [comment]
You get a raster with `x` and `y` coordinate values as grid cells with
```r
l1 = st_as_stars(L7_ETMs)[,,,1] %>% st_dim_to_attr() %>% select(1:2) %>% adrop()
```
maybe you can work it out from there?

**Comment by edzer** [comment]
And welcome back!

**Comment by adrfantini** [comment]
Hi @edzer , long time no hear!
Well keeping with this one could do:
`st_as_stars(L7_ETMs)[,,,1] %>% adrop() %>% st_transform(4326) %>% st_dim_to_attr()`

which gives the 4326 lat-lon coordinates for each point. From there then one I guess could calculate the bearing (e.g. with `geosphere:::bearing`) from one cell to the next one, and use that as rotation value?

Rotating wind values is a common enough task that I'm surprised I can't find much documentation on it at all.

**Comment by edzer** [comment]
Yes. You need to install this patch to get the right values, though...

**Comment by adrfantini** [comment]
I was not able to work on this lately, sorry for the delay. For now I'll close, I'll post again if I come around to writing a script to do this. Thanks again Edzer!
