### ISSUE TITLE
info about `read_ncdf()` in vignette outdated

### ISSUE THREAD

**Issue by konradmayer** [r-spatial/stars#447]
According to NEWS.md, parsing of time data is implemented since version 0.3-1.
Therefore (and because the example in the vignette obviously reads in `time` correctly), I think the following sentence is outdated:
https://github.com/r-spatial/stars/blob/1c6f3d902c7abc2f167dd831b0e6c4fe0fd13472/vignettes/stars1.Rmd#L188

It would be helpful if more information about the differences between `read_stars()` and `read_ncdf()` can be found at this section.

Thanks for your great work!

**Comment by edzer** [comment]
Thanks!
