### ISSUE TITLE
segfault with st_extract with stars_proxy object

### ISSUE THREAD

**Issue by ateucher** [r-spatial/stars#459]
When I run `st_extract()` with a `stars_proxy` object, it segfaults:

```r
library(stars)
library(sf)

tif = system.file("tif/L7_ETMs.tif", package = "stars")
r = read_stars(tif, proxy = TRUE)
pnt = st_sample(st_as_sfc(st_bbox(r)), 10)
st_extract(r, pnt)

 *** caught segfault ***
address 0x44, cause 'memory not mapped'

Traceback:
 1: CPL_extract(f, pts, as.logical(bilinear))
 2: FUN(X[[i]], ...)
 3: lapply(y, gdal_extract, pts = st_coordinates(at), bilinear = bilinear)
 4: do.call(abind, lapply(y, gdal_extract, pts = st_coordinates(at),     bilinear = bilinear))
 5: FUN(X[[i]], ...)
 6: lapply(x, function(y) do.call(abind, lapply(y, gdal_extract,     pts = st_coordinates(at), bilinear = bilinear)))
 7: st_extract.stars(r, pnt)
 8: st_extract(r, pnt)
```

Session info and spatial stack info: (`sf` and `stars` both installed as binaries)

``` r
library(stars)
#> Loading required package: abind
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.2.1, PROJ 7.2.1
library(sf)

sf::sf_extSoftVersion()
#>           GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
#>        "3.8.1"        "3.2.1"        "7.2.1"         "true"         "true" 
#>           PROJ 
#>        "7.2.1"

sessionInfo()
#> R version 4.1.1 (2021-08-10)
#> Platform: x86_64-apple-darwin17.0 (64-bit)
#> Running under: macOS Big Sur 10.16
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRblas.0.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] stars_0.5-3 sf_1.0-2    abind_1.4-5
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.7         pillar_1.6.2       compiler_4.1.1     highr_0.9         
#>  [5] class_7.3-19       R.methodsS3_1.8.1  R.utils_2.10.1     tools_4.1.1       
#>  [9] digest_0.6.28      evaluate_0.14      lifecycle_1.0.1    tibble_3.1.4      
#> [13] R.cache_0.15.0     pkgconfig_2.0.3    rlang_0.4.11       reprex_2.0.1      
#> [17] DBI_1.1.1          parallel_4.1.1     yaml_2.2.1         xfun_0.26         
#> [21] fastmap_1.1.0      e1071_1.7-9        dplyr_1.0.7        withr_2.4.2       
#> [25] styler_1.6.2       stringr_1.4.0      knitr_1.34         generics_0.1.0    
#> [29] fs_1.5.0           vctrs_0.3.8        tidyselect_1.1.1   grid_4.1.1        
#> [33] classInt_0.4-3     glue_1.4.2         R6_2.5.1           fansi_0.5.0       
#> [37] rmarkdown_2.11     purrr_0.3.4        magrittr_2.0.1     units_0.7-2       
#> [41] backports_1.2.1    ellipsis_0.3.2     htmltools_0.5.2    assertthat_0.2.1  
#> [45] KernSmooth_2.23-20 utf8_1.2.2         stringi_1.7.4      proxy_0.4-26      
#> [49] lwgeom_0.2-7       crayon_1.4.1       R.oo_1.24.0
```

<sup>Created on 2021-10-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by edzer** [comment]
Strange, no problems here; have you tried reinstalling sf, and using stars from github?

**Comment by stevenpawley** [comment]
I've been encountering the same issue on MacOS (Intel) and can reproduce the crash using the posted example. Unfortunately, it isn't that easy to install sf and stars from GitHub on MacOS.

Curiously, this doesn't affect st_extract on stars_proxy objects on a newer m1 mac using sf/stars from CRAN. 

R version 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.0.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.1.2 tools_4.1.2

**Comment by edzer** [comment]
> Unfortunately, it isn't that easy to install sf and stars from GitHub on MacOS.

I know (for sf), a new CRAN version is in the pipeline, let's see whether it helps.

**Comment by ateucher** [comment]
Unfortunately it's still happening for me, with github versions of both sf and stars (built against latest GDAL/GEOS/PROJ from homebrew):

```r
library(stars)
library(sf)

devtools::session_info()

sf::sf_extSoftVersion()

tif = system.file("tif/L7_ETMs.tif", package = "stars")
r = read_stars(tif, proxy = TRUE)
pnt = st_sample(st_as_sfc(st_bbox(r)), 10)
st_extract(r, pnt)
```

```
Loading required package: abind
Loading required package: sf
Linking to GEOS 3.10.1, GDAL 3.3.3, PROJ 8.2.0
─ Session info  🖕🏾  🛂  🍸   ────────────────────────────────────────────────────────────────────────────────────────────────────────────
 hash: middle finger: medium-dark skin tone, passport control, cocktail glass

 setting  value
 version  R version 4.1.1 (2021-08-10)
 os       macOS Big Sur 11.6.1
 system   x86_64, darwin17.0
 ui       X11
 language (EN)
 collate  en_CA.UTF-8
 ctype    en_CA.UTF-8
 tz       America/Vancouver
 date     2021-11-15
 pandoc   2.16.1 @ /usr/local/bin/pandoc

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version date (UTC) lib source
 abind       * 1.4-5   2016-07-21 [1] CRAN (R 4.1.0)
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.1.0)
 cachem        1.0.6   2021-08-19 [1] CRAN (R 4.1.0)
 callr         3.7.0   2021-04-20 [1] CRAN (R 4.1.0)
 class         7.3-19  2021-05-03 [2] CRAN (R 4.1.1)
 classInt      0.4-3   2020-04-07 [1] CRAN (R 4.1.0)
 cli           3.1.0   2021-10-27 [1] CRAN (R 4.1.0)
 crayon        1.4.2   2021-10-29 [1] CRAN (R 4.1.0)
 DBI           1.1.1   2021-01-15 [1] CRAN (R 4.1.0)
 desc          1.4.0   2021-09-28 [1] CRAN (R 4.1.0)
 devtools      2.4.2   2021-06-07 [1] CRAN (R 4.1.0)
 dplyr         1.0.7   2021-06-18 [1] CRAN (R 4.1.0)
 e1071         1.7-9   2021-09-16 [1] CRAN (R 4.1.1)
 ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.1.0)
 fansi         0.5.0   2021-05-25 [1] CRAN (R 4.1.0)
 fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.1.0)
 fs            1.5.0   2020-07-31 [1] CRAN (R 4.1.0)
 generics      0.1.1   2021-10-25 [1] CRAN (R 4.1.1)
 glue          1.5.0   2021-11-07 [1] CRAN (R 4.1.0)
 KernSmooth    2.23-20 2021-05-03 [2] CRAN (R 4.1.1)
 lifecycle     1.0.1   2021-09-24 [1] CRAN (R 4.1.1)
 lwgeom        0.2-8   2021-10-06 [1] CRAN (R 4.1.1)
 magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.1.0)
 memoise       2.0.0   2021-01-26 [1] CRAN (R 4.1.0)
 pillar        1.6.4   2021-10-18 [1] CRAN (R 4.1.1)
 pkgbuild      1.2.0   2020-12-15 [1] CRAN (R 4.1.0)
 pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.1.0)
 pkgload       1.2.3   2021-10-13 [1] CRAN (R 4.1.0)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.1.0)
 processx      3.5.2   2021-04-30 [1] CRAN (R 4.1.0)
 proxy         0.4-26  2021-06-07 [1] CRAN (R 4.1.0)
 ps            1.6.0   2021-02-28 [1] CRAN (R 4.1.0)
 purrr         0.3.4   2020-04-17 [1] CRAN (R 4.1.0)
 R6            2.5.1   2021-08-19 [1] CRAN (R 4.1.0)
 Rcpp          1.0.7   2021-07-07 [1] CRAN (R 4.1.0)
 remotes       2.4.1   2021-09-29 [1] CRAN (R 4.1.0)
 rlang         0.4.12  2021-10-18 [1] CRAN (R 4.1.0)
 rprojroot     2.0.2   2020-11-15 [1] CRAN (R 4.1.0)
 sessioninfo   1.2.1   2021-11-02 [1] CRAN (R 4.1.0)
 sf          * 1.0-5   2021-11-15 [1] Github (r-spatial/sf@649ae10)
 stars       * 0.5-4   2021-11-15 [1] Github (r-spatial/stars@2018665)
 testthat      3.1.0   2021-10-04 [1] CRAN (R 4.1.1)
 tibble        3.1.6   2021-11-07 [1] CRAN (R 4.1.1)
 tidyselect    1.1.1   2021-04-30 [1] CRAN (R 4.1.0)
 units         0.7-2   2021-06-08 [1] CRAN (R 4.1.0)
 usethis       2.1.3   2021-10-27 [1] CRAN (R 4.1.0)
 utf8          1.2.2   2021-07-24 [1] CRAN (R 4.1.0)
 vctrs         0.3.8   2021-04-29 [1] CRAN (R 4.1.0)
 withr         2.4.2   2021-04-18 [1] CRAN (R 4.1.0)

 [1] /Users/ateucher/Rlibrary
 [2] /Library/Frameworks/R.framework/Versions/4.1/Resources/library

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H           PROJ
      "3.10.1"        "3.3.3"        "8.2.0"         "true"         "true"        "8.2.0"

 *** caught segfault ***
address 0x0, cause 'unknown'

Traceback:
 1: CPL_read_gdal(as.character(x), as.character(options), as.character(driver),     as.logical(read_data), as.double(NA_value), RasterIO_parameters)
 2: sf::gdal_read(get_names(x), options = options, driver = driver,     read_data = !proxy, NA_value = NA_value, RasterIO_parameters = as.list(RasterIO))
 3: read_stars(tif, proxy = TRUE)
```

**Comment by ateucher** [comment]
Hmmm actually that one is segfaulting at `read_stars()`...

**Comment by edzer** [comment]
Nasty! Any chance you can run this inside an  `R -d valgrind` session? I will build a docker images with exactly those GEOS/GDAL/PROJ versions to see if I can reproduce this on linux.

**Comment by ateucher** [comment]
I'll see - it looks like it's difficult to get valgrind on recent versions of macOS, but I'll give it a try.

**Comment by edzer** [comment]
https://github.com/r-spatial/sf/commit/5ec8751b366246ed84fee3ebad7899bc3eb8bd47 runs cleanly suggesting it's a platform specific problem.

**Comment by ateucher** [comment]
Darn, ok. I'll try to get valgrind working and investigate here, but it will be a bit of time before I can get to it.

**Comment by edzer** [comment]
I'm seeing similar breaks here: https://github.com/r-spatial/stars/runs/4227739553?check_suite_focus=true but of course no ability to debug there. This run builds sf from source, using brew installs; in a few days I guess CRAN binaries will appear for all macos platforms, not requiring a source build of sf as it is now, and we can retry GA to see if they do the same thing.

**Comment by edzer** [comment]
And a few hours later: https://github.com/r-spatial/stars/runs/4233760569?check_suite_focus=true we see that with a binary sf from CRAN (which appeared in the mean time) the previous errors disappear, and errors appear in terra which now is compiled from sources in GA against brew libraries. This suggests to me the problem might be in the brew libraries...

**Comment by ateucher** [comment]
Are the Mac binaries for sf and stars compiled with brew libraries? I assume not... but interesting because the first time I found this I was using binary installs of both...

**Comment by edzer** [comment]
> Are the Mac binaries for sf and stars compiled with brew libraries? I assume not...

no. (It's only relevant for `sf` because that contains all the compiled code stars uses)

**Comment by edzer** [comment]
Current GA: https://github.com/r-spatial/stars/runs/4263626435?check_suite_focus=true gives pointers to a CPL_extract()  segfault!

**Comment by ateucher** [comment]
So after many `Rprintf()`'s I think I've fixed this here: https://github.com/r-spatial/sf/pull/1849. However when I check locally I am reproducing the error I mentioned earlier in `CPL_read_gdal()`. That one looks like:

```
> tif = system.file("tif/L7_ETMs.tif", package = "stars")
> (x = read_stars(tif))

 *** caught bus error ***
address 0x7fc3e7529a00, cause 'non-existent physical address'

Traceback:
 1: CPL_read_gdal(as.character(x), as.character(options), as.character(driver),     as.logical(read_data), as.double(NA_value), RasterIO_parameters)
 2: sf::gdal_read(get_names(x), options = options, driver = driver,     read_data = !proxy, NA_value = NA_value, RasterIO_parameters = as.list(RasterIO))
 3: read_stars(x, ..., sub = sub, proxy = TRUE, quiet = TRUE)
 4: is_big(.x, sub = sub, driver = driver, normalize_path = normalize_path,     ...)
 5: CPL_read_gdal(as.character(x), as.character(options), as.character(driver),     as.logical(read_data), as.double(NA_value), RasterIO_parameters)
 6: sf::gdal_read(get_names(x), options = options, driver = driver,     read_data = !proxy, NA_value = NA_value, RasterIO_parameters = as.list(RasterIO))
 7: read_stars(tif)
An irrecoverable exception occurred. R is aborting now ...
```

**Comment by edzer** [comment]
Does that read error also happen when you install the CRAN binary package?

**Comment by ateucher** [comment]
No, the read is fine, just the `CPL_extract()`...

**Comment by edzer** [comment]
Ah! So we can either sent the fix above to CRAN and wait for the binary there, or give `CPL_read_gdal()` the same treatment as you did in the fix - save function calls to a variable before using them in a function call.

**Comment by ateucher** [comment]
Maybe? I'm struggling to figure out how to reliably reproduce the read error, and it seems to change depending on the order in which I install sf and stars - which I know shouldn't affect things since stars only uses compiled code from sf, right? I feel like I'm losing my mind. At the very least I am less than confident I that fix!

**Comment by edzer** [comment]
So this is the GA output after merging the extract PR in sf, and installing sf from github: https://github.com/r-spatial/stars/runs/4290119481?check_suite_focus=true - note that the CPL_read_gdal error was gone in the last few builds, and now resurfaces. Pretty random!!

**Comment by ateucher** [comment]
Yeah that looks just like what I'm getting, glad that I'm not completely crazy. So do you think it's something wrong with how homebrew has compiled `gdal`? Or more like the Mac compiler compiling `sf`?

**Comment by edzer** [comment]
I'm too unfamiliar with macos & brew to say sth sensible. Have you tried macos binaries from https://r-spatial.r-universe.dev/ ?

**Comment by ateucher** [comment]
I forgot about the r-universe macos binaries. I just tried, and it works fine. What I don't know if the r-universe binary worked before. I note that they are not compiled with homebrew libraries, rather from [here](https://github.com/autobrew/bundler), which seems to be a fork of homebrew but I don't know how they differ.

**Comment by edzer** [comment]
Interesting! @jeroen do you know anything about issues with brew libraries for GDAL? We're seeing seg faults on GA, like here: https://github.com/r-spatial/stars/runs/4295059733?check_suite_focus=true#step:18:32 that won't reproduce on other platforms.

**Comment by ateucher** [comment]
I have done a bit more debugging of the read segfault, and the error seems to be generated at this line: https://github.com/r-spatial/sf/blob/2d326ccd5acc45927f96a7646aeb6683b6a54c39/src/stars.cpp#L327.

When I build the package I also get these warnings:

```
ld: warning: dylib (/usr/local/lib/libproj.dylib) was built for newer macOS version (11.0) than being linked (10.13)
ld: warning: dylib (/usr/local/lib/libtiff.dylib) was built for newer macOS version (11.0) than being linked (10.13)
ld: warning: dylib (/usr/local/lib/libgdal.dylib) was built for newer macOS version (11.0) than being linked (10.13)
ld: warning: dylib (/usr/local/lib/libgeos_c.dylib) was built for newer macOS version (11.0) than being linked (10.13)
```

**Comment by edzer** [comment]
Andy, is this still an issue?

**Comment by ateucher** [comment]
It seems fine now actually - the reprex runs successfully with CRAN binaries and built from source with latest homebrew libraries.

**Comment by edzer** [comment]
Thanks for checking!
