### ISSUE TITLE
as.data.frame error

### ISSUE THREAD

**Issue by mtennekes** [r-spatial/stars#460]
I have the following stars object:

```r
stars object with 3 dimensions and 1 attribute
attribute(s):
                                           Min. 1st Qu. Median     Mean 3rd Qu.   Max.
Total_precipitation_surface_1_... [kg/m^2]    0       0   0.75 4.143009    4.63 163.75
dimension(s):
     from  to                  offset   delta  refsys point values x/y
x       1  87                       1       1      NA    NA   NULL [x]
y       1 118                       1       1      NA    NA   NULL [y]
time    1  23 2018-09-13 19:00:00 UTC 1 hours POSIXct    NA   NULL    
curvilinear grid
```

It is contained in this file: [stars_to_df_error.zip](https://github.com/r-spatial/stars/files/7281287/stars_to_df_error.zip)

When I convert it to a `data.frame`:

```r
library(stars)
x = readRDS("stars_to_df_error.rds")
as.data.frame(x)
```

I get `Error in names(object) <- nm :   'names' attribute [2] must be the same length as the vector [0]`

**Comment by edzer** [comment]
There is something terribly wrong with that object. How did you create it?

**Comment by mtennekes** [comment]
I used `st_set_dimensions` to replace the `x` and `y` values by id numbers. My aim is to split the data (store this in a data.table) from the spatial features (in this case a curvilinear raster).

Is it a technically a valid stars object? If not is there any internal function that checks this and reports back if something is not right? The error message is not helpful for me as a user.

**Comment by edzer** [comment]
curvilinear grids need to have a matrix with coordinates in the `values` field of the corresponding dimension.

**Comment by edzer** [comment]
So, this essentially means there's a bug in `st_set_dimensions()`...

**Comment by mtennekes** [comment]
I see. So in my case, it could do a `attr(attr(x, "dimensions"), "raster")$curvilinear = FALSE` afterwards.
