### ISSUE TITLE
Load byte datatype as integer

### ISSUE THREAD

**Issue by kadyb** [r-spatial/stars#461]
I wonder if it would be possible to load byte datatype as integer by default to save memory?

```r
library("stars")

tif = system.file("tif/L7_ETMs.tif", package = "stars")
ras = split(read_stars(tif))
df = as.data.frame(ras)[, -c(1:2)]
mdl = kmeans(df, centers = 3)
ras$cluster = mdl$cluster
tmp = tempfile(fileext = ".tif")
write_stars(ras["cluster"], tmp, type = "Byte")

clus = read_stars(tmp)
typeof(clus[[1]])
#> [1] "double"
```

**Comment by edzer** [comment]
Well, "would be possible", yes of course, but "will be implemented" questionable, unless you want, or you know someone who wants, to do the implementation.

This is actually a deliberate design decision: int / double is only a factor 2, and that difference will only be decisive for a small set of problems of moderate size. My guess is that the implementation effort would be considerable. Also, the next request would be support for INT2, UINT2, CHAR, UCHAR, FLOAT, BIGINT and LONGDOUBLE.

**Comment by kadyb** [comment]
Thanks, right. After loading the data, the user can still specify the datatype himself and it will eventually reduce memory too.

```r
clus = read_stars(tmp)
clus[[1]] = as.integer(clus[[1]])
```
