### ISSUE TITLE
Request: export is_curvilinear() and co.

### ISSUE THREAD

**Issue by Jean-Romain** [r-spatial/stars#464]
Hi,

Many useful internal tools are... internal but very useful for developers. At least to be able to exit easily when some stars models are not supported. So far I found
 
- `stars:::is_curvilinear()`
- `stars:::is_rectilinear()`
- `stars:::is_regular_grid()`
- `stars:::has_rotate_or_shear()`

So far wrote the following tests to exit with the 'special' cases using https://r-spatial.github.io/stars/articles/stars4.html

```r
sdim   <- stars::st_dimensions(x)
stattr <- attr(stars::st_dimensions(x), "raster")

if (sdim$y$delta > 0) stop("stars objects with delta > 0 are not supported yet", call. = FALSE)
if (!all(stattr$affine == 0)) stop("Rotated and sheared stars objects are not supported yet", call. = FALSE)
if (stattr$curvilinear == TRUE) stop("Curvilinear stars objects are not supported yet", call. = FALSE)
```

**Comment by edzer** [comment]
See `?st_raster_type`
