### ISSUE TITLE
How to combine a list of stars objects?

### ISSUE THREAD

**Issue by Aariq** [r-spatial/stars#468]
If I have a list of stars objecs, say from `test <- purrr::map(files, ~read_ncdf(.x))`, how do I go about combining them?  Each of `files` is a .nc file containing a time dimension and a different climate variable.  `c(test[[1]], test[[2]])` works, but `c(test)` does not.

**Comment by edzer** [comment]
then, maybe, `do.call(c, test)` ?

**Comment by Aariq** [comment]
Thanks! That works.
