### ISSUE TITLE
Feature request: could `geom_stars` have a `band` argument?

### ISSUE THREAD

**Issue by davidhodge931** [r-spatial/stars#469]
It might be useful if  geom_stars had a band argument, so that you could do this:

```
system.file("tif/L7_ETMs.tif", package = "stars") %>% read_stars() -> x
library(ggplot2)
ggplot() + 
geom_stars(data = x, band = 3) +
    coord_equal() 
```

**Comment by edzer** [comment]
I'm not sure this can be done the way `geom_stars()` currently works; if that was possible, it would also already have made `coord_equal()` obsolete. But you are aware of `+ facet_wrap(~band)`, right?

**Comment by davidhodge931** [comment]
Yes, I was thinking that this might be useful, if you want to quickly visualise one particular band.

I noticed this argument was in `leafem::addStarsImage`.

I suppose you could do this though instead, but just less easy for user:

```
library(ggplot2)
library(stars)

system.file("tif/L7_ETMs.tif", package = "stars") %>% read_stars() -> x

y <- x %>% 
  filter(band == 3) 

ggplot() +
  geom_stars(data = y) +
  coord_equal() 
```

**Comment by edzer** [comment]
Ah, now I see, you want to show the third band, not point out that the third dimension should be faceted. Yes, I think this belongs to `select`, or `[`.
