### ISSUE TITLE
Function format improvements for documentation?

### ISSUE THREAD

**Issue by Aariq** [r-spatial/stars#474]
I'm very new to geospatial analysis and completely new to `stars` as well, so this is a complete beginner's perspective.

In many of the help files, functions usage shows up like:

```
read_stars(
  .x,
  ...,
  options = character(0),
  driver = character(0),
  sub = TRUE,
  quiet = FALSE,
  NA_value = NA_real_,
  along = NA_integer_,
  RasterIO = list(),
  proxy = is_functions(.x) || (!length(curvilinear) && is_big(.x, sub = sub, driver =
    driver, normalize_path = normalize_path, ...)),
  curvilinear = character(0),
  normalize_path = TRUE,
  RAT = character(0),
  tolerance = 1e-10
)

```

Where the default values for arguments are sometimes complicated functions (like for `proxy`), or empty strings or lists.  This is pretty atypical, especially compared to packages in the `tidyverse`, which `stars` aims to work well with. 

For `proxy`, I would suggest having the default be `NULL`, but also accepting `TRUE` or `FALSE`, and in the details describing what the default (`NULL`) behavior is. You'd have to move the logical statement currently the default for `proxy` into the body of the function, wrapped in an `if(is.null(proxy)) {}` and have some checks that the user supplied argument is logical.

I don't really understand what `driver` does, but I assume there are a limited set of options.  Something like `driver = c("defaultdriver", "alternativedriver", "driver3")` with a call to `match.arg()` in the function body would be preferable. This would help a beginner like me figure out what the options are with code autocomplete in RStudio, and by looking at the help file.

**Comment by edzer** [comment]
> This is pretty atypical, especially compared to packages in the tidyverse, which stars aims to work well with.

Working well doesn't imply it follows the same style. This way, at least you can see the defaults. I agree there's room for improving the documentation; feel free to contribute!
