### ISSUE TITLE
st_bbox fails with SpatRaster without CRS

### ISSUE THREAD

**Issue by Jean-Romain** [r-spatial/stars#478]
This is somewhat related to https://github.com/r-spatial/stars/issues/454. `stars` redefines `st_bbox()` for `SpatRaster` but with an additional bug because it does not support `SpatRaster` without CRS. Two reprex below

With `sf` it works as expected
``` r
library(terra)
#> terra version 1.4.11
library(sf)
#> Linking to GEOS 3.9.1, GDAL 3.3.2, PROJ 7.2.1
e <- ext(-500,500,-500,500)
r <- rast(e)
st_bbox(r)
#> xmin ymin xmax ymax 
#> -500 -500  500  500
```

<sup>Created on 2021-11-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

With `stars` it fails because the CRS is `""`. In addition it prints annoying messages about overwritten methods. It does it only once per session but in a `bookdown` or vignettes this pops out one for each chapter or vignette when calling `stars::something()` from other code. 

``` r
library(terra)
#> terra version 1.4.11
library(stars)
#> Le chargement a nécessité le package : abind
#> Le chargement a nécessité le package : sf
#> Linking to GEOS 3.9.1, GDAL 3.3.2, PROJ 7.2.1
#> Registered S3 methods overwritten by 'stars':
#>   method             from
#>   st_bbox.SpatRaster sf  
#>   st_crs.SpatRaster  sf
e <- ext(-500,500,-500,500)
r <- rast(e)
st_bbox(r)
#> Error in st_crs.character(terra::crs(x)): invalid crs:
```

<sup>Created on 2021-11-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by edzer** [comment]
This has been solved in the development version, on github, which will hopefully soon be on CRAN.

**Comment by Jean-Romain** [comment]
Thank. Sorry I searched on the open and close issues but found nothing.
