### ISSUE TITLE
Use case documentation for st_redimension? 

### ISSUE THREAD

**Issue by dblodgett-usgs** [r-spatial/stars#495]
In working through nc_proxy, I'm not seeing much documentation or example of what `st_redimension` is for. 

I get what it does structurally, but am not quite sure what the implications are regarding a proxy object. It seems like adding dimensions to a `stars` object that hasn't been fetched yet is a little risky in that you have to have special knowledge of the data that really ought to be handled by the code that fetches things?

This is leading me to think that support for `st_redimension` for `nc_proxy` is maybe not wise... but maybe there's a use case that I'm missing? I would guess that the existing method for `stars_proxy` will work, so maybe just leave it as is and make sure that the existing method returns the class its given and move on... but figured I'd put in an issue to raise the question and maybe add some documentation of the use case.

**Comment by edzer** [comment]
yes, this should be clarified by examples; there is a `redimension.R` file in `tests` though:
```r
suppressPackageStartupMessages(library(stars))
tif = system.file("tif/L7_ETMs.tif", package = "stars")
r = read_stars(list(a = c(tif,tif), b = c(tif, tif)), proxy = TRUE)
(xx = st_redimension(r, along = list(foo = 1:4)))
# stars_proxy object with 1 attribute in 4 file(s):
# $a.L7_ETMs.tif.a.L7_ETMs.tif.b.L7_ETMs.tif.b.L7_ETMs.tif
# [1] "[...]/L7_ETMs.tif" "[...]/L7_ETMs.tif" "[...]/L7_ETMs.tif"
# [4] "[...]/L7_ETMs.tif"

# dimension(s):
#      from  to  offset delta                     refsys point values x/y
# x       1 349  288776  28.5 SIRGAS 2000 / UTM zone 25S FALSE   NULL [x]
# y       1 352 9120761 -28.5 SIRGAS 2000 / UTM zone 25S FALSE   NULL [y]
# band    1   6      NA    NA                         NA    NA   NULL    
# foo     1   4       1     1                         NA    NA   NULL    
(rr = c(xx, xx))
# stars_proxy object with 2 attributes in 8 file(s):
# $a.L7_ETMs.tif.a.L7_ETMs.tif.b.L7_ETMs.tif.b.L7_ETMs.tif
# [1] "[...]/L7_ETMs.tif" "[...]/L7_ETMs.tif" "[...]/L7_ETMs.tif"
# [4] "[...]/L7_ETMs.tif"

# $a.L7_ETMs.tif.a.L7_ETMs.tif.b.L7_ETMs.tif.b.L7_ETMs.tif
# [1] "[...]/L7_ETMs.tif" "[...]/L7_ETMs.tif" "[...]/L7_ETMs.tif"
# [4] "[...]/L7_ETMs.tif"

# dimension(s):
#      from  to  offset delta                     refsys point values x/y
# x       1 349  288776  28.5 SIRGAS 2000 / UTM zone 25S FALSE   NULL [x]
# y       1 352 9120761 -28.5 SIRGAS 2000 / UTM zone 25S FALSE   NULL [y]
# band    1   6      NA    NA                         NA    NA   NULL    
# foo     1   4       1     1                         NA    NA   NULL    
st_as_stars(rr)
# stars object with 4 dimensions and 2 attributes
# attribute(s), summary of first 1e+05 cells:
#                                    Min. 1st Qu. Median    Mean 3rd Qu. Max.
# a.L7_ETMs.tif.a.L7_ETMs.tif.b....    47      65     76 77.3419      87  255
# a.L7_ETMs.tif.a.L7_ETMs.tif.b....    47      65     76 77.3419      87  255
# dimension(s):
#      from  to  offset delta                     refsys point values x/y
# x       1 349  288776  28.5 SIRGAS 2000 / UTM zone 25S FALSE   NULL [x]
# y       1 352 9120761 -28.5 SIRGAS 2000 / UTM zone 25S FALSE   NULL [y]
# band    1   6      NA    NA                         NA    NA   NULL    
# foo     1   4       1     1                         NA    NA   NULL    
(rrr = st_redimension(rr, along = list(bar = as.Date(c("2001-01-01", "2002-01-01")))))
# stars_proxy object with 1 attribute in 8 file(s):
# $a.L7_ETMs.tif.a.L7_ETMs.tif.b.L7_ETMs.tif.b.L7_ETMs.tif.a.L7_ETMs.tif.a.L7_ETMs.tif.b.L7_ETMs.tif.b.L7_ETMs.tif
# [1] "[...]/L7_ETMs.tif" "[...]/L7_ETMs.tif" "[...]/L7_ETMs.tif"
# [4] "[...]/L7_ETMs.tif" "[...]/L7_ETMs.tif" "[...]/L7_ETMs.tif"
# [7] "[...]/L7_ETMs.tif" "[...]/L7_ETMs.tif"

# dimension(s):
#      from  to     offset    delta                     refsys point values x/y
# x       1 349     288776     28.5 SIRGAS 2000 / UTM zone 25S FALSE   NULL [x]
# y       1 352    9120761    -28.5 SIRGAS 2000 / UTM zone 25S FALSE   NULL [y]
# band    1   6         NA       NA                         NA    NA   NULL    
# foo     1   4          1        1                         NA    NA   NULL    
# bar     1   2 2001-01-01 365 days                       Date    NA   NULL    
```
Since `netCDF` is already an array, I'm not sure how much need (or use) there would be to redimension these things, it is more obvious for GDAL datasets which are raster stacks (max 3 dims) per file, for handling large sets of those. Maybe you'd need this if netCDF files are cut up in one file per time period?

**Comment by dblodgett-usgs** [comment]
Alright -- I see. So if a NetCDF file had 12 variables, one for each month of a year... Yes, I've seen this and could see wanting to "fix" it in this way.

The more main-stream use case is probably where you have one or a few timesteps per FILE and need to concatenate them together after reading in a collection of `nc_proxy` objects. Given that, I'll look at this when I get to the next phase of #493 where I deal with multiple files/end points that need to be assembled into one. `st_redimension` might be the ticket there.

**Comment by edzer** [comment]
That particular case - reading a time sequence of netCDF files over multiple files through GDAL - is already handled by `read_stars` (for both settings of `proxy), see https://r-spatial.github.io/stars/articles/stars1.html#reading-datasets-from-multiple-files
