### ISSUE TITLE
stars_proxy subsetting example?

### ISSUE THREAD

**Issue by dblodgett-usgs** [r-spatial/stars#496]
I am working on "[" and st_crop methods for nc_proxy and am struggling to understand some of what's going on in the stars_proxy "[" method.

I'm not following this code. It seems like this only ever works when the fourth input to "[" but that input needs to be an expression of some kind??

The fourth input to "[" is used here: https://github.com/r-spatial/stars/blob/main/R/proxy.R#L457

And passed to this get_range function. https://github.com/r-spatial/stars/blob/main/R/proxy.R#L436

Do you have any example of the expression that would be passed in to "[" ? 

If I do the below, I just get the X,Y,Z,T subset in a call list:
``` r
library(stars)
#> Loading required package: abind
#> Loading required package: sf
#> Linking to GEOS 3.9.1, GDAL 3.2.1, PROJ 7.2.1; sf_use_s2() is TRUE

f <- system.file("nc/reduced.nc", package = "stars")

(nc <- stars::read_stars(f, proxy = TRUE))

#> stars_proxy object with 4 attributes in 4 file(s):
#> $sst
#> [1] "[...]/reduced.nc:sst"
#> 
#> $anom
#> [1] "[...]/reduced.nc:anom"
#> 
#> $err
#> [1] "[...]/reduced.nc:err"
#> 
#> $ice
#> [1] "[...]/reduced.nc:ice"
#> 
#> dimension(s):
#>      from  to         offset delta  refsys point values x/y
#> x       1 180             -1     2      NA    NA   NULL [x]
#> y       1  90             90    -2      NA    NA   NULL [y]
#> zlev    1   1          0 [m]    NA      NA    NA   NULL    
#> time    1   1 1981-12-31 UTC    NA POSIXct    NA   NULL

nc[, 20:30, 30:40, 1, 1]
#> stars_proxy object with 4 attributes in 4 file(s):
#> $sst
#> [1] "[...]/reduced.nc:sst"
#> 
#> $anom
#> [1] "[...]/reduced.nc:anom"
#> 
#> $err
#> [1] "[...]/reduced.nc:err"
#> 
#> $ice
#> [1] "[...]/reduced.nc:ice"
#> 
#> dimension(s):
#>      from to         offset delta  refsys point values x/y
#> x      20 30             -1     2      NA    NA   NULL [x]
#> y      30 40             90    -2      NA    NA   NULL [y]
#> zlev    1  1          0 [m]    NA      NA    NA   NULL    
#> time    1  1 1981-12-31 UTC    NA POSIXct    NA   NULL    
#> call_list:
#> [[1]]
#> x[i = i, 1, drop = drop, crop = crop]
#> attr(,".Environment")
#> <environment: 0x00000000230049a0>
```

<sup>Created on 2022-01-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by edzer** [comment]
Good catch!! Both
```r
nc[, 20:30, 30:40, 1]
```
and
```r
nc[, 20:30, 30:40]
```
result in
```r
stars_proxy object with 4 attributes in 4 file(s):
$sst
[1] "[...]/reduced.nc:sst"

$anom
[1] "[...]/reduced.nc:anom"

$err
[1] "[...]/reduced.nc:err"

$ice
[1] "[...]/reduced.nc:ice"

dimension(s):
     from to         offset delta  refsys point values x/y
x      20 30             -1     2      NA    NA   NULL [x]
y      30 40             90    -2      NA    NA   NULL [y]
zlev    1  1          0 [m]    NA      NA    NA   NULL    
time    1  1 1981-12-31 UTC    NA POSIXct    NA   NULL    
```
that is, without a `call_list`. I guess that is what the `FIXME:` on line 457 indicates: the fourth argument is not taken correctly (that `call_list` doesn't look good...)

So the current implementation does that wrong, but it doesn't look complicated to process all arguments this way, using a`while` loop eating up `lst` rather than the `for(ix in 1:3)`. Will try.

**Comment by edzer** [comment]
This should now work; note this is in a branch called ` dblodgett-usgs-main`

**Comment by dblodgett-usgs** [comment]
OK -- this makes sense now. I'll include this in #493, I have it in my local master branch now... feel free to merge it in here though as I don't think I'm actually going to use the "[.stars_proxy" method.
