### ISSUE TITLE
get_dimension_values still needed?

### ISSUE THREAD

**Issue by dblodgett-usgs** [r-spatial/stars#498]
In working on the nc_proxy stuff, I am seeing this get_dimension_values function and a couple methods for something of class "dimension" -- are these still needed? seems like they could be dropped...

**Comment by edzer** [comment]
There are two methods, 
```r
> methods(class = "dimension")
[1] [   seq
```
both seem to be used...

**Comment by dblodgett-usgs** [comment]
Oh -- I see now. Sorry for the confusion.
