### ISSUE TITLE
SQL Support

### ISSUE THREAD

**Issue by latot** [r-spatial/stars#500]
Hi hi, I would like to know how is the SQL support with stars.

Particularly, we know for SQL there is PostGIS, an extension for PostgreSQL for spatial data, but for spatiotemporal data like stars is other thing, when we move data to a SQL Server, one objective is, to the server execute all the queries and operations.

The only thing I found was:
https://github.com/locationtech/geomesa

Maybe there is no support from stars, in that case, I would like to propose it.

Thx.

**Comment by edzer** [comment]
Maybe you want to look into array databases, there are several of them; `stars` is about an R interface to arrays, not an SQL interface.

**Comment by latot** [comment]
I was thinking like sf and dplyr have SQL support, or I'm confuse about something?.

**Comment by edzer** [comment]
I don't think that the languages for querying array databases are standardized the way they are for relational databases.

**Comment by edzer** [comment]
Please reopen this if you (or someone) can get more specific about which type of array SQL, database backend, and functionality one would like to support.
