### ISSUE TITLE
Cannot access coerce methods (from stars object)

### ISSUE THREAD

**Issue by tcwilkinson** [r-spatial/stars#504]
I'm currently confused about how to access the coerce methods used to convert stars objects to (e.g.) `raster` objects. (Would like to use a package that relies on raster objects for hillshading).

The in-package documentation regarding coerce methods is listed under `as` (https://r-spatial.github.io/stars/reference/coerce-methods.html) but does not provide any examples of how to use, so I've tried the following to no avail:

```
> r <- stars::as(stobj,"Raster")
Error: 'as' is not an exported object from 'namespace:stars'
```

```
> r <- as.raster(stobj,"Raster")
Error in UseMethod("as.raster") : 
  no applicable method for 'as.raster' applied to an object of class "stars"
```

```
> r <- stars::st_as_raster(stobj,"Raster")
Error: 'st_as_raster' is not an exported object from 'namespace:stars'
```
(This I understand as it is an internal function, not exposed; but how do we get to it?)

The internal code looks like it should be possible to coerce from stars to raster, but I just don't seem to be able to get there!

If it's relevant, I note that when compiling latest version via `devtools::github_install`, the following warning appears:

```
...
** byte-compile and prepare package for lazy loading
in method for ‘coerce’ with signature ‘"stars","Raster"’: no definition for class “Raster”
in method for ‘coerce’ with signature ‘"stars_proxy","Raster"’: no definition for class “Raster”
in method for ‘coerce’ with signature ‘"stars","SpatRaster"’: no definition for class “SpatRaster”
in method for ‘coerce’ with signature ‘"stars_proxy","SpatRaster"’: no definition for class “SpatRaster”
in method for ‘coerce’ with signature ‘"stars","Spatial"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"stars","STFDF"’: no definition for class “STFDF”
** help
...
```

Any help gratefully received!

**Comment by edzer** [comment]
Do you have an objection against loading packages before using their functions?

**Comment by tcwilkinson** [comment]
> Do you have an objection against loading packages before using their functions and methods?

No policy on that, no. Am I missing something obvious?

**Comment by edzer** [comment]
Have you tried this?
```r
library(stars)
r <- as(stobj,"Raster")
```

**Comment by tcwilkinson** [comment]
> Have you tried this?
> 
> ```r
> library(stars)
> r <- as(stobj,"Raster")
> ```

OK. It was almost as obvious as that... I had loaded stars with library() but apparently I forgot (or lost via a restart of R) `library(raster)`.   Still can't coerce as I have apparently a curvilinear grid, but at least I can try to solve that separately. Thanks for help!
