### ISSUE TITLE
st_rasterize produces small pixels for some datasets but not others

### ISSUE THREAD

**Issue by geotheory** [r-spatial/stars#509]
Some input datasets produce small pixels i.e. not properly tiled while others render as intended. 

```
require(tmap)
require(dplyr)
require(stars)

set.seed(54)

d54 = data.frame(lon = rnorm(1e5, mean = -95.5, sd=4),
               lat = rnorm(1e5, mean = 37.5, sd=4)) |> 
  group_by(lat = round(lat), lon = round(lon)) |> 
  summarise(n = length(lat), .groups = 'drop') |> 
  st_as_sf(coords = c('lon','lat'), crs = 'WGS84') |>
  st_rasterize()

plot(d54)
```

![image](https://user-images.githubusercontent.com/1282581/152676305-fb4e01dc-26c5-44f8-aba5-69317dbae8ec.png)

```
set.seed(42)

d42 = data.frame(lon = rnorm(1e5, mean = -95.5, sd=4),
               lat = rnorm(1e5, mean = 37.5, sd=4)) |> 
  group_by(lat = round(lat), lon = round(lon)) |> 
  summarise(n = length(lat), .groups = 'drop') |> 
  st_as_sf(coords = c('lon','lat'), crs = 'WGS84') |>
  st_rasterize()

plot(d42)
```

![image](https://user-images.githubusercontent.com/1282581/152676333-f5e61a67-b4fb-474c-bb3f-1fc55f7f642b.png)

Scanning through a few seeds (you can test with [this Shiny app script](https://gist.github.com/geotheory/0db55679de75cb784686296a777638a0)) suggests about half produce the bug.

**Comment by geotheory** [comment]
A [template workaround](https://github.com/r-tmap/tmap/issues/625#issuecomment-1030801623) has been identified which might help ID the cause.

**Comment by edzer** [comment]
Thanks! Yes, this was caused by empty rows / columns in the raster, which is rather common for data produced this way.

**Comment by geotheory** [comment]
Thanks for clarifying. Are you considering this a bug or a behaviour for users to be aware of?

**Comment by edzer** [comment]
Well, it's just fixed, and I added a line to the NEWS file. Finding a raster structure from data not perfectly on a raster is tricky, and can easily become a rabbit hole. I think this will not be the last improvement possible, and at some stage needed, to that section of code.

**Comment by geotheory** [comment]
Not sure this is totally resolved yet..

```
require(tmap)
require(dplyr)
require(ggplot2)

d = readr::read_csv('https://gist.githubusercontent.com/curran/13d30e855d48cdd6f22acdf0afe27286/raw/0635f14817ec634833bb904a47594cc2f5f9dbf8/worldcities_clean.csv') |> 
  group_by(lat = 5*round(lat/5), lng = 5*round(lng/5)) |> 
  summarise(n = length(lat), .groups = 'drop')

d |> ggplot(aes(lng, lat, fill = n)) + geom_tile() + 
  coord_quickmap() + scale_fill_continuous(low = 'white', high = 'red')

p = d |> 
  sf::st_as_sf(coords = c('lng', 'lat'), crs = 'WGS84') |> 
  stars::st_rasterize()

plot(p)
```

![image](https://user-images.githubusercontent.com/1282581/152708348-8f3daefa-36f6-48a6-89f7-0863ca7e8e65.png)

```
tmap_mode("view")

tm_basemap("Stamen.TonerLite") +
  tm_shape(p) +
  tm_raster("n", palette = c('white','red'), alpha=0.5)
```

<img width="751" alt="image" src="https://user-images.githubusercontent.com/1282581/152708366-648215f5-f287-41e5-9740-34f422ae566d.png">

**Comment by geotheory** [comment]
I appreciate the challenge here is nontrivial when projections are considered. Is it possible to rasterize prior to projection?

**Comment by geotheory** [comment]
I appreciate the challenge here is nontrivial when projections are considered. Is it possible to rasterize prior to projection?

**Comment by geotheory** [comment]
If we can create the raster in the raster package (which I know stars shares quite a few authors with) is there a method to generate a valid stars raster that does not suffer from this bug?

**Comment by edzer** [comment]
As I said, the next edge case will come up soon; this now also works (directly) with `stars`.

The map from `tmap` is not empty, but seems to be plotted in the opposite region next to the dateline. A problem might be that
```r
> st_bbox(p)
  xmin   ymin   xmax   ymax 
-172.5  -57.5  182.5   72.5 
```
crosses the dateline, but (WRONGLY) resetting it hard e.g. by
```r
attr(p, "dimensions")$x$offset = -177.5
```
so that there's no antimeridian crossing
```r
> st_bbox(p)
  xmin   ymin   xmax   ymax 
-177.5  -57.5  177.5   72.5 
```
still doesn't seem to give the right `tmap` plot in `"view"` mode (the plot looks reasonable in `"plot"` mode).

**Comment by mtennekes** [comment]
Probably a leaflet thing, because mapview also doens't work well: `mapview::mapview(p)`

@tim-salabim

**Comment by tim-salabim** [comment]
Not sure about it being a leaflet issue, because `leafem::addGeotiff` seems to work:

```r
tmpfl = tempfile(fileext = ".tif")

stars::write_stars(p, tmpfl)

leaflet::leaflet() %>%
  leaflet::addTiles() %>%
  leafem::addGeotiff(
    tmpfl
  )
```
even though there are weird glitches when zooming...
