### ISSUE TITLE
st_warp() with curvilinear grid

### ISSUE THREAD

**Issue by philament** [r-spatial/stars#513]
I am trying to resample a curvilinear grid (i.e. a raster with irregular pixel geometry) to a regular grid. I figured stars::st_warp() might be the right approach, but when I do this I get an error message. Here is a simplified example (not the data I am working with but same error):

```
library(stars)
s5p = system.file("sentinel5p/S5P_NRTI_L2__NO2____20180717T120113_20180717T120613_03932_01_010002_20180717T125231.nc", package = "starsdata")
nit.c = read_stars(s5p, sub = "//PRODUCT/SUPPORT_DATA/DETAILED_RESULTS/nitrogendioxide_summed_total_column",
                   curvilinear = c("//PRODUCT/longitude", "//PRODUCT/latitude"), driver = NULL)
test = st_warp(nit.c, crs = 4326, cellsize = 0.25)
```

This results in 

`Error in colrow_from_xy(pts, x, NA_outside = TRUE) : colrow_from_xy not supported for curvilinear objects`

The same happens when I supply an explicit destination grid to st_warp().

So my questions are:
1) Does st_warp() really not support curvilinear grids or is this a bug?
2) If using st_warp() is not feasible for this use case, does anybody know how to accomplish gridding of curvilinear rasters efficiently? I guess as a workaround I could convert the raster to sf and then use st_interpolate_aw() to do the resampling but doing all this in vector space is likely prohibitively inefficient/slow for large files. Are there any better/right ways to do this?

**Comment by edzer** [comment]
Yes, good point; this should now "work":
```r
library(stars)
# Loading required package: abind
# Loading required package: sf
# Linking to GEOS 3.10.1, GDAL 3.4.0, PROJ 8.2.0; sf_use_s2() is TRUE
s5p = system.file("sentinel5p/S5P_NRTI_L2__NO2____20180717T120113_20180717T120613_03932_01_010002_20180717T125231.nc", package = "starsdata")
nit.c = read_stars(s5p, sub = "//PRODUCT/SUPPORT_DATA/DETAILED_RESULTS/nitrogendioxide_summed_total_column",
                   curvilinear = c("//PRODUCT/longitude", "//PRODUCT/latitude"), driver = NULL)
# /PRODUCT/longitude, 
# /PRODUCT/latitude, 
# /PRODUCT/SUPPORT_DATA/DETAILED_RESULTS/nitrogendioxide_summed_total_column, 
# There were 15 warnings (use warnings() to see them)
test = st_warp(nit.c, crs = 4326, cellsize = 0.25)
# Warning message:
# In transform_grid_grid(st_as_stars(src), st_dimensions(dest), threshold) :
#   using Euclidean distance measures on geodetic coordinates
plot(test)
```
![cg](https://user-images.githubusercontent.com/520851/156807259-873533b2-31f5-4958-a580-bf486891d7c6.png)

**Comment by philament** [comment]
Very nice, thanks! This appears to work now for my use case, except that nearest neighbor resampling is not ideal for this (leaves gaps when regridding to e.g. 0.1 deg) but bilinear/bicubic options are only available through  `use_gdal = TRUE`, which fails for me:

`test = st_warp(nit.c, crs = 4326, cellsize = 0.1, use_gdal = TRUE, method = 'bilinear', no_data_value = -999)`
results in 
`Error in if (dx[i] < dd[i]) { : missing value where TRUE/FALSE needed`

**Comment by edzer** [comment]
I admit that this needs work on the error handling, but this will never work (AFAICT) with `use_gdal=TRUE`, as GDAL doesn't support curvilinear grids, nor their warping. Also, the bilinear/bicubic only works with non-curvilinear grids. One thing that would be relatively easy to implement is instead of using the 1-NN (now), use the k-NN (4 to resemble bilnear) and interpolate from those, e.g. with IDW. Not exactly bilinear (in particular along the borders) but might be "good enough".

**Comment by philament** [comment]
Oh ok, I didn't know that GDAL does not support curvilinear grids. Anyway, I am already super happy that regridding of curvilinear grids works now and 1-NN might actually be sufficient for my use case (have to check over the next days) . Thanks!

**Comment by edzer** [comment]
>  I didn't know that GDAL does not support curvilinear grids.

Maybe it does, I just don't know how. This [SO post](https://gis.stackexchange.com/questions/390148/handle-curvilinear-rotated-grid-netcdf-file-in-r) and references therein might bring more solutions.

**Comment by edzer** [comment]
Found some great clues here: https://gdal.org/development/rfc/rfc4_geolocate.html

**Comment by edzer** [comment]
This gives a better error
```r
test = st_warp(nit.c, crs = 4326, cellsize = 0.1, use_gdal = TRUE, method = 'bilinear', no_data_value = -999)
# Error in st_warp(nit.c, crs = 4326, cellsize = 0.1, use_gdal = TRUE, method = "bilinear",  : 
#   use gdal_utils("warp",...) directly on the source dataset of this object
# Execution halted
```
and also reads curvilinear grids automatically, e.g. as
```r
library(stars)
# Loading required package: abind
# Loading required package: sf
# Linking to GEOS 3.10.1, GDAL 3.4.0, PROJ 8.2.0; sf_use_s2() is TRUE
s5p = system.file("sentinel5p/S5P_NRTI_L2__NO2____20180717T120113_20180717T120613_03932_01_010002_20180717T125231.nc", package = "starsdata")
(nit = gdal_subdatasets(s5p)[[6]])
# [1] "NETCDF:\"/home/edzer/R/x86_64-pc-linux-gnu-library/4.0/starsdata/sentinel5p/S5P_NRTI_L2__NO2____20180717T120113_20180717T120613_03932_01_010002_20180717T125231.nc\":/PRODUCT/nitrogendioxide_tropospheric_column"
(nit.c = read_stars(nit))
# stars object with 3 dimensions and 1 attribute
# attribute(s):
#                                                      Min.      1st Qu.
# nitrogendioxide_tropospheric_c... [mol/m^2] -3.301083e-05 1.868205e-05
#                                                   Median         Mean
# nitrogendioxide_tropospheric_c... [mol/m^2] 2.622178e-05 2.898976e-05
#                                                  3rd Qu.         Max. NA's
# nitrogendioxide_tropospheric_c... [mol/m^2] 3.629641e-05 0.0003924858  330
# dimension(s):
#      from  to         offset delta  refsys point
# x       1 450             NA    NA  WGS 84    NA
# y       1 278             NA    NA  WGS 84    NA
# time    1   1 2018-07-17 UTC    NA POSIXct    NA
#                                      values x/y
# x    [450x278] -5.81066 [°],...,30.9468 [°] [x]
# y     [450x278] 28.3605 [°],...,51.4686 [°] [y]
# time                                   NULL    
# curvilinear grid
```

**Comment by plthompson** [comment]
I'm having a related issue. I was getting this same error using the CRAN version of stars. I updated to the current github version and now I am getting the following error:

Error in matrix(seq_len(prod(dims[dxy])), dims[dxy[1]], dims[dxy[2]])[xy] : 
  subscript out of bounds

**Comment by edzer** [comment]
@plthompson could you provide a reprex?

**Comment by plthompson** [comment]
Thanks @edzer. Here is some code that produces the error on my machine.  I wasn't able to attach my .nc files so I have included code to download them from the Salish Seacast website - https://salishsea.eos.ubc.ca/erddap

Thanks so much for your help.

Patrick

```
library(stars)

# read in lat, long and bathymetry####
bathyurl <- "https://salishsea.eos.ubc.ca/erddap/griddap/ubcSSnBathymetryV17-02.nc?bathymetry[(0.0):1:(897.0)][(0.0):1:(397.0)],latitude[(0.0):1:(897.0)][(0.0):1:(397.0)],longitude[(0.0):1:(897.0)][(0.0):1:(397.0)]"
download.file(url=bathyurl, destfile="SS_bathy.nc", method="wininet", mode = "wb")
bathy <- read_stars(.x = "SS_bathy.nc")

x <- matrix(bathy[[3]], 398, 898)
y <- matrix(bathy[[2]], 398, 898)

bathy <- st_as_stars(bathy[1], curvilinear = list(x = x, y = y), crs = "EPSG:4326")

# read in salinity and temperature ####
i <- 2013
furl <- paste("https://salishsea.eos.ubc.ca/erddap/griddap/ubcSSg3DTracerFields1moV19-05.nc?salinity[(",i,"-05-16):1:(", i, "-09-16T12:00:00Z)][(0.5000003):1:(0.5000003)][(0.0):1:(897.0)][(0.0):1:(397.0)],temperature[(", i,"-05-16):1:(", i,"-09-16T12:00:00Z)][(0.5000003):1:(0.5000003)][(0.0):1:(897.0)][(0.0):1:(397.0)]", sep = "")
download.file(url = furl, destfile = paste("temp_salinity_surface_", i,".nc", sep = ""), method = "wininet", mode = "wb")

temp1 <- read_stars(.x = "temp_salinity_surface_2013.nc")
temp2 <- st_as_stars(temp1, curvilinear = list(x = x, y = y), crs = "EPSG:4326")
temp3 <- st_transform(temp2, crs = "EPSG:3005")
temp4 <- stars::st_warp(temp3, method = "near", crs = "EPSG:3005", no_data_value = NA, use_gdal = FALSE)

```

**Comment by plthompson** [comment]
After trying a few more things it looks like the issue is that I have multiple time slices. Is there a way to warp a spatiotemporal stars object? I have searched the documentation and can't find any reference for how to do it. 

I'm not sure if I am going about this the best way possible. In short, I have point locations that I need to extract the data from a netcdf files. Because the data is on a curvilinear grid I can't extract from it without warping. If I need to warp each time slice at a time, then I lose the benefit of working with stars. Thanks for any advice you can provide.

**Comment by Rapsodia86** [comment]
Hello,
I am exploring Sentinel 3 L2 LST (spatial res 1km) data which come in separate *.nc files.
I have followed the tutorial (https://cran.r-project.org/web/packages/stars/vignettes/stars4.html) and those steps: (https://github.com/r-spatial/stars/issues/54#issuecomment-422325910)
to have them displayed. That is ok. 
But I am getting trouble with warping to have them at the end exported to tif.  See the examples later in the post. 
Does anyone have any experience with those data? I am well aware of SNAP software, but I would like to avoid it as much as possible. Here is an example of processing this data using vrt in gdal (https://github.com/jgomezdans/s3_olci/blob/master/s3_olci/s3_pre_processor.py) that gives me data in tiff format (spat res: 0.009884033). I have also been exploring xarray or  pyresample & kdt (based on: https://git.earthdata.nasa.gov/projects/LPDUR/repos/ecostress_swath2grid/browse/ECOSTRESS_swath2grid.py) but was never able to match SNAP output. That is why I wanted to try starts in R.

```
library(stars)
> Loading required package: abind
> Loading required package: sf
> Linking to GEOS 3.9.3, GDAL 3.5.2, PROJ 8.2.1; sf_use_s2() is TRUE

packageVersion("stars")
>‘0.6.0’
ll_in <- ("geodetic_in.nc")
lst_in <- ("LST_in.nc")

lon <- read_stars(ll_in, sub=5) %>% adrop
lat <- read_stars(ll_in, sub=3) %>% adrop
lst <- read_stars(lst_in, sub=1) %>% adrop
ll = setNames(c(lon, lat), c("x", "y"))
temp.c = st_as_stars(lst, curvilinear = ll)
st_crs(temp.c) <- 4326

> temp.c
stars object with 2 dimensions and 1 attribute
attribute(s), summary of first 1e+05 cells:
           Min. 1st Qu.  Median     Mean 3rd Qu.   Max. NA's
LST [K] 257.794 314.068 316.592 316.0953 319.404 330.82 4101
dimension(s):
  from   to refsys                                  values x/y
x    1 1500 WGS 84 [1500x1200] 58.2526 [°],...,77.2557 [°] [x]
y    1 1200 WGS 84 [1500x1200] 28.6775 [°],...,41.9878 [°] [y]
curvilinear grid

plot(temp.c, breaks = "equal", reset = FALSE, axes = TRUE, as_points = FALSE, border = NA)
```
This looks ok! 
![image](https://user-images.githubusercontent.com/55965799/225455146-cf8c07fd-3cd4-4a72-9bad-c4ed2d7f178e.png)
```
#warp1 no cellsize provided
w = st_warp(temp.c, crs = 4326, no_data_value = -32768)
Warning message:
In transform_grid_grid(st_as_stars(src), st_dimensions(dest), threshold) :
  using Euclidean distance measures on geodetic coordinates
> w
stars object with 2 dimensions and 1 attribute
attribute(s), summary of first 1e+05 cells:
          Min. 1st Qu.  Median     Mean 3rd Qu.    Max.
LST [K] 247.34  304.19 315.336 313.9428 327.496 332.056
         NA's
LST [K] 11458
dimension(s):
  from   to  offset      delta refsys x/y
x    1 1580 58.2526  0.0120283 WGS 84 [x]
y    1 1140 42.3817 -0.0120283 WGS 84 [y]
```
Here we have an issue
![image](https://user-images.githubusercontent.com/55965799/225455207-1dcc47af-5b92-4c92-9cd6-b19ee02076d9.png)

```
#warp2 use cellsize from the previous warp1
w2 = st_warp(temp.c, crs = 4326, no_data_value = -32768, cellsize=0.012)
Warning message:
In transform_grid_grid(st_as_stars(src), st_dimensions(dest), threshold) :
  using Euclidean distance measures on geodetic coordinates
> w2
stars object with 2 dimensions and 1 attribute
attribute(s), summary of first 1e+05 cells:
           Min. 1st Qu. Median     Mean 3rd Qu.    Max.
LST [K] 294.876 317.572 325.27 322.5213 327.152 330.104
         NA's
LST [K] 97983
dimension(s):
  from   to  offset  delta refsys x/y
x    1 1584 58.2526  0.012 WGS 84 [x]
y    1 1143 42.3817 -0.012 WGS 84 [y]
```
That one also does not work
![image](https://user-images.githubusercontent.com/55965799/225455335-1aae4216-9951-4f60-8f39-72cca2989499.png)

[S3A_SL_2_LST.zip](https://github.com/r-spatial/stars/files/10984725/S3A_SL_2_LST.zip)

**Comment by btupper** [comment]
@plthompson I seem to have the same issue warping multiband stars objects.  Here is another reprex, but this one uses data distributed with the stars package.  Have you had any luck resolving this bump?

``` r
suppressPackageStartupMessages({
  library(stars)
  library(sf)
  library(dplyr)
})

# read in as per example 
# https://r-spatial.github.io/stars/articles/stars1.html#cropping-a-rasters-extent
prec_file = system.file("nc/test_stageiv_xyt.nc", package = "stars")
prec = read_ncdf(prec_file, curvilinear = c("lon", "lat"))
#> no 'var' specified, using Total_precipitation_surface_1_Hour_Accumulation
#> other available variables:
#>  lat, lon, time
#> Will return stars object with 236118 cells.
#> No projection information found in nc file. 
#>  Coordinate variable units found to be degrees, 
#>  assuming WGS84 Lat/Lon.

# get the bb as sfc and then transform to a different crs
bb_native = st_bbox(prec) |> st_as_sfc()
bb_4326 = st_transform(bb_native, 4326)

# warp using one layer - success (with a warning)
sf_use_s2(FALSE)
#> Spherical geometry (s2) switched off
warped = st_warp(slice(prec, 'time', 1), crs = bb_4326)
#> Warning in transform_grid_grid(st_as_stars(src), st_dimensions(dest),
#> threshold): using Euclidean distance measures on geodetic coordinates
#> threshold set to 0.0418148 : set a larger value if you see missing values where they shouldn't be

# try warping the entire multilayer object (fails)
sf_use_s2(FALSE)
warped = st_warp(prec, crs = bb_4326)
#> Warning in transform_grid_grid(st_as_stars(src), st_dimensions(dest),
#> threshold): using Euclidean distance measures on geodetic coordinates
#> threshold set to 0.0418148 : set a larger value if you see missing values where they shouldn't be
#> Error in matrix(seq_len(prod(dims[dxy])), dims[dxy[1]], dims[dxy[2]])[xy]: subscript out of bounds


sessionInfo()
#> R version 4.2.2 (2022-10-31)
#> Platform: x86_64-redhat-linux-gnu (64-bit)
#> Running under: Rocky Linux 8.5 (Green Obsidian)
#> 
#> Matrix products: default
#> BLAS/LAPACK: /usr/lib64/libopenblaso-r0.3.12.so
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] dplyr_1.1.2 stars_0.6-4 sf_1.0-12   abind_1.4-5
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.11        compiler_4.2.2     pillar_1.9.0       class_7.3-22      
#>  [5] tools_4.2.2        digest_0.6.31      evaluate_0.21      lifecycle_1.0.3   
#>  [9] tibble_3.2.1       RNetCDF_2.6-2      pkgconfig_2.0.3    rlang_1.1.1       
#> [13] reprex_2.0.2       DBI_1.1.3          cli_3.6.1          rstudioapi_0.14   
#> [17] parallel_4.2.2     yaml_2.3.7         xfun_0.39          fastmap_1.1.1     
#> [21] ncmeta_0.3.5       e1071_1.7-13       withr_2.5.0        knitr_1.42        
#> [25] generics_0.1.3     fs_1.6.2           vctrs_0.6.3        classInt_0.4-9    
#> [29] grid_4.2.2         tidyselect_1.2.0   glue_1.6.2         R6_2.5.1          
#> [33] fansi_1.0.4        rmarkdown_2.21     purrr_1.0.2        tidyr_1.3.0       
#> [37] magrittr_2.0.3     htmltools_0.5.5    units_0.8-3        KernSmooth_2.23-21
#> [41] utf8_1.2.3         proxy_0.4-27       lwgeom_0.2-13      FNN_1.1.3.2
```

<sup>Created on 2023-09-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by enazario11** [comment]
I'm having the same issue with marine data from Copernicus - it works on a single layer but not when there are multiple time steps. Is there a fix in the works?
