### ISSUE TITLE
st_warp: confused about when "dest" is needed

### ISSUE THREAD

**Issue by MatthieuStigler** [r-spatial/stars#514]
I am confused about the help page of `st_warp`, for the case when one wants to provide only a `crs`, and no `dest` argument. I was hoping to do this with `method="bilinear"`, but the help page suggests it is only possible with `method="near"`. Reading from:

> If dest is not specified, but crs is, the procedure used to choose a target grid is similar to that of projectRaster (currently only with method='ngb')

But I can't even get working with `method="near"`? Whichever the method is, it seems one will face the warning: _argument "dest" is missing, with no default_. See reprex below. 

More fundamentally, I am not sure (assuming I understood correctly the help page) why the _procedure to choose a target grid_ would be depending on the interpolation method chosen? Could you kindly elaborate on that?

Thanks!

``` r
library(stars)
#> Loading required package: abind
#> Loading required package: sf
#> Linking to GEOS 3.10.1, GDAL 3.4.0, PROJ 8.2.0; sf_use_s2() is TRUE

geomatrix = system.file("tif/geomatrix.tif", package = "stars")
x = read_stars(geomatrix)
new_crs = st_crs(4326)

y = st_warp(x, crs = new_crs, method = "near", use_gdal=TRUE, no_data_value = 999)
#> Error in inherits(dest, "stars_proxy"): argument "dest" is missing, with no default
```

<sup>Created on 2022-03-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by edzer** [comment]
Thanks, yes, the mess that arises when writing code incrementally. This should now be cleaned up, and also work.

**Comment by MatthieuStigler** [comment]
thanks! 

Maybe I'm just too impatient, but it seems the current github version has an issue? I get `Error in NA_real_ * dest[[1]]: non-numeric argument to binary operator`

``` r
devtools::install_github("r-spatial/stars")
#> Downloading GitHub repo r-spatial/stars@HEAD
#> rlang (1.0.1 -> 1.0.2) [CRAN]
#> Installing 1 packages: rlang
#> Installing package into '/home/mstigler/R/x86_64-pc-linux-gnu-library/4.1'
#> (as 'lib' is unspecified)
#> * checking for file ‘/tmp/RtmpRwKLpm/remotes2abb934131755/r-spatial-stars-303ab46/DESCRIPTION’ ... OK
#> * preparing ‘stars’:
#> * checking DESCRIPTION meta-information ... OK
#> * checking for LF line-endings in source and make files and shell scripts
#> * checking for empty or unneeded directories
#> * building ‘stars_0.5-6.tar.gz’
#> Installing package into '/home/mstigler/R/x86_64-pc-linux-gnu-library/4.1'
#> (as 'lib' is unspecified)

library(stars)
#> Loading required package: abind
#> Loading required package: sf
#> Linking to GEOS 3.10.1, GDAL 3.4.0, PROJ 8.2.0; sf_use_s2() is TRUE
packageVersion("stars")
#> [1] '0.5.6'

geomatrix = system.file("tif/geomatrix.tif", package = "stars")
x = read_stars(geomatrix)
new_crs = st_crs(4326)

y = st_warp(x, crs = new_crs, method = "near", use_gdal=TRUE, no_data_value = 999)
#> Error in NA_real_ * dest[[1]]: non-numeric argument to binary operator
y2 = st_warp(x, crs = new_crs, method = "near", use_gdal=TRUE, no_data_value = 999)
#> Error in NA_real_ * dest[[1]]: non-numeric argument to binary operator
```

<sup>Created on 2022-03-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by edzer** [comment]
> Maybe I'm just too impatient, 

no, you test properly. Thanks, should now work!

**Comment by MatthieuStigler** [comment]
nice, it seems to work now, thanks a lot!!
