### ISSUE TITLE
st_crop() does not work on raster and sf object

### ISSUE THREAD

**Issue by arildodias** [r-spatial/stars#519]
Hi, I am trying to crop a raster representing the biodiversity intactness index and a polygon representing Europe using the code below:

library(stars)
library(rnaturalearth)

# europe map

world <- st_as_sf(rnaturalearth::countries110)
eu.map <- dplyr::filter(world, region_un=="Europe" & !name == 'Russia')
eu.map <- eu.map %>% st_transform(4326)

# reading the biodiversity intactness index tif

bii <- read_stars(".../Documents/R_projects/EI_V0/data/bii.tif")
str(bii)

#crop and plot

bii_crop <- st_crop(bii, eu.map)
plot(bii_crop)

The operation does not work and I received the following error:

downsample set to 22
Error in x[[i]][1:-1385, 1:411, drop = FALSE] : 
  only 0's may be mixed with negative subscripts
  
  
Can you help with this issue?
Thanks

Session info ────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.1.2 (2021-11-01)
 os       macOS Monterey 12.2.1
 system   aarch64, darwin20
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Europe/Berlin
 date     2022-03-15
 rstudio  2021.09.1+372 Ghost Orchid (desktop)
 pandoc   NA

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package       * version date (UTC) lib source
 abind         * 1.4-5   2016-07-21 [1] CRAN (R 4.1.0)
 assertthat      0.2.1   2019-03-21 [1] CRAN (R 4.1.0)
 backports       1.4.1   2021-12-13 [1] CRAN (R 4.1.1)
 broom           0.7.11  2022-01-03 [1] CRAN (R 4.1.1)
 cellranger      1.1.0   2016-07-27 [1] CRAN (R 4.1.0)
 class           7.3-20  2022-01-13 [1] CRAN (R 4.1.1)
 classInt        0.4-3   2020-04-07 [1] CRAN (R 4.1.0)
 cli             3.2.0   2022-02-14 [1] CRAN (R 4.1.1)
 colorspace      2.0-3   2022-02-21 [1] CRAN (R 4.1.1)
 crayon          1.5.0   2022-02-14 [1] CRAN (R 4.1.1)
 DBI             1.1.2   2021-12-20 [1] CRAN (R 4.1.1)
 dbplyr          2.1.1   2021-04-06 [1] CRAN (R 4.1.0)
 dplyr         * 1.0.8   2022-02-08 [1] CRAN (R 4.1.1)
 e1071           1.7-9   2021-09-16 [1] CRAN (R 4.1.1)
 ellipsis        0.3.2   2021-04-29 [1] CRAN (R 4.1.0)
 fansi           1.0.2   2022-01-14 [1] CRAN (R 4.1.1)
 farver          2.1.0   2021-02-28 [1] CRAN (R 4.1.0)
 forcats       * 0.5.1   2021-01-27 [1] CRAN (R 4.1.1)
 fs              1.5.2   2021-12-08 [1] CRAN (R 4.1.2)
 generics        0.1.2   2022-01-31 [1] CRAN (R 4.1.1)
 ggplot2       * 3.3.5   2021-06-25 [1] CRAN (R 4.1.1)
 glue            1.6.1   2022-01-22 [1] CRAN (R 4.1.1)
 gtable          0.3.0   2019-03-25 [1] CRAN (R 4.1.1)
 haven           2.4.3   2021-08-04 [1] CRAN (R 4.1.1)
 here            1.0.1   2020-12-13 [1] CRAN (R 4.1.0)
 hms             1.1.1   2021-09-26 [1] CRAN (R 4.1.1)
 httr            1.4.2   2020-07-20 [1] CRAN (R 4.1.0)
 jsonlite        1.7.2   2020-12-09 [1] CRAN (R 4.1.0)
 KernSmooth      2.23-20 2021-05-03 [1] CRAN (R 4.1.2)
 lattice         0.20-45 2021-09-22 [1] CRAN (R 4.1.2)
 lifecycle       1.0.1   2021-09-24 [1] CRAN (R 4.1.1)
 lubridate       1.8.0   2021-10-07 [1] CRAN (R 4.1.1)
 lwgeom          0.2-8   2021-10-06 [1] CRAN (R 4.1.1)
 magrittr        2.0.2   2022-01-26 [1] CRAN (R 4.1.1)
 modelr          0.1.8   2020-05-19 [1] CRAN (R 4.1.0)
 munsell         0.5.0   2018-06-12 [1] CRAN (R 4.1.0)
 pillar          1.7.0   2022-02-01 [1] CRAN (R 4.1.1)
 pkgconfig       2.0.3   2019-09-22 [1] CRAN (R 4.1.0)
 proxy           0.4-26  2021-06-07 [1] CRAN (R 4.1.0)
 purrr         * 0.3.4   2020-04-17 [1] CRAN (R 4.1.0)
 R6              2.5.1   2021-08-19 [1] CRAN (R 4.1.1)
 Rcpp            1.0.8   2022-01-13 [1] CRAN (R 4.1.1)
 readr         * 2.1.1   2021-11-30 [1] CRAN (R 4.1.1)
 readxl          1.3.1   2019-03-13 [1] CRAN (R 4.1.0)
 reprex          2.0.1   2021-08-05 [1] CRAN (R 4.1.1)
 rlang           1.0.1   2022-02-03 [1] CRAN (R 4.1.1)
 rnaturalearth * 0.1.0   2017-03-21 [1] CRAN (R 4.1.0)
 rprojroot       2.0.2   2020-11-15 [1] CRAN (R 4.1.0)
 rstudioapi      0.13    2020-11-12 [1] CRAN (R 4.1.0)
 rvest           1.0.2   2021-10-16 [1] CRAN (R 4.1.1)
 s2              1.0.7   2021-09-28 [1] CRAN (R 4.1.1)
 scales          1.1.1   2020-05-11 [1] CRAN (R 4.1.0)
 sessioninfo     1.2.2   2021-12-06 [1] CRAN (R 4.1.1)
 sf            * 1.0-5   2021-12-17 [1] CRAN (R 4.1.1)
 sp              1.4-6   2021-11-14 [1] CRAN (R 4.1.1)
 stars         * 0.5-5   2021-12-19 [1] CRAN (R 4.1.1)
 stringi         1.7.6   2021-11-29 [1] CRAN (R 4.1.1)
 stringr       * 1.4.0   2019-02-10 [1] CRAN (R 4.1.1)
 tibble        * 3.1.6   2021-11-07 [1] CRAN (R 4.1.1)
 tidyr         * 1.2.0   2022-02-01 [1] CRAN (R 4.1.1)
 tidyselect      1.1.2   2022-02-21 [1] CRAN (R 4.1.1)
 tidyverse     * 1.3.1   2021-04-15 [1] CRAN (R 4.1.0)
 tzdb            0.2.0   2021-10-27 [1] CRAN (R 4.1.1)
 units           0.7-2   2021-06-08 [1] CRAN (R 4.1.1)
 utf8            1.2.2   2021-07-24 [1] CRAN (R 4.1.0)
 vctrs           0.3.8   2021-04-29 [1] CRAN (R 4.1.0)
 withr           2.4.3   2021-11-30 [1] CRAN (R 4.1.1)
 wk              0.6.0   2022-01-03 [1] CRAN (R 4.1.1)
 xml2            1.3.3   2021-11-30 [1] CRAN (R 4.1.1)

 [1] /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by edzer** [comment]
Could you provide `bii.tif`?

**Comment by arildodias** [comment]
I cannot attach the tif here (I tried but I see it does not allow it). 

But is possible to check (and download) the bii file at this link here - https://data.nhm.ac.uk/dataset/global-map-of-the-biodiversity-intactness-index-from-newbold-et-al-2016-science

In this link above, the bii is in .asc format, but it is the same data set I am using as tif.

Thanks

**Comment by arildodias** [comment]
Good point; I think it is not needed. But in that case (excluding the overseas colonies), would make it work?

**Comment by kadyb** [comment]
@arildodias, have you tried using `gdalwarp`? Something like that:

```r
library("stars")

polygon = "polygon.gpkg"
sf::gdal_utils(
  util = "warp",
  source = "raster.tif" ,
  destination = "output.tif",
  options = c("-cutline", polygon,
              "-crop_to_cutline",
              "-co", "COMPRESS=LZW")
)

r = read_stars("output.tif")
```

**Comment by edzer** [comment]
Thanks! This should fix it; funny enough, it is very slow, setting `sf_use_s2(FALSE)` makes it much faster... something to look into.

**Comment by arildodias** [comment]
Hi, sorry for the late reply. Could you explain how I can use the gdalwarp considering the code I shared in the first post? I was not able to implement this. Thanks

**Comment by kadyb** [comment]
In `gdalwarp` you have to specify the paths to the files on the disk. Here is the documentation: https://gdal.org/programs/gdalwarp.html. I tried to run the code below but it didn't finish after more than 1h on my laptop.

```r
world <- st_as_sf(rnaturalearth::countries110)
eu.map <- dplyr::filter(world, region_un == "Europe" & !name == 'Russia')
eu.map <- eu.map %>% st_transform(4326)
write_sf(eu.map, "vector.gpkg")

polygon = "vector.gpkg"
sf::gdal_utils(
  util = "warp",
  source = "lbii.asc" ,
  destination = "output.tif",
  options = c("-s_srs", "epsg:4326",
              "-cutline", polygon,
              "-crop_to_cutline",
              "-co", "COMPRESS=LZW")
)
```

**Comment by mmyrte** [comment]
Thanks for pinging/remembering me and fixing this! The new formulation is much clearer IMO.

> [...] not sure it now does what it should do, and help welcome!

To be quite honest, I'm not sure what it _should_ do. Is this correct?

You have the situation where _some_ geographic CRS (not necessarily EPSG:4326, but likely in degrees? Can't find a declaration of what counts as a geographic CRS in GDAL/Proj; I cannot find my way around the codebase to learn about `PJ_TYPE_GEOGRAPHIC_2D_CRS`, for instance. don't know Cpp) is shifted with regards to the (e.g.) polygon object that you want to crop your stars object with. Because you know you're using degrees, it makes sense to expand the stars object's extent to make sure you cover it _if_ the stars object crosses the antimeridian.

The negative index came from the negative increment between minimum and maximum longitude, which should now be impossible, since you're only increasing the maximum/decreasing the minimum longitude.

In contrast to the old behaviour, you also avoid the weird situation where you would simply shift the stars object by 360 degrees if the there was no overlap between the extents.

So AFAIK, it seems to be correct now.

(And, since I haven't done so yet, a very general thanks for SF, love it!)
