### ISSUE TITLE
st_as_stars creates an extra column

### ISSUE THREAD

**Issue by Jean-Romain** [r-spatial/stars#521]
For some specific resolutions I found that `st_as_stars` creates an extra column or row. Below a  minimal reproducible example. I created a bounding box with values that are multiple of the resolution so there is no rounding error. I'm expecting an output of 1372 x 1488 but I get 1373 x 1488 

``` r
bbox = structure(c(xmin = 581152.86, ymin = 5292941.64, xmax = 581235.18,  ymax = 5293030.92), class = "bbox")
res = 0.06
r  <- stars::st_as_stars(bbox, dx = res, dy = res, values = NA_integer_)
r
#> stars object with 2 dimensions and 1 attribute
#> attribute(s), summary of first 1e+05 cells:
#>         Min. 1st Qu. Median Mean 3rd Qu. Max.  NA's
#> values    NA      NA     NA  NaN      NA   NA 1e+05
#> dimension(s):
#>   from   to  offset delta refsys point values x/y
#> x    1 1373  581153  0.06     NA    NA   NULL [x]
#> y    1 1489 5293031 -0.06     NA    NA   NULL [y]
(bbox$xmax - bbox$xmin)/res
#> xmax 
#> 1372
(bbox$ymax - bbox$ymin)/res
#> ymax 
#> 1488
```

<sup>Created on 2022-03-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

For comparison `terra` and `raster` return the expected number of columns

``` r
bbox = terra::ext(c(xmin = 581152.86, xmax = 581235.18, ymin = 5292941.64, ymax = 5293030.92))
res = 0.06
terra::rast(bbox, resolution = res)
#> class       : SpatRaster 
#> dimensions  : 1488, 1372, 1  (nrow, ncol, nlyr)
#> resolution  : 0.06, 0.06  (x, y)
#> extent      : 581152.9, 581235.2, 5292942, 5293031  (xmin, xmax, ymin, ymax)
#> coord. ref. :

bbox = raster::extent(c(xmin = 581152.86, xmax = 581235.18, ymin = 5292941.64, ymax = 5293030.92))
res = 0.06
raster::raster(bbox, res = res)
#> class      : RasterLayer 
#> dimensions : 1488, 1372, 2041536  (nrow, ncol, ncell)
#> resolution : 0.06, 0.06  (x, y)
#> extent     : 581152.9, 581235.2, 5292942, 5293031  (xmin, xmax, ymin, ymax)
#> crs        : NA
```

<sup>Created on 2022-03-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by edzer** [comment]
```r
> print((bbox$ymax - bbox$ymin)/res, digits = 20)
                 ymax 
1488.0000000043462478 
> print((bbox$xmax - bbox$xmin)/res, digits = 20)
                 xmax 
1372.0000000010866188 
```
but I agree, that is rather annoying.

**Comment by edzer** [comment]
```r
> r  <- stars::st_as_stars(bbox, dx = res, dy = res, values = NA_integer_, inside = TRUE)
> r
stars object with 2 dimensions and 1 attribute
attribute(s), summary of first 1e+05 cells:
        Min. 1st Qu. Median Mean 3rd Qu. Max.  NA's
values    NA      NA     NA  NaN      NA   NA 1e+05
dimension(s):
  from   to  offset delta refsys point values x/y
x    1 1372  581153  0.06     NA    NA   NULL [x]
y    1 1488 5293031 -0.06     NA    NA   NULL [y]
```

**Comment by Jean-Romain** [comment]
Sounds like a hot fix on my side thank you. But I'm wondering if this shouldn't be fixed on your side too?

**Comment by Jean-Romain** [comment]
Ok on my side it does the fix because now I get  1372 x 1487. Not with my previous example where I get a reproducible 1372 x 1488 but my actual figures may be slightly different. I'm trying to make a reproducible example

**Comment by edzer** [comment]
You might try this branch; needs more testing before I merge.

**Comment by Jean-Romain** [comment]
On my side it fully fixes my bug. There was two levels of problem in my bug

- The one I reported here
- But after using `inside = TRUE` as suggested my bug was not fixed because my actual numbers were not necessarily the closed floating representation of `5293030.92` but something else with more residual caused by previous computations. With `inside = FALSE` my raster was `1373 x 1488`. With `inside = TRUE` it was still wrong with `1372 x 1487` (unlike the reprex you made).

Using your fix by bugs are all gone without changing anything in my code.

**Comment by edzer** [comment]
Thanks, helpful!

**Comment by Jean-Romain** [comment]
FYI

I also fixed my bug on my side with the current CRAN version of `stars` using `inside = TRUE` and `round(bbox, 8)` to get a bbox with the closest floating representation of the expected values. However I won't deploy this fix because I guess it makes sense only with projected data. 8 digits of lon/lat is ~1 mm which is the typical accuracy I'm dealing with so I may generate errors with lon/lat data. I'm only reporting this just in case it helps

On my side I'm fixing the bug using `nx` and `ny`
