### ISSUE TITLE
get properties from stars_proxy objects

### ISSUE THREAD

**Issue by gdkrmr** [r-spatial/stars#530]
```
  f <- system.file("nc/reduced.nc", package = "stars")
  nc <- read_ncdf(f, proxy = TRUE)
  expect_s3_class(nc, "stars_proxy")

  nc2 <- adrop(nc)
  nc3 <- slice(nc2, "lon", 90)
  nc4 <- st_as_stars(nc3)
  dim(nc4)
  dim(nc3)
```
shouldn't nc3 and nc4 have the same dimensions?

EDIT, more clearly:
Lazy application of slicing and other methods on `stars_proxy` objects does not change the dimensions. I think strictly speaking it should. At least it should give a warning that there are pending operations that may or may not be reflected in the dimensions.

**Comment by edzer** [comment]
I understand your confusion. What would be a good warning message, and should it be printed with `dim(x)`?

**Comment by gdkrmr** [comment]
Something like:

Pending operations on the stars_proxy object, the result of dim(.) may change after evaluation.

The same should probably be printed with `st_dimensions`.

Pending operations on the stars_proxy object, the result of st_dimensions(.) may change after evaluation.

**Comment by edzer** [comment]
We can't do this in `print.dimensions()` because you may just want to take these and glue them to a valid object; instead, it is done in the `print.*_proxy` methods.

**Comment by edzer** [comment]
Here's another problem when we have `dim()` print a message, in stars/tests/predict.R, it generates:
```r
> all.equal(x, st_as_stars(yp))
Object has pending lazy operations, the result of dim(.) may not reflect these.
```
we're only comparing one dim to another, but will see this message totally out of context. So that has to go, I'm afraid.
