### ISSUE TITLE
How to remove NA values in geom_stars ?

### ISSUE THREAD

**Issue by tigerwang1998** [r-spatial/stars#532]
I want to learn and use stars package to handle raster datasets.
If I use geom_raster to plot, I can transform the raster into dataframe and remove the **NA** rows using `na.rm=T`.

```
    library(terra)
    library(ggplot2)
    test1 <- rast("F:\\data\\test.tif")
    df1 <- as.data.frame(test1, xy = T, na.rm = T)
    ggplot()+
      geom_raster(data=df1,aes(x=x,y=y,fill=Band_1))
```
![image](https://user-images.githubusercontent.com/50581765/165452215-184169f6-f382-4185-886d-769f4f450249.png)

In geom_stars, even though it doesn't need transform raster into dataframe, but how to process **NA** values?

I have tried to pass `na.rm = TRUE` to `geom_stars()`, but it didn't work. And it didn't report any errors or warnings.

```
    library(stars)
    library(ggplot2)
    test <- read_stars("F:\\data\\test.tif")
    ggplot()+
      geom_stars(data = test, na.rm = T)
```
![image](https://user-images.githubusercontent.com/50581765/165452362-c8da2464-8257-4d0f-9d54-0e7a287fddbb.png)

**Comment by edzer** [comment]
Have you tried to pass `na.rm = TRUE` to `geom_stars()`?

**Comment by tigerwang1998** [comment]
您好，邮件已收到。
 久等不回或急事请电话联系。

**Comment by tigerwang1998** [comment]
I have  tried to pass `na.rm = TRUE` to `geom_stars()`, but it didn't work.

**Comment by tigerwang1998** [comment]
> Have you tried to pass `na.rm = TRUE` to `geom_stars()`?

I have tried to pass `na.rm = TRUE `to` geom_stars()`, but it didn't work.

**Comment by tigerwang1998** [comment]
I am sorry about that, it still didn't work. 
Thanks for your patience!

**Comment by edzer** [comment]
Did you reinstall stars from github with `remotes::install_github("r-spatial/stars")` ?

**Comment by tigerwang1998** [comment]
> Did you reinstall stars from github with `remotes::install_github("r-spatial/stars")` ?

Thanks a lot!!!
Finally it works.
Thanks for your patience and profession again!
