### ISSUE TITLE
geom_stars does not work when `stars:::has_rotate_or_shear(data) == TRUE`

### ISSUE THREAD

**Issue by abesolberg** [r-spatial/stars#540]
I am getting the error message `Error in geom_stars(data = data) : geom_stars only works for objects with raster or vector geometries` when trying to use geom_stars for a sheared raster. It works fine when using plot.

**Comment by edzer** [comment]
Maybe convert such data to `sf`, then use `geom_sf()`? I guess that is what `stars::plot.stars()` does...

**Comment by abesolberg** [comment]
I will try that. Thank you, @edzer!
