### ISSUE TITLE
missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/stars#55]
I am opening the file used in the first stars blog via `raster`, then to transform it to stars via `st_as_stars`. However I am getting this error:
`Error in if (diff(range(ud))/mean(ud) < 1e-10) { : 
  missing value where TRUE/FALSE needed`

If instead I read two bands at a time, converting them works.

To reproduce:
```R
inputFile <- "full_data_daily_2013.nc" #Same data used in star's first blog post:http://r-spatial.org/r/2017/11/23/stars1.html#reading-a-raster-time-series-netcdf

r <- raster::raster(inputFile, varname="p")
s <- raster::stack(inputFile, varname="p", bands=1:2)

r2 <- stars::st_as_stars(r) # DOES NOT WORK
s2 <- stars::st_as_stars(s) # WORKS
```

**Comment by edzer** [comment]
Thanks!
