### ISSUE TITLE
recording of talks, slides or other resources

### ISSUE THREAD

**Issue by btupper** [r-spatial/stars#552]
Hello,

This isn't an issue, but a request for resources. Our group will be presenting short tutorials on data access and visualizations in R during this year's [Ocean Hack Week '22](https://github.com/oceanhackweek). We have been looking for some inspiration on the World Wild Web, but `stars` seems to be an untold story. There are many tutorials online for [sf](https://r-spatial.github.io/sf/) but not so much for `stars`. Might folks be willing to post links to publicly available talks/slides that explain how to use `stars` and that showcase some use-cases? I could assemble them into a easy-to-find document (perhaps the github wiki?)

Thanks,
Ben

**Comment by kadyb** [comment]
There are several workshops and presentations from Edzer Pebesma on YouTube (just type his full name to search):

- [Handling and analysing vector and raster data cubes with R](https://www.youtube.com/watch?v=9by7zsGms40)
- [Spatial data science in the Tidyverse](https://www.youtube.com/watch?v=2d8YaVu1uzs)
- [Analyzing & visualising spatial data cubes](https://www.youtube.com/watch?v=eGUjpqkoBCM)

Moreover, here is book [Spatial Data Science with applications in R](https://www.r-spatial.org/book), [tutorials](https://r-spatial.github.io/stars/articles/) and [blogposts](https://r-spatial.org/).

**Comment by edzer** [comment]
Thanks for the clear list @kadyb ! Happy to be involved in your ocean hack week, remotely - I'm always on the watch for challenges and new use cases.

**Comment by btupper** [comment]
Oh, nice!  This is a very helpful set of resources.  They don't really pop up in [Rseek.org](https://rseek.org/?q=stars) - a whole new universe awaits.  Thank you!

Thanks so much for your offer regarding Ocean Hack Week; I'm not an organizer but I am alerting Emilio Mayorga (@emiliom) and Filipe Fernandes (@ocefpaf) who are very much involved in organizing.  I suspect that this year's week (starts in about 10 days) may be closing in very quickly for them.  They have provided for some showcase tutorials using xarray in Python, but are not presenting anything similar in R... a showcasing of `stars` would be perfect.  

Our group can share with you what develop during the hack week; we are hopeful to crowd source some data-access packages using `sf` and `stars`, but much depends upon the folks that show up to hack.

**Comment by Tartomas** [comment]
Hi @btupper I have starting working with _stars_ for extract information from physical model from MERCATOR and I can state that it has been a pretty intuitive. If is not to late, I could also offer me to cooperate in some script or analysis to share in the Ocean Hack. I have been analyzing temperature from satellite and modelling information. Tell me what you think. 
Best !

**Comment by btupper** [comment]
Awesome!  It looks to me like registration might be closed for this year, but I shall inquire. If it is closed for this year, please do consider joining next year.

Either way, let's connect outside of this thread to discuss and share.  It would be so useful to compile a suite of use cases to share widely.

**Comment by Tartomas** [comment]
@btupper here is my direct contact if you want to reach me out tomasacuna@ug.uchile.cl
Best

**Comment by btupper** [comment]
Thanks! I'll reach out to you. 

I have heard back that OHW22 registration is fully closed for this year.

**Comment by kadyb** [comment]
Hi @btupper, here is a little self-promotion, but you might be interested. I taught workshop on [OpenGeoHub](https://opengeohub.org/summer-school/siegburg-2022/) this week comparing/benchmarking spatial packages in Python and R, and one part is about raster packages (`{terra}`, `{stars}`, `{rasterio}`). Here is the repository with notebooks: https://github.com/kadyb/ogh2022
