### ISSUE TITLE
Request: Adding the ability to write to ASCII

### ISSUE THREAD

**Issue by robbie-still** [r-spatial/stars#556]
Hi, it would be very helpful if the ability to write directly from {stars} to ASCII were added. Currently I add the following two lines to do the job, and would love to cut out the extra dependency on {raster}.  

`as("Raster") %>% 
  writeRaster(test.asc)`

**Comment by edzer** [comment]
the [AAIGrid](https://gdal.org/drivers/raster/aaigrid.html) GDAL driver doesn't support creation; I also don't think it is a useful data format for creation of anything serious; I would consider a PR but will not work on this myself.
