### ISSUE TITLE
r stars_proxy raster cannot be plotted: Error in attributes(.Data) <- c(attributes(.Data), attrib)

### ISSUE THREAD

**Issue by AlexandreWadoux** [r-spatial/stars#561]
I have 6 large rasters of a soil property and I wish to plot them using facet_wrap. Each of these raster represent a different depth interval for the same area and the same property. I usually load my raster from my hard drive but this time I load them from an online link. The following code works when loading my data from my hard drive, but doesn't when loading my data from the link online.

Here is a reproducible example of my error:

```
library(stars)
library(ggplot2

##### Access the COG directly from the DataStore and Plot it #######
list_ras <- c("SOC_000_005_EV_N_P_AU_TRN_N_20220727.tif",
              "SOC_005_015_EV_N_P_AU_TRN_N_20220727.tif",
              "SOC_015_030_EV_N_P_AU_TRN_N_20220727.tif",
              "SOC_030_060_EV_N_P_AU_TRN_N_20220727.tif",
              "SOC_060_100_EV_N_P_AU_TRN_N_20220727.tif",
              "SOC_100_200_EV_N_P_AU_TRN_N_20220727.tif")
ras <- read_stars(paste0('/vsicurl/https://esoil.io/TERNLandscapes/Public/Products/TERN/SLGA/SOC/', list_ras), along = 'depth')

names(ras$attr) <- c("0-5 cm", "5-15 cm", "15-30 cm", 
                     "30-60 cm", "60-100 cm", "100-200 cm")

ggplot() +
  geom_stars(data = ras, downsample = 100) + 
  facet_wrap(~depth)
```
And I get the error:
```
Error in attributes(.Data) <- c(attributes(.Data), attrib) : 
 dims [product 197152] do not match the length of object [1182912]
```
I have tried even more basic plotting but it always gives me a similar error. It seems that there is a problem with one dimension because 1182912/197152 = 6, i.e. my number of rasters.

it seems that others have faced a similar issue (e.g. see  https://stackoverflow.com/questions/72352195/r-stars-error-dims-do-not-match-the-length-of-object-when-evaluating-proxy) but I could not find the answer nor the explanation to solve this in the various documentation files.

**Comment by edzer** [comment]
Thanks, great reprex, and a longstanding bug it seems.

**Comment by AlexandreWadoux** [comment]
It is solved thanks for the quick answer!

**Comment by edzer** [comment]
Thanks! that should work now.

**Comment by Shappiro** [comment]
Thanks, at first I thought the fix worked, but this still seems to fail when the stars object has more than 3 dimensions.
Building from the above reprex:

```
newras <- c(ras,ras)
names(newras)<-c("pack1","pack2")
newras <- st_redimension(newras)

newras[,,,,1] %>% plot()
```
...It might well be I'm trying to do something horribly wrong here: if that's the case, I'm really sorry!

**Comment by edzer** [comment]
No, you are completely right; this should work better now, also with more than 4 dimensions (but not tested).

**Comment by Shappiro** [comment]
Thanks a lot! From what I can see, works good now

**Comment by edzer** [comment]
I think it will fail when the tiff files are multi-band.

**Comment by edzer** [comment]
For reference:
```r
library(stars)
# Loading required package: abind
# Loading required package: sf
# Linking to GEOS 3.10.2, GDAL 3.4.3, PROJ 8.2.1; sf_use_s2() is TRUE

l7 = system.file("tif/L7_ETMs.tif", package = "stars")

##### Access the COG directly from the DataStore and Plot it #######
list_ras <- c(l7, l7, l7, l7)
ras <- read_stars(list_ras, along = 'depth', proxy = TRUE)

ras[,,,,1:2] |> st_as_stars() # doesn't reduce the number of files
# Error in dim(ret[[i]]) <- dim(new_dim) : 
#   dims [product 1474176] do not match the length of object [2948352]
# Calls: st_as_stars ... st_as_stars.stars_proxy -> process_call_list -> fetch
# Execution halted
```
