### ISSUE TITLE
Netcdf file error using read_ncdf() on files that usually work

### ISSUE THREAD

**Issue by acrunyon** [r-spatial/stars#571]
I have been using the same script to open the NOAA nClimGrid nc files (https://www.ncei.noaa.gov/thredds/catalog/data-in-development/nclimgrid/catalog.html) for months using read_ncdf().

As of this morning I get the following error (yet the file opens just fine with ncdf4). I have updated R and all packages and have tried using different netcdf files of different datasets, all with same result. Did something change in the package or its dependencies?

Error: Tibble columns must have compatible sizes.
• Size 2: Columns filter_id and filter_params.
• Size 3: Column chunksizes.
ℹ Only values of size one are recycled.

I get the same error when using tidync() and functions from ncmeta.

**Comment by edzer** [comment]
> I get the same error when using tidync() and functions from ncmeta.

Maybe you can post the issue there, or ask @mdsumner here?

**Comment by acrunyon** [comment]
@edzer - The issue is with the ncmeta package. Installing the dev version, as described in this link resolves the problem. https://github.com/hypertidy/ncmeta/issues/42
