### ISSUE TITLE
Error in plotting regular stars raster using `geom_stars` for ggplot2

### ISSUE THREAD

**Issue by tcwilkinson** [r-spatial/stars#572]
Enjoying using stars to play with mapping rasters. Came across the below problem, whose origin I can't track down.

Basically x,y aesthetics are apparently not being passed to geom_raster using geom_stars.

reprex based on docs from here: https://r-spatial.github.io/stars/articles/stars5.html 

```
packageVersion("stars")
## ‘0.5.6’
> packageVersion("ggplot2")
## [1] ‘3.3.6’

library(stars)
library(ggplot2)

system.file("gpkg/nc.gpkg", package = "sf") %>%
  read_sf() %>%
  st_transform(32119) -> nc
nc$dens = nc$BIR79 / units::set_units(st_area(nc), km^2)
nc.st = st_rasterize(nc["dens"], dx = 5000, dy = 5000)

ggplot() + geom_stars(data=nc.st,mapping=aes(fill=dens))
## Error in `check_required_aesthetics()`:
## ! geom_raster requires the following missing aesthetics: x and y
## Run `rlang::last_error()` to see where the error occurred.
```

For comparison: the error is no longer called if stars object converted to sf, or if we convert to curvilinear grid -- so clearly something to do with geom_raster.  Could be used as workaround, but suspect it is very costly to convert large rasters this way (as in my case, where I was specifically trying to avoid using curvilinear rasters as they can be slow).

``` 
ggplot() + geom_stars(data=nc.st,mapping=aes(fill=dens),sf=T)
## works, although creates an unwanted moiré pattern
```
![image](https://user-images.githubusercontent.com/13162107/199554960-f3a8feb8-fd7b-4543-b16d-75a4d96b3c7d.png)

```
nc.st %>% st_transform("+proj=laea +lat_0=34 +lon_0=-60") -> nc.curv
ggplot() + geom_stars(data=nc.curv,mapping=aes(fill=dens))
## also works, this time with different kinds of artifacts
```
![image](https://user-images.githubusercontent.com/13162107/199555631-10e5eca7-fdad-4b80-8c3c-357407c964a5.png)

Thanks in advance for any insight...

**Comment by edzer** [comment]
Yes, but `ggplot() + geom_stars(data=nc.st)` works too. `geom_sf()` is a whole different beast compared to `geom_stars()` which is a thin wrapper around `geom_raster()` (for grids) or `geom_sf()` (for the rest). Copying that behaviour would require me to first learn how to [dance ggplot2](https://cran.r-project.org/web/packages/ggplot2/vignettes/extending-ggplot2.html).

**Comment by tcwilkinson** [comment]
Thanks for this.   [ggplot2 nothing like foxtrot](https://cran.r-project.org/web/packages/ggplot2/vignettes/extending-ggplot2.html) I guess :-) ...

Couple of follow-ups:

1. Why does `ggplot() + geom_stars(data=nc.st,sf=T)` plot as lat-lon coords, but `ggplot() + geom_stars(data=nc.st)` in x/y from nc.st ?  (something to do with `geom_sf` vs `geom_raster`?)

2. I wasn't quite clear why `ggplot() + geom_stars(data=nc.st)` worked but not `ggplot() + geom_stars(data=nc.st,mapping=aes(fill=dens))` (even though, I realise in this particular case, it is redundant). 

https://github.com/r-spatial/stars/blob/cbb085b944700a84bd98a611f6258013fe58890a/R/tidyverse.R#L306-L311

Looking at geom_stars function code, I now see that if _any_ mapping provided to geom_stars then you have to provide all mapping, i.e. you can't just overlay `fill=`.

Would addition of a few scattered `modifyList` be useful then? (e.g. as below)

```r
	if (has_raster(d) && (is_regular_grid(d) || is_rectilinear(d))) {
		xy = attr(d, "raster")$dimensions
		if (is_regular_grid(d)) {
			if (is.null(mapping)) {
				mapping = ggplot2::aes(x = !!rlang::sym(xy[1]), y = !!rlang::sym(xy[2]),
					fill = !!rlang::sym(names(data)[1])) } else {
                                mapping = modifyList( ggplot2::aes(x = !!rlang::sym(xy[1]), y = !!rlang::sym(xy[2]),
					fill = !!rlang::sym(names(data)[1])), mapping) }
			data = na.action(dplyr::as_tibble(data))
			ggplot2::geom_raster(mapping = mapping, data = data, ...)
		} else {  # rectilinear: use geom_rect, passing on cell boundaries
			xy_max = paste0(xy, "_max")
			if (is.null(mapping)) {
				mapping = ggplot2::aes(xmin = !!rlang::sym(xy[1]), ymin = !!rlang::sym(xy[2]),
					xmax = !!rlang::sym(xy_max[1]), ymax = !!rlang::sym(xy_max[2]),
					fill = !!rlang::sym(names(data)[1])) } else {
				mapping = modifyList(ggplot2::aes(xmin = !!rlang::sym(xy[1]), ymin = !!rlang::sym(xy[2]),
					xmax = !!rlang::sym(xy_max[1]), ymax = !!rlang::sym(xy_max[2]),
					fill = !!rlang::sym(names(data)[1])), mapping }
			data = na.action(dplyr::as_tibble(data, add_max = TRUE))
			ggplot2::geom_rect(mapping = mapping, data = data, ...)
		}
	} else if (has_sfc(d)) {
		if (is.null(mapping)) {
			mapping = ggplot2::aes(fill = !!rlang::sym(names(data)[1])) } else {
		        mapping = modifyList( ggplot2::aes(fill = !!rlang::sym(names(data)[1])), mapping) }
		ggplot2::geom_sf(data = st_as_sf(data, long = TRUE), color = NA, mapping = mapping, ...)
	} else
		stop("geom_stars only works for objects with raster or vector geometries")
```
