### ISSUE TITLE
Problems with GHA workflow

### ISSUE THREAD

**Issue by kadyb** [r-spatial/stars#575]
I think there are at least two problems. The first is with `{sf}` installation from GH. The second is with the `{starsdata}` installation. I removed these two packages from DESCRIPTION and the workflow runs better: https://github.com/kadyb/stars/actions/runs/3388425471/jobs/5630393298

Regarding the first, maybe you should install `{sf}` using `remotes::install_github("r-spatial/sf")` or `pak::pkg_install("r-spatial/sf")`? Regarding the second one, I'm not sure. Maybe `{pkgdepends}` doesn't support external sources?

**Comment by edzer** [comment]
Thanks, will try!

**Comment by kadyb** [comment]
https://github.com/r-spatial/stars/blob/27528afb2c66cd5c1d9f69c051e8da5180ebb48b/vignettes/stars2.Rmd#L36

this URL should be `http://gis-bigdata.uni-muenster.de/pebesma`.

**Comment by kadyb** [comment]
So I removed `{sf}` and `{starsdata}` from DESCRIPTION, next I added them as manual installation:

https://github.com/kadyb/stars/blob/a8ab29206234079d8c627c95ca39beb40f7222a1/.github/workflows/tic.yml#L80-L85

and it seems to be working. However, there is still one note related to `{starsdata}` (probably because I removed it from DESCRIPTION):

```
❯ checking for unstated dependencies in vignettes ... NOTE
  'library' or 'require' call not declared from: ‘starsdata’
```

**Comment by edzer** [comment]
Only removing `starsdata` from the list was sufficient for the ubuntu platforms. I'll file a but with r-lib/actions - this used to work fine.

**Comment by kadyb** [comment]
#576 will fix installing on macOS. On Windows there is problem with `{sf}` compilation, but I don't know how to fix it (GDAL missing in RTools? or wrong path?). Probably the easiest way will be to turn off testing on Windows.

<details>
  <summary>Windows log</summary>
  
```
Failed to build source package 'sf', stdout + stderr:

OE> * installing *source* package 'sf' ...
OE> staged installation is only possible with locking
OE> ** using non-staged installation
OE> 
OE>    **********************************************
OE>    WARNING: this package has a configure script
OE>          It probably needs manual configuration
OE>    **********************************************
OE> 
OE> 
OE> ** libs
OE> rm -f sf.dll RcppExports.o bbox.o gdal.o gdal_geom.o gdal_read.o gdal_utils.o gdal_write.o geos.o hex.o mdim.o ops.o polygonize.o proj.o proj_info.o raster2sf.o sfc-sfg.o signed_area.o stars.o wkb.o zm_range.o
OE> cp -r "c:/rtools42/x86_64-w64-mingw32.static.posix/share/gdal" ../inst/
OE> cp: cannot stat 'c:/rtools42/x86_64-w64-mingw32.static.posix/share/gdal': No such file or directory
OE> make: *** [Makevars.ucrt:11: winlibs] Error 1
OE> ERROR: compilation failed for package 'sf'
```

</details>

**Comment by kadyb** [comment]
I think the workflow is not working now because there is something wrong with `Remotes: r-spatial/sf`. If I deleted it from DESCRIPTION and added `pak::pkg_install("r-spatial/sf")` it was ok.

**Comment by edzer** [comment]
No, Remotes: is OK, I added `starsdata` back in `Suggests:`; see https://github.com/r-lib/actions/issues/656 and https://github.com/r-spatial/stars/commit/7f95e7b5bae0ff1abbcd7f6404bf47a6f3198f83

**Comment by kadyb** [comment]
Hmmm. I see you have this [error now](https://github.com/r-spatial/stars/actions/runs/3392701953/jobs/5639194166):

```
subscript out of bounds, candidate$extra[[1]][["remotesha"]], NA, NA, remotesha <subscriptOutOfBoundsError in candidate$extra[[1]][["remotesha"]]: subscript out of bounds>
```

It looks like the same error when I wanted to install `{sf}` with GH. So I removed `Remotes: r-spatial/sf` and it works on Ubuntu now: https://github.com/kadyb/stars/actions/runs/3392850971/jobs/5639514981.

But now on macOS I see now:

```
* deps::/Users/runner/work/stars/stars: Can't install dependency starsdata
Execution halted
* starsdata: Can't find package called starsdata.
```

**Comment by kadyb** [comment]
Next issue on macOS:

```
Error(s) in re-building vignettes:
Warning in doTryCatch(return(expr), name, parentenv, handler) :
  no font could be found for family "Arial"
SUMMARY: processing the following files failed:
  ‘stars1.Rmd’ ‘stars3.Rmd’
```

**Comment by edzer** [comment]
Thanks for all the help!
