### ISSUE TITLE
Values from netCDF file are read all as 0

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/stars#58]
I am trying to read [this 60MB file](https://drive.google.com/open?id=1RyeaTJ7E17JynOnAsUvqEpRddiZBnZk0), which can be read correctly with `ncview`, `raster` etc.
However, when reading with `stars`, all values are NA or 0. Maybe GDAL is not applying the `scale_factor` attribute correctly?

```R
fn_in = 'E_OBS_mon_1980-2008.nc'
nc_in = read_stars(fn_in, sub = 'rr')
a = st_apply(nc_in, 1:2, sum, na.rm=TRUE)
plot(a)
```
Gives an empty plot. What's going on?

**Comment by edzer** [comment]
`plot(a[,,,1:10])` reveals that the 0 vs NA pattern is OK. scale factors are being taken care of by stars. `read_ncdf` also seems rather unhelpful for this file: the data are read (not sure if scale is applied?) but the dimensions table is a mess; maybe @mdsumner can take a look?

**Comment by mdsumner** [comment]
Will do, but btw is there any chance we could get a system where we share wget-able file links, or upload them directly to starsdata so I can rsync that?

**Comment by edzer** [comment]
I don't have a paid dropbox account; I could set up an owncloud directory for this, and create starsdata from there (I don't increase starsdata version numbers, to avoid many files - haven't figure out how to remove files from the directory I scp it to).

**Comment by adrfantini** [comment]
I have an http server at work I can use, but I'm not sure of the long term availability of it nor how much space I can use. I might set up a small server I have lying around in the office but I won't be able to do so before december.

**Comment by edzer** [comment]
Do you two already use owncloud file servers?

**Comment by adrfantini** [comment]
No, was planning to setup a personal one but never got around to that, not yet at least.

**Comment by adrfantini** [comment]
I have access to a server with reasonaby fast upload, but space is very limited, how much do we need?

**Comment by edzer** [comment]
I think we want something sustainable for at least, say 5-10 years, more is better.

**Comment by adrfantini** [comment]
That's not something I can assure, unfortunately.

**Comment by mdsumner** [comment]
Haven't heard of ownCloud - but anything like that I could get to work. We are starting to use Amazon more at my workplace, but it's an active topic and we are still in the middle of it.  We probably need to outline the whole picture better - but it is a bit of a pain for me, atm I have to download local and then upload if I can't wget or rsync direct. 

(There is googledrive for R, and now piggyback that uses github releases - maybe those could work?)

rstudio.cloud would be super for me, if they could provide the disk space (or we could pay and it wasn't too much).

**Comment by edzer** [comment]
We have some budget in the stars data project, but I'd planned to spend that on computing, and rent a machine that has (nearly) free access to the complete Sentinel 2 archive. For a test dataset, I'd prefer to keep this in an R package, so that it's all in one place, and we don't clutter the user's disk with downloaded files wherever she/he works.

**Comment by mdsumner** [comment]
That sounds right to me, we were discussing piggyback today and that seems pretty promising. I'll try it out and put up my own "weird/*.nc" folder.

**Comment by edzer** [comment]
My feeling was that it's not meant for single files in the 1 Gb range or larger.

**Comment by mdsumner** [comment]
We'd get a heap of value from dozens of little files that we can add to often, and keep the really big stuff in drat/starsdata?

**Comment by edzer** [comment]
Example use of `starsdata` and installations instructions are in the .travis.yml file, and in the vignettes using them.
