### ISSUE TITLE
Axis from geom_sf() in geom_stars()

### ISSUE THREAD

**Issue by jmburgos** [r-spatial/stars#580]
Hello,

Something I really like is that geom_sf() takes care of the axis labels, and greates a graticule in epsg=4326 even though the data I am plotting is projected in some other system.

How can I make geom_stars() to behave in the same way?  I know that I can convert the stars object into an sf object (using sf=TRUE), but this is slow for large rasters.  I can also add to the plot the bounding box of the raster with geom_sf(), which is faster  but it feels hackish.  Is there another way to do this?

**Comment by edzer** [comment]
This, for instance, brings the `geom_sf()` axis labels:
```r
library(stars)
w = st_warp(L7_ETMs, crs = st_crs("EPSG:4326")) # to have long/lat data
ggplot() + geom_sf(data = st_as_sfc(st_bbox(w))) + geom_stars(data = w)
```
adding `na.action = na.omit` to `geom_stars()` should not grey out the raster area with `NA` values, and reveal the graticule.
