### ISSUE TITLE
`st_rgb()` fails when `stars` object contains `NA`'s

### ISSUE THREAD

**Issue by tsamsonov** [r-spatial/stars#581]
Hi @edzer! Here is a simple reprex:
 
``` r
library(stars)

img = read_stars('https://raw.githubusercontent.com/tsamsonov/r-geo-course/master/data/world/BlueMarbleJuly.tif')

plot(st_rgb(img)) # works fine
```

![](https://i.imgur.com/hVnGFHh.png)

``` r

img_prj = st_warp(img, crs = '+proj=moll', use_gdal = T)
#> Warning in st_warp(img, crs = "+proj=moll", use_gdal = T): no_data_value not
#> set: missing values will appear as zero values

plot(st_rgb(img_prj)) # error
#> Error in rgb(r[sel, 1:3], maxColorValue = maxColorValue): неправильное значение 'maxColorValue'
```

<sup>Created on 2022-11-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Seems that `na.rm = T` should be added to the inner `max()` call [here](https://github.com/r-spatial/stars/blob/0dfb012299199e15b2b472457ca9a4aaa3765046/R/plot.R#L540).

I can make a PR, if this is correct.

**Comment by edzer** [comment]
> I can make a PR, if this is correct.

LGTM, please do!

**Comment by edzer** [comment]
```r
plot(img_prj, rgb = 1:3)
```
works, btw:
![x](https://user-images.githubusercontent.com/520851/201332740-9ce8bddd-432c-413a-8ab3-c2ed6c395ae0.png)

**Comment by edzer** [comment]
Thanks!

**Comment by tsamsonov** [comment]
> works, btw:

Interesting! Worked for me as well.
