### ISSUE TITLE
`st_warp()` fails if the inverse projection to geographic CRS produces out of bounds (`NA`) coordinates

### ISSUE THREAD

**Issue by tsamsonov** [r-spatial/stars#583]
Hi @edzer! Here is a small reprex:

``` r
library(stars)
#> Loading required package: abind
#> Loading required package: sf
#> Linking to GEOS 3.10.2, GDAL 3.4.2, PROJ 8.2.1; sf_use_s2() is TRUE

img = read_stars('https://raw.githubusercontent.com/tsamsonov/r-geo-course/master/data/world/BlueMarbleJuly.tif')

img_prj = st_warp(img, crs = '+proj=moll') # error if use_gdal = FALSE
#> Warning in CPL_proj_direct(from_to, as.matrix(pts), keep, warn,
#> authority_compliant): one or more projected point(s) not finite
#> Error in if (x[1, 1] > bb["xmax"]) x[1, 1] = x[1, 1] - 360: missing value where TRUE/FALSE needed
```
<sup>Created on 2022-11-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

The problem emerges when the target grid contains points which cannot be inverse projected to the source geographic CRS — results are out of [-180, 180]×[-90, 90] domain. In this case `sf_project` produces `NA` coordinates [here](https://github.com/r-spatial/stars/blob/1cc5c7ad9981e221f6f8fdc8aa84ef71a5e008d7/R/warp.R#L84) which leads to `NAs are not allowed in subscripted assignments` error [here](https://github.com/r-spatial/stars/blob/1cc5c7ad9981e221f6f8fdc8aa84ef71a5e008d7/R/stars.R#L251) since `ix` contains `NA`s.

I [fixed](https://github.com/tsamsonov/stars/commit/3e36cef39b66921196638b304c49a2a2f83856d2) the problem by filtering `NA`s before subscription. If that is correct, I'll make a PR.

**Comment by edzer** [comment]
Yes, that looks like a reasonable approach; please PR!
