### ISSUE TITLE
accessing data from curvilinear NetCDF causes error if file is opened as proxy 

### ISSUE THREAD

**Issue by iona5** [r-spatial/stars#586]
using `stars 0.5.6` and R 4.2.1 on Windows

I have NetCDF files with a curvilinear grid. These are rather large so they are opened implicitly as a proxy. the `read_ncdf` command executes fine, but when i want to convert those to a data.frame i get the error:

```
Error in dims$start[dims$name == coord] <- which(coords[[coord]] == uc[[coord]][1]) : 
  replacement has length zero
```

As an example see the NetCDF (where i reduced the data to a simple 2x2 curvilinear grid with one timestep, my actual files are much larger) packaged in [attached ZIP](https://github.com/r-spatial/stars/files/10012129/curvilinear.zip) .

```
> nc = stars::read_ncdf("curvilinear.nc", proxy=TRUE, var="precip_g_rate")
No projection information found in nc file. 
 Coordinate variable units found to be degrees, 
 assuming WGS84 Lat/Lon.
> nc
netcdf source stars proxy object from:
[1] "[...]/curvilinear.nc"

Available nc variables:
precip_g_rate

dimension(s):
     from to offset delta  refsys point                    values x/y
lon     1  2     NA    NA  WGS 84    NA  [2x2] 10.864,...,10.8914 [x]
lat     1  2     NA    NA  WGS 84    NA [2x2] 47.0606,...,47.0793 [y]
time    1  1     NA    NA POSIXct    NA            2015-01-01 UTC    
curvilinear grid
> as.data.frame(nc)
Error in dims$start[dims$name == coord] <- which(coords[[coord]] == uc[[coord]][1]) : 
  replacement has length zero
```

If I load this file without "proxy" parameter (so it will be loaded in total) it works:

```
> nc = stars::read_ncdf("curvilinear.nc", var="precip_g_rate")
Will return stars object with 4 cells.
No projection information found in nc file. 
 Coordinate variable units found to be degrees, 
 assuming WGS84 Lat/Lon.
> as.data.frame(nc)
       lon      lat       time          precip_g_rate
1 10.86404 47.06065 2015-01-01 0.004917145 [mm/15min]
2 10.89139 47.06061 2015-01-01 0.008358002 [mm/15min]
3 10.86411 47.07927 2015-01-01 0.005493164 [mm/15min]
4 10.89145 47.07924 2015-01-01 0.007896423 [mm/15min]
```

**Comment by iona5** [comment]
as you rightfully point out from a memory perspective other methods should be used to access the data in practice and my steps to reproduce was probably a bit random.

my point is i guess that the user gets a random low-level error if they access the data from a curvilinear data from a proxied file. 

For example `stars::st_downsample()`  (where the use case is much more clearer i guess) also throws the same error:
```` 
> stars::read_ncdf("curvilinear.nc", proxy=T, var="precip_g_rate") %>% stars::st_downsample(1)
No projection information found in nc file. 
 Coordinate variable units found to be degrees, 
 assuming WGS84 Lat/Lon.
for stars_proxy objects, downsampling only happens for dimensions x and y
Error in dims$start[dims$name == coord] <- which(coords[[coord]] == uc[[coord]][1]) : 
  replacement has length zero
````

**Comment by edzer** [comment]
I found one bug, but that gets you to the next,
```r
> stars::read_ncdf("curvilinear.nc", proxy=T, var="precip_g_rate") %>% stars::st_downsample(1)
No projection information found in nc file. 
 Coordinate variable units found to be degrees, 
 assuming WGS84 Lat/Lon.
for stars_proxy objects, downsampling only happens for dimensions x and y
Error in seq.default(dims$start[ic], length = dims$count[ic]) : 
  'from' must be a finite number
```
This code was written by @mdsumner and @dblodgett-usgs and I don't know how to fix it; You may have more luck with
```r
stars::read_stars("curvilinear.nc", proxy=T) %>% stars::st_downsample(1)
```

**Comment by iona5** [comment]
alright, thanks! :)

regarding the workaround: `read_stars()` with my rather large NetCDF files seemed to hang (killed after 10 minutes). stars::read_ncdf() with proxy=FALSE and subsequent st_downsample() is good enough for me for now because i have lots of RAM.
