### ISSUE TITLE
Return warning when assigning CRS

### ISSUE THREAD

**Issue by kadyb** [r-spatial/stars#587]
This is already done in `{sf}` and just added to `{terra}` (https://github.com/rspatial/terra/issues/897). Maybe `{stars}` should also return a warning when assigning CRS?

```r
library("sf")
f = system.file("shape/nc.shp", package = "sf")
nc = read_sf(f)
st_crs(nc) = "EPSG:4326"
#> Warning message:
#> st_crs<- : replacing crs does not reproject data; use st_transform for that 
```

**Comment by tsamsonov** [comment]
`st_warp() or st_transform()`? I've seen people (including myself) who `st_transform` their raster and then scratch their heads not understanding why projected `stars` object is plotted so slowly.

**Comment by edzer** [comment]
Yes, good point, had been thinking of that too.
