### ISSUE TITLE
st_as_stars(raster()) should inherit variable name

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/stars#59]
When `st_as_stars` is called on a `raster` object the dataset name is set to `raster`. It should imho inherit instead the variable that `raster` read, if there is any, which I believe is stored in `rasterobject@data@zvar`.

**Comment by edzer** [comment]
Not sure:
```r
> raster()@data@zvar
Error: no slot of name "zvar" for this object of class ".SingleLayerData"
```
I'll do this if you provide me the right information.

**Comment by adrfantini** [comment]
AFAIK all `raster`s that come from a netCDF file have that slot filled in with the variable that was read. However, not all `raster`s come from files which indicate the name of the variable, which is why that slot sometimes does not exist.
Might want to set it to `raster` whenever there is no slot, and the value of the slot otherwise. Or always `raster` for consistency, up to you. Feel free to close if this is the case.

**Comment by edzer** [comment]
S4 works differently: slots should always be there; also, they shouldn't be used directly outside the package. Does `raster` have a function to obtain the layer name(s)?

**Comment by adrfantini** [comment]
No, it does not, as far as i know at least.

**Comment by tim-salabim** [comment]
it has `names()`

**Comment by edzer** [comment]
I also now `adrop` the band dimension in case of single layer rasters.

**Comment by adrfantini** [comment]
`names()` gets the names of the layers, not of the variable that was read from the file. Try it on a 3D file.

**Comment by edzer** [comment]
So, we can't get this from a raster stack?

**Comment by adrfantini** [comment]
You can extract the name for each layer and check if they are all the same:
```R
s = stack('pr_1981010112-2005120112.nc')
sapply(1:nlayers(s), function(i) s[[i]]@data@zvar)
```
In this case:
```
"pr" "pr" "pr" "pr"
```

**Comment by mdsumner** [comment]
Any idea why this doesn't show the `@zvar`, but it's there?  (This confused me)

```R
s <- raster::stack(system.file("nc/reduced.nc", package = "stars"), varname = "err")
str(s@layers[[1]]@data)

s@layers[[1]]@data@zvar

```

**Comment by edzer** [comment]
I see
```r
> s@layers[[1]]@data@zvar
[1] "err"
```

**Comment by mdsumner** [comment]
I should have been more clear, why doesn't str show zvar? It doesn't for me

**Comment by edzer** [comment]
```r
> slotNames(s@layers[[1]]@data)
 [1] "values"     "offset"     "gain"       "inmemory"   "fromdisk"  
 [6] "isfactor"   "attributes" "haveminmax" "min"        "max"       
[11] "band"       "unit"       "names"     
> .hasSlot(s@layers[[1]]@data, "zvar")
[1] TRUE
```
puzzling -- I never really got S4.

**Comment by mdsumner** [comment]
Hmm, I happened to see in the show method for brick: 

```R
 attr(x@data, "zvar")
[1] "z"
x@data@zvar
[1] "z"
```

So, @thing is a S4 shortcut for attributes maybe  ...
