### ISSUE TITLE
geom_stars gives an Error: vector memory exhausted (limit reached?)

### ISSUE THREAD

**Issue by ManuelSpinola** [r-spatial/stars#592]
I am trying to make a map of a raster layer with geom_stars but I ran into an Error: vector memory exhausted (limit reached?)

If I use plot (stars) or geom_spatraster (terra) the map display as expected.

I am working in an IMac with Ventura (Intel, 32 GB of RAM) and R 4.2.2. 

When plotting with geom_stars I see an increase in memory used of more tan 10 GB which I don't understand.

```{r}
cr_s <- read_stars("lulc_cr_categorical.tif", proxy = TRUE) |>
  droplevels()
```

```{r}
object.size(cr_s)
```
9600 bytes

```{r}
ggplot() +
  geom_stars(data = cr_s, na.rm = TRUE)
```
Error: vector memory exhausted (limit reached?)

**Comment by edzer** [comment]
Your raster is probably too large to plot _completely_, you have to set a value for parameter `downsample` in `geom_stars`. I'll give it a thought how we can set this automatically to a useful value - ggplot2 doesn't give geoms any info about the size (in pixels) of the plot or facet, so it will remain a guess. `tidyterra::geom_spatraster` has a `maxcell` argument with 1e5 as default.
