### ISSUE TITLE
How to plot cube1.jpg cube2.jpg cube3.jpg?

### ISSUE THREAD

**Issue by tigerwang1998** [r-spatial/stars#594]
I want to create a diagram in my work.  
cube1/2/3.jpg is wonderful, but I don't know how to plot it in R. 
![image](https://user-images.githubusercontent.com/50581765/204128447-786e062b-582f-436b-9e61-3dc1464a70d9.png)
![image](https://user-images.githubusercontent.com/50581765/204128454-241f39f9-71f3-457f-bda1-9a07ee516bd9.png)
![image](https://user-images.githubusercontent.com/50581765/204128465-f3231937-b18e-4c72-aeab-dd420d4292c0.png)

**Comment by edzer** [comment]
See https://r-spatial.org/book/06-Cubes.html and open up the code sections; please do respect the copyright statements.

**Comment by tigerwang1998** [comment]
Of course I will respect the copyright statements! 
I promise I will quote them in my work and education PPT.
Thanks a lot!!!
