### ISSUE TITLE
Can't download Stars and Starsdata for R version 4.2.1 (2022-06-23)

### ISSUE THREAD

**Issue by SGREEN1994** [r-spatial/stars#598]
I'm trying to download the stars package to be able to use NetCDF files as an sf object. 
However the download fails no matter how I try to download it.

I've tried the following ways and recieved the following error messages:

>install.packages("stars", dependencies = TRUE)

Installing 'stars' ...
[1/3] Installing sf...
Installing package into ‘/Users/sofigreen/Library/R/arm64/4.2/library’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository http://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2:
  download from 'http://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/PACKAGES' failed
Package which is only available in source form, and may need
  compilation of C/C++/Fortran: ‘sf’
installing the source package ‘sf’

trying URL 'http://cran.rstudio.com/src/contrib/sf_1.0-9.tar.gz'
Content type 'application/x-gzip' length 3480774 bytes (3.3 MB)
====[2/3] Installing lwgeom...

downloaded 307 KB

Error in download.file(url, destfile, method, mode = "wb", ...) : 
  download from 'http://cran.rstudio.com/src/contrib/sf_1.0-9.tar.gz' failed
In addition: Warning messages:
1: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 315076 != reported length 3480774
2: In download.file(url, destfile, method, mode = "wb", ...) :
  URL 'http://cran.rstudio.com/src/contrib/sf_1.0-9.tar.gz': Timeout of 60 seconds was reached
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘sf’ failed
Installing package into ‘/Users/sofigreen/Library/R/arm64/4.2/library’
(as ‘lib’ is unspecified)
trying URL 'http://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/lwgeom_0.2-10.tgz'
Content type 'application/x-gzip' length 8374732 bytes (8.0 MB)
======[3/3] Installing stars...

downloaded 1001 KB

Error in download.file(url, destfile, method, mode = "wb", ...) : 
  download from 'http://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/lwgeom_0.2-10.tgz' failed
In addition: Warning messages:
1: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 1025168 != reported length 8374732
2: In download.file(url, destfile, method, mode = "wb", ...) :
  URL 'http://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/lwgeom_0.2-10.tgz': Timeout of 60 seconds was reached
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘lwgeom’ failed
Installing package into ‘/Users/sofigreen/Library/R/arm64/4.2/library’
(as ‘lib’ is unspecified)
also installing the dependencies ‘sf’, ‘lwgeom’

trying URL 'http://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/sf_1.0-9.tgz'
Content type 'application/x-gzip' length 89952912 bytes (85.8 MB)

downloaded 833 KB

Error in download.file(url, destfile, method, mode = "wb", ...) : 
  download from 'http://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/sf_1.0-9.tgz' failed
In addition: Warning messages:
1: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 853054 != reported length 89952912
2: In download.file(url, destfile, method, mode = "wb", ...) :
  URL 'http://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/sf_1.0-9.tgz': Timeout of 60 seconds was reached
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘sf’ failed
trying URL 'http://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/lwgeom_0.2-10.tgz'
Content type 'application/x-gzip' length 8374732 bytes (8.0 MB)
====
downloaded 698 KB

Error in download.file(url, destfile, method, mode = "wb", ...) : 
  download from 'http://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/lwgeom_0.2-10.tgz' failed
In addition: Warning messages:
1: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 715644 != reported length 8374732
2: In download.file(url, destfile, method, mode = "wb", ...) :
  URL 'http://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/lwgeom_0.2-10.tgz': Timeout of 60 seconds was reached
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘lwgeom’ failed
trying URL 'http://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/stars_0.6-0.tgz'
Content type 'application/x-gzip' length 4050752 bytes (3.9 MB)
====
downloaded 351 KB

Error in download.file(url, destfile, method, mode = "wb", ...) : 
  download from 'http://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/stars_0.6-0.tgz' failed
In addition: Warning messages:
1: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 359492 != reported length 4050752
2: In download.file(url, destfile, method, mode = "wb", ...) :
  URL 'http://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/stars_0.6-0.tgz': Timeout of 60 seconds was reached
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘stars’ failed

✔ Package 'stars' successfully installed.

And then won't find the package when called --> library(stars)

> devtools::install_github("https://github.com/r-spatial/stars.git")
Downloading GitHub repo r-spatial/stars@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/r-spatial/stars/tarball/HEAD' failed

> install.packages("starsdata", repos = "http://pebesma.staff.ifgi.de", type = "source")
Installing package into ‘/Users/sofigreen/Library/R/arm64/4.2/library’
(as ‘lib’ is unspecified)
trying URL 'http://pebesma.staff.ifgi.de/src/contrib/starsdata_0.0-1.tar.gz'
Content type 'application/x-gzip' length 1087830521 bytes (1037.4 MB)

downloaded 1.8 MB

Warning in install.packages :
  downloaded length 1884160 != reported length 1087830521
Warning in install.packages :
  URL 'https://pebesma.staff.ifgi.de/src/contrib/starsdata_0.0-1.tar.gz': Timeout of 60 seconds was reached
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  download from 'http://pebesma.staff.ifgi.de/src/contrib/starsdata_0.0-1.tar.gz' failed
Warning in install.packages :
  download of package ‘starsdata’ failed

> install.packages("stars", lib="/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library")
also installing the dependencies ‘sf’, ‘lwgeom’

trying URL 'http://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/sf_1.0-9.tgz'
Content type 'application/x-gzip' length 89952912 bytes (85.8 MB)

downloaded 1.0 MB

Warning in install.packages :
  downloaded length 1059044 != reported length 89952912
Warning in install.packages :
  URL 'http://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/sf_1.0-9.tgz': Timeout of 60 seconds was reached

Help please! 

Thanks

**Comment by edzer** [comment]
Set
```r
options(timeout = 60000)
```
before downloading packages.

**Comment by SGREEN1994** [comment]
> ```r
> options(timeout = 60000)
> ```

Thank you @edzer that worked!
