### ISSUE TITLE
Error in expand_dimensions.dimensions(d) :    cannot determine x and y coordinates without geotransform

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/stars#60]
Reading [this](https://drive.google.com/open?id=1YnrUnpydoNdMUUSJ_TrTh-nBxl693dik) small netCDF file seems to induce some problems. The file is a projected model which, as sometimes happens, contains no projection information whatsoever (but contains the lats and lons of the pixels). Still, it would be nice if `stars` could still deal with it even with no knowledge of geolocalization.
```R
(s = read_stars('test.nc'))
# stars object with 3 dimensions and 1 attribute
# attribute(s):
#    test.nc      
#  Min.   : 0.000  
#  1st Qu.: 1.171  
#  Median : 2.236  
#  Mean   : 2.840  
#  3rd Qu.: 3.961  
#  Max.   :92.606  
# dimension(s):
#     from  to              offset delta  refsys point values    
# x       1 424                  NA    NA      NA    NA   NULL [x]
# y       1 412                  NA    NA      NA    NA   NULL [y]
# time    1   1 2071-01-16 12:00:00    NA POSIXct    NA   NULL    
# affine parameters: NA NA 

s[1,,,]
# Error in expand_dimensions.dimensions(d) : 
#   cannot determine x and y coordinates without geotransform

plot(s)
# Error: length(gt) == 6 && !any(is.na(gt)) is not TRUE
```
Reading with `read_ncdf` does not help:
```R
s = read_ncdf('/dev/shm/test.nc')
#Error in nc$dim[[idobj$list_index]] : 
#  attempt to select more than one element in get1index <real>
```

**Comment by edzer** [comment]
The only way "out" I see here is to simply set `offset` to 0 and `delta` to 1 (-1 for y). This would be similar to what raster does.

**Comment by adrfantini** [comment]
Yes, I would think that for unknown dataset that would be a convenient default. Any major drawback?

**Comment by edzer** [comment]
This now works, without setting `offset` and `delta` to these, but assuming them when expanding dimensions:
![x](https://user-images.githubusercontent.com/520851/46748172-47c36480-ccb3-11e8-83b9-e3b5c82bec10.png)

**Comment by edzer** [comment]
(I didn't address the `read_ncdf` issue)

**Comment by adrfantini** [comment]
Beautiful.  Should I open another ticket for the `read_ncdf` issue?

**Comment by edzer** [comment]
If we (i.e., @mdsumner ) want to get that to work, yes, please.

**Comment by adrfantini** [comment]
Done in #64
