### ISSUE TITLE
inform hook of the current subplot?

### ISSUE THREAD

**Issue by btupper** [r-spatial/stars#600]
Hi,

I am wondering about ancillary plotting when plotting a multiband object using the `hook` argument.  As far as I can tell, there is no mechanism for the user-provided hook function to know which subplot is the current one.  In the example below, there doesn't seem to be a way to draw only the points associated with the current band.

I see that [terra](https://github.com/rspatial/terra/blob/dfe4edd765b90894d4a230e7a7a937d26a8aaa92/R/plot_raster.R#L630) passes one argument to the function that contains the index of the current subplot.  

I think something similar could be done in [stars](https://github.com/r-spatial/stars/blob/806bf22ab06424a811751cc57a95468e4daabb7f/R/plot.R#L178), but I am not sure of the unintended consequences (like backwards compatibility).

Are there any tricks to access the current subplot info?  Below is an example, where it would be nice to show only the points associated with each band.

I'm happy to make a pull request if it makes sense to do so.

Thanks,
Ben

``` r
suppressPackageStartupMessages({
  library(dplyr)
  library(sf)
  library(stars)
})

tif = system.file("tif/L7_ETMs.tif", package = "stars")
x = read_stars(tif)
xvals =  stars::st_get_dimension_values(x, which = 1)
yvals = stars::st_get_dimension_values(x, which = 2)
zvals = stars::st_get_dimension_values(x, which = 3)
nb = length(zvals)

pts <- dplyr::tibble(text = LETTERS[seq_len(nb)],
                     x = sample(xvals, nb, replace = FALSE),
                     y = sample(yvals, nb, replace = FALSE),
                     z = zvals) |>
  sf::st_as_sf(coords = c("x", "y", "z"), crs = sf::st_crs(x))

hook_fun <- function(){
  plot(pts['text'], add = TRUE, col = 'orange', pch = 16)
}

plot(x, hook = hook_fun)
#> downsample set to 1
```

![](https://i.imgur.com/kmFt5Aj.png)

``` r

sessionInfo()
#> R version 4.2.1 (2022-06-23)
#> Platform: x86_64-apple-darwin17.0 (64-bit)
#> Running under: macOS Big Sur ... 10.16
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRblas.0.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] stars_0.6-1  abind_1.4-5  sf_1.0-10    dplyr_1.0.10
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.9         pillar_1.8.1       compiler_4.2.1     highr_0.9         
#>  [5] class_7.3-20       tools_4.2.1        digest_0.6.30      evaluate_0.18     
#>  [9] lifecycle_1.0.3    tibble_3.1.8       pkgconfig_2.0.3    rlang_1.0.6       
#> [13] reprex_2.0.1       cli_3.4.1          DBI_1.1.3          rstudioapi_0.14   
#> [17] parallel_4.2.1     yaml_2.3.6         xfun_0.35          fastmap_1.1.0     
#> [21] e1071_1.7-12       withr_2.5.0        stringr_1.5.0      knitr_1.41        
#> [25] generics_0.1.3     fs_1.5.2           vctrs_0.5.1        grid_4.2.1        
#> [29] classInt_0.4-8     tidyselect_1.2.0   glue_1.6.2         R6_2.5.1          
#> [33] fansi_1.0.3        rmarkdown_2.18     magrittr_2.0.3     units_0.8-1       
#> [37] htmltools_0.5.3    assertthat_0.2.1   utf8_1.2.2         KernSmooth_2.23-20
#> [41] stringi_1.7.8      proxy_0.4-27       lwgeom_0.2-10
```

<sup>Created on 2022-12-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by edzer** [comment]
I think that's a great idea, and afaict it wouldn't break anything, as all examples of a hook function have no arguments. Rather than how `terra` does it, I would prefer named arguments, such that you can not only catch the panel number, but also e.g. the panel row and column, or even the panel title. Does that sound reasonable?

**Comment by edzer** [comment]
(Currently, the ugly solution would be to use global variables)

**Comment by btupper** [comment]
Yes, that does sounds very good.  Does that require that the hook function at least accept the dots argument `...`.  Like this?

```
my_hook_fun <- function(...){
 # something happens here
}
```

**Comment by edzer** [comment]
Yes, we could use the terra trick `is.null(formals(hook))` to detect `hook` has no arguments (and call it without), then call it with "all" parameters otherwise.

**Comment by edzer** [comment]
```r
hook2 = function(..., row, col, nr, value, bbox) {                                    
        str = paste("row:", row, "col:", col, "\nnr:", nr, "value:", value)           
        bbox |> st_as_sfc() |> st_centroid() |> st_coordinates() -> pt                
        text(pt[,"X"], pt[,"Y"], str, col = 'red', cex =2)                            
}                                                                                     
plot(x, hook = hook2)  
```
gives
![x](https://user-images.githubusercontent.com/520851/209857374-fd4e6c03-465e-4ce6-b7ce-575bb3320c4b.png)

**Comment by btupper** [comment]
This is terrific - thank you!
