### ISSUE TITLE
Synchronizing GDAL/GEOS/PROJ versions between machines

### ISSUE THREAD

**Issue by fgoerlich** [r-spatial/stars#601]
On a local Windows machine I have:
```
sf::sf_extSoftVersion()
          GEOS           GDAL         proj.4     GDAL_with_GEOS     USE_PROJ_H           PROJ 
         "3.9.3"       "3.5.2"       "8.2.1"             "true"         "true"         "8.2.1" 
```
On a remote Linux host I get:
```
sf::sf_extSoftVersion()
          GEOS           GDAL         proj.4      GDAL_with_GEOS     USE_PROJ_H           PROJ 
         "3.8.0"       "3.5.1"       "6.2.1"             "false"         "true"        "6.2.1" 
```
1) Whats the meaning of `GDAL_with_GEOS` `true`/`false`?
2) How may I synchronize `GDAL` / `GEOS` / `PROJ` versions between machines?
3) Do I have any control on Windows on the versions of `GDAL` / `GEOS` / `PROJ` that are installed?

Thanks a lot!

**Comment by edzer** [comment]
1. Whether the GDAL version used was linked against GEOS. (sf geometric measures/predicates/transformers don't need this as they call GEOS directly without GDAL in the middle; it may affect the `query` argument in `st_read` when formulating geometric predicates there, I haven't tried this out)
2. Install the libraries yourself, compile them from source (e.g. using rtools42), and install R packages from source linking against your libraries. Make sure that on linux you don't install any of these in addition to system installs, see [here](https://github.com/r-spatial/sf#multiple-gdal-geos-andor-proj-versions-on-your-system)
3. Yes, by following 2.

**Comment by fgoerlich** [comment]
1. Is there a way to switch `GDAL_with_GEOS` from / to `true` to / from `false` once installed?

**Comment by edzer** [comment]
> Is there a way to switch GDAL_with_GEOS from / to true to / from false once installed?

No. Does it affect your workflows?

**Comment by fgoerlich** [comment]
I have an script that runs perfectly on the Windows machine, but it gets hung up on the Linux host, and I´m trying to synchronize configurations.
Thanks a lot!
