### ISSUE TITLE
proposal for version of sampleRandom for stars

### ISSUE THREAD

**Issue by dmkaplan2000** [r-spatial/stars#602]
Hi,

I read in the raster=>stars mapping vignette that there is no stars equivalent to the sampleRandom function and that creating one is low priority. For something I am working on, I needed to make a stars equivalent of the sampleRandom function and thought I would share it in case that would be useful. My solution seems fairly generic and works in all the cases I have thrown at it, but I am not a huge user of stars.

If you want me to create a pull request adding this function to stars, I can do that, but given the simplicity of the function I thought I would run it by you first before doing so. If you want me to do a pull request, then let me know what you would like the canonical function name to be. Perhaps "st_sample_random"?

Cheers,
David

```r
sampleRandom_stars = function(x,size,return_coords=TRUE) {
  # If object just has one attribute, split bands if they exist
  if (length(x)==1 & length(dim(x))>2) {
    x = st_redimension(x,c(dim(x)[1:2],prod(dim(x)[-1:-2])))
    x = split(x)
  }
    
  
  d = dim(x)
  n = sample(1:prod(d[1:2]),size)
  
  r = lapply(names(x),function(xx) x[[xx]][n])
  r = do.call(cbind,r)
  colnames(r) = names(x)

  r = as.data.frame(r)
  
  if (return_coords) {
    X = rep(1:d[1],d[2])
    Y = rep(1:d[2],each=d[1])
    
    ll = st_coordinates(x)
    
    r = cbind(gid=n,xid=X[n],yid=Y[n],ll[n,],r)
  }
  
  return(r)
}
```

Some sample code to use it might be:

```r
library(stars)
x = array(1:(4*5*3*2),c(4,5,3,2))
s = st_as_stars(x)
dimnames(s) = c("x","y","band","depth")

sampleRandom_stars(s,5)


s2 = st_as_stars(matrix(1:(4*5),4))
s2$A2 = s2$A1

sampleRandom_stars(s2,5)
```

**Comment by dmkaplan2000** [comment]
Now that I understand better how stars works, I realize that this function is actually pretty useful. Random sampling is easiest by just converting to data frame and randomly selecting rows. Sorry for the bother. Perhaps this should be explained in the vignette about raster to stars conversion?

**Comment by kadyb** [comment]
There is also the `st_sample()` function, but it is very simple -- it works only for one attribute (sampling from all bands) and doesn't return coordinates.

```r
set.seed(1)
r = read_stars(system.file("tif/L7_ETMs.tif", package = "stars"))
dim(r)[[3]]
#> 6
st_sample(r, 10)
#> 103  64  67  53  13  64  50  66  42  72 # in sampleRandom() you would get 6 columns
```

**Comment by edzer** [comment]
`stars::st_sample.stars` samples cells randomly from the entire n-dimensional array. For spatial sampling, `sf::st_sample` can be used like this:
```r
library(stars)
# Loading required package: abind
# Loading required package: sf
# Linking to GEOS 3.11.1, GDAL 3.6.2, PROJ 9.1.1; sf_use_s2() is TRUE
r = read_stars(system.file("tif/L7_ETMs.tif", package = "stars"))
st_bbox(r) |> st_as_sfc() |> st_sample(6) -> pts
st_extract(r, pts) |> st_as_sf()
# Simple feature collection with 6 features and 6 fields
# Geometry type: POINT
# Dimension:     XY
# Bounding box:  xmin: 289986.6 ymin: 9111547 xmax: 297825.1 ymax: 9116878
# Projected CRS: SIRGAS 2000 / UTM zone 25S
#   L7_ETMs.tif.V1 L7_ETMs.tif.V2 L7_ETMs.tif.V3 L7_ETMs.tif.V4 L7_ETMs.tif.V5
# 1             73             60             60             74             97
# 2             81             72             70             69            101
# 3             98             89             62             13             14
# 4             70             56             56             46             85
# 5            105             93            104             71            112
# 6             66             52             46             57             53
#   L7_ETMs.tif.V6                 geometry
# 1             57 POINT (294667.4 9116539)
# 2             72 POINT (295026.3 9116878)
# 3             11 POINT (297825.1 9112979)
# 4             67 POINT (289986.6 9112579)
# 5             83 POINT (293461.2 9111547)
# 6             31 POINT (295849.9 9113727)
```

**Comment by dmkaplan2000** [comment]
The one thing about this solution is that I don't think we can easily control with and without replacement, correct? As the points are randomly assigned to an entire rectangle, you can have two within the same grid cell. The solution of converting to data.frame allows you to control this, but is undoubtedly slower.

**Comment by edzer** [comment]
I agree; maybe we can expand `st_sample.stars` such that it samples over a limited set of dimensions, and does that for all other dimensions? Not sure what would be a good approach.

**Comment by dmkaplan2000** [comment]
I must admit I get lost when we start talking about lots of dimensions and this may make `st_sample.stars` difficult to understand. But maybe I don't understand the use cases well enough to make a decision. It seems to me like the current behavior of sampling over all bands together at once is unlikely to be a useful option for many people.

**Comment by edzer** [comment]
I agree, but that might change if time is one of the dimensions.

**Comment by kadyb** [comment]
> As the points are randomly assigned to an entire rectangle, you can have two within the same grid cell.

For this one, we can also create a sequence from the bounding box every n meters, then sample and finally extract by points. But, I didn't check the performance.

```r
sample_stars = function(x, n, dist) {
  x_smp = seq(st_bbox(x)["xmin"], st_bbox(x)["xmax"], dist) |> sample(n, replace = TRUE)
  y_smp = seq(st_bbox(x)["ymin"], st_bbox(x)["ymax"], dist) |> sample(n, replace = TRUE)
  pts = data.frame(x = x_smp, y = y_smp) |> st_as_sf(coords = c("x", "y"), crs = st_crs(x))
  vals = st_extract(r, pts) |> st_as_sf()
  return(vals)
}

r = read_stars(system.file("tif/L7_ETMs.tif", package = "stars"))
pts = sample_stars(r, n = 10000, dist = 30)
```

It also seems to me that it would be better to return data frame with columns for each band instead of the combined values in single vector.

**Comment by kadyb** [comment]
> Also wouldn't the solution above only work for replace=TRUE? replace=FALSE seems to be the hard one to solve and for that I think you need to get a full list of all grid cells to select from. Perhaps we would want two different approaches, one quicker one that could be used with replace=TRUE and a slower one that would be used when replace=FALSE?

I think creating a list of all cells will be inefficient and requires much more memory than sampling with replacement from X and Y coordinate vectors. In the end, the result should be the same. Here is comparison:

```r
f1 = function(x, n, dist) {
  x_smp = sample(seq(x["xmin"], x["xmax"], dist), n, replace = TRUE)
  y_smp = sample(seq(x["ymin"], x["ymax"], dist), n, replace = TRUE)
  mat = cbind(x = x_smp, y = y_smp)
  return(mat)
}

f2 = function(x, n, dist) {
  seq1 = seq(x["xmin"], x["xmax"], dist)
  seq2 = seq(x["ymin"], x["ymax"], dist)
  mat = cbind(x = rep.int(seq1, length(seq2)),
              y = rep.int(seq2, rep.int(length(seq1), length(seq2))))
  mat = mat[sample(nrow(mat), n), ]
  return(mat)
}

x = c(xmin = 0, xmax = 500000, ymin = 0, ymax = 500000)
n = 200000
t = bench::mark(
  check = FALSE, iterations = 5,
  f1 = f1(x, n, dist = 30),
  f2 = f2(x, n, dist = 30)
)
t[, 1:5]
#>   expression      min   median `itr/sec` mem_alloc
#> 1 f1          25.68ms  25.75ms    37.9       8.5MB
#> 2 f2            1.99s    2.17s     0.468    4.29GB
```

> Also, in the solution above, couldn't you use calls to st_get_dimension_values to get the list of possible x and y values and then select from those instead of using the sequence over the bounding box?

I think so. It probably doesn't matter much in terms of performance, but the coordinates may be a little different.

**Comment by kadyb** [comment]
It would be great to finally implement this (my students have asked 😄). What do you think @edzer about the function below?

```r
st_sample.stars = function(x, n, dist = st_res(x)) {
  if (length(x) > 1) warning("only sampling the first attribute")
  if (length(dist) == 1) dist = c(dist, dist)
  x_smp = sample(seq(st_bbox(x)["xmin"], st_bbox(x)["xmax"], dist[1]), n, replace = TRUE)
  y_smp = sample(seq(st_bbox(x)["ymin"], st_bbox(x)["ymax"], dist[2]), n, replace = TRUE)
  pts = cbind(x = x_smp, y = y_smp)
  vals = st_extract(x, pts)
  vals = st_as_sf(data.frame(pts, vals), coords = c("x", "y"), crs = st_crs(x))
  return(vals)
}
```
