### ISSUE TITLE
Is there any way that I can do cloud masking using SCL file of Sentinel-2

### ISSUE THREAD

**Issue by monasound** [r-spatial/stars#610]
I am following you code in the post https://r-spatial.org/r/2018/03/23/stars3.html to create a database of Sentinel-2 images of region of interest.  Your code helps me to read the zipped sentinel-2 file and return only interested bands and stack all in to one file. I am wondering is there is any way that I can mask the cloud using SCL.jp2 and apply on the interested bands? Please let me know. Thank you for your time and looking forward to your comments.

**Comment by kadyb** [comment]
You can replace the values with NAs in the spectral bands based on the classification mask using `ifelse()`:

```r
library("stars")

# S2A_MSIL2A_20220922T100031_N0400_R122_T33UXU_20220922T174559.SAFE
red = "T33UXU_20220922T100031_B04_20m.jp2"
green = "T33UXU_20220922T100031_B03_20m.jp2"
blue = "T33UXU_20220922T100031_B02_20m.jp2"
files = c(red, green, blue)

r = read_stars(files, along = 3, proxy = FALSE)
r[[1]] = as.integer(r[[1]])
mask = read_stars("T33UXU_20220922T100031_SCL_20m.jp2", proxy = FALSE)
mask[[1]] = as.integer(mask[[1]])

# mask cloud shadows (3) and clouds (8, 9)
id_mask = c(3, 8, 9)
r[[1]] = ifelse(mask[[1]] %in% id_mask, NA, r[[1]])
plot(r)
```

**Comment by monasound** [comment]
Hi Kadyb, Thank you for your insight. I could mask the files now.
