### ISSUE TITLE
Overhead when loading online file

### ISSUE THREAD

**Issue by kadyb** [r-spatial/stars#612]
I tested this on WiFi, so there may be significant differences, but it seems there is some overhead when loading online files using `stars::read_stars()`. Downloading file using `download.file()` and then loading works faster.

```r
library("terra") # 1.7.3
library("stars")

## Example 1
url = "https://download.osgeo.org/geotiff/samples/usgs/c41078a1.tif"
tmp = tempfile(fileext = ".tif")
system.time(terra::rast(url)) #> 6.35
system.time(read_stars(url, proxy = TRUE)) #> 30.72

system.time(download.file(url, tmp, mode = "wb")) #> 4.37 
system.time(read_stars(tmp, proxy = FALSE)) #> 4.77

## Example 2 (doesn't work on Linux)
url = "https://opendata.geoportal.gov.pl/ortofotomapa/75106/75106_1051955_N-33-130-D-b-2-3.tif"
tmp = tempfile(fileext = ".tif")
system.time(terra::rast(url)) #> 9.83
system.time(read_stars(url, proxy = TRUE)) #> 43.95

system.time(download.file(url, tmp, mode = "wb")) #> 8.56
system.time(read_stars(tmp, proxy = FALSE)) #> 2.69
```

**Comment by edzer** [comment]
`terra` glues `/vsicurl/` in front of the URL, `stars` doesn't:
```r
library(stars)
# Loading required package: abind
# Loading required package: sf
# Linking to GEOS 3.11.1, GDAL 3.6.2, PROJ 9.1.1; sf_use_s2() is TRUE
url = "/vsicurl/https://download.osgeo.org/geotiff/samples/usgs/c41078a1.tif"

system.time(r <- read_stars(url, proxy = TRUE, curvilinear = character(0)))
#    user  system elapsed 
#   0.119   0.002   1.744 
system.time(r <- read_stars(url, proxy = TRUE))
#    user  system elapsed 
#   0.018   0.008   6.378 
system.time(o <- terra::rast(url))
# allowed_drivers: 
#    user  system elapsed 
#   2.289   0.015   2.304 
```
not setting `curvilinear = character(0)` makes `stars` calling `gdal_metadata()`, to figure out whether we have a curvilinear raster (not supported by terra).

**Comment by kadyb** [comment]
> terra glues /vsicurl/ in front of the URL, stars doesn't:

Isn't this feature available in the development version (https://github.com/rspatial/terra/commit/65f58c1d9452bba571670e8948619c50800adcff)? I tested on stable 1.7.3.

What in case the server doesn't support range requests, so we can't use `/vsicurl/`? In this case I see similar timings as in the first post (despite the use of `curvilinear = character(0)`).

**Comment by edzer** [comment]
Where did you find that `/vsicurl/` has anything to do with servers supporting range requests?

**Comment by kadyb** [comment]
https://github.com/OSGeo/gdal/blob/b302f21843605aa64049e4d7c2b71e2ecb2f88fc/port/cpl_vsil_curl.cpp#L1809

**Comment by edzer** [comment]
Oh well. Should we worry?

**Comment by kadyb** [comment]
Generally, I think no. In Poland, we have problem that the main cartographic institution provides several TB of data and it is necessary to download them (`/vsicurl/` doesn't work). Personally, I think this problem should be solved by the data provider.

But if you are asking about the difference in loading speed between `{stars}` and `{terra}` / `{raster}` then I think it is worth improving, as long as it's easy and you have the time ;)
