### ISSUE TITLE
`!is.na(r)` (where `r` is a `stars` object) not working

### ISSUE THREAD

**Issue by michaeldorman** [r-spatial/stars#615]
Seems like one of the `stars` updates made it impossible to assign values to all non-`NA` “pixels” in a `stars` object. Specifically, an expression such as `!is.na(r)` now produces an error, rather than a `logical` raster with non-`NA` pixels marked.

Here is a reproducible example:

``` r
library(stars)
r = read_stars(system.file("tif/L7_ETMs.tif", package = "stars"))
r = r[,,,1,drop=TRUE]
r[[1]][10:100, 10:100] = NA
r[!is.na(r)] = 1
```

    ## Error in inherits(e2, "stars"): argument "e2" is missing, with no default

Thank you very much!

Session information:

``` r
sessionInfo()
```

    ## R version 4.2.1 (2022-06-23)
    ## Platform: x86_64-pc-linux-gnu (64-bit)
    ## Running under: Ubuntu 22.04.2 LTS
    ## 
    ## Matrix products: default
    ## BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0
    ## LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0
    ## 
    ## locale:
    ##  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
    ##  [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
    ##  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
    ## [10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
    ## 
    ## attached base packages:
    ## [1] stats     graphics  grDevices utils     datasets  methods   base     
    ## 
    ## other attached packages:
    ## [1] stars_0.6-0 sf_1.0-9    abind_1.4-5
    ## 
    ## loaded via a namespace (and not attached):
    ##  [1] Rcpp_1.0.9.5       pillar_1.7.0       compiler_4.2.1     class_7.3-20      
    ##  [5] tools_4.2.1        digest_0.6.29      evaluate_0.15      lifecycle_1.0.3   
    ##  [9] tibble_3.1.7       pkgconfig_2.0.3    rlang_1.0.6        DBI_1.1.2         
    ## [13] cli_3.5.0          yaml_2.3.5         parallel_4.2.1     xfun_0.30         
    ## [17] fastmap_1.1.0      e1071_1.7-9        stringr_1.4.0      dplyr_1.0.9       
    ## [21] knitr_1.39         generics_0.1.2     vctrs_0.5.1        classInt_0.4-3    
    ## [25] grid_4.2.1         tidyselect_1.1.2   glue_1.6.2         R6_2.5.1          
    ## [29] fansi_1.0.3        rmarkdown_2.14     purrr_0.3.4        magrittr_2.0.3    
    ## [33] ellipsis_0.3.2     htmltools_0.5.4    units_0.8-0        utf8_1.2.2        
    ## [37] KernSmooth_2.23-20 stringi_1.7.6      proxy_0.4-26       lwgeom_0.2-8      
    ## [41] crayon_1.5.1

**Comment by edzer** [comment]
Thanks, Michael!
