### ISSUE TITLE
Support for many legends

### ISSUE THREAD

**Issue by kadyb** [r-spatial/stars#616]
`{terra}` and `{raster}` support plotting rasters with multiple legends. It would be great to add such feature to `{stars}` too.

```r
library("stars")
library("terra")

tif = system.file("tif/L7_ETMs.tif", package = "stars")
r1 = read_stars(tif)
plot(r1)
```

![1](https://user-images.githubusercontent.com/35004826/223278609-f481b210-63ea-4b50-8999-3e792ee341ec.png)

```r
r2 = rast(tif)
plot(r2)
```

![2](https://user-images.githubusercontent.com/35004826/223278648-a134428c-7d95-4c05-acbd-95c405c09a2a.png)

**Comment by kadyb** [comment]
And it seems that `par(mfrow())` and `layout()` don't work in this case as workaround?

```r
r1 = read_stars(system.file("tif/L7_ETMs.tif", package = "stars"))
r1 = split(r1)

# par(mfrow = c(3, 3))
# layout(matrix(c(1:6), 2, 3, byrow = TRUE))

for (i in seq_along(var)) {
  plot(r1[i], reset = FALSE)
}
```

**Comment by edzer** [comment]
I don't like such plots very much because of all the white space and the boxes; I think I would go for creating ggplot subplots and arranging those, wouldn't that look better?

**Comment by kadyb** [comment]
By arranging do you mean using `cowplot` or `patchwork`?

**Comment by edzer** [comment]
Yes. Or even do this downstream, in LaTeX or LibreOffice or so. They're just subplots, sharing nothing.

**Comment by kadyb** [comment]
Ok, I will try!
