### ISSUE TITLE
Error: 'st_crop' is not an exported object from 'namespace:stars

### ISSUE THREAD

**Issue by ang-ita** [r-spatial/stars#622]
I am trying to crop and mask a stars object based on a studyarea (sf object) 
If I do not call stars:: before st_crop  the function is extremely slow and I suspect that it's because it may call the relative sf function .. but 
However if I do call stars before st_crop I am getting the following error 

    

> Error: 'st_crop' is not an exported object from 'namespace:stars'

This is my code 

`preds_cut <- stars::st_crop(x=predictors, y=studyarea, crop=FALSE)`

**Comment by edzer** [comment]
No, it's an exported object from `namespace:sf`. You're calling a generic, so omit the `stars::` in your call and you should be fine.

**Comment by ang-ita** [comment]
@edzer if I use it without stars it's extremely slow and  I suspect that it may be due to the fact that there's a similar function in sf

**Comment by edzer** [comment]
If `y` is of class `stars` and you're leaving out the `stars::`, you are still using the `stars` method for `st_crop`, from package `stars`. The generic for `st_crop` however is (only defined) in `sf`.

**Comment by ang-ita** [comment]
y is a sf object .. but if I am running  the following code the function is still extremely slow which is weird given that stars is supposed to be 26 times faster than raster 


preds_cut <-st_crop(x=predictors, y=st_as_stars(studyarea), crop=FALSE)

**Comment by edzer** [comment]
> If y is of class stars and

Ah, apologies, I meant to say "if `x` is of class `stars`..."
