### ISSUE TITLE
st_extract with large netcdf object on OpenDAP server

### ISSUE THREAD

**Issue by dmkaplan2000** [r-spatial/stars#624]
Hi,

I am trying to extract data from a large netcdf file that is accessible via an OpenDAP server (specifically one of the datasets here: https://data.marine.copernicus.eu/products, but I think the question is more general). `st_extract` with a stars proxy object would seem to be the ticket, but I cannot get the proxy object to work with an OpenDAP URL and `read_ncdf` does not seem to work with proxy objects. 

Do you have any suggestions for the best way to attack this problem with the `stars` package?

Thanks,
David

**Comment by edzer** [comment]
Possibly, maybe also `read_mdim()`. Could you share what you tried so far?

**Comment by dmkaplan2000** [comment]
I haven't tried much. So far I have mainly been trying to open the data without things freezing or behaving strangely. I got `stars::read_ncdf` to read in a small subset of the dataset, but the whole dataset is way to large. When I tried `read_stars`, it had the following error:

```r
arning: GDAL Error 1: An error occurred while creating a virtual connection to the DAP server:transfer closed with outstanding read data remainingWarning: GDAL Error 1: An error occurred while creating a virtual connection to the DAP server:transfer closed with outstanding read data remainingWarning: GDAL Error 1: An error occurred while creating a virtual connection to the DAP server:transfer closed with outstanding read data remainingtrying to read file: https://USERNAME:PASSWORD@my.cmems-du.eu/thredds/dodsC/cmems_mod_glo_bgc_my_0.25_P1D-m?longitude[872:1:1063],latitude[230:1:386],depth[0:1:31],time[6574:1:6575],nppv[6574:1:9497][0:1:31][230:1:386][872:1:1063]
Error: file not found
```

Perhaps copernicus doesn't like me doing so many read?

I also tried `read_mdim`, but it complains that I need a newer version of GDAL. Updating to a newer version of GDAL is probably a larger project than I want to take on right now (I am using Linux and would need to get the repositories right and update GDAL and everything else that depends on it...).

**Comment by edzer** [comment]
Which version of `sf` do you have installed, and what does `sf::sf_extSoftVersion()` give as output? Which data source do you try to read?

**Comment by dmkaplan2000** [comment]
For `sf`:

```
> sf::sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H           PROJ 
       "3.8.0"        "3.0.4"        "6.3.1"         "true"         "true"        "6.3.1" 
```

I am trying to read this data source (among others):

```
https://USERNAME:PASSWORD@my.cmems-du.eu/thredds/dodsC/cmems_mod_glo_bgc_my_0.25_P1D-m?longitude[872:1:1063],latitude[230:1:386],depth[0:1:31],time[6574:1:6575],nppv[6574:1:9497][0:1:31][230:1:386][872:1:1063]
```

The dimension restrictions on the URL are just to try to make things quicker. But ideally, I wouldn't have to do that and just let st_extract figure it out using a proxy object to keep from downloading the whole thing...
