### ISSUE TITLE
How to work with single bands of a multiband image?

### ISSUE THREAD

**Issue by gilbertocamara** [r-spatial/stars#626]
Hi @edzer 

I have a multiband image and I am trying to process each band independently. However, I am at a loss to find out how to do so.
Please see the following MWE

```{r}
image_path <- "https://www.dropbox.com/s/az9oxl1tcw1mz84/SENTINEL-2_MSI_20LLQ_2020-06-04_2021-08-26_variance_v1.tif?dl=1"

# read image using stars
image_st <- stars::read_stars( image_path, proxy = FALSE)
# set the labels
labels <- c("Water", "ClearCut_Burn", "ClearCut_Soil", "ClearCut_Veg",
            "Forest", "Wetlands")
names(labels) <- seq_along(labels)

# rename stars object dimensions to labels
image_st <- stars::st_set_dimensions(image_st, "band", values = labels)
```
The following command, which processes all pixels of all bands, works fine.
```{r}
scale <- 0.01
image_st <- image_st * scale
```
I can acess the an image subset, but not process it. The following commands work.

```{r}
image_st[,,,"Water"] 
image_st[,,,"Water"] > 5.0
```
My problem is that I want to process each band independently and the following command does not work.
```{r}
scale <- 0.01
image_st[,,,"Water"] <- image_st[,,,"Water"]  * scale
```
What is the correct way to process individual bands in a `stars` image?

Many thanks,
Gilberto

**Comment by edzer** [comment]
Yes, that was also my first thought: use the fact that `image_st[[1]]` is an R array. The alternative (using labels) could split the array into a set of 6 2-dimensional arrays:
```r
image_spl = split(image_st)
image_spl[["Water"]] = image_spl[["Water"]] * scale                                   
```
and if needed merge again by
```r
merge(image_spl)
```
This works at the same level: `[[` extracts the array, `[[<-` replaces it.

**Comment by gilbertocamara** [comment]
Thanks, @edzer, works!

**Comment by edzer** [comment]
Great idea!
