### ISSUE TITLE
Summary functions for st_rasterize

### ISSUE THREAD

**Issue by samuelVJrobinson** [r-spatial/stars#629]
I'm trying to create a stars object from a spatial point dataset, where some field from the point values is summarized into the resulting raster cells. Here's a simple example:

```
library(tidyverse)
library(sf)
library(stars)

#Make data
N <- 1000
dat <- data.frame(x=runif(N,-10,10),y=runif(N,-10,10),a=rgamma(N,1,1)) %>% 
  st_as_sf(coords=c('x','y')) %>% st_set_crs(4326)

#2 x 2 grid for rasterization
grd <- st_as_stars(st_bbox(dat), dx = 2, dy = 2)
x <- st_rasterize(dat,grd)
plot(x)
```

This is summarizing the point values within each grid cell, but what is the summary statistic being returned? Is there a way to get `st_rasterize` to use a different summary function (e.g. `sd`, `median`), as can be done in `raster::rasterize`, or am I approaching this the wrong way? 

This is similar to the issue seen [here](https://gis.stackexchange.com/questions/432367/how-to-apply-mean-min-max-merge-functions-on-a-vector-layer-to-create-a-stars-ra) on StackExchange.

**Comment by kadyb** [comment]
Maybe do some aggregation at the vector level, and then convert the vector to raster? In this way:

```r
grd_vec = st_as_sf(grd)
agg = aggregate(dat, grd_vec, FUN = median)
x = st_as_stars(agg)
```

I suspect that there may be problem if there are no points in some cell, but this can be filtered beforehand.

**Comment by samuelVJrobinson** [comment]
That works just fine. I'll use that for my workflow in the future.
