### ISSUE TITLE
support for writing to GDAL virtual filesystems?

### ISSUE THREAD

**Issue by cboettig** [r-spatial/stars#631]
Does stars support writing rasters (or vectors for that matter) directly to GDAL virtual file systems?  This works really nicely in `sf` with vector objects, but my attempts to write rasters with comparable `/vsis3/` paths keep hitting an error "creating dataset failed":

```
5. | stop(structure(list(message = "creating dataset failed", call = NULL, cppstack = structure(list(file = "", line = -1L, stack = c("/home/cboettig/R/x86_64-pc-linux-gnu-library/4.3/sf/libs/sf.so(Rcpp::exception::exception(char const*, bool)+0x9a) [0x7fcb3b01702a]", "/home/cboettig/R/x86_64-pc-linux-gnu-library/4.3/sf/libs/sf.so(void Rcpp::stop<>(char const*)+0x4f) [0x7fcb3aff1274]", "/home/cboettig/R/x86_64-pc-linux-gnu-library/4.3/sf/libs/sf.so(+0x3b8bd) [0x7fcb3affc8bd]", ...
-- | --
```

any ideas?  

Not sure how best to create a copy-paste reproducible example, but I'm using MINIO to create a local S3 bucket system I can write to.  After setting env vars appropriately following the GDAL VSI docs,

```r
Sys.setenv("AWS_ACCESS_KEY_ID"="xxx") 
Sys.setenv("AWS_SECRET_ACCESS_KEY"="xxx")
Sys.setenv("AWS_S3_ENDPOINT"="localhost:9001")
Sys.setenv("AWS_HTTPS"="FALSE")
Sys.setenv("AWS_VIRTUAL_HOSTING"="FALSE")
```

I can write `sf` style objects to buckets I created there no problem by using the `/vsis3/` prefix on my paths, like so:

```r
sf::st_write(test_sf_object, "/vsis3/test_bucket/test.fgb", "FlatGeobuf")
```

but no luck with stars objects: 

```r
tif = system.file("tif/L7_ETMs.tif", package = "stars")
(x1 = read_stars(tif))
stars::write_stars(x1, "/vsis3/test_bucket/test.tif")
```

**Comment by edzer** [comment]
These things are not impossible but cumbersome to try out. Please try if it works with e.g. the command line utility `gdal_translate` (alternatively, less preferred, `sf::gdal_utils("translate",..)` - if that is the case, it should work with `write_stars` IMO.

**Comment by cboettig** [comment]
Thanks @edzer , :100:.  I was able to reproduce the error on the cli utility, which throws the very helpful error

```
ERROR 1: w+ not supported for /vsis3, unless CPL_VSIL_USE_TEMP_FILE_FOR_RANDOM_WRITE is set to YES
```

Once I set  this env var and it works perfectly in `stars`.  Thanks again for all the great software and great support!
