### ISSUE TITLE
Mapping `terra` to `stars` seems to miss attributes / layers

### ISSUE THREAD

**Issue by Martin-Jung** [r-spatial/stars#634]
I am using both the `terra` and `stars` packages in a R-package. Having recently transitioned from `raster` to `terra` i am trying to map all the different functions to allow seemless data exchange between the packages. 

I am running in some unexpected issues when converting between the objects ( using `st_as_stars` ) when there is only a single (or multiple) time dimension.

**Some example code:**
```
library(terra)
library(stars)

# Create a dummy raster
ras <- c(
  rast(nrows=100, ncols=100, xmin=0, xmax=10, vals = rnorm(10000,2)),
  rast(nrows=100, ncols=100, xmin=0, xmax=10, vals = rpois(10000,2)),
  rast(nrows=100, ncols=100, xmin=0, xmax=10, vals = rpois(10000,.1))
)
names(ras) <- c("cov1", "cov2", "cov3")
# Set time dimension
terra::time(ras) <- rep(as.Date("2015-01-01"), 3)

new <- stars::st_as_stars(ras)
# Only 1 attribute gets mapped
```

In this case I would expect the new object to have 3 attributes and 1 single entry in the time/band dimension (for the year 2015). However instead cov2 and cov3 are ignored. 
Am I missing some parameter in `st_as_stars` or is there a different way to map SpatRaster objects to stars?

**Comment by edzer** [comment]
If they would be put in three attributes in a `stars` object, the time information would be lost. They get put as three "layers" of a 3-D cube in a time dimension, where the time reference is stored. Try
```r
plot(new)
```
Then, `split(new)` distributes them over three attributes that have time label as their name (which is, IMO, not very useful, but may help).

**Comment by edzer** [comment]
I see what you mean. However the `terra` object stores a time stamp for each layer, not a single time stamp for the three layers. If it would do that then you could argue on the `stars` side that it has a time dimension with singular cardinality. But it doesn't do that. From `SpatRaster` objects you can't tell whether whether layers should be mapped into distinct `stars` attributes or into some third dimension, would you agree?

**Comment by Martin-Jung** [comment]
Agree, whether something is distinct or not might not be known. Ok, I will continue with my workaround for this kind of data format.
Thanks and sorry for using issues as discussion ground.

**Comment by edzer** [comment]
No need to apologize, your issue cleared things up for me.
