### ISSUE TITLE
Implement `levels` argument in `plot()`

### ISSUE THREAD

**Issue by kadyb** [r-spatial/stars#639]
In `{terra}` there is `levels` argument in [plot()](https://rspatial.github.io/terra/reference/plot.html#arguments-1) to change labels in legend, but there is no such thing in `{stars}`?

**Comment by edzer** [comment]
Isn't there a `levels<-` method to change levels?

**Comment by kadyb** [comment]
Yeah, but I have a numeric raster and my concern is that the conversion from numeric to factor takes a relatively long time compared to plotting. However, it is not big problem, so we can close this issue.

```r
library("stars")

v = rep(1:10, each = 10000000) # 10000 x 10000 cells
bbox = st_bbox(c(xmin = 0, xmax = 1, ymin = 0, ymax = 1))
r = st_as_stars(bbox, nx = 10000, ny = 10000, values = v)

system.time({plot(r)})
#> user  system elapsed
#> 1.52    0.30    1.82

system.time({
  r[[1]] = factor(r[[1]], labels = letters[1:10])
})
#> user  system elapsed
#> 4.69    0.33    5.03
```
