### ISSUE TITLE
read_ncdf error: attempt to select more than one element in get1index <real>

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/stars#64]
When reading [this](https://drive.google.com/open?id=1YnrUnpydoNdMUUSJ_TrTh-nBxl693dik) small file with `read_ncdf`, I am getting the following error:
```R
s = read_ncdf('/dev/shm/test.nc')
#Error in nc$dim[[idobj$list_index]] : 
#  attempt to select more than one element in get1index <real>
```

This was initially reported in #60 .

**Comment by mdsumner** [comment]
Can you try with https://github.com/r-spatial/stars/pull/61 ?

**Comment by adrfantini** [comment]
Mh, how do I do that? Seems to be not merged right now and not installable with `devtools`:
```R
> devtools::install_github('r-spatial/stars@mike-ncdf-001')
Downloading GitHub repo r-spatial/stars@mike-ncdf-001
from URL https://api.github.com/repos/r-spatial/stars/zipball/mike-ncdf-001
Installation failed: 404: Not Found
 (404)
```

**Comment by mdsumner** [comment]
Probably check out the repo and switch branches then build locally, I don't know that PRs present like branches do in this way (but I'd like to know).

**Comment by mdsumner** [comment]
At any rate I'm pretty sure this makes it work, but I'm not across the rest of changes since, or plotting this

**Comment by tim-salabim** [comment]
try `devtools::install_github('mdsumner/stars@mike-ncdf-001')`

**Comment by mdsumner** [comment]
oh!  (thanks ...) :)

**Comment by adrfantini** [comment]
Works using Mike's branch!

**Comment by edzer** [comment]
PR?

**Comment by mdsumner** [comment]
Are you not getting notified of updates? (I've been meaning to check ) This had an egregious oversight, now hopefully fixed!    https://github.com/r-spatial/stars/pull/66

**Comment by edzer** [comment]
Sorry, my mistake.
