### ISSUE TITLE
c.stars function with a single stars object

### ISSUE THREAD

**Issue by jaehyunjoo** [r-spatial/stars#646]
Dear @edzer, 

Thanks for the great package. I started to use this package to process spatial data summarized at certain time windows. 
Since I download data sequentially via API with `mapply`, I wrote a script that returns a named list of stars objects (identical dims) where its names represent the objects' time stamps.  I combine this list as a single stars object using `c.stars`  with 'along' argument so that the new dimension stores the time values. 

```r
library(stars)
tif <- system.file("tif/L7_ETMs.tif", package = "stars")
x <- read_stars(tif)
dl <- list(Jan = x, Feb = x, Mar = x)
y <- do.call(c, c(dl, along = "month"))
> y
stars object with 4 dimensions and 1 attribute
attribute(s), summary of first 1e+05 cells:
             Min. 1st Qu. Median    Mean 3rd Qu. Max.
L7_ETMs.tif    47      65     76 77.3419      87  255
dimension(s):
      from  to  offset delta                     refsys point        values x/y
x        1 349  288776  28.5 SIRGAS 2000 / UTM zone 25S FALSE          NULL [x]
y        1 352 9120761 -28.5 SIRGAS 2000 / UTM zone 25S FALSE          NULL [y]
band     1   6      NA    NA                         NA    NA          NULL    
month    1   3      NA    NA                         NA    NA Jan, Feb, Mar    
```

Unfortunately, data are not available at some time points like below

```r
z <- do.call(c, c(list(Apr = x, May = NULL), along = "month"))
> z
stars object with 3 dimensions and 1 attribute
attribute(s):
             Min. 1st Qu. Median     Mean 3rd Qu. Max.
L7_ETMs.tif     1      54     69 68.91242      86  255
dimension(s):
     from  to  offset delta                     refsys point x/y
x       1 349  288776  28.5 SIRGAS 2000 / UTM zone 25S FALSE [x]
y       1 352 9120761 -28.5 SIRGAS 2000 / UTM zone 25S FALSE [y]
band    1   6      NA    NA                         NA    NA    
```

Since new data `z` does not have 'month' dimension, it is not easy to combine it with the existing data `y`. Also, it accidentally lost information that we got data for April but not for May.

```r
# fail due to dimension mismatch
c(y, z)

# My inefficient way 
yy <- st_redimension(c(split(y), setNames(z, "Apr")), name = "month")
yy <- setNames(yy, names(y))
> yy
stars object with 4 dimensions and 1 attribute
attribute(s), summary of first 1e+05 cells:
             Min. 1st Qu. Median    Mean 3rd Qu. Max.
L7_ETMs.tif    47      65     76 77.3419      87  255
dimension(s):
      from  to  offset delta                     refsys point      values x/y
x        1 349  288776  28.5 SIRGAS 2000 / UTM zone 25S FALSE        NULL [x]
y        1 352 9120761 -28.5 SIRGAS 2000 / UTM zone 25S FALSE        NULL [y]
band     1   6      NA    NA                         NA    NA        NULL    
month    1   4      NA    NA                         NA    NA Jan,...,Apr    
```

I checked the source code of `c.stars` and if the length of '...' is 1, it just returns the input as is, which seems reasonable as a new dimension would be redundant. However, I feel such redundancy can be useful sometimes. I am wondering whether we can have a redundant dimension when a user sets 'along' argument explicitly. It may be achieved by changing (`if (length(dots) == 1) dots[[1]]` -> `if (length(dots) == 1 && is.na(along)) dots[[1]]` in the source code.  I was not able to find an easy way to add a dimension using stars' exported functions for my use case. 

```r
#  very clumsy; hope c(x, along = "month") does the same thing 
x.m <- c(x, x, along = list("month" = c("Apr", "dummy")))[, , , , "Apr"]
stars object with 4 dimensions and 1 attribute
attribute(s):
             Min. 1st Qu. Median     Mean 3rd Qu. Max.
L7_ETMs.tif     1      54     69 68.91242      86  255
dimension(s):
      from  to  offset delta                     refsys point values x/y
x        1 349  288776  28.5 SIRGAS 2000 / UTM zone 25S FALSE   NULL [x]
y        1 352 9120761 -28.5 SIRGAS 2000 / UTM zone 25S FALSE   NULL [y]
band     1   6      NA    NA                         NA    NA   NULL    
month    1   1      NA    NA                         NA    NA    Apr    
```

Maybe I am the only one who thinks this feature is necessary. If you think this is not useful, please close the issue. 

BTW, I found an inconsistent behavior of `c.stars` when `NULL` is involved. 
```r
c(x, NULL) # this returns a star object
c(NULL, x) # this returns a ugly list
```
Again, thanks for your time and support!

**Comment by edzer** [comment]
As of your last comment, there is little a package can do; try
```r
c(NULL, Sys.Date())
```

**Comment by edzer** [comment]
> Also, it accidentally lost information that we got data for April but not for May.

I think that is intentional, the (dense) arrays `stars` deals with do not have a "missing" slot for a slice that has no data. The closest to representing that, IMO, is to add that slice after assigning it `NA` values.

**Comment by edzer** [comment]
I think this addresses your issue. Thanks, btw, great explanation.

**Comment by jaehyunjoo** [comment]
Wow! That is so quick! Thanks a bunch! I really appreciate your kind explanations and help!
