### ISSUE TITLE
Warning message in reading a raster object

### ISSUE THREAD

**Issue by fgoerlich** [r-spatial/stars#649]
In reading a raster object (tif file) in `stars` I get the following messge:
```
Warning messages:
1: In CPL_get_metadata(file, NA_character_, options) :
  GDAL Message 1: The definition of geographic CRS EPSG:4258 got from GeoTIFF keys is not the same as the one from the EPSG registry, which may cause issues during reprojection operations. Set GTIFF_SRS_SOURCE configuration option to EPSG to use official parameters (overriding the ones from GeoTIFF keys), or to GEOKEYS to use custom values from GeoTIFF keys and drop the EPSG code.
2: In CPL_read_gdal(as.character(x), as.character(options), as.character(driver),  :
  GDAL Message 1: The definition of geographic CRS EPSG:4258 got from GeoTIFF keys is not the same as the one from the EPSG registry, which may cause issues during reprojection operations. Set GTIFF_SRS_SOURCE configuration option to EPSG to use official parameters (overriding the ones from GeoTIFF keys), or to GEOKEYS to use custom values from GeoTIFF keys and drop the EPSG code.
```
Curiously I don´t get this message when I read the file in `terra`.

1. I can guess what it means, but not sure if it is critical or important when manipulating `stars` objects. Reprojecting, `st:warp`, in particular.
2. If it is not critical, how may I suppress this particular warning globally (not using `suppressWarnings` each time)

Thanks a lot!

**Comment by edzer** [comment]
`terra` suppresses (some?) gdal warnings, see `terra::gdal`

The warning suggests to set `Sys.setenv(GTIFF_SRS_SOURCE="EPSG")` to resolve this. Please report back whether this worked.

**Comment by kadyb** [comment]
Edzer probably meant to test `{terra}` with `gdal(warn = 1)` to see if this message would also appear.
