### ISSUE TITLE
abind Error when converting a .tif raster data object to an sf object using st_xy2sfc() in R

### ISSUE THREAD

**Issue by fgoerlich** [r-spatial/stars#651]
Hi,
I get this error
```
Error in abind(x, along = length(dim(x)) + 1) : 
  along must be between 0 and 2
```
when converting an star object into a point `sfc` using st_xy2sfc() in R:

`read_stars("NDSM-Edificacion-REGCAN95-H28-1083-COB1.tif") |> st_xy2sfc(as_points = TRUE, na.rm = TRUE)`

Other similiar files work properly.
Thanks a lot!

[NDSM-Edificacion-REGCAN95-H28-1083-COB1.zip](https://github.com/r-spatial/stars/files/12777987/NDSM-Edificacion-REGCAN95-H28-1083-COB1.zip)

**Comment by edzer** [comment]
```r
read_stars("NDSM-Edificacion-REGCAN95-H28-1083-COB1.tif") |> st_as_stars() |> st_xy2sfc(as_points = TRUE, na.rm = TRUE)
```
I agree the error message is far from helpful, let's leave this issue open.

**Comment by fgoerlich** [comment]
You are right!
But If I read the file in terra I get the same error
```
terra::rast("NDSM-Edificacion-REGCAN95-H28-1083-COB1.tif") |> st_as_stars() |> st_xy2sfc(as_points = TRUE, na.rm = TRUE)
Error in abind(x, along = length(dim(x)) + 1) : 
  along must be between 0 and 2
```

**Comment by edzer** [comment]
In that case, you need to specify `proxy = FALSE` in `st_as_stars()`.
