### ISSUE TITLE
collapse an x/y dimension to a single geometry dimension

### ISSUE THREAD

**Issue by jvandens** [r-spatial/stars#654]
Apologies if this isn't an 'issue' but more of a question.

Below is an reprex, but I have a stars object with 2 'raster-like' grid dimensions (but no projection), of x and y.  I also have a polygon sf file that contains a field that contains a combination of xy element ids that the polygons correspond to (but will be a subset of them!).  I want to reshape the star to remove the xy dimensions and replace with the single geometry dimension.  Essentially the equivalent of doing a table join between the data in the star with the xy dimensions.

Here is a reprex:

```r
# create a star
x = seq(1,5,1)
y = seq(1,8,1)
z = seq(1,3,1)
t = seq(1,4,1)

d <- st_dimensions(x=x, y=y,z=z,t=t)

values <- runif(length(x) * length(y) * length(z) * length(t))
data = array(values, dim = c(length(x),
                             length(y),
                             length(z),
                             length(t)))

star <- st_as_stars(data = data,  dimensions = d)
star

# create an arbitrary geometry of a subset of the number of x and y
nc = sf::read_sf(system.file("gpkg/nc.gpkg", package = "sf"), "nc.gpkg") |>
  head(0.5 * length(x) * length(y)) |>  # the number of polygons < total number of x * y grid elements
  select(geom) |>
  # add an x-y ID, these are what should be 'joined' with the star xy
   mutate(x = c(rep(1,4), rep(2,4), rep(3,4), rep(4,4), rep(5,4)),
         y = rep(c(1,3,5,8),5),
         label = paste0(x,"-",y))
```

I was trying to do something like:

```r
st.g <- star |> filter(x %in% c(1.5,2.5,3.5,4.5,5.5),
                       y %in% c(1.5,3.5,5.5,8.5)) 

(nc.geom <- st_set_dimensions(st.g, 1, st_geometry(nc)))

```
but I get an error because the number of geometry elements (20) is not the same.

I basically need to extract the elements of the star in the nc$label column and make a new star with the geometry of nc applied.

**Comment by edzer** [comment]
That gives
```r
Error in st_set_dimensions(st.g, 1, st_geometry(nc)) : 
  length of values ( 20 ) does not match length of dimension 1 ( 5 )
```
which is correct, right?

**Comment by jvandens** [comment]
Yes that is a correct error message, but I was mostly asking (which admittedly isn't so much an error as a it is a question) is how to collapse the x and y dimensions into a single geom dimension based on a known correspondence between  x/y pairs and the geometry. 

For example, using the above data, there are 5 * 8 = 40 unique x/y elements, I also have an sf file with columns for x and y (and the geom) that identify the x/y coordinates of that geom (and this will be less than 40 rows long as it is subset of the x/y pairs).  I am wondering if there is an efficient way to collapse the stars x/y pairs and replace with the corresponding geom from the sf.

PS:  Is their a general "Discussions" board for this repo or other forum to ask specific Stars/sf related questions?  I looked on r-spatial.org but didn't see any.  The r-spatial family of packages is SO USEFUL (thanks to all!) that it would be great to have a discussion community.

**Comment by edzer** [comment]
collapse:
```r
# create a star
library(stars)
# Loading required package: abind
# Loading required package: sf
# Linking to GEOS 3.11.1, GDAL 3.6.4, PROJ 9.1.1; sf_use_s2() is TRUE
library(dplyr)

# Attaching package: ‘dplyr’

# The following objects are masked from ‘package:stats’:

#     filter, lag

# The following objects are masked from ‘package:base’:

#     intersect, setdiff, setequal, union

x = seq(1,5,1)
y = seq(1,8,1)
z = seq(1,3,1)
t = seq(1,4,1)

d <- st_dimensions(x=x, y=y,z=z,t=t)

values <- runif(length(x) * length(y) * length(z) * length(t))
data = array(values, dim = c(length(x),
                             length(y),
                             length(z),
                             length(t)))

star <- st_as_stars(data = data,  dimensions = d)
star |> st_redimension(c(40, 3, 4))
# stars object with 3 dimensions and 1 attribute
# attribute(s):
#              Min.   1st Qu.    Median      Mean   3rd Qu.      Max.
# data  0.004779889 0.2509251 0.5014874 0.5043166 0.7639743 0.9986302
# dimension(s):
#    from to
# X1    1 40
# X2    1  3
# X3    1  4
```
raster-to-vector:
```r
star |> st_xy2sfc(as_points = TRUE)
# stars object with 3 dimensions and 1 attribute
# attribute(s):
#              Min.   1st Qu.    Median      Mean   3rd Qu.      Max.
# data  0.002253571 0.2623123 0.4992395 0.5089288 0.7805655 0.9999312
# dimension(s):
#          from to offset delta point                              values
# geometry    1 40     NA    NA  TRUE POINT (1.5 1.5),...,POINT (5.5 8.5)
# z           1  3      1     1 FALSE                                NULL
# t           1  4      1     1 FALSE                                NULL
```

**Comment by edzer** [comment]
> PS: Is their a general "Discussions" board for this repo or other forum to ask specific Stars/sf related questions? I looked on r-spatial.org but didn't see any. The r-spatial family of packages is SO USEFUL (thanks to all!) that it would be great to have a discussion community.

Thanks! https://github.com/r-spatial/discuss

**Comment by edzer** [comment]
Your `filter` example filters values for a dimension, not combinations of points. Are you trying to extract values at particular points from the raster (`st_extract`)?

**Comment by jvandens** [comment]
yes precisely, in the example above for instance, I created a subset of nc file (20 elements) and added the x/y id's to it.  I would like to now subset the stars object (of 40 elements) down to these 20 geometries and replace the geom in the stars with these 20.

I suppose I could create a POINT(x,y) geom in the nc file, then use `st_extract` on the star with it? 

```r
nc = sf::read_sf(system.file("gpkg/nc.gpkg", package = "sf"), "nc.gpkg") |>
  head(0.5 * length(x) * length(y)) |>  # the number of polygons < total number of x * y grid elements
  select(geom) |>
  # add an x-y ID, these are what should be 'joined' with the star xy
   mutate(x = c(rep(1,4), rep(2,4), rep(3,4), rep(4,4), rep(5,4)),
         y = rep(c(1,3,5,8),5),
         label = paste0(x,"-",y))
```

**Comment by edzer** [comment]
I don't really get where you're trying to go. Maybe you can share a file, or files that you're working on and explain the problem based on them?

**Comment by jvandens** [comment]
Thanks Edzer, apologies for the confusion, I updated my above post but your suggestion on `st_extract()` did the trick!  For posterity, I've posted a complete solution down below based on my original example which seems to be working great.

```r
library(stars)
library(dplyr)

# create a star
x = seq(1,5,1)
y = seq(1,8,1)
z = seq(1,3,1)
t = seq(1,4,1)

d <- st_dimensions(x=x, y=y,z=z,t=t)

values <- runif(length(x) * length(y) * length(z) * length(t))
data = array(values, dim = c(length(x),
                             length(y),
                             length(z),
                             length(t)))

star <- st_as_stars(data = data,  dimensions = d)
star

# as example of my geometry layer I want to merge,
# create an arbitrary geometry of a subset of the number of x and y in the star
# and add x/y column column that we want to extract
nc = sf::read_sf(system.file("gpkg/nc.gpkg", package = "sf"), "nc.gpkg") |>
  head(0.5 * length(x) * length(y)) |>  # the number of polygons < total number of x * y grid elements
  select(geom) |>
  # add an x-y ID, these are what should be extracted with the star xy, adding 0.5 to 
  # account for star point centers
  mutate(x = 0.5+c(rep(1,4), rep(2,4), rep(3,4), rep(4,4), rep(5,4)),
         y = 0.5+rep(c(1,3,5,8),5)) 
  
# so this mimics what I have, a set of geometries (polygons) that map to a set of arbitrary x and y pairs in the star and I want to extract from the star those x/y pairs and replace with the geometry:

## SOLUTION  ################

# drop the existing geometry and add in a new xy point geom to make the extraction mask
nc.mask <- nc |> 
st_drop_geometry() |> 
  st_as_sf(coords = c("x", "y"))  # make apoint geom of the x/y pairs to extract from the star

# extract from the star the points in nc.mask
ext <- st_extract(star, at=nc.mask)

# replace the geometry to the original grid geom
final <- st_set_dimensions(ext, 1, sf::st_geometry(nc))

# plot
plot(final[,,1,1])

```
