### ISSUE TITLE
released read_stars errors on standard dataset

### ISSUE THREAD

**Issue by rsbivand** [r-spatial/stars#655]
With `stars`  0.6-4 and 
[L7_ETM8s.zip](https://github.com/r-spatial/stars/files/13164539/L7_ETM8s.zip) (ASDAR checks):

```
library(stars)
pan <- as(read_stars("L7_ETM8s.tif"), "Spatial")
## Error in read_stars("L7_ETM8s.tif") : object 'which.column' not found
```

With 0.6-5 (current main) there is no error, probably from https://github.com/r-spatial/stars/commit/a7fcbf1bd5a2fddcee6cb7a608385d2ced382ee6#diff-239a0d05d561b10f42a6822636b70a7b1c0a2b457fe1fc9b37d8f4e48c3240bb. Sorry for not reporting earlier.

**Comment by edzer** [comment]
Thanks!
