### ISSUE TITLE
How to add map scale and north arrow?

### ISSUE THREAD

**Issue by kadyb** [r-spatial/stars#656]
I would like to add scale and north arrow to the map generated with `plot()`. How can this be done? In `{terra}` there are dedicated functions [sbar()](https://rspatial.github.io/terra/reference/sbar.html) and [north()](https://rspatial.github.io/terra/reference/north.html).

**Comment by edzer** [comment]
It's all base plot, this seems to work:
```r
library(stars)
plot(L7_ETMs[,,,1], reset = FALSE)
terra::north(d=500, xy=c(298722.8 -500, 9110728.8 + 1000))
terra::sbar(1000, c(298722.8 -1000, 9110728.8 + 100))
```
![x](https://github.com/r-spatial/stars/assets/520851/ddb94353-f937-426a-a162-432dc4f15884)

**Comment by kadyb** [comment]
It would be super great if it could be done in `{stars}`  without relying on `{terra}`. But of course someone has to implement it :-)

**Comment by edzer** [comment]
> But of course someone has to implement it :-)

you mean "copy it"? Yes, and maintain changes in upstream...

**Comment by kadyb** [comment]
Not to copy, but would it be easier to follow the existing implementation and maybe simplify something? It seems that these functions are quite stable: https://github.com/rspatial/terra/blame/master/R/plot_scale.R

**Comment by edzer** [comment]
It would be great to have examples somewhere in the documentation.
