### ISSUE TITLE
Unexpected behavior: st_transform a raster and transforming back, it is not identical unless applying st_warp

### ISSUE THREAD

**Issue by jfsalzmann** [r-spatial/stars#672]
I noticed some unexpected behavior that seems to me like a bug but may not be (disclaimer, I'm quite new to geospatial analysis and stars). 

```r
# vector shape file with EPSG 4326
states = st_read("vg2500_bld.shp")
# raster file with EPSG 31467
temperature = read_stars("mean_temp_2023_germany.tif")

# transforming temperature raster to states' CRS
transf = temperature %>% st_transform(st_crs(states))
# transforming back
back = transf %>% st_transform(st_crs(temperature))
# transforming back and warping, computationally expensive
back_w = transf %>% st_transform(st_crs(temperature)) %>% st_warp(dest = temperature)

# visualisation: zoom in, you'll obvserve that back is slightly shifted against temperature (unexpected, expected: identical),
# back_w is not (expected)
mapview(temperature) + mapview(back) + mapview(back_w) # + mapview(transf)

# compare whether raster is identical after transforming and re-transforming,
# checking CRS, matrix values, and dimensions

# TRUE, TRUE, FALSE (unexpected, expected: TRUE, TRUE, TRUE)
identical(st_crs(temperature),st_crs(back))
identical(temperature[[1]],back[[1]])
identical(st_dimensions(temperature),st_dimensions(back))

# TRUE, TRUE, TRUE (expected as is)
identical(st_crs(temperature),st_crs(back_w))
identical(temperature[[1]],back_w[[1]])
identical(st_dimensions(temperature),st_dimensions(back_w))


# note that the difference in the dimensions is that back is still a curvilinear grid (unexpected, expected: normal grid)

st_dimensions(back)
# from  to                       refsys point                        values x/y
# x    1 654 DHDN / 3-degree Gauss-Kru... FALSE [654x866] 3280915,...,3933915 [x]
# y    1 866 DHDN / 3-degree Gauss-Kru... FALSE [654x866] 5238001,...,6103001 [y]
# curvilinear grid

st_dimensions(back_w)
# from  to  offset delta                       refsys point x/y
# x    1 654 3280415  1000 DHDN / 3-degree Gauss-Kru... FALSE [x]
# y    1 866 6103501 -1000 DHDN / 3-degree Gauss-Kru... FALSE [y]
```

I transform a raster to another CRS, and back to it's original CRS.

I would expect that
- this is a losless operation as described in the documentation and doesn't actually change my data
- it results in having an identical raster object after transforming and re-transforming
- i.e., CRS (✅), raster matrix (✅), and dimensions (❌) would be identical

Instead, I notice that, when only re-transforming,
- stars still considers the object to be in a curvilinear grid (which doesn't make sense imo because it isn't anymore)
- it's plotted slightly different on mapview (surprising)
- supposedly (haven't tested though) would also result in differing computational results

To get back to the actually identical object, I have to warp the raster after transforming and re-transforming, which I note is computationally expensive (in my case needs longer than a second). At least, warping in this case doesn't result in data loss appearently.

Geo files used are available here: [data.zip](https://github.com/r-spatial/stars/files/14462131/data.zip)

**Comment by edzer** [comment]
> stars still considers the object to be in a curvilinear grid (which doesn't make sense imo because it isn't anymore)

yes, because it does not contain information about what the original CRS was, in which it was regular

> it's plotted slightly different on mapview (surprising)

mapview will do some warping, which is lossy

**Comment by jfsalzmann** [comment]
> yes, because it does not contain information about what the original CRS was, in which it was regular

hmm, doesn't it? I thought I've passed it this information.
```r
# transforming back
back = transf %>% st_transform(st_crs(temperature))
```

and, this is `TRUE`:
```r
identical(st_crs(temperature),st_crs(back))
```

maybe I misunderstand what you mean here.

**Comment by edzer** [comment]
In `transf %>% st_transform(st_crs(temperature))`, `trans` doesn't know its grid can be represented by a regular grid in `st_crs(temperature)`.

**Comment by edzer** [comment]
> So I would suggest the following behavior: when (re-)transforming to the CRS that a raster had originally, assume a regular grid again, as no re-calculation / warping is required in fact. Possibly store the original CRS (I assume it would be stored somehow already).

Yes, of course one can do all that, the question is how large the benefit is compared to the cost, and how this can be made waterproof such that all kind of operations in between (cropping, downsampling) lead to the right regular grid again. In your case, going from CRS A to B to A and no messing, you can set back the dimension table by
```r
st_dimensions(back) = st_dimensions(temperature)
```
but only because you know that this is OK: no cost, also no guarantee or checking from the software side.

**Comment by jfsalzmann** [comment]
(can be closed)

**Comment by jfsalzmann** [comment]
(can be closed)
