### ISSUE TITLE
Update failed for stars... same error for leafem, leafgl, and rgee installation.

### ISSUE THREAD

**Issue by YinOsu** [r-spatial/stars#697]
Update failed for stars

> install.packages("stars")
Installing package into ‘/usr/local/lib/R/4.4/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/stars_0.6-6.tar.gz'
Content type 'application/x-gzip' length 3741200 bytes (3.6 MB)
==================================================
downloaded 3.6 MB

* installing *source* package ‘stars’ ...
** package ‘stars’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** demo
** inst
** byte-compile and prepare package for lazy loading
>Error: package or namespace load failed for ‘sf’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/4.4/site-library/sf/libs/sf.so':
  dlopen(/usr/local/lib/R/4.4/site-library/sf/libs/sf.so, 0x0006): Library not loaded: /usr/local/opt/gdal/lib/libgdal.34.dylib
  Referenced from: <3FE68D79-51B5-3CC6-A059-6294E70939DF> /usr/local/lib/R/4.4/site-library/sf/libs/sf.so
  Reason: tried: '/usr/local/opt/gdal/lib/libgdal.34.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/gdal/lib/libgdal.34.dylib' (no such file), '/usr/local/opt/gdal/lib/libgdal.34.dylib' (no such file), '/usr/local/Cellar/r/4.4.1/lib/R/lib/libgdal.34.dylib' (no such file), '/usr/local/Cellar/gdal/3.9.1_1/lib/libgdal.34.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/gdal/3.9.1_1/lib/libgdal.34.dylib' (no such file), '/usr/local/Cellar/gdal/3.9.1_1/lib/libgdal.34.dylib' (no such file), '/usr/local/Cellar/r/4.4.1/lib/R/lib/libgd
Execution halted
ERROR: lazy loading failed for package ‘stars’
* removing ‘/usr/local/lib/R/4.4/site-library/stars’
* restoring previous ‘/usr/local/lib/R/4.4/site-library/stars’
Warning in install.packages :
  installation of package ‘stars’ had non-zero exit status

**Comment by edzer** [comment]
reinstall `sf`.

**Comment by YinOsu** [comment]
> reinstall `sf`.

I have, and when I did, I got error. 

> remove.packages("sf")
Removing package from ‘/usr/local/lib/R/4.4/site-library’
(as ‘lib’ is unspecified)
> install.packages("sf")
Installing package into ‘/usr/local/lib/R/4.4/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/sf_1.0-16.tar.gz'
Content type 'application/x-gzip' length 3493756 bytes (3.3 MB)
==================================================
downloaded 3.3 MB

* installing *source* package ‘sf’ ...
** package ‘sf’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: clang
configure: CXX: clang++ -std=gnu++17
checking for gdal-config... /usr/local/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 3.9.1
checking GDAL version >= 2.0.1... yes
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether clang accepts -g... yes
checking for clang option to enable C11 features... unsupported
checking for clang option to enable C99 features... none needed
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /usr/local/Cellar/gdal/3.9.1_1/share/gdal/pcs.csv readable... no
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available for running:... ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db
ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db
ERROR 1: PROJ: proj_create: unrecognized format / unknown name
ERROR 1: PROJ: proj_create: unrecognized format / unknown name
no
configure: error: OGRCoordinateTransformation() does not return a coord.trans: PROJ not available?
ERROR: configuration failed for package ‘sf’
* removing ‘/usr/local/lib/R/4.4/site-library/sf’
Warning in install.packages :
  installation of package ‘sf’ had non-zero exit status

**Comment by edzer** [comment]
Looks like you're on MacOS (you didn't specify) - if this is the case, please install `sf` as a binary package.

**Comment by YinOsu** [comment]
> Looks like you're on MacOS (you didn't specify) - if this is the case, please install `sf` as a binary package.

Sorry about that. is this the same as installing from the binary package.. ?
>install_github("r-spatial/sf", configure.args = "--with-proj-lib=$(brew --prefix)/lib/")

**Comment by YinOsu** [comment]
> No, you'd use
> 
> ```
> install.packages("sf", type = "binary")
> ```

I get this error:
> install.packages("sf", type = "binary")
Error in install.packages : type 'binary' is not supported on this platform

@edzer

**Comment by edzer** [comment]
sorry, please try
```
install.packages("sf", type = "mac.binary")
```

**Comment by YinOsu** [comment]
> sorry, please try
> 
> ```
> install.packages("sf", type = "mac.binary")
> ```

Here is the output @edzer 

> install.packages("sf", type = "mac.binary")
Installing package into ‘/usr/local/lib/R/4.4/site-library’
(as ‘lib’ is unspecified)
Warning in install.packages :
  unable to access index for repository https://cran.rstudio.com/bin/macosx/contrib/4.4:
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.4/PACKAGES'

   package ‘sf’ is available as a source package but not as a binary

Warning in install.packages :
  package ‘sf’ is not available as a binary package for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by edzer** [comment]
This is not a stars issue, but an issue with your R installation; as I don't use a mac, I'm giving up, pls find help elsewhere.

**Comment by YinOsu** [comment]
> > reinstall `sf`.
> 
> I have, and when I did, I got error.
> 
> > remove.packages("sf")
> > Removing package from ‘/usr/local/lib/R/4.4/site-library’
> > (as ‘lib’ is unspecified)
> > install.packages("sf")
> > Installing package into ‘/usr/local/lib/R/4.4/site-library’
> > (as ‘lib’ is unspecified)
> > trying URL 'https://cran.rstudio.com/src/contrib/sf_1.0-16.tar.gz'
> > Content type 'application/x-gzip' length 3493756 bytes (3.3 MB)
> > ==================================================
> > downloaded 3.3 MB
> 
> * installing _source_ package ‘sf’ ...
>   ** package ‘sf’ successfully unpacked and MD5 sums checked
>   ** using staged installation
>   configure: CC: clang
>   configure: CXX: clang++ -std=gnu++17
>   checking for gdal-config... /usr/local/bin/gdal-config
>   checking gdal-config usability... yes
>   configure: GDAL: 3.9.1
>   checking GDAL version >= 2.0.1... yes
>   checking for gcc... clang
>   checking whether the C compiler works... yes
>   checking for C compiler default output file name... a.out
>   checking for suffix of executables...
>   checking whether we are cross compiling... no
>   checking for suffix of object files... o
>   checking whether the compiler supports GNU C... yes
>   checking whether clang accepts -g... yes
>   checking for clang option to enable C11 features... unsupported
>   checking for clang option to enable C99 features... none needed
>   checking for stdio.h... yes
>   checking for stdlib.h... yes
>   checking for string.h... yes
>   checking for inttypes.h... yes
>   checking for stdint.h... yes
>   checking for strings.h... yes
>   checking for sys/stat.h... yes
>   checking for sys/types.h... yes
>   checking for unistd.h... yes
>   checking for gdal.h... yes
>   checking GDAL: linking with --libs only... yes
>   checking GDAL: /usr/local/Cellar/gdal/3.9.1_1/share/gdal/pcs.csv readable... no
>   checking GDAL: checking whether PROJ is available for linking:... yes
>   checking GDAL: checking whether PROJ is available for running:... ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db
>   ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db
>   ERROR 1: PROJ: proj_create: unrecognized format / unknown name
>   ERROR 1: PROJ: proj_create: unrecognized format / unknown name
>   no
>   configure: error: OGRCoordinateTransformation() does not return a coord.trans: PROJ not available?
>   ERROR: configuration failed for package ‘sf’
> * removing ‘/usr/local/lib/R/4.4/site-library/sf’
>   Warning in install.packages :
>   installation of package ‘sf’ had non-zero exit status

Got to resolve this issue by doing:
`>export PROJ_DATA="/usr/local/Cellar/proj/9.4.1/share/proj" `
(Note that DeprecationWarning: PROJ_LIB environment variable is deprecated, and will be removed in a future release. You are encouraged to set PROJ_DATA instead.)
`>export GDAL_DATA="/usr/local/Cellar/gdal/3.9.2/share/gdal"`

Then install "sf" after which I was able to install "stars"
