### ISSUE TITLE
Subsetting does not work with read_ncdf

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/stars#72]
Subsetting with files returned by `read_ncdf` seems to be problematic:
```R
library(stars)
f = system.file("nc/reduced.nc", package = "stars")
a = read_ncdf(f)
p = st_sf(a=1, geometry = st_geometry(st_point(c(0, 0))))
a[p]
```
Returns:
```
Error in xy_from_colrow(x, geotransform, inverse = TRUE) : 
  geotransform not invertible
```
Instead with `read_stars`:
```R
b = read_stars(f)
b[p]
```
Gives no error and both the subsetting and the cropping work file.

**Comment by edzer** [comment]
Strange, for me both give the same output.

**Comment by adrfantini** [comment]
Uhm, I just updated both stars and sf and I am running on a machine with ubuntugis-unstable.
```
> sf_extSoftVersion()
      GEOS           GDAL         proj.4 GDAL_with_GEOS 
       "3.5.1"        "2.2.2"        "4.9.2"         "true"
```
Trying on my ArchLinux machine instead works:
 ```
> sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS 
       "3.7.0"        "2.3.2"        "5.2.0"         "true"
```

**Comment by adrfantini** [comment]
I'll test with our cluster later, let's see.

**Comment by adrfantini** [comment]
Works with our cluster, with:
```
          GEOS           GDAL         proj.4 GDAL_with_GEOS 
       "3.4.2"        "2.3.1"        "4.8.0"        "false"
```
Any idea what it could be?

**Comment by edzer** [comment]
It calls a GDAL function, so it could be the gdal version; still pretty strange, with all of them being this high.

**Comment by adrfantini** [comment]
GDAL seems to be 2.2.2 in ubuntugis-unstable:

`https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable/+packages?field.name_filter=gdal&field.status_filter=published&field.series_filter=`

Not 2.2.3, like you have. What is up?

**Comment by edzer** [comment]
Is this ubuntu 18.04?

**Comment by adrfantini** [comment]
```
> lsb_release -a
No LSB modules are available.
Distributor ID: LinuxMint
Description:    Linux Mint 18 Sarah
Release:        18
Codename:       sarah
```

**Comment by edzer** [comment]
That may be it, I have
```
> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

**Comment by adrfantini** [comment]
In the link I gave above I don't see any gdal specific to bionic. I am not that familiar with Ubuntu packaging tho. Are you sure your GDAL is from `ubuntugis-unstable`?

**Comment by edzer** [comment]
```bash
$ grep ubuntugis /etc/apt/*/*
/etc/apt/sources.list.d/ubuntugis-ubuntu-ubuntugis-unstable-bionic.list:deb http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu bionic main
```

**Comment by adrfantini** [comment]
I have
```
/etc/apt/sources.list.d/ubuntugis-ppa-xenial.list:deb http://ppa.launchpad.net/ubuntugis/ppa/ubuntu xenial main
/etc/apt/sources.list.d/ubuntugis-ppa-xenial.list:deb-src http://ppa.launchpad.net/ubuntugis/ppa/ubuntu xenial main
/etc/apt/sources.list.d/ubuntugis-ubuntugis-unstable-xenial.list:deb http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu xenial main
/etc/apt/sources.list.d/ubuntugis-ubuntugis-unstable-xenial.list:deb-src http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu xenial main
```
I'll see what the sysadmins say.

**Comment by edzer** [comment]
xenial = 16.04, bionic = 18.04.

**Comment by adrfantini** [comment]
I know that, it's just that GDAL does not seem to be available in ubuntugis-unstable for bionic:
https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable/+packages?field.name_filter=gdal&field.status_filter=published&field.series_filter=

Unless it is provided by `libgdal-grass`...

**Comment by adrfantini** [comment]
Yeah. Should I close this? I have not resolved, yet, but at least we know it probably is down to package versions.

**Comment by edzer** [comment]
Yes, I can confirm from a 16.04 container:
```
> library(stars)
Loading required package: abind
Loading required package: sf
Linking to GEOS 3.5.1, GDAL 2.2.2, PROJ 4.9.2
> library(stars)
> f = system.file("nc/reduced.nc", package = "stars")
> a = read_ncdf(f)
> p = st_sf(a=1, geometry = st_geometry(st_point(c(0, 0))))
> a[p]
Error in xy_from_colrow(x, geotransform, inverse = TRUE) : 
  geotransform not invertible
```
