### ISSUE TITLE
read_ncdf dimension direction: latitudes inverted

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/stars#73]
I have a file which is correctly read by `raster`, `read_stars`, `ncview` etc., but that gets read with inverted latitudes if using `read_ncdf`.
[Here](https://drive.google.com/open?id=1BlQHDCdD8wLu4vqSmCndpO29SdJFuh0G) it is.

To test, just issue
```R
library(raster)
library(stars)
fn = 'regcm-nn-2100_reg4_22.nc'
r = raster(fn)
s = read_stars(fn)
n = read_ncdf(fn)
plot(r)
plot(s)
plot(n)
```

**Comment by mdsumner** [comment]
This is one of those cases I'm not sure what to do. 

The latitudes aren't regular, so perhaps we are too strict compared to GDAL or raster. 

I think we just detect that latitude runs increasing so we flip it. 

```R
## compare to with ncdf4 which suggests we must flip
image(st_dimensions(x)$lon$values, st_dimensions(x)$lat$values, s[[1]][,ncol(x[[1]]):1,1])

library(ncdf4)
f <- "extdata/inverted_73/regcm-nn-2100_reg4_22.nc"
nc <- nc_open(f)
lon <- ncvar_get(nc, "lon")
lat <- ncvar_get(nc, "lat")
z <- ncvar_get(nc, "POT")
image(lon, lat, z[,,1])
```

I haven't explored the implications across the other cases we've seen, yet.

**Comment by adrfantini** [comment]
My bad, I missed it. Yeah, works for me!
