### ISSUE TITLE
"[" behaves differently for proxy objects?

### ISSUE THREAD

**Issue by tghoward** [r-spatial/stars#74]
Consider the subsetting example provided here:
https://www.r-spatial.org/r/2018/03/22/stars2.html

```
> library(stars)
> tif = system.file("tif/L7_ETMs.tif", package = "stars")
> x = read_stars(tif)
> x <- x[,,,1]
> pol <- x %>% st_bbox() %>% st_as_sfc() %>% st_centroid() %>% st_buffer(200)
> plot(x[pol])
> 
```
 results in a circular clip of the object, but this
```
y <- read_stars(tif, proxy = TRUE)
y <- y[,,,1]
ysub <- y[pol]
plot(st_as_stars(ysub))
```
results in a rectangular crop.  

![proxycropexample](https://user-images.githubusercontent.com/6129193/48419011-d39e3580-e724-11e8-9c7b-25269a43ffa8.png)

If I then try to crop this object, it errors out
```
> z <- st_as_stars(ysub)
> zsub <- z[pol]
Error in .Primitive("[")(x = `C:\\Users\\Tim\\Documents\\R\\win-library\\3.5\\stars\\tif\\L7_ETMs.tif`,  : 
  subscript out of bounds
> 
```

thanks for any thoughts ...

**Comment by edzer** [comment]
Thanks! Should work now.

**Comment by tghoward** [comment]
Yep, it now crops to the circle the second time (e.g. when using "[" on the stars object, not the proxy object). Thank you!
