### ISSUE TITLE
Difference between filter and subsetting

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/stars#75]
I have found a very subtle difference between `filter` and subsetting with `[`:

```R
library(stars)
library(dplyr)
tif = system.file("tif/L7_ETMs.tif", package = "stars")
x1 = read_stars(tif)
a = x1[,,,1]
b = x1 %>% filter(band==1)
identical(a, b)
# [1] FALSE
```
In fact the difference is in the dimensions:
```R
> st_dimensions(a)
     from  to  offset delta                       refsys point values    
x       1 349  288776  28.5 +proj=utm +zone=25 +south... FALSE   NULL [x]
y       1 352 9120761 -28.5 +proj=utm +zone=25 +south... FALSE   NULL [y]
band    1   1      NA    NA                           NA    NA   NULL    
> st_dimensions(b)
     from  to  offset delta                       refsys point values    
x       1 349  288791  28.5 +proj=utm +zone=25 +south... FALSE   NULL [x]
y       1 352 9120747 -28.5 +proj=utm +zone=25 +south... FALSE   NULL [y]
band    1   1      NA    NA                           NA    NA      1
```

This very slight difference in x-y dimensions can introduce huge problems in some workflows. In my case, I banged my head for two days before figuring out that this was the source of an annoying problem which resulted in this:
![spectacle mn7444](https://user-images.githubusercontent.com/12826141/48430137-dfaee500-e76e-11e8-8468-21cc1899fa8c.png)

instead of this:
![spectacle lh7444](https://user-images.githubusercontent.com/12826141/48429916-61ead980-e76e-11e8-8ea5-f1e4320e9d55.png)

**Comment by edzer** [comment]
Good catch -- hit by the bloody half cell size, once more. This at least gives
```r
> all.equal(st_dimensions(a)[1:2], st_dimensions(b)[1:2])
[1] TRUE
```

**Comment by adrfantini** [comment]
Thanks! Closing, then, right?

**Comment by edzer** [comment]
Note that the b option makes a roundtrip from geotransform -> cell center coordinates -> geotransform, which gives near equality; `identical` will yield `FALSE`. This may bite someone at some stage.
