### ISSUE TITLE
Axes labels computed erroneously

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/stars#81]
I'm opening TIF files downloaded from here:
    https://data.jrc.ec.europa.eu/collection/id-0054
In particular, this one:
http://cidportal.jrc.ec.europa.eu/ftp/jrc-opendata/FLOODS/GlobalMaps/floodMapGL_rp200y.zip

This happens:
```
tif = "floodMapGL_rp200y.tif"
(x = read_stars(tif, options = c("OVERVIEW_LEVEL=2")))

stars object with 2 dimensions and 1 attribute
attribute(s), summary of first 1e+05 cells:
 floodMapGL_rp200y.tif 
 Min.   :0.02          
 1st Qu.:0.15          
 Median :0.23          
 Mean   :0.23          
 3rd Qu.:0.34          
 Max.   :0.40          
 NA's   :99958         
dimension(s):
  from   to  offset      delta                       refsys point values    
x    1 5202  -166.8  0.0666667 +proj=longlat +datum=WGS8... FALSE   NULL [x]
y    1 2059 83.2251 -0.0666505 +proj=longlat +datum=WGS8... FALSE   NULL [y]
```
Offset and delta are OK. Now plotting:
```
plot(x, axes=TRUE)
```
Results in:
![spectacle lh7356](https://user-images.githubusercontent.com/12826141/50217110-138db380-0388-11e9-9730-93d54cb104ab.png)

Which shows that the axes ticks are indeed wrong: not only they indicate wrong values, but they seem to not cover the complete extent too.

**Comment by edzer** [comment]
Thanks! This turned out to be hidden a little bit deeper than I'd expected, but should work now.
