### ISSUE TITLE
Test output reference files with absolute paths

### ISSUE THREAD

**Issue by helix123** [r-spatial/stars#83]
Some of the test output reference files (.Rout.save) contain absolute paths. e.g.
`"/home/edzer/git/stars.Rcheck/stars/tif/L7_ETMs.tif"`.

This is a little disturbing when running the package's checks as the output on other persons local machines won't match (or, more precisely: only match in very rare circumstances).

**Comment by edzer** [comment]
Thanks! Please feel invited to develop a PR addressing this without decreasing testing power. For me, priority is now to get the software work without errors and have it do something useful.
