### ISSUE TITLE
Reading from multiple NetCDF files 

### ISSUE THREAD

**Issue by dblodgett-usgs** [r-spatial/stars#85]
Starting to investigate what's in `stars` a bit more regarding XYT datasets, I decided to just build a useful test dataset and start working with it a bit. The code below pulls down one file with 12 months in it and 12 separate files with the same data. These files add up to about 500KB total and should be representative of a lot of datasets. A third case might be to do two files with 6 months each, but having the two end members (one file with all time and one time step per file) should be good for testing. See screen shot below for spatial coverage. If this is useful test data for `stars` that would be great.

<img width="581" alt="screen shot 2019-01-03 at 2 24 02 pm" src="https://user-images.githubusercontent.com/1492803/50659848-6f009980-0f63-11e9-9900-1a154ee1341c.png">

The issue I'm having is trying to follow the example here: https://r-spatial.github.io/stars/articles/blog1.html#reading-datasets-from-multiple-files with my own data. 

When I run the last line in the snippet below, I get 
`Error in CPL_read_gdal(as.character(x), as.character(options), as.character(driver),  :  file not found` 
In fact, I get a read gdal error using read_stars for a single NetCDF file... 

I'd be keen to work on some examples of how to implement the area-weighted intersection workflow using `stars` `aggregate.stars` if I can get a little boost getting familiar with what should work and what the plan is. 

<details>
 <summary>download data and load into stars</summary>

```r
library(stars)

one_year <- "https://cida.usgs.gov/thredds/ncss/bcsd_obs?var=pr&var=tas&north=37&west=-85&east=-75&south=33&disableProjSubset=on&horizStride=1&time_start=1999-01-01T00%3A00%3A00Z&time_end=1999-12-31T00%3A00%3A00Z&timeStride=1"
download.file(one_year, destfile = "bcsd_obs_1999_two_var.nc")

month_u1 <- "https://cida.usgs.gov/thredds/ncss/bcsd_obs?var=pr&var=tas&north=37&west=-85&east=-75&south=33&disableProjSubset=on&horizStride=1&time_start="
month_u2 <- "T00%3A00%3A00Z&time_end="
month_u3 <- "T00%3A00%3A00Z&timeStride=1"
start_dates <- seq(as.Date("1999-01-01"), length = 12, by = "1 month")
end_dates <- seq(as.Date("1999-02-01"), length = 12, by = "1 month") - 1

urls <- paste0(month_u1, start_dates, month_u2, end_dates, month_u3)

for(i in 1:length(urls)) {
  destFile <- paste0("monthly_bcsd_obs_1999", 
                     stringr::str_pad(i, 2, "left", "0"), 
                     "_two_var.nc")
  download.file(urls[i], destfile = destFile)
}

bcsd <- read_ncdf("bcsd_obs_1999_two_var.nc")

nc_files <- list.files("./", pattern = "monthly_*")

bcsd_1 <- read_ncdf("monthly_bcsd_obs_199901_two_var.nc")
bcsd_2 <- read_ncdf("monthly_bcsd_obs_199902_two_var.nc")

bcsd_two_file <- c(bcsd_1, bcsd_2, along = "time")

bcsd_multi_file <- read_stars(nc_files)

```
</details>

**Comment by edzer** [comment]
Thanks for exploring. Most of this actually worked as intended:
```r
> bcsd_multi_file
stars object with 3 dimensions and 2 attributes
attribute(s):
   pr [mm/m]         tas [C]      
 Min.   :  0.59   Min.   :-0.421  
 1st Qu.: 56.14   1st Qu.: 8.899  
 Median : 81.88   Median :15.658  
 Mean   :101.26   Mean   :15.489  
 3rd Qu.:121.07   3rd Qu.:21.780  
 Max.   :848.55   Max.   :29.386  
 NA's   :7116     NA's   :7116    
dimension(s):
     from to     offset  delta  refsys point                      values    
x       1 81        -85  0.125      NA    NA                        NULL [x]
y       1 33     37.125 -0.125      NA    NA                        NULL [y]
time    1 12 1999-01-31     NA POSIXct    NA 1999-01-31, ..., 1999-12-31    
```
and 
```r
plot(bcsd_multi_file)
```
gives
![x](https://user-images.githubusercontent.com/520851/50665462-11933980-0fb1-11e9-8640-40790a87f363.png)

The thing that didn't work correctly was
```r
bcsd_two_file <- c(bcsd_1, bcsd_2, along = "time")
```
but if you'd read `bcsd_1` and `bcsd_2` with `read_stars` instead of `read_ncdf`, it would have worked. `read_ncdf` doesn't read time values into an R time format, and apparently that is assumed by the `c()`. Will have to look closer into.

**Comment by edzer** [comment]
Do you also see this?
```r
> st_drivers("raster")["netCDF",]
         name                  long_name write copy is_raster is_vector   vsi
netCDF netCDF Network Common Data Format  TRUE TRUE      TRUE      TRUE FALSE
```

**Comment by dblodgett-usgs** [comment]
Ahhh looks like this is it.
```r
> st_drivers("raster")["netCDF",]
   name long_name write copy is_raster is_vector vsi
NA <NA>      <NA>    NA   NA        NA        NA  NA
```
Will work on getting the netCDF gdal driver available from R.

**Comment by dblodgett-usgs** [comment]
OK -- there it is. I hadn't properly removed the normal brewed gdal when I installed gdal2 (with NetCDF). Once I got the old one all wiped out and the new one linked with `brew link --force gdal2` it worked.
