### ISSUE TITLE
ncdf test coverage

### ISSUE THREAD

**Issue by mdsumner** [r-spatial/stars#94]
We need some tests that exercise the red lines that show up as untested here: 

https://codecov.io/gh/r-spatial/stars/src/master/R/ncdf.R

(Navigate to that travis summary by clicking on the codecov badge of this project readme). When pushed to github, the entire repo is sent to travis for a full R CMD check, and this facility summarizes the results so we can find untested code). 

The first lines are about NetCDF files with scalar values (tidync identifies them with "S", they have a non-valid "dimension", NA in ncmeta and -1 here. 

The bottom section is about curvilinear coordinates. 

There should be example files that exercise these lines in https://github.com/mdsumner/rasterwise

Could you have a look @dblodgett-usgs - especially for a small example with curvilinear coords in NetCDF format?  (Or craft one). 

They need to be small, and hopefully have some link to their origin - many  in rasterwise are from my personal collection, but more recent ones come from discussions here. The GDAL autotest suite is also a good source for small files, but I didn't find any suitable just now.

**Comment by mdsumner** [comment]
Also, I'm happy to do the tests - don't worry if you can't be sure, it'd be very helpful to have a set of candidate files that you think trigger use of those untested code lines.

**Comment by dblodgett-usgs** [comment]
Ahhh I see. I have a curvilinear dataset that's well documented and have been meaning to work it in here. I'm used to coveralls and testthat tests -- the style in this repo is new to me, sorry for the confusion. I'll work on this later on today.

**Comment by edzer** [comment]
testthat tests are fully OK. If datasets are too large to be added to the package, I can add them to the starsdata package (see e.g. the `data_model` vignette).

I'm working on the `data_model` vignette to make stuff more clear, as there are so many options now. Your tests were very helpful, @dblodgett-usgs !

**Comment by edzer** [comment]
We're at 100% coverage, now, thanks a lot. Thanks also for the brilliant and beautiful hurricane / curvilinear grid example, @dblodgett-usgs !

**Comment by dblodgett-usgs** [comment]
My pleasure! If there are ever questions about the lat/lon grid -- or you just want to see how horribly bad people can mangle projections and datums, I have an old publication about the dataset here: https://pubs.usgs.gov/fs/2013/3035/pdf/fs2013-3035.pdf

**Comment by edzer** [comment]
Thanks, I enjoyed reading that!
