### ISSUE TITLE
Is there a plan to add a `write_stars()` function?

### ISSUE THREAD

**Issue by Nowosad** [r-spatial/stars#97]
Right now, the `st_write()` should be used to save stars objects.
I assume there are some benefits from this approach, however, I can think of some issues as well:
1. It can be confusing for new users, as there is the `read_stars()` function to read objects, but there isn't a `write_stars()` to save objects.
2. It is hard to find a **stars** documentation about `st_write()`. 
Simple `?st_write()` just shows information related to sf objects. 
Users need to remember that to find expected documentation, they should type `?st_write.stars`.

*Follow-up from a discussion at https://github.com/edzer/gstat/issues/39#issuecomment-456182144.*

**Comment by edzer** [comment]
I agree, `read_stars` also calls for a `write_stars`.
