### ISSUE TITLE
R CMD check breaks on r-oldrel

### ISSUE THREAD

**Issue by edzer** [r-spatial/stars#98]
See here: https://travis-ci.org/r-spatial/stars/builds/489120624 - this breaks on read_ncdf in the tests in testthat/test_ncdf.R ; I could reproduce the same using winbuilder. @mdsumner and/or @dblodgett-usgs any idea why? What am I overlooking?

[winbuilder check](https://win-builder.r-project.org/0pZgxVcy70g2/)

**Comment by mdsumner** [comment]
What I'm seeing (3.4.4 vs 3.5.1 on Windows) is that

### 3.4.4

```R 
isTRUE(c(lon = TRUE))
[1] FALSE
```

### 3.5.1 
```R 
isTRUE(c(lon = TRUE))
[1] TRUE
```

So, for oldrel we need to wrap this line in `unname()`: 

https://github.com/r-spatial/stars/blob/master/R/ncdf.R#L9

That's definitely a new one for me!

**Comment by mdsumner** [comment]
Actually, better to avoid isTRUE - can't remember why I thought it was needed. PR updated

**Comment by edzer** [comment]
Thanks for the quick action - I didn't know that either!
