### ISSUE TITLE
stars vignettes overhaul

### ISSUE THREAD

**Issue by edzer** [r-spatial/stars#99]
See here: https://r-spatial.github.io/stars/ - I overhauled all vignettes and added some. Comments are welcome - I'm planning to submit stars 0.3-0 in the next few days.

The things still missing is transformation and warping; I'm all ear for suggestions for adds, deletes, or moves of stuff. @mdsumner @dblodgett-usgs @adrfantini

**Comment by mdsumner** [comment]
Thanks!

Sorry to pick so early  :) - I'm a bit surprised you treat a multi-band GeoTIFF as 3D with one attribute, rather than 2D with many attributes. That's probably what the creators intended, but that's an odd interpretation to me. Can it be controlled on read?  Does it invoke band metadata to determine that interpretation as is done for the NetCDF GDAL driver?

**Comment by mdsumner** [comment]
It's a fair default though!   (I'm trying to sort out in my head if stars should adopt the GDAL view  (or the GeoTIFF view) and when, or not -  It's neat to be able to split on dimension arbitrarily, and happy to see stars will read multiple 4D variables sensibly!  I'll try to do a useful extraction from some nasty model output I have).

**Comment by Nowosad** [comment]
> Thanks!
> 
> Sorry to pick so early :) - I'm a bit surprised you treat a multi-band GeoTIFF as 3D with one attribute, rather than 2D with many attributes. That's probably what the creators intended, but that's an odd interpretation to me. Can it be controlled on read? Does it invoke band metadata to determine that interpretation as is done for the NetCDF GDAL driver?

@mdsumner, related discussion: https://github.com/r-spatial/stars/issues/96

**Comment by edzer** [comment]
Would you put land use, elevation and yearly precipitation as three bands in a single GeoTIFF, or serve these as three different files? If you do, how can I read which one is what, when using the GDAL C++ API? Suppose I can't figure out proper names for bands, how do I assign names to attributes in a stars object?

**Comment by mdsumner** [comment]
Good points! What about a RGB image? I guess in that case you have the colour interp on the bands, so a possible guideline

**Comment by mdsumner** [comment]
Actually it's fine, but I definitely think of colour channels as attributes. There's no structural reason to separate them, though. Interesting!

**Comment by adrfantini** [comment]
Nice overhaul, Edzer. In the new article, `tif = system.file("tif/L7_ETMs.tif", package = "stars")` requires GDAL>=2.4, maybe you want to point that out:
```
Error in CPL_polygonize(file, mask_name, "GTiff", "Memory", "foo", character(0),  : 
  contour only available in GDAL >= 2.4.0
```

BTW, I find it a bit confusing that `as_points = TRUE, merge = TRUE` creates contours, to be honest.

**Comment by edzer** [comment]
I added the note about GDAL >= 2.4.0, and will hard-code the figure that comes out.

I agree with your assessment of `as_points = TRUE, merge = TRUE`; shall we introduce an `st_contour` for this case?

(the logic why I got there is this: the contours are to be interpreted as point sets, interpolated, over continuous space; I'm with you that it's a bit far fetched)

**Comment by edzer** [comment]
The more logical outcome for `as_points = TRUE, merge = TRUE` would be a `MULTIPOINT` for each unique raster value / raster value set, that would be in line with `as_points = FALSE, merge = TRUE`.

**Comment by adrfantini** [comment]
Currently:
```
as_points    merge
        T        T      ->    CONTOURS, GDAL>=2.4
        T        F      ->    POINTS
        F        T      ->    POLYGONS, merged
        F        F      ->    POLYGONS, not merged
```
Ideally:
```
as_points    merge
        T        T      ->    MULTIPOINTS
        T        F      ->    POINTS
        F        T      ->    POLYGONS, merged, maybe MULTIPOLYGONS?
        F        F      ->    POLYGONS, not merged
```
and then maybe a separate function for contours... but this seems a bit inelegant.

What about a single `st_as_sf` function serving all three scopes, with a type argument that can take `type = c('point', 'polygon', 'contour')` and a `merge` argument?
```
type    merge
point       T      ->    MULTIPOINTS
point       F      ->    POINTS
polygon     T      ->    POLYGONS, merged, maybe MULTIPOLYGONS?
polygon     F      ->    POLYGONS, not merged
contour     T      ->    CONTOURS (MULTIPOLYGON?)
contour     F      ->    CONTOURS (POLYGON?)
```

**Comment by edzer** [comment]
I like your option 2, and have a `st_contour` that contours. The latter needs options too, since you can get them as lines, or as polygons.

**Comment by adrfantini** [comment]
> I like your option 2, and have a `st_contour` that contours. The latter needs options too, since you can get them as lines, or as polygons.

True that, being able to create both lines and polys would be very handy and this would probably be the most intuitive way.

**Comment by Nowosad** [comment]
@edzer Another thing - there is a warning that happens several time in the vignettes (e.g. https://r-spatial.github.io/stars/articles/stars1.html#reading-datasets-from-multiple-files):
```
## Warning: ignoring unrecognized unit: percentage
```
Should it be there?

**Comment by edzer** [comment]
It's an error in the netcdf file, I don't know how to correct it. @adrfantini any idea?

**Comment by edzer** [comment]
```r
> units::set_units(1, percent)
1 [percent]
> units::set_units(1, percentage)
Error: In ‘percentage’, ‘percentage’ is not recognized by udunits.
See a table of valid unit symbols and names with valid_udunits().
Add custom user-defined units with install_symbolic_unit().
```

**Comment by adrfantini** [comment]
> It's an error in the netcdf file, I don't know how to correct it. @adrfantini any idea?

Sure, do this on the source files (not tested but it should work):
```R
x = c(
"avhrr-only-v2.19810901.nc",
"avhrr-only-v2.19810902.nc",
"avhrr-only-v2.19810903.nc",
"avhrr-only-v2.19810904.nc",
"avhrr-only-v2.19810905.nc",
"avhrr-only-v2.19810906.nc",
"avhrr-only-v2.19810907.nc",
"avhrr-only-v2.19810908.nc",
"avhrr-only-v2.19810909.nc"
)
file_list = system.file(paste0("netcdf/", x), package = "starsdata")
library(ncdf4)
lapply(file_list, function(fn) {
    nc = nc_open(fn, write=TRUE)
    ncatt_put(nc, 'ice', 'units', 'percent')
    nc_sync(nc)
    nc_close(nc)
})
```

**Comment by edzer** [comment]
@Nowosad with the cleaned netcdfs, the warnings are gone, now.

**Comment by adrfantini** [comment]
> I like your option 2, and have a `st_contour` that contours. The latter needs options too, since you can get them as lines, or as polygons.

Re: `st_as_sf` when polygonizing, the GDAL underlying functions (`GDALPolygonize` and `GDALFPolygonize`) support 4- and 8- connectedness; this is quite important if using `merge=TRUE` and could be an option.

**Comment by edzer** [comment]
I saw that too, and also had the idea to interface that. Do both result in valid polygons?

**Comment by adrfantini** [comment]
> I saw that too, and also had the idea to interface that. Do both result in valid polygons?

Not necessarily, no. Unfortunately. Already the current results are not perfect:
```R
# example from ?stars::st_as_sf
tif = system.file("tif/L7_ETMs.tif", package = "stars")
x = read_stars(tif)
x = x[,,,6]
x[[1]][x[[1]] < 30] = NA  # set lower values to NA
x[[1]] = x[[1]] < 100 # make the rest binary

x %>% st_as_sf(merge=FALSE, as_points=FALSE, use_integer=TRUE)
# Error: length(d) == length(dim(x[[1]])) is not TRUE

x %>% st_as_sf(merge=TRUE, as_points=FALSE, use_integer=TRUE) %>% st_is_valid %>% summary
#    Mode   FALSE    TRUE 
# logical      47    2902
```
In fact I am currently working with a large raster flood dataset which was polygonized with `gdal_polygonize.py -8` and about 25% of the polygons are invalid. Will check without the `-8`.

**Comment by edzer** [comment]
This obviously affects both sf and stars, and introduces a version dependency. `lwgeom::st_make_valid` has no trouble making the 4 or 8-connected polygons valid (converting them to multipolygons), it seems.

**Comment by adrfantini** [comment]
On my dataset, using 4-connectedness creates much less invalid geometries, but still creates them. I am trying to use `lwgeom::st_make_valid`, hopefully it'll be done by tomorrow.

**Comment by edzer** [comment]
I noticed; It depends on what you want to do with the polygons downstream - e.g. for plotting there's no issue if they're invalid, but I guess you know what you want them for ;-)

**Comment by adrfantini** [comment]
> I noticed; It depends on what you want to do with the polygons downstream - e.g. for plotting there's no issue if they're invalid, but I guess you know what you want them for ;-)

Yeah, I need to calculate some areas and I need valid polygons of course.

**Comment by edzer** [comment]
Which reminds me off ... a function that returns the area of every grid cell? Would that be another approach?

**Comment by adrfantini** [comment]
> Which reminds me off ... a function that returns the area of every grid cell? Would that be another approach?

That would be awesome!

**Comment by edzer** [comment]
I disabled the `connect8` option in stars for now, since it needs a new version of sf on CRAN before it will stop giving warnings. Some patience needed...

**Comment by adrfantini** [comment]
Do you want me to open a separate ticket for that, maybe?

**Comment by edzer** [comment]
Yeah, that's OK!

**Comment by adrfantini** [comment]
> Yeah, that's OK!

Will do so.

> On my dataset, using 4-connectedness creates fewer invalid geometries, but still creates them. I am trying to use `lwgeom::st_make_valid`, hopefully it'll be done by tomorrow.

Took 6h, ouch!

**Comment by edzer** [comment]
Here's your `st_area` method. It always returns a 2D raster, is that convenient?

**Comment by adrfantini** [comment]
> Here's your `st_area` method. It always returns a 2D raster, is that convenient?

Certainly, perfect, thanks. The area is apparently reported in squared meters, which is nice. I tested for a regular lat-lon grid which `stars` does not interpret with any CRS (`st_crs` is `NA`); in this case `stars` should throw an error or at least a warning, instead of just returning a raster with missing units. In this test case the resolution is 0.25deg and all values reported were all (constant) 0.25**2, while after setting the correct CRS this is of course not the case.

**Comment by edzer** [comment]
From your POV yes, but others may be looking at MRI scans. This follows the logic of `sf` (and `sp`): use a crs if provided, if crs is NA, assume Cartesian coordinates with unknown units.

**Comment by adrfantini** [comment]
Fair point. Personally I would think a warning would help most users more than it would hurt, but I am clearly biased. Thanks again for the function, very handy.

**Comment by edzer** [comment]
Printing a message now in case of missing CRS, rather than a warning.

**Comment by edzer** [comment]
IMO this issue can be closed when we have a contour example figure in the vignette mentioning it.

**Comment by adrfantini** [comment]
Yes, do you want me to open a new issue re contour and what happens with different combinations of `st_as_sf` options?
([as per previous comment](https://github.com/r-spatial/stars/issues/99#issuecomment-461811517))

**Comment by edzer** [comment]
Good idea; this one is getting messy.
